### ISSUE TITLE
Create a Helm Chart for FaaS

### ISSUE THREAD

**Issue by errm** [openfaas/faas-netes#10]
A helm chart would make deploying FasS to Kubernetes much simpler, and it is quickly becoming the standard way to try out third party solutions on Kubernetes...

Once FaaS on kubernetes is somewhat stable we can then submit our chart to the official repo ... https://github.com/kubernetes/charts

I am happy to work on this unless someone else wants to give it a go...

**Comment by alexellis** [comment]
Please go ahead @errm this sounds like a great idea. What repo would it live in?

**Comment by errm** [comment]
I guess here for now ...

**Comment by alexellis** [comment]
No problems. Does this also need #3 to be done?

**Comment by alexellis** [comment]
Hey Ed have you had a go at this?

**Comment by genexp** [comment]
We're actually doing this now.  We might be able to get a pull request in for it.  

cc: @cforbes

**Comment by weikinhuang** [comment]
I opened a PR for this, can't use dynamic named services because a few of the containers have hard coded values.

**Comment by alexellis** [comment]
@genexp @weikinhuang @errm what do we need to wrap this up? Does it test out OK?

@weikinhuang the hard-coded values are kept in the main FaaS repo here - https://github.com/alexellis/faas/tree/master/prometheus

^ that's where we need to update and then I have to re-push the builds from Docker Hub.

**Comment by weikinhuang** [comment]
I'll leave it to everyone else on deciding if helm is going to be the preferred deployment method (which lets us get rid of having hard coded values in the main repo, and lets us use configmap mounted volumes). We can also keep the regular yaml files and update them with the configmaps that are found in the helm charts 
 (thereby removing them from the main repo as well and not having to build custom copies of prometheus and alertmanager).

**Comment by alexellis** [comment]
I'd say we need to support both for now.. so let's go with the pain. It's easy to remove the hard-coded "vanilla" config in the future if helm is supported on all platforms we need.

**Comment by weikinhuang** [comment]
I can create vanilla configmaps for this, would prevent you from having to build 2 images, and we can use stock docker hub images.

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by gardlt** [comment]
I would be very interested in a openfaas helm chart since i am currently using this for all my deployments. Let me know how I can help.

**Comment by alexellis** [comment]
Thanks to @weikinhuang for leading this.

@genexp, @errm, @gardlt, @e-beach  if you can get involved with testing that would be great. I've compiled RBAC instructions here:

https://github.com/openfaas/faas-netes/blob/master/HELM.md

Once we're happy, how do we go about submitting this to the upstream Helm chart repo?

**Comment by gardlt** [comment]
i cant seem to package the helm chart: 
`Error: directory name (helm) and Chart.yaml name (openfaas) must match`

**Comment by alexellis** [comment]
You can use the instructions in the link above for testing.

That error is the result of linting, do a `mv helm openfaas` and it should sort it.

**Comment by alexellis** [comment]
Let's find out how to get this chart released and merged in kubernetes/charts

cc/ Captain @spiddy
