### ISSUE TITLE
Create a guide for deploying OF on K8 on AWS

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-netes#100]
I will write a guide in the form of a blog post about how to deploy OpenFaaS on Kubernetes on AWS.

This work item was suggested by @alexellis, who also suggested that I create an issue to track my progress of this task.

I will leverage my K8-on-AWS deploy script which is here (https://github.com/ericstoekl/bash_profile/blob/master/kubesetup.bash).

**Comment by ericstoekl** [comment]
Derek assign: ericstoekl

**Comment by alexellis** [comment]
@ericstoekl are you working on this or should I close the issue?

**Comment by ericstoekl** [comment]
I posted this blog back in december :)

https://medium.com/@ericstoekl/deploying-openfaas-on-kubernetes-aws-259ec9515e3c

**Comment by ericstoekl** [comment]
Indeed it is -- under [Blog posts and write-ups](https://github.com/openfaas/faas/blob/master/community.md#blog-posts-and-write-ups)

**Comment by alexellis** [comment]
Perfect thank you 👍
