### ISSUE TITLE
Shell script or other solution to validate image fields within Helm chart

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#1007]
## Why do you need this?

An error ([incorrect image tag](https://github.com/openfaas/faas-netes/commit/9d0cc6959dd8c640196af845f4f477451401fa1f)) caused ArgoCD to perform a rolling update for OpenFaaS for a customer.

This would have remained in an errored state, but the chart was then completely removed and installed again, and so failed to work.

Reverting to an earlier version of the chart may have been a workaround, but some form of automated check or validation for container images could have either prevented this problem or got it bubbled up sooner for a fix.

## Expected Behaviour

A basic check that the image: fields within the various helm charts is valid and can be accessed from a container registry

## Current Behaviour

It is possible to update the wrong tag through human error, or for a build to fail to publish its container image, and therefore update to a matching release, but non-existing image.

## What solution do you recommend?

I am not sure if a shell script could handle this, or whether a generic OSS Go utility exists to do this?

I've used the [crane library](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/crane) in the past along with a YAML package to parse values.yaml files, so we may be able to come up with a bespoke solution.

The solution would run as part of `make charts`, so that it's always run when regenerating and republishing the Helm charts.

**Comment by kevin-lindsay-1** [comment]
Have you tried using the `wait` or `atomic` flags? I use this with `helmfile` and when a deployment fails to come online, it will auto-rollback after I think a default of `300s`.

https://helm.sh/docs/helm/helm_upgrade/

**Comment by rgee0** [comment]
This seems to be achievable with bash/curl but does, I think, require a access token to interrogate ghcr.
```
$ curl --head https://ghcr.io/v2/openfaasltd/faas-netes/manifests/0.1.6 
HTTP/2 401 
content-type: application/json
www-authenticate: Bearer realm="https://ghcr.io/token",service="ghcr.io",scope="repository:openfaasltd/faas-netes:pull"
date: Thu, 25 Aug 2022 07:43:15 GMT
content-length: 73
x-github-request-id: F4F7:5577:2AAC07:2EA46E:6307281
```

**Comment by alexellis** [comment]
Since arkade already gets installed in CI and by most openfaas users, perhaps it could be added there.

I prototyped this, and auth may be required (but is usually available in both contexts - making a PR and in CI)

https://twitter.com/alexellisuk/status/1562733666253828101?s=20&t=wunrazoD8_kkfCPym5Dl4w

**Comment by alexellis** [comment]
Here is the release of arkade:

https://github.com/alexellis/arkade/releases/tag/0.8.37

And the usage in `make charts` (run by a maintainer)

https://github.com/openfaas/faas-netes/blob/master/Makefile#L80

And in CI, for belt and braces:

https://github.com/openfaas/faas-netes/blob/master/.github/workflows/verify-images.yaml

cc @willfore
