### ISSUE TITLE
How to install to K8s cluter which has no access to dockerhub?

### ISSUE THREAD

**Issue by 160173995** [openfaas/faas-netes#1017]
Our network environment can not allow K8S cluster to access the public docker hub, but only pull image from private docker repository. So I wonder how we can build and push those OpenFAAS dcoker imange to the private docker repository? Thanks!

**Comment by alexellis** [comment]
Sorry, it seems like you've misunderstood how we use the issue tracker. I get it, some projects
give away free support via their issue tracker. We only use it track bugs and our own work.

For community support, you can check out our free training or come along to a weekly community call
and ask your questions there

https://docs.openfaas.com/community/
