### ISSUE TITLE
Add resource limits and requests to all helm charts, where not present already

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#1025]
Add resource limits and requests to all helm charts, where not present already

## Expected Behaviour

Our various helm charts like the nats-/cron-/sqs-connector charts should be able to take a set of requests and limits via their values.yaml files.

Full list of charts:

https://github.com/openfaas/faas-netes/tree/master/chart

## Current Behaviour

They're currently missing, but I added them to the pro-builder chart as an example:

https://github.com/openfaas/faas-netes/commit/b1153dd477abffda191b2c587bc9a7796153d38c

## Which Solution Do You Recommend?

Follow the example as per here: https://github.com/openfaas/faas-netes/commit/b1153dd477abffda191b2c587bc9a7796153d38c

Which in turn was taken from the gateway's YAML files.

## Steps to Reproduce (for bugs)

1. Deploy a connector with Helm
2. Get its YAML `kubectl get -o yaml deploy/cron-connector -n openfaas` 
3. See no resource requests or limits set

## Context

Without a requests value K8s cannot schedule pods effectively.

## Your Environment

* What version and distriubtion of Kubernetes are you using? `kubectl version`

All versions of K8s

**Comment by alexellis** [comment]
@Jasstkn would you be interested in taking one of the charts to work on and send your first PR to OpenFaaS?

**Comment by Jasstkn** [comment]
> @Jasstkn would you be interested in taking one of the charts to work on and send your first PR to OpenFaaS?

Yes, I'll take it. will submit a PR later today.
