### ISSUE TITLE
Add CPU based constraints

### ISSUE THREAD

**Issue by nicholasjackson** [openfaas/faas-netes#103]
Memory based constraints are already enabled in the k8s provider, we should extend this functionality to add cpu based constraints which are already defined in the gateway.
[https://github.com/openfaas/faas/blob/613ac888cdb6ffad2dcbef90282f1eea90ce85a3/gateway/requests/requests.go#L47](https://github.com/openfaas/faas/blob/613ac888cdb6ffad2dcbef90282f1eea90ce85a3/gateway/requests/requests.go#L47)

## Expected Behaviour
When a new function is deployed or a replica is created any cpu constraints set in the stack file should be applied to the deployment spec.

## Current Behaviour
Currently only memory is applied, cpu is ignored

## Possible Solution
Amend `func createResources(request requests.CreateFunctionRequest)` to handle CPU limits passed from the gateway.

**Comment by dungeonmaster18** [comment]
Hey @nicholasjackson can you close this it's been fixed in #104
