### ISSUE TITLE
Annotations for Liveness and Readiness Probes

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas-netes#1042]
Liveness and readiness probes on functions should be as tune-able as they are in kubernetes.

## Expected Behaviour

For example, if I want a health check to run every 10s, last for 10s, count as unhealthy after 3 tries, and reset to "healthy" after 1 try, I should be able to configure that.

The annotations for health and readiness should both be:

- `initialDelay`
- `period`
- `timeout`
- `failureThreshold`
- `successThreshold`

## Current Behaviour

- the level of specificity is not currently enough, as each parameter is useful for configuring specific behavior
- health and readiness do not appear to have the same parameters (according to the docs), even though they do in k8s, for good reason
- the annotation `periodSeconds` is not in seconds, it's a string duration.
- `com.openfaas.ready.http.failureThreshold` does not appear to work as stated in the [docs](https://docs.openfaas.com/reference/workloads/#custom-http-health-checks).

## Why is this needed?

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## Context

We cannot tune readiness and health to be adequately specific right now. Failure threshold and timeout not being available on Health probe is particularly problematic, because if a pod remains unready for a length of time we expect, it is restarted anyway.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by kevin-lindsay-1** [comment]
@alexellis I really need this configurable because I now have functions that are being killed early due to the health check effectively being the same as the readiness check.

**Comment by kevin-lindsay-1** [comment]
cc @welteki

**Comment by alexellis** [comment]
We need to add:

* ~~path~~
* ~~initialDelay~~
* ~~period~~
* ~~timeout~~
* failureThreshold
* successThreshold

**Comment by kevin-lindsay-1** [comment]
@alexellis just updated the chart. any reason I would see this?
```
operator W0602 00:55:12.343332       1 deployment.go:39] Function sleep probes parsing failed: invalid annotation com.openfaas.health.http.periodSeconds duration format: time: missing unit in duration "10"
```
Is this not yet implemented?

**Comment by alexellis** [comment]
@welteki can you advise Kevin please?

**Comment by welteki** [comment]
Hi, @kevin-lindsay-1

A new version of the chart has not been released yet. We are still making some changes there.
We will inform you as soon as the updated chart has been published.

If you want to try out the new annotations already you can upgrade your faas-netes pro image: `ghcr.io/openfaasltd/faas-netes:0.3.0`

**Comment by kevin-lindsay-1** [comment]
> What did you change? Did you just update the chart or did you change the image version for the operator?

I updated the chart. Part of our chart update process involves getting current with all images according to the chart's yaml. I'll try `0.3.0`.

**Comment by welteki** [comment]
A new version of the chart is available now. It includes some breaking changes. The announcement in the customers repo lists all changes.
