### ISSUE TITLE
Removing the CRD from Community Edition, really?

### ISSUE THREAD

**Issue by d-grasshopper** [openfaas/faas-netes#1053]
Thanks for keeping me up at 3 AM, having to fix my function deployments.

**Comment by rgee0** [comment]
Derek close

**Comment by alexellis** [comment]
Hi @d-grasshopper,

If you'd like to use OpenFaaS commercially, in production, you should consider OpenFaaS Pro.

The Community Edition (CE) is meant for open source developers and basic exploration.

You can find out more about the differences in the docs and pricing page:

https://docs.openfaas.com/openfaas-pro/introduction/

https://www.openfaas.com/pricing/

Feel free to reach out.

Alex
