### ISSUE TITLE
Question:How to access openFaas on web dashboard?

### ISSUE THREAD

**Issue by aditodkar** [openfaas/faas-netes#1054]
I am trying to run openfaas directly on cloud VPS not on local machine with 4gb RAM. I am referring these tutorials:

1) https://www.openfaas.com/blog/puppeteer-scraping/

By referring above link I was able to run function on cloud VPS and everything works fine (build/deploy/push).

Now I am facing issue with using web dashboard  through cloud VPS IP address. 

## Expected Behaviour
I should be able to access web dashboard on `http://CLOUD_VPS_IP:8080/ui/`

## Current Behaviour
I changed gateway url from `http://127.0.0.1:8080` to `http://CLOUD_VPS_IP:8080` in scrape-title.yml

but build and push is working fine but deployment does not work. Any idea what I am missing?  And how can I connect external IP to gateway-external service so that I can access web dashboard using cloud VPS IP?

```
root@localhost:~# kubectl get service --namespace openfaas
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
alertmanager        ClusterIP   10.96.92.188    <none>        9093/TCP         17h
basic-auth-plugin   ClusterIP   10.96.78.147    <none>        8080/TCP         17h
gateway             ClusterIP   10.96.31.171    <none>        8080/TCP         17h
gateway-external    NodePort    10.96.172.120   <none>        8080:31112/TCP   17h
gateway-provider    ClusterIP   10.96.143.170   <none>        8081/TCP         17h
nats                ClusterIP   10.96.181.159   <none>        4222/TCP         17h
prometheus          ClusterIP   10.96.94.57     <none>        9090/TCP         17h
```

## Your Environment
Linode cloud VPS 4GB RAM

**Comment by alexellis** [comment]
We would recommend trying [arkade](https://arkade.dev) and running `arkade info openfaas` which prints the connection information you need.

**Comment by aditodkar** [comment]
Logs show timeout error. updated yml file:
```
   environment:
      read_timeout: "1m"
      write_timeout: "1m"
      exec_timeout: "1m"

``` but did not work. Getting same error 504 gateway timeout

**Comment by alexellis** [comment]
Hi @aditodkar those settings are unrelated to accessing the UI

You should consider following a tutorial or buying the eBook if you are in need of additional help accessing the UI. This is something that requires a little basic knowledge of how servers and IP addresses work.

Sorry that we can't support you directly on this one.

Why don't you try this article? https://blog.alexellis.io/tls-the-easy-way-with-openfaas-and-k3sup/

Alex

**Comment by alexellis** [comment]
/lock: no issue with OpenFaaS, tutorial suggested for user.
