### ISSUE TITLE
Custom Function Scheduling

### ISSUE THREAD

**Issue by tburchardt** [openfaas/faas-netes#1059]
Dear Community,

we are using Kubernetes scheduling plugins to customize scheduling of Pods.
After the custom scheduler Pod was deployed, we tell Kubernetes with the property 'schedulerName' to use our custom scheduler for this Pod.

Unfortunately we could not find a way to customize this behaviour for the Scheduling mechanism of Openfaas functions.
The closest to a solution was using profiles, but the 'schedulerName' field is not supported.
Adding it to the function template did not work either.

#### Is there a way to customize the scheduler for function deployments?

The following configuration example works in Kubernetes.
`
spec:
   containers:
          - name: nginx
            resources:
            image: nginx:1.14.2
            ports:
              - containerPort: 80
   schedulerName: my-custom-scheduler
`
Thank you.

## Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
* / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  0074051aeb837f5f160ee8736341460468b5c190
 version: 0.15.4

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.25.5
 sha:     f9245ebbb308cf6c8b86436bd25643322198e9dc

Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.16.2 
 sha:           a58a014c4c7beffc627b4e2f1f296bea9185181f

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
* Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
* Ubuntu 20.04

**Comment by tburchardt** [comment]
Hi @alexellis,

Thank you for your message!

I am a student and do evaluations of different scheduling approaches on Kubernetes for my master thesis.
We chose to use OpenFaas in some parts of the evaluation, but in order to tell Kubernetes to use our schedulers it is required to specifiy the "schedulerName" field.

My solution was to fork the faas-netes repository and add the "schedulerName" property manually to the profiles.go and ProfileSpec. Then I built the image locally and installed openfaas with a flag to use my custom faas-netes image.
`arkade install openfaas --set faasnetes.image=XXXX/my-faas-netes:latest`

This approach made it possible to specify the "schedulerName" property in a profile.

**Comment by alexellis** [comment]
Hi @tburchardt I was going to suggest this myself - but perhaps not to the profile - but directly in the spec in make/update function. Glad you figured it out

Were you following this tutorial? https://blog.alexellis.io/how-i-test-openfaas-with-kubernetes/

What's the hypothesis for your custom scheduler?

If you'd like to share more, we meet weekly on Zoom - details at https://docs.openfaas.com/community/

Alex

**Comment by CherifMZ** [comment]
Hello @alexellis 

As I'm also interested in trying different schedulers for OpenFaaS functions, I'm looking into trying out the solution you proposed; **_to directly add the "schedulerName" property manually in the spec in make/update function_**. It seems promising, and I'd like to understand it better before implementing it.

I want to understand exactly if by make/update function you mean makeDeploymentSpec and updateDeploymentSpec in deploy.go and update.go like I did below?

`func makeDeploymentSpec()`
    
	    deploymentSpec := &appsv1.Deployment{
		    ...
    
		    Spec: appsv1.DeploymentSpec{
			    ...	
    
			    Template: corev1.PodTemplateSpec{
				    ObjectMeta: metav1.ObjectMeta{
                                           ...
				    },
				    Spec: corev1.PodSpec{
					    NodeSelector: nodeSelector,
                                        schedulerName: string,
					    Containers: ...,
				    },
			    },
		    },
	    }


`updateDeploymentSpec`

	getOpts := metav1.GetOptions{}

	...

	deployment.Spec.Template.Spec.schedulerName = "my-scheduler"

	if len(deployment.Spec.Template.Spec.Containers) > 0 {
		...
	}

	return nil, http.StatusAccepted
