### ISSUE TITLE
Both readiness and liveness probes use /_/health

### ISSUE THREAD

**Issue by zhulik** [openfaas/faas-netes#1072]
When scaling a function out I see errors. It seems like when kubernetes starts new pods it makes them available for incoming traffic before containers are ready. 

In according to https://github.com/openfaas/faas-netes/blob/master/pkg/k8s/probes.go, both liveness and readiness probes use `/_/health` which is served by `of-watchdog` (in my case) and does not reflect the actual state of the app it's watching.

## Expected Behaviour

Traffic does not reach containers which are not ready yet.

## Current Behaviour

Traffic reaches containers which are not ready yet.

## Why is this needed?

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Who is this for?

I use openfaas as a private person.

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## Steps to Reproduce (for bugs)

Using Openfaas CE and and a simple function which is watched by `of-watchdog` in http mode (for example https://github.com/zhulik/functions/pkgs/container/fn-dummy):
1. Run any load test(k6 or ab/hey) with more than 50 rps
2. Wait till function is automatically scaled out by alertmanager
3. Observe non-200 responses in the  `gateway_function_invocation_total` metric

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): I don't use faas-cli

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? k3s 1.25.3

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? Flannel

**Comment by zhulik** [comment]
I prepared a quick fix it: https://github.com/zhulik/faas-netes/commit/23a3e62a06d1430c33866f86adb47588bb320a55

**Comment by alexellis** [comment]
Hi @zhulik as I mentioned on the watchdog issue, there is no bug or regression here, and no fix required. 
cc @rgschmitz1

Health checks and readiness are only really required for commercial use of OpenFaaS so are part of OpenFaaS Pro.

The Community Edition is aimed at hobbyists and experimentation.

If you'd like to talk to us about options for Pro, feel free to reach out using the form at https://openfaas.com/pricing.

Alex
