### ISSUE TITLE
Why the configuration of environment variables  image_pull_policy does not take effect

### ISSUE THREAD

**Issue by Jwinf** [openfaas/faas-netes#1075]
In CentOS7, I use **export image_pull_policy=IfNotPresent**, but when I deploy function the pod's **imagePullPolicy** is still **Always**.
## Expected Behaviour

I hope that the pod's **imagePullPolicy** will be **IfNotPresent** instead **Always** when I set environment variable image_pull_policy.
## Current Behaviour

 I use **export image_pull_policy=IfNotPresent**, but when I deploy function the pod's **imagePullPolicy** is still **Always**.
## Why is this needed?

My Internet environment is poor so I need to change the imagePullPolicy to avoid pulling image from dockerhub.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):
  20

* What version and distriubtion of Kubernetes are you using? `kubectl version`
  1.20

* Operating System and version (e.g. Linux, Windows, MacOS):
    CentOS7

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
Hey, we need more info than this to be able to help you.

Can you fill out the whole template, or let us know if you don't need help any more?

Thanks.

Alex

**Comment by alexellis** [comment]
Hi @Jwinf 

Thanks for your interest in OpenFaaS.

I did ask you to fill out the whole issue template with some evidence about how you're configuring and confirming the behaviour. You've not done that, so I can't really do much more here.

`imagePullPolicy` should be set in the Helm chart, and I can't see any reason why it wouldn't work. It's not changed in a very long time.

> My Internet environment is poor so I need to change the imagePullPolicy to avoid pulling image from dockerhub.

You may prefer to use faasd which is much more lightweight and better for hobbyists, and less technical.

It also supports locally cached images.

http://github.com/openfaas/faasd

Alex

**Comment by alexellis** [comment]
/set title: Support request about image pull policy
