### ISSUE TITLE
Documentation for working with the Function CRD - need more documentation about it in my opinion

### ISSUE THREAD

**Issue by yairyairyair** [openfaas/faas-netes#1085]
## Why is this needed?

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
Hey @yairyairyair the CRD is for OpenFaaS Pro customers and not available in CE which you are using.

What exactly where you hoping to learn beyond the documentation?

https://www.openfaas.com/blog/manage-functions-with-kubectl/

https://www.openfaas.com/blog/howto-package-functions-with-helm/

Alex
