### ISSUE TITLE
namespaces.yml should be moved to ./yaml

### ISSUE THREAD

**Issue by amney** [openfaas/faas-netes#113]
## Expected Behaviour

Deployment on k8s requires creating namespaces. Documentation suggests running
```
$ cd faas-netes && \
 kubectl apply -f ./yaml/namespaces.yml && \
 kubectl apply -f ./yaml
```

## Current Behaviour

`namespaces.yml` did not get moved to `./yaml` in dc515030c9164683a5334d635f404231f9b48c79 so current output is:
```
kubectl apply -f ./yaml/namespaces.yml
error: the path "./yaml/namespaces.yml" does not exist
```

## Possible Solution

Move `namespaces.yml` to `./yaml`

* https://github.com/amney/faas-netes/commit/0e21fdd860e5be061ee6edf416b58e51d0f34f6c

**Comment by alexellis** [comment]
This is as designed. I moved namespaces.yml outside of the yaml folder because the kubectl command fails to work if it decides to run the namespace creation after any of the other resources. We've had the documentation updated instead. Please do re-test and thank you for using OpenFaaS
