### ISSUE TITLE
Error response from daemon: manifest unknown

### ISSUE THREAD

**Issue by bgv1729** [openfaas/faas-netes#1130]
Were these container images removed/untagged? 

~~~
docker pull ghcr.io/openfaas/gateway:0.23.0 
docker pull ghcr.io/openfaas/faas-netes:0.15.1
docker pull ghcr.io/openfaas/queue-worker:0.13.0
~~~

**Comment by arnediekmann** [comment]
Seemingly, only the latest versions are available at ghcr.io ... So our fix was to update the Helm chart to v14.

**Comment by alexellis** [comment]
We have purged old images that had severe and critical security issues, see: https://www.openfaas.com/blog/time-to-update/
