### ISSUE TITLE
Container Gateway of  pod faas-netes CrashLoopBackOff : Readiness probe failed and Liveness probe failed

### ISSUE THREAD

**Issue by WhaleSpring** [openfaas/faas-netes#1159]
## Expected Behaviour

I hope my openfaas in my cluster to be ok.

## Current Behaviour

My openfaas was OK 2 weeks ago, but it turns down last week:
Container `gateway` of  pod `faas-netes` `CrashLoopBackOff `, with `queue-worker` alse being  `CrashLoopBackOff `sometimes:
![image](https://github.com/openfaas/faas-netes/assets/81799971/46ca076d-3704-4804-9d11-a79e6bbb95cf)

Here are the messages got by `kubectl describe pod -n openfaas faas-netes-xxxxx`
`  Warning  Unhealthy  43m (x9 over 43m)      kubelet            Readiness probe failed: Get "http://10.244.104.19:8080/healthz": dial tcp 10.244.104.19:8080: connect: connection refused
  Warning  Unhealthy  14m (x45 over 43m)     kubelet            Liveness probe failed: Get "http://10.244.104.19:8080/healthz": dial tcp 10.244.104.19:8080: connect: connection refused
  Warning  BackOff    4m45s (x164 over 42m)  kubelet            Back-off restarting failed container`

Here are the logs of container `gateway` and conatiner `faas-netes` of pod `faas-netes`:
![image](https://github.com/openfaas/faas-netes/assets/81799971/8b9be563-5443-4c7c-9b14-abba150ddb87)
![image](https://github.com/openfaas/faas-netes/assets/81799971/aca22674-64ec-434d-b47a-c0044dd04b00)

## Why is this needed?

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
![image](https://github.com/openfaas/faas-netes/assets/81799971/6cf59079-1db0-41e7-87aa-830fd550ad6e)

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client: Docker Engine - Community
 Version:           20.10.21
* What version and distriubtion of Kubernetes are you using? `kubectl version`
1.23.0
* Operating System and version (e.g. Linux, Windows, MacOS):
CentOS Linux release 7.6.1810 (Core) 
* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
calico

**Comment by TYsonHe** [comment]
mark it. I have the same problem on my cluster

**Comment by WhaleSpring** [comment]
It is worth mentioning that this issue also occurred in my newly deployed virtual machine cluster of ubuntu22.04.

**Comment by WhaleSpring** [comment]
It's  errors from my network . Not openfaas.

**Comment by alexellis** [comment]
No problems. We've not experienced any issues over here, so it looks like it's localised to your own environments.

If you're enjoying OpenFaaS, check out how you can support the project back:

https://github.com/sponsors/openfaas/
