### ISSUE TITLE
Helm chart openfaas/openfaas:14.1.7 fails to install because annotation bool value is not quoted

### ISSUE THREAD

**Issue by mschoones** [openfaas/faas-netes#1168]
Attempt `helm install --namespace openfaas --version 14.1.17 openfaas openfaas/openfaas`
fails.

## Expected Behaviour
I expect the chart to install, but it fails with message:

> Error: INSTALLATION FAILED: 1 error occurred:                                                       
>     * Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into
>  Go struct field ObjectMeta.spec.template.metadata.annotations of type string

## List All Possible Solutions and Workarounds
Add quotes to the value of the annotation (in this case "false") in file:
https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/nats-dep.yaml (line 21)

**Comment by alexellis** [comment]
Thanks for letting us know.

@mschoones since this is the first time you've asked for support, can you tell us what company is using OpenFaaS Community Edition here?

Can you send a PR to our ADOPTERS file and list the use-case? https://github.com/openfaas/faas/blob/master/ADOPTERS.md
