### ISSUE TITLE
basic-auth secret is missing in install yaml

### ISSUE THREAD

**Issue by m1093782566** [openfaas/faas-netes#1169]
## Expected Behaviour

install openfaas in one command.

## Current Behaviour

basic-auth secret is missing in install yaml, what format of the secret should be? can provide an example?

## Why is this needed?

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] 

without basic-auth secret, I am unable to install the openfaas ce.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
This is a user error, you've omitted a step to create namespace and the secret.

However, why are you trying to apply YAML files? That's a deprecated installation method.
