### ISSUE TITLE
Avoid Default Use of Nodeport?

### ISSUE THREAD

**Issue by JacobSanford** [openfaas/faas-netes#117]
Thanks for a great product. I appreciate the work and effort.

Based on our local use, I am inquiring about your interest in a PR that pulls out the the default port-opening Nodeport services for Prometheus and Gateway into a new YAML files. The documentation would instead encourage users to leverage the ```kubectl proxy``` to reach the gateway (similar to the dashboard):

```
http://localhost:8001/api/v1/namespaces/openfaas/services/gateway/proxy/
```

and avoid opening unnecessary ports on their k8s cluster. Where necessary (faas-cli?), one could then create those Nodeport services separately with a ```kubectl create``` pointing to the new YAML files.

If this isn't your vision for the product, I understand. I wanted to inquire before making the effort.

Regards

**Comment by alexellis** [comment]
Hi @JacobSanford thank you for using OpenFaaS! I'd like to know more about your use-case and why NodePorts don't work for you and proxies do.

How would you invoke or expose your functions?
Could you maintain a separate YAML file to lock down / remove the NodePorts?

We have a guide on locking down OpenFaaS - do you have any thoughts on that? 

https://blog.alexellis.io/lock-down-openfaas/

Looking forward to hearing more and I hope we can help you.

**Comment by JacobSanford** [comment]
Hi @alexellis 

My concern is not that Nodeport doesn't work for us - it certainly does! That route does, however, open external -> k8s ports that may be unnecessary, as ```kubeadm proxy``` can be used to provide access into the k8s network (as long as the cluster's API port is open). 

Users then reach the openfaas gateway/api/functions via browser/CLI tool at the ```kubectl proxy``` URI. In our case at UNB, the goal is to leverage the k8s cluster with openfaas for image encoding, OCR, etc, but do not wish any public access, so the above is the preferred networking setup, and we remove the NnodePort services from the ```yaml``` directory files before creating the faas-netes services. It's a quick change.

The reason for the query: it occurred to me that you may want to do this by default - start with recommending the most restrictive permissions, and then provide instructions to deploy the NodePort Services if desired (or if ```kubectl proxy``` isn't an option).

Without opening the ports by default, users conquer most of the security concerns addressed in your 'lock down' guide, as you kick the authentication and access concerns upstream to the k8s cluster itself.

Just an idea. It would be trivial to pull out the services into separate NodePort service YAML files, and not too bad to add this to the documentation.

**Comment by alexellis** [comment]
I think you can do this through the helm chart currently.. are you pro/against helm?

**Comment by alexellis** [comment]
@JacobSanford do you want to use YAML or helm? If using helm we could add an option not to expose any NodePorts, LoadBalancers or etc.

**Comment by alexellis** [comment]
FYI the UI now fully works over `kubectl proxy` - https://github.com/openfaas/faas/issues/519

cc/ @stefanprodan

**Comment by alexellis** [comment]
Derek close: inactive
