### ISSUE TITLE
Can we configure openfaas not to reach "checkip.amazonaws.com" for opensource version

### ISSUE THREAD

**Issue by saikumar0412** [openfaas/faas-netes#1185]
I am trying to install openfaas in our AKS cluster and I was able to install, How ever some of the pods were in crashloop.

Upon checking the logs it's due to the above reason that our firewall is blocking the connection to url "checkip.amazonaws.com".

`

## Expected Behaviour
Able to install openfaas without any issues

## Current Behaviour
Installation blocked due to above mentioned error

## Why is this needed?
As our firewall is blocking this IP we need what is the exact reason open faas is reaching above IP and would like to know if it. could be bypassed.

**Comment by saikumar0412** [comment]
Could you please check and update on alternative for above issue

**Comment by alexellis** [comment]
Hi @saikumar0412 please check the terms of usage for Community Edition, this is not for commercial usage or within an enterprise network, you should really buy a license of OpenFaaS Standard.

These are available on a monthly basis, please feel free to get in touch to see what we can do for your employer.

https://openfaas.com/pricing

Alex

**Comment by alexellis** [comment]
Alternatively, add checkip.amazonaws.com to your firewall rules?
