### ISSUE TITLE
Question : about local development for free users and pull policy

### ISSUE THREAD

**Issue by rgunindi** [openfaas/faas-netes#1186]
I see some text in the readme file here: https://github.com/openfaas/faas-netes/blob/dc9c84659707d5ed61dd429929aa8c8cb89640b1/README.md?plain=1#L123C16-L123C16

> The part that says: If this is not desired behavior, OpenFaaS Pro customers can set the `image_pull_policy` environment variable to an alternative. `IfNotPresent` is particularly useful when developing locally with minikube. In this case, you can set your local environment to [use minikube's docker](https://kubernetes.io/docs/getting-started-guides/minikube/#reusing-the-docker-daemon) so `faas-cli build` builds directly into minikube's image store.

Is this the correct way for local development for free users? Because users already have k8s and if they want to, they can change the image pull policy for these function deployments. Is this a present plus for pro customers? Isn't it ridiculous? Or am I missing something?

Thank you

**Comment by alexellis** [comment]
Hi @rgunindi if you're a commercial user of OpenFaaS, you should be buying a license. These limits and restrictions aren't an issue for the intended audience for Community Edition.

OpenFaaS Standard is for commercial development and production.

Hope this clears things up for you.

https://openfaas.com/pricing
