### ISSUE TITLE
Support request about image pull policy

### ISSUE THREAD

**Issue by bin-lian** [openfaas/faas-netes#1195]
In MacOS, I use export image_pull_policy=IfNotPresent, but when I deploy function the pod's imagePullPolicy is still Always.
OpenFaaS CE I installed using arkade

## Expected Behaviour
I hope that the pod's imagePullPolicy will be IfNotPresent instead Always when I set environment variable image_pull_policy.

## Current Behaviour
I use export image_pull_policy=IfNotPresent, but when I deploy function the pod's imagePullPolicy is still Always.

## Why is this needed?
I'm using k3d for local debugging and don't want to pull the image from the remote repository

## List All Possible Solutions and Workarounds
1.kubectl edit deployment gateway -n openfaas   
Modifying image_pull_policy IfNotPresent does not take effect
2.kubectl delete deployment gateway -n openfaas  
Download gateway-dep.yml from github, modify image_pull_policy IfNotPresent and it still doesn’t work after applying it.
3.k3d image has been imported

## Steps to Reproduce (for bugs)
<img width="929" alt="image" src="https://github.com/openfaas/faas-netes/assets/97667612/50c8c3ba-d51d-4a4e-9eb7-3b6a37cd22d8">

<img width="729" alt="image" src="https://github.com/openfaas/faas-netes/assets/97667612/289da8ca-f984-4496-876f-4a8628b76338">

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):0.16.23

* Docker version `docker version` (e.g. Docker 17.0.05 ): 24.0.7

* What version and distriubtion of Kubernetes are you using? `kubectl version`: v1.27.5+k3s1

* Operating System and version (e.g. Linux, Windows, MacOS):MacOS

* What network driver are you using and what CIDR? i.e. Weave net / Flannel   :Flannel

**Comment by alexellis** [comment]
Hi @bin-lian 

> I use export image_pull_policy=IfNotPresent, but when I deploy function the pod's imagePullPolicy is still Always.

You're describing the behaviour of [OpenFaaS Community Edition accurately](https://openfaas.com/pricing).

To get what you want, you'll need to upgrade to OpenFaaS Standard.

I'll get this closed.

Alex
