### ISSUE TITLE
CRDs are installed despite of createCRDs: false

### ISSUE THREAD

**Issue by vkryzh** [openfaas/faas-netes#1208]
I believe, issue is introduced here - https://github.com/openfaas/faas-netes/commit/cce949eedf000c5e7cf0e8fcf5fb8943eb0c8805

## Expected Behaviour

`createCRDs: false` - no CRDs should be installed

## Current Behaviour

`createCRDs: false` - 3 CRDs are installed (policies, roles, jwtissuers)

## Who is this for?

Corva

## List All Possible Solutions and Workarounds

- add flag to new CRDs to skip their installation

## Steps to Reproduce (for bugs)

1. Install latest Openfaas with only `createCRDs: false` in values override
2. Have CRDs installed

## Context

With Namespace admin permissions we cannot install CRDs, so their installation should be moved to a different place. And, as it stated in chart documentation, we should be able to do this using simple flag.

**Comment by vkryzh** [comment]
Hey @alexellis . Added context, thank you.

**Comment by alexellis** [comment]
Hi @vkryzh 

Those IAM-based CRDs can be suppressed via `--skip-crds` being passed into Helm

Hope this helps.

I'm having a look at the docs for "namespaced installation" at the moment so will get this closed.

Alex

**Comment by alexellis** [comment]
Related to this issue, we've consolidated the way CRDs will be created, feel free to comment:

https://github.com/openfaas/faas-netes/pull/1212
