### ISSUE TITLE
Custom IngressClass cannot be set for gateway ingress

### ISSUE THREAD

**Issue by vkryzh** [openfaas/faas-netes#1210]
IngressClass conflicts with the default annotation

## Expected Behaviour

When IngressClass is set to custom value, it is working

## Current Behaviour

When IngressClass is set to custom value, it is conflicting with default ingress annotation

## Who is this for?

Corva

**Comment by alexellis** [comment]
Hi @vkryzh 

The issue template is not optional, but at times some fields may not apply. https://github.com/openfaas/faas-netes/blob/master/.github/ISSUE_TEMPLATE.md

Most importantly here, we need:

* Steps to Reproduce (for bugs)

That should include showing us any ingress classes you have in your cluster, along with the name of the one you're trying to use for OpenFaaS.

Alex

**Comment by alexellis** [comment]
Since we didn't have any steps to reproduce the issue, I've tried to guess what you're trying to do.

https://docs.openfaas.com/tutorials/local-kind-ingress/

It seems to have adopted the Ingress Class:

```
kubectl get -n openfaas ingress
NAME               CLASS   HOSTS            ADDRESS   PORTS   AGE
openfaas-ingress   nginx   openfaas.local             80      20m
```

**Comment by alexellis** [comment]
Closing this issue since the ingress annotation is deprecated in Kubernetes, as linked above. No example was provided for reproducing the issue. I was able to show that ingressClassName is working as described in the Kubernetes documentation.

Feel free to comment here if you have further input.
