### ISSUE TITLE
Deploy Error:"the Community Edition license agreement only supports public images"

### ISSUE THREAD

**Issue by Lsgoose** [openfaas/faas-netes#1217]
## Current Behaviour
When I try to deploy a function after build and push it, problem occurs as follows:
![image](https://github.com/openfaas/faas-netes/assets/76503549/d6f02247-f095-4abf-9e18-d974ba0c22b3)
It's weird that when I used the openfaas ui to deploy a store function it still failed:
![469681a1cda73325c824b927b5de26c6](https://github.com/openfaas/faas-netes/assets/76503549/c76432e9-e90a-424d-8dfb-5249d2c3600c)
Both the pictures mentioned that "the Community Edition license agreement only supports public images". But I cannot even deply the store functions. So it confused me for days. I tried to pull my images pushed to my docker registry using "docker pull lsgoose/hello:latest", but it still failed:
![image](https://github.com/openfaas/faas-netes/assets/76503549/c0f8f3d2-7a61-4b8b-a173-7c8b9bb5f216)

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
![image](https://github.com/openfaas/faas-netes/assets/76503549/ea42e9b5-e0b4-43ed-a8ed-9dc214f6c5b2)

* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.24

* What version and distriubtion of Kubernetes are you using? `kubectl version`    1.23.7

* Operating System and version (e.g. Linux, Windows, MacOS):  VMware Ubuntu 22.04

* What network driver are you using and what CIDR?  Flannel

**Comment by alexellis** [comment]
This message clearly explains the situation. If you'd like to know more, please feel free to [review a comparison here](https://docs.openfaas.com/openfaas-pro/introduction/#comparison).

**Comment by alexellis** [comment]
No issue with deploying store functions from the classic UI portal, or the CLI to OpenFaaS CE:

![image](https://github.com/openfaas/faas-netes/assets/6358735/6b4372b8-ce42-4907-929b-13d08090cf2f)

If you're a hobbyist user, faasd may suit you better, which does have support for private images.

https://github.com/openfaas/faasd
