### ISSUE TITLE
HOW TO REMOVE HEALTH CHECK FROM DEPLOYMENTS

### ISSUE THREAD

**Issue by omryshay** [openfaas/faas-netes#1228]
Hey, my name is Omry.

I wanted to seek help with functions configurations..
I trying to upload a deployment with faas-cli without the use of watchdogs, the only thing the docker file does is activate the python code that uses a while true to never stop, i inserted in the main path

when i upload the function as a deployment it restarts because of the healthcheck failure

when i remove the health check from the yaml in the kuberentes it works but i  want it to work automatically and not always delete it

can anyone help me with this?
is it something in the stack.yaml?
something i can manipulate to work?

USING OPENFAAS 5.8.8 (old version)

**Comment by alexellis** [comment]
Hi Omry,

This is only supported in OpenFaaS Standard as explained in our docs and on our pricing page.

We've already exchanged several emails and talked on the phone, so let us know if/when you'd like to upgrade and you can get this working immediately.

https://docs.openfaas.com/openfaas-pro/introduction/#comparison

https://www.openfaas.com/pricing/

I've also replied to your email just now.

Let us know over there if we can help further.

Alex
