### ISSUE TITLE
Upgrade to Prometheus 2.0

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#129]
## Current Behaviour

We are using ConfigMaps but still on Prometheus 1.5 - 2.0 works well and is available in the main faas project as an example.

## Scope

This should cover the plain YAML files and the helm chart.

## Acceptance criteria

It must be tested including via CLI, UI and still trigger auto-scaling.

**Comment by alexellis** [comment]
Is it compatible with 2.0 configs?

**Comment by LucasRoesler** [comment]
for the helm chart, would it make sense to just add the stable prometheus chart as a dependency? The biggest downside is that the yaml manifests and the helm chart would then be different .

**Comment by stefanprodan** [comment]
2.1 is fully compatible with 2.0 config

**Comment by LucasRoesler** [comment]
@alexellis it seems that the `arm` images are all managed by you, but I can't find a repo for the docker files you used to build them.  Are these in a public repo somewhere? Can we update them to 2.1 as well?

**Comment by LucasRoesler** [comment]
I was just reading the prometheus migration guide and it contains this 

> The data format in Prometheus 2.0 has completely changed and is not backwards compatible with 1.8. To retain access to your historic monitoring data we recommend you run a non-scraping Prometheus instance running at least version 1.8.1 in parallel with your Prometheus 2.0 instance, and have the new server read existing data from the old one via the remote read protocol.

Do we need to add a migration warning and instructions?

**Comment by alexellis** [comment]
We could put this into the release notes perhaps?
