### ISSUE TITLE
Helm Fails to install with --set armhf=true

### ISSUE THREAD

**Issue by dvdmuckle** [openfaas/faas-netes#130]
Because there are no arm images for any of the async deployments, Helm fails on there being an empty arm image for queueworker.

## Expected Behaviour
Helm should be able to install with --set async=false,armhf=true.

## Current Behaviour
When doing `helm upgrade --install --set async=false --set armhf-true openfaas chart/openfaas`, or just `helm upgrade --reuse-values --set async=false openfaas chart/openfaas`, the error `Error: UPGRADE FAILED: failed to create resource: Deployment.apps "queue-worker" is invalid: spec.template.spec.containers[0].image: Required value` is reported.

## Possible Solution
Set the queueworker template to only be applied if async=true, or if armhf=false. Considering it's only necessary if async=true, the former option may be better.

## Steps to Reproduce (for bugs)
See above.

## Context
Trying to upgrade the OpenFaaS charts, or deploy them to begin with, fails without editing the charts.

## Your Environment
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/arm"}
```

**Comment by alexellis** [comment]
Please see #134 - we'll remove helm support for armhf until there is an official Tiller image. Please use the regular YAML for the time being.
