### ISSUE TITLE
Deployment with "rbac=false" is currently broken

### ISSUE THREAD

**Issue by hypnoglow** [openfaas/faas-netes#136]
Commit 44f7d42 broke "rbac=false" deployment mode, because now the ServiceAccount is only created when RBAC is enabled. 

## Expected Behaviour
openfaas helm chart successfully deployed.

## Current Behaviour
replicaset fails to create pods:
```
Events:
  Type     Reason        Age               From                   Message
  ----     ------        ----              ----                   -------
  Warning  FailedCreate  4m (x17 over 9m)  replicaset-controller  Error creating: pods "faas-netesd-655559f4fc-" is forbidden: error looking up service account openfaas/faas-controller: serviceaccount "faas-controller" not found
```

## Possible Solution
Solution 1: Bind pods to ServiceAccount only if RBAC is enabled.
Solution 2: Always create a ServiceAccount even if RBAC is disabled.

## Steps to Reproduce (for bugs)
1. `helm upgrade --install --debug --reset-values --set async=false --set rbac=false openfaas openfaas/`
2. `kubectl describe replicaset -l app=faas-netesd`

## Context
I've tried to deploy openfaas to my minikube cluster. But replicaset was stuck on creating pods.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): 
```
ή docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? 
Kubernetes (minikube)

* Operating System and version (e.g. Linux, Windows, MacOS):
macOS

* Link to your project or a code example to reproduce issue: 
\-

**Comment by alexellis** [comment]
@rimusz

**Comment by alexellis** [comment]
Hi @hypnoglow I don't think you've filled out the whole issue template. Please could you do that including which specific version of Kubernetes you are using and whether that is self-hosted or hosted on GKE, AKS etc etc?

**Comment by hypnoglow** [comment]
@alexellis My bad, I thought it's unrelated. I've filled it.

**Comment by alexellis** [comment]
Do you know which Kubernetes version you're using with minikube?

**Comment by alexellis** [comment]
@hypnoglow I spoke to @rimusz he said we need the ServiceAccount binding all the time even when RBAC is disabled. I'm reading the YAML in the repo and I can't see the bit where you say we are conditionally creating the ServiceAccount. Can you link me to it please?

**Comment by hypnoglow** [comment]
> Do you know which Kubernetes version you're using with minikube?

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

> I'm reading the YAML in the repo and I can't see the bit where you say we are conditionally creating the ServiceAccount. Can you link me to it please?

Here it is: https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/rbac.yaml#L5

> I spoke to @rimusz he said we need the ServiceAccount binding all the time even when RBAC is disabled.

I guess then the condition `{{- if .Values.rbac }}` should be moved below ServiceAccount definition.

**Comment by alexellis** [comment]
I spent a few hours on this last night and found another error that had been merged in where environmental variables were not quoted for timeouts. I actually tried removing the if guard but it didn't work. 

If you can figure out the other breaking changes between that commit and HEAD I'd appreciate it. 

The raw yaml files are working as expected in the yaml folder.

**Comment by alexellis** [comment]
This is from a community member for setting up minikube with rbac:

`minikube start  --bootstrapper=kubeadm --disk-size=50g --memory=4096 --v 5 --kubernetes-version=v1.8.1`

**Comment by LucasRoesler** [comment]
If I move the ServiceAccount definition outside of the if block, everything seems to work for me

```yaml
{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: faas-controller
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: faas-controller
  namespace: {{ $functionNs | quote }}
{{- if .Values.rbac }}
```

**Comment by hypnoglow** [comment]
> If I move the ServiceAccount definition outside of the if block, everything seems to work for me

Yeah, that's what I was talking about. Works for me too.

**Comment by alexellis** [comment]
Thanks both
