### ISSUE TITLE
cloud/lb.yml not working

### ISSUE THREAD

**Issue by justindavies** [openfaas/faas-netes#140]
## Expected Behaviour
When removing the default NodePort gateway service and applying the cloud version, the gateway should be exposed correctly.

## Current Behaviour
The Service is plumbed into the "default" namespace

## Possible Solution
Specify the Service namespace so that it follows the namespaces.yml setup

## Your Environment
ACS and AKS on Azure

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

**Comment by alexellis** [comment]
Justin thank you for working on this. I would suggest using helm and passing the LoadBalancer configuration option. Checkout the chart/openfaas folder for more info. 

It's good to have this YAML up to date though.

**Comment by alexellis** [comment]
Fixed & merged.
