### ISSUE TITLE
Question: How do I install OpenFaaS with helm?

### ISSUE THREAD

**Issue by VenkateshSrini** [openfaas/faas-netes#142]
I'm using the command 
```
helm upgrade --install --set async=true --set rbac=false --set serviceType=LoadBala
ncer openfaas chart/openFaas
```
I get an error 

**> WARNING: Namespace doesn't match with previous. Release will be deployed to openfaas
> Error: UPGRADE FAILED: "openfaas" has no deployed releases**
Please help me with the same. I use AKS for deployment

**Comment by alexellis** [comment]
Hi @VenkateshSrini the error is saying you previously deployed faas-netes into a different namespace. Perhaps you should delete it then run it again.

The command should also use the openfaas and openfaas-fn namespaces.. is this from the guide via @ericstoekl ?

This is the reference method to install via helm with `--set rbac=false` added to accommodate AKS:

```
$ kubectl create ns openfaas
$ kubectl create ns openfaas-fn

$ helm upgrade --install openfaas openfaas/ \
   --namespace openfaas \
   --set functionNamespace=openfaas-fn
   --set rbac=false
```

Prior to running that please run `helm delete --purge openfaas`

Let us know how you get on.

**Comment by alexellis** [comment]
Derek set title: Question: How do I install OpenFaaS with helm?

**Comment by ericstoekl** [comment]
@VenkateshSrini Seconding what Alex said, let us know what guide you are following to deploy OF via Helm. Use `helm list --all` to show what deployments are currently active, and delete all of them by running `helm delete <deployment_name> --purge` for each deployment name. Run `kubectl get ns` to show what namespaces are active, and if none are then run:

```
$ kubectl create ns openfaas
$ kubectl create ns openfaas-fn
```

Finally deploy OF with:

```
$ git clone https://github.com/openfaas/faas-netes && cd faas-netes
$ helm upgrade --install --namespace openfaas --set functionNamespace=openfaas-fn --set async=true --set rbac=false --set serviceType=LoadBalancer openfaas chart/openfaas
```

**Comment by VenkateshSrini** [comment]
Yes i installed another one with openfaas 1 and it worked

**Comment by VenkateshSrini** [comment]
Yes i installed another one with openfaas 1 and it worked

**Comment by alexellis** [comment]
Glad it worked out for you @VenkateshSrini 

@ericstoekl thanks for helping out
