### ISSUE TITLE
How to send a Http Response from a function

### ISSUE THREAD

**Issue by VenkateshSrini** [openfaas/faas-netes#147]
I use C# for creating openFaas function. How do I send a return HttpResponse Message to the caller. Now only I get the response status code as 200 and so on.

**Comment by iyovcheva** [comment]
Derek add label: question

**Comment by iyovcheva** [comment]
Derek add label: question

**Comment by iyovcheva** [comment]
Hi @VenkateshSrini 

Can you please share more details about your function - how do you implement it and what the full picture of what you'd like to achieve looks like?

**Comment by VenkateshSrini** [comment]
@iyovcheva ,
Very simple. I have written a function that accepts a JSON. Just in case the input string in function handler can not be deserialized to JSON, I want to throw an 400 (Bad request) with a proper JSON error message. If there are any other exception I want to retrun 500 (Internal server error) with proper JSON. Now if I do Console.Write (<<JSON String>>) it is still has the response status code as 200. So please let me know how we can return context sensitive error messages.

**Comment by alexellis** [comment]
We have something coming soon which will address the use of arbitrary status codes and headers, but for the time being you can do the following:

* Return as normal and get a response code of 200
* Print your value then call system / exit with a non-zero exit code - this results in a 500
* return a JSON body with the status code wrapped (easiest option)

```json
{
 "statusCode": "400",
 "message": "That was invalid JSON, we couldn't parse it"
}
```

I'll close the issue as we've answered the support question. Feel free to keep commenting.

**Comment by VenkateshSrini** [comment]
what is the time line I can expect the use of headers and arbitrary status codes to implemented in the product

**Comment by alexellis** [comment]
OpenFaaS is a community project, not a product.

Are you able to work within the constraints explained above? I'd suggest you return a JSON body and parse that on the client to determine success/failure. It's a very minimal overhead.

**Comment by VenkateshSrini** [comment]
@alexellis ,
I also understand that it is an open source project. But in this thread it was told that soon we will be getting this facility of custom status code and headers and hence I wanted to know the time line. In enterpirse this is important because there are other programs and product that react differently based on the Http Status code. In fact they would treat this as an contract itself

**Comment by alexellis** [comment]
Update: You should use of-watchdog for this usecase, see the documentation site for more.

**Comment by alexellis** [comment]
Derek: lock
