### ISSUE TITLE
Support /system/info endpoint 

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#163]
We need to support the /system/info endpoint which has been updated in the latest release of faas-provider

## Tasks:

- Update vendored package for https://github.com/openfaas/faas-provider to 0.6
- Add new handler for system info endpoint included in faas-provider package
- Inject build version and SHA into binary at build-time (look at faas-cli as an example of how to do this)
- Add unit test for the HTTP handler

Related: https://github.com/openfaas/faas-swarm/issues/16

**Comment by alexellis** [comment]
This is my PR to faas-nomad - I think the implementation would be similar minus all the logging/stats which are specific to Nomad.

https://github.com/hashicorp/faas-nomad/pull/36/files#diff-a31692c2f19298fb01f34a8683e5969c

**Comment by viveksyngh** [comment]
I will take this one.

**Comment by alexellis** [comment]
Thanks @viveksyngh please shout if you have questions or send a message to us on #faas-netes on Slack

**Comment by alexellis** [comment]
Good progress is being made on this via https://github.com/openfaas/faas-swarm/pull/17#issuecomment-375867419

**Comment by alexellis** [comment]
Merged in https://github.com/openfaas/faas-netes/pull/180
