### ISSUE TITLE
po/prometheus and po/alertmanager in the status of "CreateContainerConfigError"

### ISSUE THREAD

**Issue by liukaikai1211** [openfaas/faas-netes#164]
## Expected Behaviour

All pods should be in "running" status.

## Current Behaviour

The two pods "prometheus" and "alertmanager" always stay in "CreateContainerConfigError" status.

`root@lkk-nuc:~/faas-netes# kubectl get pods --all-namespaces`
`NAMESPACE     NAME                              READY     STATUS                       RESTARTS   AGE`
`kube-system   etcd-lkk-nuc                      1/1       Running                      0          15m`
`kube-system   kube-apiserver-lkk-nuc            1/1       Running                      0          16m`
`kube-system   kube-controller-manager-lkk-nuc   1/1       Running                      0          15m`
`kube-system   kube-dns-6f4fd4bdf-zpnnf          3/3       Running                      0          17m`
`kube-system   kube-proxy-8vtsb                  1/1       Running                      0          17m`
`kube-system   kube-scheduler-lkk-nuc            1/1       Running                      0          15m`
`kube-system   weave-net-m8d5g                   2/2       Running                      0          15m`
`openfaas      alertmanager-76c4595457-zm9ct     0/1       CreateContainerConfigError   0          12m`
`openfaas      faas-netesd-6b99db9f49-glxxj      1/1       Running                      0          12m`
`openfaas      gateway-7f5bcf864-sh5c2           1/1       Running                      1          12m`
`openfaas      nats-6c4f7df-6j9cs                1/1       Running                      0          12m`
`openfaas      prometheus-65b9b5c86d-z4q6s       0/1       CreateContainerConfigError   0          12m`
`openfaas      queue-worker-676ccd9fb9-fbpn9     1/1       Running                      0          12m`

## Steps to Reproduce (for bugs)

1. `$ git clone https://github.com/openfaas/faas-netes`
2. `$ cd faas-netes && \`
       `kubectl apply -f ./namespaces.yml,./yaml`
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
`root@lkk-nuc:~/faas-netes# docker version`
`Client:`
` Version:      17.03.2-ce`
` API version:  1.27`
` Go version:   go1.7.5`
` Git commit:   f5ec1e2`
` Built:        Tue Jun 27 03:35:14 2017`
` OS/Arch:      linux/amd64`
`Server:`
` Version:      17.03.2-ce`
` API version:  1.27 (minimum version 1.12)`
` Go version:   go1.7.5`
` Git commit:   f5ec1e2`
` Built:        Tue Jun 27 03:35:14 2017`
` OS/Arch:      linux/amd64`
` Experimental: false`

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
I am using Kubernetes.
` `
`root@lkk-nuc:~/faas-netes# kubectl version`
`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4",` `GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5",` `GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

* Operating System and version (e.g. Linux, Windows, MacOS):
I am using Ubuntu 16.04.3.
` `
`root@lkk-nuc:~# cat /etc/os-release`
`NAME="Ubuntu"`
`VERSION="16.04.3 LTS (Xenial Xerus)"`
`ID=ubuntu`
`ID_LIKE=debian`
`PRETTY_NAME="Ubuntu 16.04.3 LTS"`
`VERSION_ID="16.04"`
`HOME_URL="http://www.ubuntu.com/"`
`SUPPORT_URL="http://help.ubuntu.com/"`
`BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"`
`VERSION_CODENAME=xenial`
`UBUNTU_CODENAME=xenial`

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi there, thanks for using OpenFaaS. This issue is due to a late breaking patch by the Kubernetes team - they were fixing a CVE and introduced a bug into Kubernetes.

The best thing you can do (I verified it last night) is to upgrade your apt packages and initialise your cluster again with 1.9.5 which has the fix for their regression.

https://github.com/kubernetes/kubernetes/issues/61076

https://cloud.google.com/kubernetes-engine/release-notes

I'll close the issue as this is not a problem with OpenFaaS and upgrading Kubernetes does fix the error reported.

**Comment by alexellis** [comment]
Here's the latest patched version of Kubernetes on ARM:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}
```

All Deployments are up and running now. For the last few days since Kubernetes released the CVE fix these services had the same error as your cluster.

```
pi@pi300-1:~/faas-netes $ kubectl get pods -n openfaas
NAME                            READY     STATUS    RESTARTS   AGE
alertmanager-59f64fb5d4-9pnm5   1/1       Running   0          27m
faas-netesd-7db4d57c98-zng8r    1/1       Running   0          27m
gateway-7974dd58b7-qpv8t        1/1       Running   2          27m
nats-6c4f7df-2526l              1/1       Running   0          27m
prometheus-79fc6c7566-rn79g     1/1       Running   0          27m
queue-worker-9c6d8d896-dlb9d    1/1       Running   1          27m
```

**Comment by liukaikai1211** [comment]
Thanks, Alex. It is running now. 

But when I tested or invoked the services, I got the error of "`Can't reach service: url-ping`" or the response body of "`Service Unavailable`". What is the problem with this?

**Comment by liukaikai1211** [comment]
Alex, any idea on that? @alexellis

**Comment by iyovcheva** [comment]
@liukaikai1211 Can you please share steps to reproduce?
What `kubectl get svc` shows?

**Comment by liukaikai1211** [comment]
@iyovcheva This is what `kubectl get svc --all-namespaces` shows.

`root@lkk-S2600WFT:~# kubectl get svc --all-namespaces`
`NAMESPACE     NAME           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE`
`default       kubernetes     ClusterIP   10.96.0.1        <none>        443/TCP          1d`
`kube-system   kube-dns       ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP    1d`
`openfaas-fn   hello-python   ClusterIP   10.103.28.18     <none>        8080/TCP         1d`
`openfaas      alertmanager   ClusterIP   10.96.102.130    <none>        9093/TCP         1d`
`openfaas      faas-netesd    ClusterIP   10.100.179.141   <none>        8080/TCP         1d`
`openfaas      gateway        NodePort    10.104.117.130   <none>        8080:31112/TCP   1d`
`openfaas      nats           ClusterIP   10.98.252.23     <none>        4222/TCP         1d`
`openfaas      prometheus     NodePort    10.108.166.235   <none>        9090:31119/TCP   1d`

I followed Alex's blog [Your first serverless Python function with OpenFaaS](https://blog.alexellis.io/first-faas-python-function/) to create a python function service. All the other functions like url-ping or nodejs-echo (which were removed thereby not showing above) give the same error like `Can't reach service` or the response body of `Service Unavailable`in the UI.

What might be the problem?

**Comment by tshravan86** [comment]
@kaikai-liu Hi KaiKai. I apologise as this is not a relevant question what I'm going to ask. I'm trying to access the prometheus dashboard. When I port-forward using kubectl, I'm not getting any error as if the command getting hanged. When I see the svc list I have observed that the type is "Cluster-Ip" for promotheus.

`NAMESPACE     NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE`
`openfaas      prometheus          ClusterIP   10.100.247.94   <none>        9090/TCP                 20h`

I'd like to know how to change from ClusterIP to Nodeport so that port-forward command may work. The stats of yours in your answer is what I'd like to replicate. Could you please help me out here on how did you port-forwarded your prometheus? Thanks a lot for your time.

**Comment by alexellis** [comment]
@tshravan86 I'm going to lock this issue, please open your own issue if you have found something which you feel is an error, if you need technical support please use Slack.

**Comment by alexellis** [comment]
--
Join Slack to connect with the community
https://docs.openfaas.com
