### ISSUE TITLE
Feature: Include base url as a configuration item

### ISSUE THREAD

**Issue by patrickstjohn** [openfaas/faas-netes#166]
## Expected Behaviour

Provide a configurable base url for HTTP endpoints so external reverse proxies and/or load balancers can access endpoints via custom ingress controllers.

## Current Behaviour

Specific endpoints must be configured such as /metrics, /function, /system, /ui (for example with the gateway) to point to the proper ingress point. This way possible collisions with other systems will not impact openfaas (jenkins/kibana/etc. which provide their own base url for this reason). It's entirely possible a base url setting exists and I'm not seeing it in the documentation but nothing seemed obvious to me.

## Possible Solution

Ideally, this would be a setting placed in values.yaml for the Helm chart.

## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Bare-metal Kubernetes 1.9.5 installation via kubeadm.

* Operating System and version (e.g. Linux, Windows, MacOS): Linux RHEL 7

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
I am just googling around to get familiar with this line of thinking, but would something like this provide at least a work-around for your reverse proxy scenario?

https://github.com/elastic/kibana/issues/5230#issuecomment-152688743

**Comment by patrickstjohn** [comment]
@ericstoekl appreciate the response. That's fairly close. I probably wasn't being super clear. Here is a use-case we're looking at:

- On premises deployment behind a reverse proxy operating a blue/green deployment that is also multi-tenant and a front-end at /. Because of the initial redirect from / to /ui the ability do a rewrite like that is limited since it's easy to end up in redirect loops and since we want to have multiple instances behind the proxy not having a base path this gets pretty tricky quickly. Ideally we could do something like:

1. https://gateway/group1-fass/ui

1. https://gateway/group2-faas/ui

1. https://gateway/group1-faas/function

1. https://gateway/group2-faas/function

So on and so forth where different deployments were behind a single reverse proxy/load balancer set of infrastructure that then tied into potentially different infrastructure, regions, etc.

**Comment by alexellis** [comment]
I'm not clear on the use-case here. We use reverse proxies with OpenFaaS already.

Pinging @stefanprodan to see if we can get another perspective on the issue.

**Comment by robertrbruno** [comment]
Patrick and I were able to work a solution out.  The issue was we couldn't use the ingress that is in your helm charts as is because we can't easily control the host which is what your ingress was keying off of.

The solution was to create a path to key off of say /faas_gateway and then set the annotation nginx.ingress.kubernetes.io/rewrite-target to /.

Then you just need to make sure you browse to a specified path in that if you go straight to /faas_gateway/ the 302 to /ui won't work.  But if you say browse directly to /faas_gateway/ui then it will work correctly.

**Comment by alexellis** [comment]
I'm not 100% clear.

>The issue was we couldn't use the ingress that is in your helm charts as is because we can't easily control the host which is what your ingress was keying off of.

Can you explain this in more detail?
