### ISSUE TITLE
Remove arm / armhf references from helm chart

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#168]
# Summary

Helm relies on a server-side component called tiller which is not available for ARM

## Changes

Update the helm chart to remove all references to arm / armhf including the templating

https://github.com/openfaas/faas-netes/tree/master/chart/openfaas

Bump the version when doing this.

## Testing

Test that helm still deploys as expected and that there

**Comment by tranotheron** [comment]
I'm on it

**Comment by alexellis** [comment]
Thank you. I had a go at this but didn't have enough time to finish it and test so I appreciate you picking it up.
