### ISSUE TITLE
[k8s] Support secrect type `SecretTypeDockerConfigJson` for ImagePullSecrets

### ISSUE THREAD

**Issue by martin-liu** [openfaas/faas-netes#176]
Need to support secret type `SecretTypeDockerConfigJson` for ImagePullSecrets

## Expected Behaviour
Secret with type `SecretTypeDockerConfigJson` should be `ImagePullSecrets`.

## Current Behaviour
Only type `SecretTypeDockercfg` will be `ImagePullSecrets`, see https://github.com/openfaas/faas-netes/blob/0.4.5/handlers/deploy.go#L235

## Possible Solution
Add support of `SecretTypeDockerConfigJson`

## Context
config.json is newer docker config, see https://stackoverflow.com/questions/35519072/docker-config-json-vs-dockercfg

When I tried to follow https://github.com/openfaas/faas-netes/blob/master/SECRETS.md to create a image pull secret using below command. 
```
kubectl create secret docker-registry dockerhub \
    --docker-username=$DOCKER_USERNAME \
    --docker-password=$DOCKER_PASSWORD \
    --docker-email=$DOCKER_EMAIL
```

This command actually create a secret with type `SecretTypeDockerConfigJson` (kubernetes.io/dockerconfigjson), so that it doesn't work with openfaas by default.

I have to manually create a SecretTypeDockercfg type secret to make it works.

## My Environment
kubernetes v1.9.3

**Comment by alexellis** [comment]
Hi Martin please can you give us more context about your request? i.e. Why should we make this change? Did creating an image pull secret not work for your configuration?

**Comment by martin-liu** [comment]
@alexellis added context in issue body.
The thing is when I follow https://github.com/openfaas/faas-netes/blob/master/SECRETS.md for my k8s cluster (v1.9.3), it doesn't work, I have to manually create a secret with type SecretTypeDockercfg(kubernetes.io/dockercfg) to work around.

**Comment by alexellis** [comment]
How are you creating you secrets otherwise?

**Comment by martin-liu** [comment]
@alexellis 
I created it with config like below:
```
apiVersion: v1
kind: Secret
metadata:
  name: private-registry-secret
  namespace: default
type: kubernetes.io/dockercfg
data:
  .dockercfg: <base64 content>
```

**Comment by LucasRoesler** [comment]
Hi, @martin-liu, I dug through some of the k8s documentation and it looks like this behavior for the docker config secrets changed around version 1.9, but I think it is a simple change to the code base right here https://github.com/openfaas/faas-netes/blob/master/handlers/deploy.go#L235 . We can add `or` in the that `if` statement to also catch this new type or use a [switch statement](https://gobyexample.com/switch), which might be more go-idiomatic here.

**Comment by alexellis** [comment]
Would you like to submit a pull request for this?

**Comment by martin-liu** [comment]
@alexellis @LucasRoesler 👍 👍 👍
