### ISSUE TITLE
Guide how to deploy Deep Learning application which perform batch image processing (inference) on OpenFaas + Kubernetes + GPU/CPU

### ISSUE THREAD

**Issue by dkozlov** [openfaas/faas-netes#184]
How can OpenFaaS be used to perform batch image processing (inference) on GPU/CPU? Provide detailed instructions and provide changes to the YAML manifests where necessary.

**Comment by dkozlov** [comment]
Tutorial is in progress https://github.com/dkozlov/openfaas-tensorflow-gpu/

**Comment by alexellis** [comment]
/lock: closing as inactive. Feel free to raise a new issue if this is still required
