### ISSUE TITLE
Function requiring secret failed to deploy

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#188]
When deploying a simple function with a secret to a new Kuberenetes cluster today, I received an error concerning the mounting of the secrets

```
Error: failed to start container "repocount":
Error response from daemon: oci runtime error: container_linux.go:247: 
    starting container process caused "process_linux.go:359: 
    container init caused "rootfs_linux.go:54: 
        mounting "/var/lib/kubelet/pods/50e6d5d3-4222-11e8-b966-42010a9c00be/volumes/kubernetes.io~secret/default-token-hfcvr" 
            to rootfs "/var/lib/docker/overlay2/ff8d2b9dabbe75a4d79e964eb31056480017c9f99d0ea6cb1c23203dc98f9390/merged" 
            at "/var/lib/docker/overlay2/ff8d2b9dabbe75a4d79e964eb31056480017c9f99d0ea6cb1c23203dc98f9390/merged/run/secrets/kubernetes.io/serviceaccount" 
        caused "mkdir /var/lib/docker/overlay2/ff8d2b9dabbe75a4d79e964eb31056480017c9f99d0ea6cb1c23203dc98f9390/merged/run/secrets/kubernetes.io: read-only file system"
```

It seems that the function is trying to mount a read-only file system to `/run/secrets` and Kubernetes is also trying to mount another read-only filesystem to `run/secrets/kubernetes.io`.  

## Expected Behaviour

When I deploy a function that requires a secret, there should be no errors from Kubernetes.

## Current Behaviour

Function deployment appears to succeed but actually fails if the function requires a secret

## Possible Solution

We should add `automountServiceAccountToken: false` to the `PodTemplateSpec` in the function `Deployment`.  The default-token for the service account should only be useful if you want to access the Kubernetes API.  Most functions probably shouldn't have this access.

Alternatively, we can allow the function to specify the `serviceAccountName` on the  spec and then allow the cluster admin to configure the ServiceAccount with `automountServiceAccountToken` set to true or false as they need it. 

Either way, we can not mount secrets from the cluster and have kubernetes automatically mount this token in the same function.

## Steps to Reproduce (for bugs)

I have created a small public repo with an example function https://github.com/LucasRoesler/repostats

1. Setup minikube
2. Deploy faas-netes
3. Deploy the function using `faas-cli deploy`
3. Open the minikube dashboard
4. Observe the pod failure
5. Manually edit the Deployment spec to include `automountServiceAccountToken: false`
6. Observe the pod successfully start

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:	18.04.0-ce-rc2
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	f4926a2
 Built:	Thu Apr  5 05:39:27 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.04.0-ce-rc2
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	f4926a2
  Built:	Thu Apr  5 05:47:53 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
```

```
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.4-gke.1", GitCommit:"10e47a740d0036a4964280bd663c8500da58e3aa", GitTreeState:"clean", BuildDate:"2018-03-13T18:00:36Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:
Super simplified example of the original function
https://github.com/LucasRoesler/repostats

**Comment by LucasRoesler** [comment]
One other thought, this can probably also be solved by using a separate namespace and configuring the default service account in that namespace

**Comment by iyovcheva** [comment]
Derek add label: review

**Comment by alexellis** [comment]
@LucasRoesler are you using openfaas-fn as a namespace here for functions?

From the sounds of things I would implement your suggested fix in faas-netes & openfaas-operator.

@stefanprodan what do you think?

**Comment by alexellis** [comment]
Why haven't we seen this error yet in our testing?

**Comment by LucasRoesler** [comment]
That is a good question, a think when this was originally reported it was discussed in slack and it was not reproducible. But I wasn't able to determine how my k8s got into a state where this happened.

**Comment by alexellis** [comment]
I got a similar error on my Kubernetes NUC

Might be related to https://github.com/openfaas/faas/issues/683

```14s         14s          1         check-5d58bf95-m42gx.153058a8f589b348   Pod          spec.containers{check}   Warning   Failed                  kubelet, nuc7           Error: failed to start container "check": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/a19c9282-5c25-11e8-ac06-001fc69c3073/volumes/kubernetes.io~secret/default-token-5ltcs\\\" to rootfs \\\"/var/lib/docker/overlay2/db25445e3f86be1732428884c4b4509ced32dc2cf02b005a3b464ddf03f805b8/merged\\\" at \\\"/var/lib/docker/overlay2/db25445e3f86be1732428884c4b4509ced32dc2cf02b005a3b464ddf03f805b8/merged/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"mkdir /var/lib/docker/overlay2/db25445e3f86be1732428884c4b4509ced32dc2cf02b005a3b464ddf03f805b8/merged/run/secrets/kubernetes.io: read-only file system\\\"\"": unknown```

Creating secret on faas-netes using `curl`

Client Version: version.Info{Major:“1”, Minor:“10", GitVersion:“v1.10.0”, GitCommit:“fc32d2f3698e36b93322a3465f63a14e9f0eaead”, GitTreeState:“clean”, BuildDate:“2018-03-26T16:55:54Z”, GoVersion:“go1.9.3”, Compiler:“gc”, Platform:“linux/amd64”}
Server Version: version.Info{Major:“1", Minor:“9”, GitVersion:“v1.9.6", GitCommit:“9f8ebd171479bec0ada837d7ee641dec2f8c6dd1”, GitTreeState:“clean”, BuildDate:“2018-03-21T15:13:31Z”, GoVersion:“go1.9.3", Compiler:“gc”, Platform:“linux/amd64"}
```curl nuc-k8s:31112/system/functions --data-binary '
{
"image": "functions/alpine:latest",
"service": "check",
"secrets": ["k8s-tester"],
"envProcess": "xargs find",
"network": "func_functions"
}
' -i;echo```

**Comment by alexellis** [comment]
@LucasRoesler you suggested:

> Add automountServiceAccountToken: false to the PodTemplateSpec

Does this fix the issue? If so I think we should make this change and ship it in a point release. 

I don't know what changed between the previous usage of secrets on my NUC and now, but secrets are broken for me.

**Comment by LucasRoesler** [comment]
I specifically tested it by testing it on the service account level, but it can be done at the pod level as well (which is better for this case). The relevant docs are here https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

**Comment by robertrbruno** [comment]
I don't have a namespace named "openfaas-fn"  we deployed to a namespace just named "openfaas".  Is that an issue?  As in are certain things relying on the name of the namespace to be "openfaas-fn"?
