### ISSUE TITLE
Proposal: use Golang reverseproxy construct

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#19]
Let's try using https://golang.org/pkg/net/http/httputil/#ReverseProxy in this code: https://github.com/alexellis/faas-netes/blob/master/handlers/proxy.go

I think it could be more efficient and less maintenance.

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by shorsher** [comment]
I'll take a shot at this.  Just replace current proxy, with reverse?

**Comment by alexellis** [comment]
I started looking into it and I think it may be more complex than that since it needs to be a multi-host reverse proxy
