### ISSUE TITLE
Helm: Prometheus & AlertManager Should Be Optional

### ISSUE THREAD

**Issue by rawkode** [openfaas/faas-netes#190]
## Expected Behaviour

When installing faas-netes with Helm, I should be able to install without adding Prometheus and AlertManager.

## Current Behaviour

Can't disable provisioning of Prometheus and AlertManager

## Possible Solution

Wrap entire YAML files with `.Values` conditional

## Steps to Reproduce (for bugs)

helm install

**Comment by iyovcheva** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Prometheus is not an optional component. Why do you feel it should not be installed?

**Comment by rawkode** [comment]
I already have a Prometheus and Alert Manager in my infrastructure, why can't I connect faas to them?

**Comment by rawkode** [comment]
This was already proposed in the issue: use the `.Values` conditional check, which seems to be the common approach on "official" Helm repositories.

The Chart should expect two situations within `values.yaml`:

1. As now, spin up a Prometheus

```yaml
prometheus:
  provision: true
```

2. Use my Prometheus

```yaml
prometheus:
  provision: false
  host: prometheus.monitoring.svc.cluster.local
  port: 9090
```

**Comment by alexellis** [comment]
Can you test it and show that it works when you JG an existing config for both? I don't think it will work because you'll have duplicate sections in the configuration files for alertmanager and Prometheus.

**Comment by alexellis** [comment]
Can you link to one of the common helm examples so we can take a look?

**Comment by rawkode** [comment]
JG?

**Comment by alexellis** [comment]
I don't know which project JG is, but if you can link to it that'd be great.

I think we could do this, but with the proviso that OpenFaaS is not expected to work without manual interventions afterwards to configure Prometheus and AlertManager to your instances. You will also have to manually update your configuration files.

cc @rawkode @stefanprodan 

Alex

**Comment by rawkode** [comment]
Sorry, @alexellis; you said JG. I was asking what that meant :smile: 

I've started playing with Prometheus federation a lot more and collating to a higher level Prometheus, so FaaS running it's own is less offensive to me now. I'm happy to close this, as there's been no other interest.

**Comment by alexellis** [comment]
Haha "JG" seems to have been a typo on my part (possibly I dictated the message on my phone)

OK thanks again for the update and your recent PRs 😄 . I'm keen to see if other people comment on this too.

Alex
