### ISSUE TITLE
Proposal: Add ability to specify which namespace to run functions under.

### ISSUE THREAD

**Issue by weikinhuang** [openfaas/faas-netes#20]
Right now the entire setup is run under the default namespace regardless of if the yaml files specified a `namespace` key or not. It would be useful to give the user (cluster) a ability to specify an arbitrary namespace to run under (ex. `openfaas`, or `open-faas`, etc).

**Comment by weikinhuang** [comment]
It would also be useful to be able to specify a different namespace for control plane components and the function components.

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by alexellis** [comment]
This has been merged.
