### ISSUE TITLE
Question: Should be gateway's `upstream_timeout` changeable in the `values.yaml`

### ISSUE THREAD

**Issue by martin-liu** [openfaas/faas-netes#203]
Gateway support an env variable `upstream_timeout`, should be that configuable in the chart [configuration](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/values.yaml#L13)?

**Comment by alexellis** [comment]
Yes absolutely. I would merge a PR for this.

**Comment by alexellis** [comment]
@martin-liu 👍
