### ISSUE TITLE
Changes needed to install in multiple k8s namespaces with Helm

### ISSUE THREAD

**Issue by martin-liu** [openfaas/faas-netes#211]
I tried to install 2 openfaas envs in one k8s cluster's 2 different namespaces for different usage.
I'm using different helm release names, but the later installation will override cluster role and binding, hence the former env will not work.

## Expected Behaviour
It should be able to install openfaas seprately in multiple k8s namespaces

## Current Behaviour
The ClusterRole and ClusterRoleBinding is global across namespaces, and it's using a static name [faas-controller](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/rbac.yaml#L27), this will cause overriding issue

## Possible Solution
Add helm release name as suffix to the name of ClusterRole/ClusterRoleBinding, so that different release will use different name, the permission will not be overrided.

## Steps to Reproduce (for bugs)
1. install one release
```shell
helm upgrade --install openfaas openfaas/  \
  --namespace openfaas \
  --set functionNamespace=openfaas-fn
```
2. install another release
```shell
helm upgrade --install openfaas-dev openfaas/ \
   --namespace openfaas-dev \
   --set functionNamespace=openfaas-fn-dev
```

Then you'll find the first release will not work.

## Context
I'm setting up 2 envs for dev usage and prod usage

## Your Environment
k8s v1.9.2

**Comment by martin-liu** [comment]
Added pull request #212 for this issue.

**Comment by martin-liu** [comment]
@alexellis updated #212 to use Role/RoleBinding.

**Comment by alexellis** [comment]
We are working on this right now with @stefanprodan putting together the PR.

**Comment by alexellis** [comment]
Derek close: resolved by using a named prefix in helm. The ClusterRole needs to be removed.
