### ISSUE TITLE
Add annotations to schema, retaining labels

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#221]
Kubernetes has a preference for storing labels and metadata in "annotations" rather than in labels as we do currently.

OpenFaaS is an abstraction which has a top-level concept of labels which can store metadata - therefore we can just create our labels in annotations and retrieve them from annotations without affecting the interface to OpenFaaS.

## Example:

The following are abstract examples to show how this change should take place:

OpenFaaS Function:

```
Name: fn-1
Labels:
 - Git-Owner=alexellis
```

Kubernetes Deployment before:

```
Name: fn-1
Labels:
 - Git-Owner=alexellis
Annotations:
 - None
```

Kubernetes Deployment after:

```
Name: fn-1
Labels:
 - None
Annotations
 - Git-Owner=alexellis
```

The annotations may need to be scoped with a prefix such as `com.openfaas.` or placed inside a metadata object such as a map with a well-known key: `com.openfaas.labels: [ "k=v", "k1=v1" ]`

**Comment by LucasRoesler** [comment]
I think it is important to note that you can not filter on annotations, only labels are searchable. So, we should only move values to annotations that we do not need to use as filters.

**Comment by alexellis** [comment]
That's another way of doing it which I hadn't thought of. 

Here are some notes on Annotations vs. Labels. https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

**Comment by affix** [comment]
we still need to support annotations, not doing so breaks the ability to use the ingress-shim for ingress-nginx meaning people will need to manually modify their Ingress to use it

**Comment by LucasRoesler** [comment]
I thought you the cert-manager annotation goes on the ingress itself? For functions, we don't create an ingress. The only ingress would be for then gateway, which to support annotations, would be a change to the helm chart, for that use case.

**Comment by affix** [comment]
ahh sorry @LucasRoesler I mis-read this issue. I will open another around the helm chart, maybe a PR to resolve said issue

**Comment by dkozlov** [comment]
Will the following syntax be supported?
```
    labels:
      node-type: CPU
    constraints:
     - "node-type=CPU"
    requests:
      memory: 200Mi
```

**Comment by LucasRoesler** [comment]
@dkozlov  Both `constraints` and resource `requests` and `limits` are supported already for functions see #104 and #81 for example. Both are supported in Swarm and K8S with full support in the in the stack.yaml schema https://github.com/openfaas/faas-cli/blob/master/stack/schema.go

Currently, these optinos are not configurable for the core components (gateway etc) when deployed by the helm chart, but there is an issue for this #213

**Comment by wwsean08** [comment]
Currently playing around with getting this working, do we want to allow users to have labels added to their function at all, or just store all labels as annotations as they are currently setup.  The main issue I see from a backwards compatibility standpoint is that we'll need to either support the faas_function label in both the annotation and label or need to make this as a breaking change where existing functions can't be deleted.  I'd lean towards making it backwards compatible myself but just want to see what others thing.

**Comment by LucasRoesler** [comment]
How does listing functions work with only annotations? Are you listing all pods and then filtering that list on the annotation?  Selectors only work on the label field, as far I can tell from the documentation.  

I don't think there is a nice way to refactor this code to use annotations https://github.com/openfaas/faas-netes/blob/0d4f816096a5c84740d185101054f047dedb8eff/handlers/reader.go#L38-L45

I understand that "Kubernetes has a preference for ... annotations" but I think we should really document what _our_ goals are with labels.  List our use cases for labels in OF and then identify where the data goes.    Kubernetes specifically also says that **labels** should be used for _identifying_ data.  If OF Labels should behave like tags that a user can filter on, then they need to be in the k8s Label field.   If this data should be filterable via `kubectl`, then it also needs to be in the k8s Label field.  If we drop support for labels and put all information into the annotations, then we are implying that information _is not and should not_ be used to identify the object and is only accessible by actually requesting the object and looking at the annotation field. 

I use selectors frequently in building my own applications and even just for daily management.  From an operations/management perspective, having and controlling labels is very useful.

Additionally, what are the penalties for putting metadata into the labels? Is there a technical issue that we are trying to avoid? Considering that they are one of the few searchable fields, I assume there must be an index being built and maintained somewhere.   This must add some overhead to labels, but is it currently worth avoiding?

If we care about this distinction between labels and annotations in k8s, perhaps the most flexible thing to do is to support both fields in OF.  In Swarm both values would be mapped to labels.

**Comment by alexellis** [comment]
I'd like @stefanprodan to give his thoughts on the comment by @dkozlov 

https://github.com/openfaas/faas-netes/issues/221#issuecomment-397882839

As I remember it Stefan said that with the next Kubernetes version node-selectors will be deprecated and unavailable. 

This is a node-constraint which works with a label - if we only store labels in annotations then I would think this use-case would be broken.

```
    labels:
      node-type: CPU
    constraints:
     - "node-type=CPU"
```

Kubernetes will move to the much more complex [Affinity concept](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity). We'll need a way to abstract this concept into something we can represent in the YAML for Kubernetes, Swarm and Fargate (@edwilde)

This is explained in the issue but I'll re-iterate the key reasons for storing labels in annotations for Kubernetes:

* Labels only support limited values - a domain-name style regex - no config, no JSON, not even a date-time stamp or non-alpha character

In OpenFaaS Cloud we were storing a date-time stamp for the `Git-DeployTime` label, and this had to change to ticks which is much less readable to work with the Kubernetes label limit on valid values. We also have a field that contains Git-Repo / Git-Owner - if these fields in the source system support characters outside of the regex Kubernetes allows then we'll not be able to support those use-cases. Swarm allows any data in a label value.

* Kubernetes has strong opinions on what may be stored in Labels, [example issue](https://github.com/openfaas-incubator/openfaas-operator/issues/15)

This would be an implementation detail for the OpenFaaS API - so if you set labels for your function then queried it from the OpenFaaS API you'd see them assigned as labels. Behind the scenes we'd be placing these into a "bucket" or field in the annotations metadata and parsing it/returning it to you as labels.

**Comment by alexellis** [comment]
Perhaps another approach we could take is to allow `annotations` as a field for Kubernetes where we can store metadata. This would mean labels stay unmodified but still hold the same constraints, but for Swarm and Fargate we'd probably store this data inside a label.

```
annotations:
 Git-Owner: alexellis
labels:
 - node.type=GPU
```

`->`

Swarm internal representation:

```
labels:
  - annotations: { "Git-Owner": "alexellisuk" }
 - node.type=GPU
```

K8s internal representation:

```
annotations:
  - annotations: { "Git-Owner": "alexellisuk" }
labels:
 -node.type=GPU
```

**Comment by LucasRoesler** [comment]
Each of these examples and use cases for annotations make sense.  Also allowing users to set annotations could lead to interesting integrations with other k8s controller/operators.

My only real concern is around list/filter of functions. Right now I can currently query k8s for "the functions with label equal 'teamA'" or "the functions with label equal 'projectX'".  The only way I know to implement this with annotations is to stream all of the functions out of k8s and then filter that stream _or_ add a separate database/index into OpenFaaS.

Being able to set and filter on my own labels is important to how I currently interact with OpenFaaS.

**Comment by wwsean08** [comment]
I wasn't aware of the potential change to deprecate the node selector in kubernetes.  The representation of annotations that way you mentioned Alex is probably a good idea.  My knowledge on Swarm and Fargate is minimal but do they support dictionaries for labels or are you proposing setting `{ "Git-Owner": "alexellisuk" }` as a string in swarm?

**Comment by alexellis** [comment]
Another reason we need this is to be able to store JSON or CSV-type text in a value. When we want to map "topics" in a label/annotation for use with our event brokers such as the [Kafka broker](https://github.com/openfaas-incubator/kafka-connector). Right now we can't store arbitrary data or even a comma in the strict Kubernetes format.

i.e. 

Currently valid:

```
  name: audit-function
  labels:
    topic: "kafka.payment.received"
```

Currently invalid:

```
  name: audit-function
  labels:
    topic: "kafka_payment_received"
```


Currently invalid:

```
  name: audit-function
  labels:
    topic: "topic1,topic2,topic3,topic4"
```

**Comment by alexellis** [comment]
So @LucasRoesler @stefanprodan what do you want to do to move this forward? For several use-cases this is blocking progress on Kubernetes.

**Comment by alexellis** [comment]
@wwsean08 

```
The affinity feature consists of two types of affinity, “node affinity” and “inter-pod affinity/anti-affinity”. Node affinity is like the existing nodeSelector (but with the first two benefits listed above), while inter-pod affinity/anti-affinity constrains against pod labels rather than node labels, as described in the third item listed above, in addition to having the first and second properties listed above.

nodeSelector continues to work as usual, but will eventually be deprecated, as node affinity can express everything that nodeSelector can express.
```

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

**Comment by LucasRoesler** [comment]
@alexellis  for moving forward, I favor your proposal here https://github.com/openfaas/faas-netes/issues/221#issuecomment-399656087

**Comment by alexellis** [comment]
No word from Stefan yet, he may still be traveling. Any thoughts @affix?

**Comment by alexellis** [comment]
To summarise consensus from core contributors (Stefan/Lucas/myself) - we will take this approach:

* Labels remain unaltered
* Annotations will be added to schema.

See updated https://github.com/openfaas/faas/issues/682

This is a full end to end change from CLI to function schema to back-end handlers.

**Comment by alexellis** [comment]
This has been released and out in the open for a few months now.

**Comment by martindekov** [comment]
Should we close the issue then? ^

**Comment by alexellis** [comment]
@martindekov please do! Use Derek

**Comment by martindekov** [comment]
Derek close: released
