### ISSUE TITLE
Issue with AlertManager and Gossip (Kubernetes on DC/OS)

### ISSUE THREAD

**Issue by raditsp** [openfaas/faas-netes#224]
I'm trying to install faas-netes to Kubernetes on top of DC/OS. 
I ran this command 
`$ cd faas-netes && \ kubectl apply -f ./yaml
`
and it is working but the alertmanager won't start.

## Expected Behaviour

The alertmanager should run properly without any fails, and the auto scaler is working properly

## Current Behaviour

Currently, the alertmanager is failing with this error message in the logs:

` level=info ts=2018-06-21T15:16:26.512176938Z caller=main.go:145 msg="Starting Alertmanager" version="(version=0.15.0-rc.0, branch=HEAD, revision=68122e7005958df611baec01b316355a6f408bae)"
addrs 0.0.0.0:9094 
level=info ts=2018-06-21T15:16:26.512226406Z caller=main.go:146 build_context="(go=go1.10, user=root@46262c45c129, date=20180228-11:57:18)"
level=error ts=2018-06-21T15:16:26.518200226Z caller=main.go:166 msg="Unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided" `

## Steps to Reproduce (for bugs)

1. Install kubernetes on dc/os
2. clone faas-netes repo
3. install faas-netes namespace
4. `$ cd faas-netes && \ kubectl apply -f ./yaml`

## Context

I'm trying to test the auto scale but I think it wont works because the alertmanager is required for the autoscaling based on this docs https://docs.openfaas.com/architecture/autoscaling/

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.3.0

* What version and distriubtion of Kubernetes are you using? `kubectl version`
1.9.7

* Operating System and version (e.g. Linux, Windows, MacOS):
CoreOS

**Comment by alexellis** [comment]
Hi,

We are making use of this successfully on Kubernetes 1.9.6 and onwards. There was an issue with several of the Kubernetes `1.9.x` versions which were patched by Google.

I wonder if your Kubernetes version is accurate? `1.9` seems like you are missing the patch version.

Have you tried Googling the errors from AlertManager or raising an issue on the AlertManager GitHub repo? I don't believe this is an OpenFaaS code issue.

https://github.com/prometheus/alertmanager/issues

**Comment by raditsp** [comment]
@alexellis Hi, I've updated the kubernetes verison that I used. Yes, I think it is related with `cluster.listen-address` but I'm not sure how to get the cluster IP itself.

@stefanprodan thank you, going to check it 👍

**Comment by raditsp** [comment]
I've tried to follow @stefanprodan recommendation.

I update the alertmanager-dep.yml to add the `cluster.listen-address` like this:
```
- name: alertmanager
        image: prom/alertmanager:v0.15.0-rc.0
        imagePullPolicy: Always
        command: 
          - "alertmanager"
          - "--config.file=/alertmanager.yml"
          - "--storage.path=/alertmanager"
          - "--cluster.listen-address=$(POD_IP):6783"
```

the alertmanager is created but when I checked the error logs, another error appeared:

```
level=info ts=2018-06-22T10:51:03.250123008Z caller=main.go:145 msg="Starting Alertmanager" version="(version=0.15.0-rc.0, branch=HEAD, revision=68122e7005958df611baec01b316355a6f408bae)"
level=info ts=2018-06-22T10:51:03.250185551Z caller=main.go:146 build_context="(go=go1.10, user=root@46262c45c129, date=20180228-11:57:18)"
level=warn ts=2018-06-22T10:51:03.250221506Z caller=cluster.go:81 component=cluster err="couldn't deduce an advertise address: failed to parse bind addr '$(POD_IP)'"
addrs $(POD_IP):6783 
level=info ts=2018-06-22T10:51:03.252454971Z caller=main.go:271 msg="Loading configuration file" file=/alertmanager.yml
level=info ts=2018-06-22T10:51:03.257506202Z caller=main.go:346 msg=Listening address=:9093 
```

I assume if the alertmanager is not running properly, the autoscaling is not going to work, is it correct? @alexellis

**Comment by alexellis** [comment]
Stefan thanks for the input on this. The output from AlertManager is stating that it has not parsed the value `'$(POD_IP)'"`. @stefanprodan how did you want @raditsp to enter the value?

I don't believe this is a problem with OpenFaaS or our current configuration since it is working in our development clusters without issues.

As advised above please raise a ticket with the AlertManager maintainers. Happy to accept a PR to the AlertManager configuration if they can suggest a fix for your configuration.

**Comment by alexellis** [comment]
You can also search Google and the AlertManager repo for the error message. I did that and saw some issues which may be related:

- https://github.com/prometheus/alertmanager/issues/1323
- https://github.com/prometheus/alertmanager/issues/1323
- https://github.com/prometheus/alertmanager/issues/1341

The README file for their project states that you can set this value to `0.0.0.0:9094` - https://github.com/prometheus/alertmanager/blob/master/README.md#high-availability - not sure if this is relevant.

**Comment by stefanprodan** [comment]
@raditsp you used the Pod IP env var without providing it using the downward API. Take a look at the docs there is an example here https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
```
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

**Comment by raditsp** [comment]
@alexellis @stefanprodan thanks, I already include the podIP as env vars, and it worked

**Comment by Sangshaai** [comment]
> thanks, I already include the podIP as env vars

how did you config?
