### ISSUE TITLE
When using the Helm installer OpenFaaS Gateway doesn't work with Istio 

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas-netes#237]
When installing OpenFaaS with Helm on Istio enabled namespaces the Gateway pod enters `Init:CrashLoopBackOff`.

## Expected Behaviour

The Helm chart should offer on option that would allow Istio init container to run as root.

## Current Behaviour

The Gateway pod Istio init container errors out with:

```
iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```

## Possible Solution
Disable the Gateway security context.

## Steps to Reproduce (for bugs)

1. Install Istio
2. Add the `istio-injection: true` label to openfaas namepaces
3. Deploy OpenFaaS with Helm

## Your Environment

* GKE 1.10 with Istio 0.8

**Comment by alexellis** [comment]
This is due to the security policy added by the operator. The init Pod needs CAP_NET_ADMIN to intercept traffic. The workaround is to make the security policy optional. Is that what you had in mind?

**Comment by stefanprodan** [comment]
I made the security policy optional in the Helm chart. The PR is linked to this ticket
