### ISSUE TITLE
Rename faas-netesd -> faas-netes

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#240]
Now that with #225 we'll need to type more verbose commands to get the logs, let's make everything consistent by renaming the faas-netesd references to faas-netes.

```
kubectl logs -n openfaas deploy/gateway -c gateway
kubectl logs -n openfaas deploy/gateway -c faas-netesd
```

I think the consistency will help with new users.

Alex

**Comment by mrtind** [comment]
@alexellis  Can I take this one? It seems like something I can do.

**Comment by alexellis** [comment]
Go for it, it will need testing by removing the openfaas namespace and openfaas-fn then creating again after a couple of minutes.

**Comment by mrtind** [comment]
Should i change names of files and mentions of faasnetesd to faasnetes also?

**Comment by alexellis** [comment]
Thank you for this Martin!
