### ISSUE TITLE
Question: Can functions be restricted to certain users?

### ISSUE THREAD

**Issue by jrivera97** [openfaas/faas-netes#244]
I've deployed faas-netes with an ingress and basic auth in a k8s cluster. If I were to add users into the cluster, is there a way I could restrict functions in the openfaas-fn namespace to only be called by certain users? For example, an admin that could call any function, and then others with fewer privileges that could only invoke certain functions or not be allowed to create/deply their own. 

## Expected Behaviour
N/A

## Current Behaviour
N/A

## Possible Solution
Would the best approach be to use rbac? Or would it be easier to go through some other type of authentication

**Comment by ivanayov** [comment]
Derek add label: enhancement

**Comment by alexellis** [comment]
@jrivera97 could you give us an idea of the size of your organization and specific business use-case or regulatory requirements?

**Comment by jrivera97** [comment]
**Solution**
Deploying openfaas from GitHub instead of using the helm chart, you can reconfigure the yaml files to deploy separate instances of openfaas in dedicated namespaces, and set privileges for users with RBAC for each namespace the way you would for any other application on k8s. May look into the possibility of having only one instance of openfaas running in the cluster with multiple function namespaces, but I'm pleased with the solution, for now, closing issue.

**Comment by alexellis** [comment]
Hi @jrivera97 

NetworkPolicy in Kubernetes can provide good isolation between functions. There are examples available from @stefanprodan.

OpenFaaS is light-weight so you could also it multiple times in your cluster into openfaas-a / openfaas-a-fn and openfaas-b / openfaas-b-fn for instance. Flags are available for this in the helm chart, it makes it much easier than hacking on YAML - look into the [chart/openfaas folder for the README](https://github.com/stefanprodan/openfaas-flux).

Glad you found a solution that works for your use-case. You can connect with the community via https://docs.openfaas.com/community and are welcome to join Slack too.

Alex

**Comment by alexellis** [comment]
Instructions from @stefanprodan on installing OpenFaaS into different namespaces for staging/production or multiple teams. https://www.openfaas.com/blog/gke-multi-stage/

**Comment by alexellis** [comment]
Derek lock: inactive thread
