### ISSUE TITLE
Add scale_from_zero to helm chart

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#250]
The env-var `scale_from_zero` needs to be added to the helm chart for the gateway pod.

Default is false

This relates to work -> https://github.com/openfaas/faas/pull/685/files

Should also be documented in the README for the chart.

You also need to run `make charts` and bump the version number.

Add this to the ./yaml/gateway_dep.yml file too but as false.

Alex

**Comment by alexellis** [comment]
@viveksyngh

**Comment by viveksyngh** [comment]
I will be working on this one.
