### ISSUE TITLE
Turn off Prometheus LB in helm chart

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#260]
In the helm chart a LB is exposed for Prometheus which is unnecessary.

We should remove it. I don't think it makes sense to even make it an option. If multiple services need ingress then an IngressController would be more suitable and we have an option for that already.

**Comment by stefanprodan** [comment]
Assing this to me please

**Comment by alexellis** [comment]
Sure, next time you can use "self-service" with: "Derek assign: me"
