### ISSUE TITLE
Gateway: nats: no servers available for connection

### ISSUE THREAD

**Issue by maheshvra** [openfaas/faas-netes#265]
Since my org does not allow pulling images from public registry, pulled images and pushed to private registry, made required changes in faas-netes/yaml
`kubectl apply -f faas-netes/yaml`
deployed all components except `gateway`

## Expected Behaviour
All pods should be up and gateway endpoint url should be reachable

## Current Behaviour
Gateway pod failed. i.e. gateway-78947cc7f6-tv6pr        1/2       Error     1          3s

container logs: gateway
<pre>2018/07/27 19:28:47 HTTP Read Timeout: 35s
2018/07/27 19:28:47 HTTP Write Timeout: 35s
2018/07/27 19:28:47 Binding to external function provider: http://127.0.0.1:8081/
2018/07/27 19:28:47 Async enabled: Using NATS Streaming.
2018/07/27 19:28:47 Opening connection to nats://nats.openfaas.svc.cluster.local.:4222
2018/07/27 19:28:47 nats: no servers available for connection
</pre>

container logs: faas-netes

<pre>2018/07/27 19:25:47 HTTP Read Timeout: 10s
2018/07/27 19:25:47 HTTP Write Timeout: 10s
2018/07/27 19:25:47 Function Readiness Probe Enabled: true</pre>

container logs: nats

<pre>kubectl logs -f nats-6bb7bdf7cb-g9hqc -n openfaas
[1] 2018/07/27 19:20:51.186409 [INF] STREAM: Starting nats-streaming-server[faas-cluster] version 0.6.0
[1] 2018/07/27 19:20:51.186450 [INF] STREAM: ServerID: kOwMlMa9u5C5fk2GzUtNCb
[1] 2018/07/27 19:20:51.186456 [INF] STREAM: Go version: go1.9.1
[1] 2018/07/27 19:20:51.186679 [INF] Starting nats-server version 1.0.4
[1] 2018/07/27 19:20:51.186811 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2018/07/27 19:20:51.186818 [INF] Server is ready
[1] 2018/07/27 19:20:51.464361 [INF] STREAM: Message store is MEMORY
[1] 2018/07/27 19:20:51.464448 [INF] STREAM: ---------- Store Limits ----------
[1] 2018/07/27 19:20:51.464458 [INF] STREAM: Channels:                  100 *
[1] 2018/07/27 19:20:51.464465 [INF] STREAM: --------- Channels Limits --------
[1] 2018/07/27 19:20:51.464471 [INF] STREAM:   Subscriptions:          1000 *
[1] 2018/07/27 19:20:51.464476 [INF] STREAM:   Messages     :       1000000 *
[1] 2018/07/27 19:20:51.464482 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2018/07/27 19:20:51.464488 [INF] STREAM:   Age          :     unlimited *
[1] 2018/07/27 19:20:51.464494 [INF] STREAM: ----------------------------------</pre>

## Possible Solution
I did not face any issue deploying openfaas in my personal cloud account. I am facing this issue when using org. cloud account. Should i have any SG port/protocol open.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
<pre>Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true</pre>

* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
calico

**Comment by stefanprodan** [comment]
The connection to NATS takes some time, usually after 30s the gateway will be up.

**Comment by LucasRoesler** [comment]
@maheshvra can you share the output of `kubectl -n openfaas get po,svc` ?

**Comment by alexellis** [comment]
If the gateway doesn't appear to be ready then scale to deployment to zero and then back to 1 again.

**Comment by maheshvra** [comment]
@LucasRoesler 

<pre>
NAME                               READY     STATUS             RESTARTS   AGE
po/alertmanager-69d4d848d6-zz2js   1/1       Running            1          3d
po/gateway-78947cc7f6-tv6pr        1/2       CrashLoopBackOff   155        3d
po/nats-6bb7bdf7cb-g9hqc           1/1       Running            1          3d
po/prometheus-6d877b78f9-nwn46     1/1       Running            1          3d
po/queue-worker-5df596bdb5-jkglh   1/1       Running            6          3d

NAME               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
svc/alertmanager   ClusterIP   10.0.162.195   <none>        9093/TCP         3d
svc/faas-netes     ClusterIP   10.0.201.71    <none>        8081/TCP         3d
svc/gateway        NodePort    10.0.206.29    <none>        8080:31112/TCP   3d
svc/nats           ClusterIP   10.0.208.146   <none>        4222/TCP         3d
svc/prometheus     NodePort    10.0.77.124    <none>        9090:31119/TCP   3d
</pre>

<pre>
Name:           nats-6bb7bdf7cb-g9hqc
Namespace:      openfaas
Node:           10-205-80-28.mmst.aws-card-dqa.cb4good.com/10.205.80.28
Start Time:     Fri, 27 Jul 2018 15:20:48 -0400
Labels:         app=nats
                pod-template-hash=2663689376
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"openfaas","name":"nats-6bb7bdf7cb","uid":"2ac6743a-91d2-11e8-bbab-0e7db1cc5486","...
Status:         Running
IP:             10.10.70.94
Controlled By:  ReplicaSet/nats-6bb7bdf7cb
Containers:
  nats:
    Container ID:  docker://ceb95ad1d34d39599ae746c562bb143d96f03361872207a413c40917db6a840a
    Image:         artifactory.cloud.capitalone.com/ofaas/nats-streaming:0.6.0
    Image ID:      docker-pullable://artifactory.cloud.capitalone.com/ofaas/nats-streaming@sha256:97279123669f461b236a4fee74aeb8d2de0de64b1877989657c5c040e77becf3
    Ports:         4222/TCP, 8222/TCP
    Command:
      /nats-streaming-server
    Args:
      --store
      memory
      --cluster_id
      faas-cluster
    State:          Running
      Started:      Mon, 30 Jul 2018 07:32:07 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 27 Jul 2018 15:20:51 -0400
      Finished:     Fri, 27 Jul 2018 19:21:18 -0400
    Ready:          True
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cq8f9 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  default-token-cq8f9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cq8f9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:          <none>
</pre>

**Comment by LucasRoesler** [comment]
At first glance it seems like the correct components are there with the right values. When I looked at your original logs the nats address did seem a little odd though

```
nats://nats.openfaas.svc.cluster.local.:4222
```

There is an extra trailing dot. I won't have a chance tonight, but I will try it again on my machine and see if it has the same.

**Comment by LucasRoesler** [comment]
Looks like the trailing dot is intentional

**Comment by rgee0** [comment]
Ref trailing dot: 
https://github.com/openfaas/faas/issues/576

**Comment by alexellis** [comment]
Hi @maheshvra please can you follow my suggestion? Thanks

Alex

**Comment by alexellis** [comment]
```
kubectl scale -n openfaas deploy gateway --replicas=0
sleep 30
kubectl scale -n openfaas deploy gateway --replicas=2
```

**Comment by davidrama** [comment]
@alexellis hi did had the same issues and followed your suggestoin with no succes:
 $ kubectl -n openfaas get po,svc
NAME                                READY     STATUS             RESTARTS   AGE
pod/alertmanager-75d7c5f4f6-jmgrq   1/1       Running            0          22m
pod/gateway-79664fb67d-4hb27        0/2       Terminating        3          1m
pod/gateway-79664fb67d-mt9hj        1/2       CrashLoopBackOff   1          12s
pod/nats-86955fb749-tqslt           1/1       Running            0          22m
pod/prometheus-5bd4d5bd98-j2rsb     1/1       Running            0          22m
pod/queue-worker-557dff4dd5-bnzj4   1/1       Running            0          22m

**Comment by stefanprodan** [comment]
@davidrama I suspect there is a problem with Kubernetes networking. 

You could do a test with `nc` like this:

```
kubectl run -n openfaas -it --rm --restart=Never nc \
--image=quay.io/stefanprodan/podinfo:0.2.1 \
--image-pull-policy=Always \
-- sh

$ nc -v nats.openfaas.svc.cluster.local. 4222
```

See if that works or not.

**Comment by kirecek** [comment]
maybe it's related to this https://github.com/openfaas/faas-netes/issues/266

Check your if your kube-dns is using "cluster.local" domain.

**Comment by alexellis** [comment]
Derek close: resolved. A custom Kubernetes domain can now be specified via helm / env-vars in YAML

**Comment by cpani** [comment]
Hi,
I am facing this issue for connecting to Nats Streaming server. 
I have my server running 

[1] 2019/01/04 10:06:53.790584 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.11.2
[1] 2019/01/04 10:06:53.790624 [INF] STREAM: ServerID: xdbAYK8WyPNA0h68NJQaMk
[1] 2019/01/04 10:06:53.790629 [INF] STREAM: Go version: go1.11.1
[1] 2019/01/04 10:06:53.791115 [INF] Starting nats-server version 1.3.0
[1] 2019/01/04 10:06:53.791124 [INF] Git commit [not set]
[1] 2019/01/04 10:06:53.791214 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2019/01/04 10:06:53.791253 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2019/01/04 10:06:53.791260 [INF] Server is ready

When I try to connect from my client I am getting this error 

[Fatal]: Can't connect: nats: no servers available for connection.

Any help would be appreciated.

**Comment by alexellis** [comment]
Hi please can your open your own issue?

Alex

**Comment by alexellis** [comment]
Derek lock

**Comment by alexellis** [comment]
> When I try to connect from my client I am getting this error

I'm also not sure what you mean by "from my client", but I assume you don't mean by the queue-worker which is the only supported subscriber right now?

Please fill out a fresh issue.
