### ISSUE TITLE
x509 certificate error upon `git repo add`

### ISSUE THREAD

**Issue by nerdguru** [openfaas/faas-netes#269]
## Expected Behaviour
When following these instructions:

https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md

On minikube 0.28.0, the expected behavior happens just fine:
`$ helm repo add openfaas https://openfaas.github.io/faas-netes/
"openfaas" has been added to your repositories`

## Current Behaviour
But on GKE:

`$ helm repo add openfaas https://openfaas.github.io/faas-netes/
Error: Looks like "https://openfaas.github.io/faas-netes/" is not a valid chart repository or cannot be reached: Get https://www.openfaas.com/faas-netes/index.yaml: x509: certificate signed by unknown authority`

This occurs on both 1.9.7-gke.3, and 1.10.5-gke.0

## Possible Solution
There's some sort of redirect happening there from https://openfaas.github.io/faas-netes/ to https://www.openfaas.com/faas-netes/index.yaml, maybe something in there?

## Steps to Reproduce (for bugs)
Setting up Helm:

`kubectl -n kube-system create sa tiller \
 && kubectl create clusterrolebinding tiller \
      --clusterrole cluster-admin \
      --serviceaccount=kube-system:tiller`

Helm init:
`helm init --skip-refresh --upgrade --service-account tiller`

Set up namespaces:

`kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml`

Then the `helm repo add` fails.

**Comment by alexellis** [comment]
I was unable to reproduce the error on my GKE cluster using the upper version mentioned, but I'll look into this. It may be related to the blog which is served via GitHub pages. Please use the deployment instructions which use the GitHub repo instead of the http helm repo.

**Comment by ivanayov** [comment]
Derek add label: support

**Comment by alexellis** [comment]
I've not seen this mentioned again, so I'll close for now and re-open if other people see it.

Alex
