### ISSUE TITLE
Can't start OpenFaaS over Kubernetes

### ISSUE THREAD

**Issue by Kuvesz** [openfaas/faas-netes#270]
I have been trying to get openfaas to start for a while now, I always get the same result no matter what way I go about it, which is this:
```

NAMESPACE     NAME                                                                          READY     STATUS    RESTARTS   AGE
kube-system   coredns-78fcdf6894-6ncxh                                                      1/1       Running   0          6m
kube-system   coredns-78fcdf6894-s7shg                                                      1/1       Running   0          6m
kube-system   etcd-node1.szefoka-qv39694.cloudnet-pg0.utah.cloudlab.us                      1/1       Running   0          5m
kube-system   kube-apiserver-node1.szefoka-qv39694.cloudnet-pg0.utah.cloudlab.us            1/1       Running   0          5m
kube-system   kube-controller-manager-node1.szefoka-qv39694.cloudnet-pg0.utah.cloudlab.us   1/1       Running   0          5m
kube-system   kube-proxy-lf4bc                                                              1/1       Running   0          6m
kube-system   kube-scheduler-node1.szefoka-qv39694.cloudnet-pg0.utah.cloudlab.us            1/1       Running   0          5m
kube-system   weave-net-nlft8                                                               2/2       Running   0          5m
openfaas      alertmanager-6b69d64c7c-d8vvc                                                 0/1       Pending   0          3m
openfaas      gateway-6bc6f9f566-8znxj                                                      0/2       Pending   0          3m
openfaas      nats-74fc8944fb-57qlq                                                         0/1       Pending   0          3m
openfaas      prometheus-5db75b5d64-zvbn5                                                   0/1       Pending   0          3m
openfaas      queue-worker-76cc7f859c-gv6cf                                                 0/1       Pending   0          3m
```

## Expected Behaviour
I believe that every "Pending" should be a "Running".

## Current Behaviour
It's not changing from "Pending". I'm new to Kubernetes, so I probably don't know a lot of things that could be wrong.

## Steps to Reproduce (for bugs)
I installed Kubernetes based on this guide: https://www.techrepublic.com/article/how-to-quickly-install-kubernetes-on-ubuntu/
After that I installed OpenFaaS based on this guide: https://docs.openfaas.com/deployment/kubernetes/

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.06.0-ce

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 16.04.5 LTS

* What network driver are you using and what CIDR? i.e. Weave net / Flannel: Weave net atm, I tried Flannel before that.

Any help appreciated!

**Comment by stefanprodan** [comment]
What happens if you do `kubectl run --image=nginx nginx` does the nginx pod starts? I'm guessing you have a single node and by default no workloads are allowed to run on the master.

**Comment by Kuvesz** [comment]
@stefanprodan Hm, no it doesn't, I'll try bringing aboard another node and be back after that.

**Comment by Kuvesz** [comment]
@stefanprodan It seems to work now (well the containers are crashing all over the place, but they started), wow, thanks, I expected this to be more like Docker Swarm in that regards.

**Comment by stefanprodan** [comment]
Kubernetes is nothing like Docker Swarm ;)

**Comment by Kuvesz** [comment]
Yea, seems so. :)

**Comment by stefanprodan** [comment]
I would advise you to read the "Kubernetes Up And Running" book to familiarise yourself with the terminology and get a feeling on what Kubernetes is.

**Comment by Kuvesz** [comment]
I'll take a look at that than. Never suspected to get something to read when I aksed this question, but stil, thank you, it could help even though I should not be working with Kubernetes for that long.

**Comment by alexellis** [comment]
Glad you have managed to overcome those difficulties.

> well the containers are crashing all over the place, but they started

It sounds like your cluster may not be configured correctly. Perhaps a managed Kubernetes service would be a good starting-point like GKE? https://cloud.google.com/kubernetes-engine/ 

Alex

**Comment by alexellis** [comment]
Derek lock
