### ISSUE TITLE
Auth not working when getting data from script

### ISSUE THREAD

**Issue by amatzia** [openfaas/faas-netes#271]
When adding "basic_auth=true" flag to the helm chart the UI asks for username and password
but when running a python script to run a function from gateway no password is needed and data is returned

## Expected Behaviour
An exception on credentials should be raised

## Current Behaviour
Function can still work without credentials 

## Steps to Reproduce (for bugs)
1.Deploy chart with helm and add "--set basic_auth=true"
2.Write a basic python script to use request to return data
Example:
```
import requests
url = "http://$GATEWAY/function/$FUNCTION"
data = ""
response = requests.post(url, data=data)
print(response.content.decode("utf-8"))
```

## Context
Was expecting for the function running to be secure but they are still accessible 

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Tue Jan 30 09:17:00 2018
 OS/Arch:         linux/amd64

* What version and distriubtion of Kubernetes are you using? `kubectl version`

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS):
Centos 7

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Calico

**Comment by amatzia** [comment]
found a solution

**Comment by alexellis** [comment]
This is in the docs at https://docs.openfaas.com 😄
