### ISSUE TITLE
Update armhf images

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#274]
A build/push of each armhf image is required.

It would be good if there was a single script I could run on an ARM machine to generate all the required images and have them pushed with whatever the latest git tag happened to be (even if that isn't HEAD)

Alex

**Comment by alexellis** [comment]
```
./publish_arm.sh
```

Would be ideal if it could clone each of the repositories, do a `docker login` and then build all the images. If all pass, it should push them.

**Comment by rdimitrov** [comment]
@alexellis Seems it's already done.

**Comment by alexellis** [comment]
Thanks
