### ISSUE TITLE
Question: how does zero-scale work in OpenFaaS?

### ISSUE THREAD

**Issue by white-cloud** [openfaas/faas-netes#275]
Hello ,
I want to ask please about the cold start of the openfaas function ? if  we are not calling the function for a long period of time is the container would be deleted ?? or the container keeps always the stat running even if ze aren't using it .

Thank you.

**Comment by ivanayov** [comment]
Derek add label: question

**Comment by ivanayov** [comment]
Hi @white-cloud,

Your function container will be alive until it is stopped from an external process (for reference [watchdog/main.go#L74](https://github.com/openfaas/faas/blob/d8d6349b2b86d6f913a73cacb91ffc6017b2def6/watchdog/main.go#L74)).

If you configure it with `write_timeout`, this will be used as a grace period to finish jobs before the shut down.

You can use the [faas-idler](https://github.com/openfaas-incubator/faas-idler) do scale your function to 0 if it's not used for a given period and if you're using gateway v0.8.7 or higher, your function will scale back the first time it is invoked again.

Ivana

**Comment by white-cloud** [comment]
Hi @ivanayov  thank you for your answer 
so if i undertood right your explanation that mean that the default configuration is a function running always with no idle time, the container zill be aways running even after a long time of not calling the function it will be always active?

**Comment by alexellis** [comment]
Please see the blog post [Scale to Zero and Back Again with OpenFaaS](https://www.openfaas.com/blog/zero-scale/)

By default this behaviour is not enabled, so you will always have the [minimum availability you specify in your deployment](https://docs.openfaas.com/architecture/autoscaling/), which by default is 1. 

@ivanayov I'm not sure that is the correct definition of `write_timeout`. That only specifies the HTTP transport and dictates how long a function can keep a connection open to write a response to the caller.

@white-cloud are you wanting to enable zero-scale? If so let us know and we'll point you in the right direction. The leading question of "what is the cold start time" for "Zero-scale" is determined by how you configure your health-checks in Kubernetes.

**Comment by alexellis** [comment]
Please also see the documentation on zero-scale which I added today: https://docs.openfaas.com/architecture/autoscaling/#zero-scale

**Comment by white-cloud** [comment]
Thank you @alexellis im trying to read everything related to openfaas and get deeper with it , as im still beginner zith the function as a service term and using for the first time openfaas to deploy fnctions that,s why feeling a bit lost .
Thank you all for your help.

**Comment by xueli-daisy** [comment]
How can I check the openfaas container grace period? Is it in the document?
