### ISSUE TITLE
Enable variable timeouts for HTTP

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#28]
This matches the API gateway in the faas repo:

```
read_timeout - seconds as an integer
write_timeout - seconds as an integer
```

The code can be copied from read_config.go

**Comment by e-beach** [comment]
Doing.

Note that the code Alex is referring to is at https://github.com/alexellis/faas/blob/1aeb978617258da80a684121ce8b3e72e7201910/gateway/types/readconfig.go#L56-L57

**Comment by alexellis** [comment]
@e-beach are you working on this?

**Comment by alexellis** [comment]
Derek add label: hacktoberfest
