### ISSUE TITLE
Add zero-scale to Helm chart (turned on)

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#281]
## Expected Behaviour

Add the configuration to the gateway to enable zero-scale and make this enabled by default - provide a way to disable it showing this in the table of options.

Add faas-idler into the mix helm chart but with `--dry-run` set to true by default. Allow users to override this to false in the table of options.

## Current Behaviour

Zero scale is set to false and the idler is not included or packaged with the deployment. 

## Possible Solution

Update helm, and YAML.

**Comment by bartsmykla** [comment]
derek assign: me

**Comment by bartsmykla** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thanks for taking this Bart.
