### ISSUE TITLE
Make it clear how/where to change environment variable for ImagePullPolicy

### ISSUE THREAD

**Issue by Hellisotherpeople** [openfaas/faas-netes#292]
I am trying to build an OpenFaas workload. I want to use a prebuilt image that I know built correctly with faas-cli build. 

## Expected Behaviour
setting either an environment variable in the shell where I run faas-cli, or setting an environment variable somewhere in the function.yml file propegates s.t. kubernetes get deployment -o yml shows that the function pod has ImagePullPolicy = "IfNotPresent"

## Current Behaviour
ImagePullPolicy value does not propegate, and it's not clear where to change the environment variable to make this work for non-helm configurations

## Possible Solution
Make it clear in documentation of what file to change 

## Steps to Reproduce (for bugs)
single machine Minikube + Kubernetes setup on Fedora 27

**Comment by Hellisotherpeople** [comment]
To be clear, this should be a really simple question - but I need an answer ASAP. 

I am NOT using Helm, and do not want to for my workload

Basic python tutorial workloads fail because I am using a pre-built image that does not exist on dockerhub, hence why I want ImagePullPolicy=IfNotPresent

**Comment by LucasRoesler** [comment]
@Hellisotherpeople updated docs are coming soon that specifically address the image pull policy, checkout openfaas/docs#53

**Comment by Hellisotherpeople** [comment]
Thank you! My question is answered.
