### ISSUE TITLE
Add communication with apiserver testing when build in-cluster config

### ISSUE THREAD

**Issue by zouyee** [openfaas/faas-netes#294]
Add communication with apiserver testing.
## Current Behaviour

Currently， we could not check the health of client, it is a reasonable to support the health check.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by viveksyngh** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
/lock: closing as inactive. Feel free to raise a new issue if this is still required
