### ISSUE TITLE
Bump operator/gw/faas-netes to latest versions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#300]
Please bump the following for x86_64 in YAML and Helm.

* https://github.com/openfaas-incubator/openfaas-operator/releases/latest
* https://github.com/openfaas/faas/releases/latest
* https://github.com/openfaas/faas-netes/releases/latest

The operator contains an essential fix for reconciliation of deployments.

**Comment by stefanprodan** [comment]
Derek assign me

**Comment by stefanprodan** [comment]
Derek assign: me
