### ISSUE TITLE
Offer instructions for helm without Tiller

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#302]
## Expected Behaviour

I got some feedback from @jbeda regarding potential security issues with the way some people configure helm's server-side component called "Tiller".  We should offer an alternative in the helm chart / docs that shows how to use `helm template` to generate a set of YAML files for the user to apply with `kubectl`.

@stefanprodan shared that Istio are also doing this. https://istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template

## Current Behaviour

Nothing stops users from doing this, but we could make it easier with a one-liner and some context.

## Possible Solution

See above.

## Context

Joe has a good point and we could improve this.

I'm looking for this to come from the community, so "help wanted".

**Comment by LucasRoesler** [comment]
@alexellis I added some initial documentation to both faas-netes and to the docs repo

**Comment by alexellis** [comment]
👍

**Comment by alexellis** [comment]
Derek close: resolved by Lucas in official docs
