### ISSUE TITLE
 Deployment error: secret not found on Amazon EKS

### ISSUE THREAD

**Issue by anubhabMajumdar** [openfaas/faas-netes#303]
## Expected Behaviour
While using `faas-cli up -f <function_name>.yml`, expect the function to be deployed on Kubernetes.

## Current Behaviour
Operation fails with message 

> Unexpected status: 400, message: Deployment error: secret not found: mongo-pwd; possible choices: [secret-api-key]
> Function 'locationfunction' failed to deploy with status code: 400

However, the other secrets clearly exists as can be verified on using 
`kubectl get secrets -n openfaas-fn`

Output:

> NAME                        TYPE                                  DATA      AGE
default-token-vtc7m   kubernetes.io/service-account-token   3         8d
kong-pwd                    Opaque                                1         2d
kong-username          Opaque                                1         2d
mongo-pwd                Opaque                                1         3d
secret-api-key            Opaque                                1         2d

## Steps to Reproduce (for bugs)

1. I have faas-netes (version 0.8.9) running on Amazon EKS cluster. Faas-cli version is 0.7.3.
2. The faas-cli up command worked perfectly for over 50 times before this error showed up.

## Context

I cannot deploy new functions or modify existing ones.

## Your Environment

* What version and distriubtion of Kubernetes are you using?  v1.11.1

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

**Comment by alexellis** [comment]
Hi your secret needs to be deployed into the correct namespace. Please see the documentation site. 

Regards,

Alex

**Comment by anubhabMajumdar** [comment]
Hi Alex,
I have followed this [tutorial](https://docs.openfaas.com/reference/secrets/) and deployed secrets in namespace openfaas-fn. Infact this function was deployed successfully couple of days ago and working perfectly in Kubernetes. I just cannot deploy it back even though nothing has changed in terms of Kubernetes or Openfaas environment.

**Comment by alexellis** [comment]
I've updated my comment with some more details.

Could you also give the command you use to create the secret `mongo-pwd`?

Perhaps in the interim you could also try deleting your function with faas-cli remove` before attempting to deploy again.

The Kubernetes events log and faas-netes logs may give us some more information about the message. 

I generally would run:

```
kubectl -n openfaas-fn create secret generic mongo-pwd --from-literal mongo-username=alex --from-literal mongo-password=test1234
```

stack.yml
```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  has-mongo:
    lang: node
    handler: ./has-mongo
    image: alexellis/has-mongo:latest
    secrets:
     - mongo-pwd
```

Here's a quick test I did:

```
for I in {1..50} ; do sleep 1 && faas-cli up -f has-mongo.yml -g 127.0.0.1:31112 ; done
```

The results are as below:

```
Deployed. 202 Accepted.
URL: http://127.0.0.1:31112/function/has-mongo
```

Are you planning on working on this over the weekend? It's almost mid-night in Europe.

Alex

**Comment by alexellis** [comment]
I'll share my output from above in a gist for reference: https://gist.github.com/alexellis/faa835a780267dfc488085614d630668

**Comment by anubhabMajumdar** [comment]
- I have also updated my comment to include the log file and namespaces.
- I am deleting the function before trying to redeploy.
- I will try what you suggested about creating password. 
- I won't work over the weekend. Apologies for keeping you up.
Anubhab

**Comment by alexellis** [comment]
Last thought for the evening. What instances are you using for the EKS cluster specifically?

**Comment by alexellis** [comment]
Please add the event log asked for above. See the troubleshooting guide for more details and add the logs from faasnetes. See the guide for the commands to enter.

**Comment by anubhabMajumdar** [comment]
`kubectl logs -n openfaas deploy/gateway -c operator > operator_log.txt`

[operator_log.txt](https://github.com/openfaas/faas-netes/files/2407251/operator_log.txt)

I am using `t2.medium` aws instances.

Please let me know if I have attached the logs necessary for you to help. Thank you.
Anubhab

**Comment by alexellis** [comment]
Derek close: wrong repo

**Comment by alexellis** [comment]
Hi Anubhab,

This helps a lot! The issue is not with faas-netes but with the Kubernetes operator. You can switch to the more stable and battle-tested "faas-netes" by running the helm installation and passing false to the create operator flag. 

You may need to delete the helm deployment first with `helm delete --purge openfaas` and also delete the namespace before running the install again.

There's an issue with the operator in the very latest version. https://github.com/openfaas-incubator/openfaas-operator/issues/50

We are recommending faas-netes for production usage. 

Alex

**Comment by anubhabMajumdar** [comment]
Thank you so much Alex!

**Comment by alexellis** [comment]
I appreciate your patience and helping us get to the root cause. As a side-note we've also released a fix for the operator - https://github.com/openfaas-incubator/openfaas-operator/releases/tag/0.8.9

Let's catch up on Slack. 👍 

Alex
