### ISSUE TITLE
Deploy failed to find image secret (not an error - created in wrong namespace)

### ISSUE THREAD

**Issue by philippe-lavoie** [openfaas/faas-netes#306]
I'm trying to deploy and leverage AzureContainerServices from my own kubernetes.

## Expected Behaviour
Setting athena.yml
```
provider:
  name: faas
  gateway: http://127.0.0.1:31112

functions:
  athena:
    lang: node
    handler: ./athena
    image: myuser.azurecr.io/athena
    secrets:
      - acr-auth
```

then 
```
faas-cli deploy -f athena.yml
```
results in successful deployment

## Current Behaviour
Now, I get this

```
c:\athena>faas-cli deploy -f athena.yml
Deploying: athena.

Unexpected status: 400, message: secrets "acr-auth" not found

Function 'athena' failed to deploy with status code: 400
```

## Possible Solution
No clue....

## Steps to Reproduce (for bugs)
1. I did a docker login to my azure credential repository
2. add your secret
     kubectl create secret docker-registry acr-auth --docker-server https://myuser.azurecr.io/v2/ --docker-username myuser --docker-password SomeSecurePassword --docker-email myuser@somewhere.com

3. faas-cli push -f athena.yml   
4. faas-cli deploy -f athena.yml

Step 4 fails.

## Context
Need to use the corporate registry service inside Azure.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 18.06.1-ce, build e68fc7a

* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10

* Link to your project or a code example to reproduce issue:
I wanted to share after I test it :)

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
No clue

**Comment by stefanprodan** [comment]
You have to create the secret in the `openfaas-fn` namespace. Can you please try that?

**Comment by alexellis** [comment]
Off the top of my head you may need to select the namespace for openfaas when you create the pull secret or openfaas-fn. There's also a way to set this once - https://docs.openfaas.com/deployment/kubernetes/#link-the-image-pull-secret-to-a-namespace-service-account

**Comment by alexellis** [comment]
If that's the case perhaps we need to update that docs page for the first half?

**Comment by philippe-lavoie** [comment]
Guys, creating the secrete inside openfaas-fn allowed the faas-cli deploy command to work. Thanks for the suggestion! 

I'm keeping this close as I feel this should be mentionned somewhere in the docs. Thanks for the help guys.
