### ISSUE TITLE
Add  prometheus.io.scrape="false" wherever possible

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#325]
To follow up to #93 - seems like we missed some key services like NATS which were being scraped in my cluster. We should annotate all services with ` prometheus.io.scrape="false"` to prevent Weave Cloud from attempting to scrape endpoints which do not support this.

cc @stefanprodan

**Comment by alexellis** [comment]
The same should apply to any microservices inside https://github.com/openfaas/openfaas-cloud

**Comment by stefanprodan** [comment]
Derek assign :me

**Comment by stefanprodan** [comment]
Derek assign: me
