### ISSUE TITLE
Persistant Volume Claim in Helm

### ISSUE THREAD

**Issue by danieljrich** [openfaas/faas-netes#335]
If the node running OpenFaas dies or needs to be rebuilt, or Helm redeployed, all the functions running in openfaas need to be redeployed as well, as they are wiped out. If I create a PersistentVolumeClaim resource, where would that need to be mounted in order to store all the function data and retain it in the event of a redeploy. If there is another way I can retain those deployed functions, that is fine as well. Doesn't need to be a PVC.

## Expected Behaviour
When helm is applied or changes are made to OpenFaas, the functions are still loaded in OpenFaas after the rebuild.

## Current Behaviour
OpenFaas doesn't contain any functions after a rebuild.

## Possible Solution
Add PersistentVolumeClaim to helm charts for OpenFaas

## Context
In a production environment, if the nodes dies and Kubernetes automatically spins up a new one, there will be no functions to be invoked.

## Your Environment

* What version and distriubtion of Kubernetes are you using? `kubectl version`

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS):

AWS EKS
Kubernetes version: 1.10.0

* Potential changes:

# pcv.yaml
```{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "openfaas.fullname" . }}
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ template "openfaas.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end -}}
```
# values.yaml
```persistence:
  enabled: true
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  subPath: ""
  existingClaim:```

**Comment by danieljrich** [comment]
I'm sorry, I think I misunderstood the issue on my end. A co-worked originally came to me with this problem, but upon further testing it looks like when a node dies and is rebuilt, functions are retained. Only when helm is completely deleted or wiped out do the functions need to be redeployed. Which is totally expected. Thank you for your quick response, and sorry to waste your time!

**Comment by alexellis** [comment]
No problems @danieljrich - please feel free to join Slack and email alex@openfaas.com for the invite.
