### ISSUE TITLE
Remove command does not remove replicaset and pod objects

### ISSUE THREAD

**Issue by psyhomb** [openfaas/faas-netes#34]
Prior to Kubernetes v1.7 deletion basically requires four separate Kubernetes API requests, first one will scale down number of `pods` to zero, second will remove `deployment` object, third will remove `replicaset` object and finally last one will remove `service` object (exactly like `kubectl` is working), this method will leave no orphaned objects behind, basically it will execute a proper GC after deletion.

On the other hand, on older versions of Kubernetes, by default you will have situation where only `deployment` and `service` objects are removed and all other subordinate objects (`replicaset` and `pods`) will still be running on Kubernetes, this is definitely some kind of GC issue.

This issue has already been addressed for Kubernetes >=v1.7 [#44058](https://github.com/kubernetes/kubernetes/pull/44058).

That said, it would be nice if you can make it vertically compatible by applying proposed changes in to the [faas-netesd](https://github.com/openfaas/faas-netes/blob/master/handlers/delete.go) code.

Thanks

**Comment by alexellis** [comment]
@psyhomb thank you for raising this. It may explain why we saw this on Azure but not on newer 1.7 clusters. One other action we took around this was to move to update instead of delete/create.

**Comment by psyhomb** [comment]
@alexellis thank you for quick response and thank you for such a great tool

Cheers
