### ISSUE TITLE
Bump openfaas-provider to 0.8.0 and update function proxy implementation

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#341]
The openfaas-provider is now at v0.8.0, we should upgrade.  

## Possible Solution

This will require upgrading both the provider and gorilla mux, since the mux version was increased in the provider code. The new version also brings the [standardized function proxy implementation](https://github.com/openfaas/faas-provider/issues/9), we should update the faas-netes provider to use that implementation.

## Context

This is related to openfaas/faas-provider#9 and openfaas/faas#946

**Comment by alexellis** [comment]
Derek add label: design/approve
