### ISSUE TITLE
Namespace is not set for ingress

### ISSUE THREAD

**Issue by hullarb** [openfaas/faas-netes#350]
After deploying OpenFaaS with the helm generated, ingress enabled yaml: 
`helm template faas-netes/chart/openfaas     --name openfaas     --namespace openfaas      --set basic_auth=true     --set functionNamespace=openfaas-fn  --set ingress.enabled=true > openfaas.yaml`

The ingress was created in the default namespace and not in the openfaas namespace and faas-cli was not able to connect.

## Expected Behaviour
The gateway should be accessible through the ingress.

## Current Behaviour
Gateway is not accessible.

## Possible Solution
Add `namespace: {{ .Release.Namespace | quote }}` to the ingress template https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/ingress.yaml#L5

If the yaml is already generated one can add the `namespace: openfaas` line directly to the ingress specification.
If it's already deployed the ingress can be deleted and the ingress specification can be applied separately.

## Steps to Reproduce (for bugs)
Run the command above to generate the yaml and deploy it to a kubernetes cluster, then try to connect to OpenFaas.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
``` 
 CLI:
 commit:  5b36c50280d961d3aa248bd17f901f4ef2774447
 version: 0.8.1

Gateway
 uri:     https://openfaas.kube......
 version: 0.9.14
 sha:     a65df4795bc66147c41161c48bfd4c72f60c7434
 commit:  Update swagger for missing secret definitions


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.7.0
 sha:           ab9b56c0760eadba05762fa53dbe99d890bc9e19
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux/ Ubuntu 16.04
* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
Hi thanks for raising this issue. Would you like to work on a fix?

Just make sure you sign off the commits and double-check the contributing guide. 

Thanks,

Alex

**Comment by alexellis** [comment]
I generally install my ingress definitions into the `openfaas` namespaces with the core services and then I install nginx in the default namespace.

```
helm install stable/nginx-ingress --name nginxingress --set rbac.create=true
```

**Comment by hullarb** [comment]
Hi Alex,

Thanks for the quick response.  I would be happy to work on a fix, i think on the weekend i'll have some time to look into it.

Regarding the setup we have the nginx ingress installed in a separate namespace, but i think that should not make a difference in this case. The important part is still that the ingress resource and the backend service (gateway) should be in the same namespace.

Bela
