### ISSUE TITLE
Suggestion: add trailing dot to faas_nats_address

### ISSUE THREAD

**Issue by swachter** [openfaas/faas-netes#351]
Gateway and queue-worker pods can not connect to nats thereby preventing them from starting up.

## Expected Behaviour

Gateway and queue-worker pods can start up.

## Current Behaviour

The environment setting in the gateway and queue-worker deployments for faas_nats_address is "nats.openfaas.svc.cluster.local", i.e. without a trailing dot.

## Possible Solution

After I changed that setting to "nats.openfaas.svc.cluster.local." the nats service could be resolved in the gateway and queue-worker pod.

## Your Environment

OpenFaas was installed via helm.

* FaaS-CLI version ( Full output from: `faas-cli version` ):

version: 0.8.1

* Docker version `docker version` (e.g. Docker 17.0.05 ):

Docker version 18.06.1-ce, build e68fc7a

* What version and distriubtion of Kubernetes are you using? `kubectl version`

I run OpenFaas on minikube with --vm-driver=none

```Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}                                           
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}  
```
                                          
* Operating System and version (e.g. Linux, Windows, MacOS):

Linux

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
The trailing dot is not in my experience required. @stefanprodan removed this for compatibility with Istio. 

Are you using yaml or helm to install? 

I haven’t had issues with minikube working so I’m a bit confused why the trailing dot made things better. Maybe it was coincidental?

**Comment by swachter** [comment]
I used helm to install. Maybe it is because I use minikube with --vm-driver=none?

**Comment by alexellis** [comment]
If you have a few minutes can you try with using KinD? https://blog.alexellis.io/get-started-with-openfaas-and-kind/

Alex

**Comment by swachter** [comment]
Thanks for the link! KinD looks promising. I will look into KinD next week. (I have to do weekend shopping right now).

**Comment by swachter** [comment]
I tried to use `kind` tono avail (see below). The reason might be that I tried to use `kind` inside a VirtualBox.

```
    default: Creating cluster 'kind-openfaas' ...
    default:  • Ensuring node image (kindest/node:v1.12.3) 🖼  ...
    default:  ✓ Ensuring node image (kindest/node:v1.12.3) 🖼
    default:  • [control-plane] Creating node container 📦  ...
    default:  ✓ [control-plane] Creating node container 📦
    default:  • [control-plane] Fixing mounts 🗻  ...
    default:  ✓ [control-plane] Fixing mounts 🗻
    default:  • [control-plane] Starting systemd 🖥  ...
    default:  ✓ [control-plane] Starting systemd 🖥
    default:  • [control-plane] Waiting for docker to be ready 🐋  ...
    default:  ✓ [control-plane] Waiting for docker to be ready 🐋
    default:  • [control-plane] Pre-loading images 🐋  ...
    default:  ✓ [control-plane] Pre-loading images 🐋
    default:  • [control-plane] Creating the kubeadm config file ⛵  ...
    default:  ✓ [control-plane] Creating the kubeadm config file ⛵
    default:  • [control-plane] Starting Kubernetes (this may take a minute) ☸  ...
    default: time="12:17:10" level=error msg="failed to apply overlay network: exit status 1"
    default:  ✗ [control-plane] Starting Kubernetes (this may take a minute) ☸
    default: time="12:17:10" level=error msg="failed to apply overlay network: exit status 1"
    default: Error: failed to create cluster: failed to apply overlay network: exit status 1```

**Comment by swachter** [comment]
I prepare a small project to reproduce the problem.

**Comment by swachter** [comment]
Project to reproduce the problem: https://github.com/swachter/vagrant-minikube-openfaas

**Comment by alexellis** [comment]
I would like to know why this is the case only with Minikube with Vagrant and not with KinD/Docker for Mac/kubeadm or cloud Kubernetes - AKS/EKS/GKE and others? I'm also pretty sure Minikube works in a plain configuration because @martindekov uses that and @ivanayov 

Do you think it's worth an issue on the Minikube repo?

Alex

**Comment by acornies-tc** [comment]
@swachter Can you try the scenario with a native minikube installation and the virutalbox vm driver? I usually use Vagrant for more raw host-level provisioning.

**Comment by swachter** [comment]
> 
> 
> Have you tried Docker for Windows? it has Kubernetes support

That would be nice, Yet, we are still on Windows 7. AFAIK, Docker for Windows is available for Windows 10 only.

**Comment by swachter** [comment]
Is it possible that some timeouts are too thight? For example queue-worker fails many times with

```
Loading basic authentication credentials
Can't connect: nats: no servers available for connection
```
while all other deployments are available. After several minutes, the queue-worker deployment also succeedes.

(This may be a separate issue that is not related to the faas_nats_address.)

**Comment by swachter** [comment]
When I add the argument

```
--extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
```

to the minikube start command then pods enter the state much, much faster.

I tried if this change would make tweaking the `faas_nats_address` to the value `nats.openfaas.svc.cluster.local.` obsolete. The setup did start, however, it took considerably longer then with the tweak.

**Comment by alexellis** [comment]
Derek close
