### ISSUE TITLE
Test helm chart in CI using KinD

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#352]
## Expected Behaviour

We can test the helm chart and yaml files during builds by using the KinD tool in the Travis build it only needs Docker and kubectl to be installed. 

## Current Behaviour

Manual testing 

## Possible Solution

We should also run the certifier tool / tests as part of this work. 

Example:  

https://blog.alexellis.io/get-started-with-openfaas-and-kind/

https://github.com/openfaas/certifier

**Comment by alexellis** [comment]
Booting a KinD cluster took about 90s - adding 1m30s.

**Comment by zeerorg** [comment]
Are you working with this issue? Or can I take this up ?

**Comment by burtonr** [comment]
@zeerorg the `help wanted` tag indicates that it's up for grabs (as long as nobody else has mentioned they would take it). Let us know if you have any questions or need any help!

**Comment by zeerorg** [comment]
I think alex has done some work in this PR https://github.com/openfaas/faas-netes/pull/375

**Comment by burtonr** [comment]
hmm... looks like you're right. I guess this will have to wait until @alexellis can respond. I didn't see that change as there is no indication of that in the PR, only in the commit messages (and files changed)

good catch!

**Comment by alexellis** [comment]
I have started on this, but have deliberately left the testing stage unimplemented for the community to pick up.

**Comment by zeerorg** [comment]
I'll pick this issue up. I've been wanting to get more into e2e testing with kubernetes and this seems like a good starting point. 

We can also look at k3s for testing since it has lesser starting time, though it can be done later on to improve performance

**Comment by zeerorg** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
@zeerorg I was just chatting with @LucasRoesler and noticed that the certifier hadn't been done as part of #382.

I'd be happy for either of you to pick that up. I'll re-open the issue.

**Comment by zeerorg** [comment]
Ceritifer skipped my mind. I'll add that in a PR.

**Comment by zeerorg** [comment]
Derek assign: me

**Comment by alexellis** [comment]
@LucasRoesler would you like to take over please with a fresh PR?

**Comment by alexellis** [comment]
Basically, I would think a copy/paste of your instructions in the README of the certifier wouldn't be far off the mark.

**Comment by LucasRoesler** [comment]
Derek assign: me

**Comment by alexellis** [comment]
/lock: closing as inactive. Feel free to raise a new issue if this is still required
