### ISSUE TITLE
Multiple gateways are not detected by Prometheus

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#354]
## Expected Behaviour

If I have multiple gateway replicas in Kubernetes, I expect metrics to be scraped from each of them. This not the case with our current discovery based upon DNS-A records.

## Current Behaviour

The metrics are inconsistent and appear not to update.

## Possible Solution

Via Stefan we could use Pod discovery:

https://github.com/stefanprodan/k8s-prom-hpa/blob/master/prometheus/prometheus-cfg.yaml#L202

## Steps to Reproduce (for bugs)

1. Scale the gateway to > 1 replica and invoke a function
2. Use `kubectl port-forward` to bring back Prometheus to your local machine to look at the targets page for the amount of gateways being scraped.

## Context

This probably doesn't affect most users who I believe run only one gateway replica, however we recommend > 1 for HA.

Docker Swarm is unaffected.

## Your Environment

Present in the current version of helm / YAML config.

**Comment by alexellis** [comment]
This is a community project so the community is free to take responsibility for "movement" on things :smile:

As far as I can see nobody has volunteered to work on the fix. If you'd like you can try to do it and use the link provided by Stefan? You will also need to setup some RBAC permissions to allow Prometheus to list Pods.

**Comment by martindekov** [comment]
Hey Alex, I have set up Kubernetes Cluster on Digital Ocean for this one and it is nice to have OF instance in general somewhere, I won't be able to actively work on the Issue this and the next week since university is calling(exams). Just wanted to let you now in case this is critical issue.

**Comment by alexellis** [comment]
Let's see if anyone else can pick it up in #kubernetes?

**Comment by martindekov** [comment]
Ok I will ask
