### ISSUE TITLE
ARM64: Update the K8s deployment files

### ISSUE THREAD

**Issue by rdimitrov** [openfaas/faas-netes#356]
Related to the changes in https://github.com/openfaas/faas-netes/pull/331 and https://github.com/openfaas/faas/pull/995
## Expected Behaviour

Successful deployment of OpenFaaS on K8s using the latest images for ARM64
## Current Behaviour

The deployment files are not using the latest images for ARM64
## Possible Solution

Update the necessary files.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by rdimitrov** [comment]
@alexellis This can be considered as done, right?

**Comment by alexellis** [comment]
Yes next time put a closing keyword in your PR.

Fixes: X
Or
Closes: Y
