### ISSUE TITLE
Proposal: configure memory/CPU limits upon deployment

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#36]
## Expected Behaviour

This needs to sync with the main `faas` project, but the idea is to provide memory/CPU limits for functions as we create their deployment spec through the Kubernetes API.

## Current Behaviour

Unbounded.

## Possible Solution

Add to basic Create type in `faas` project.

Pass values onto the spec when doing a create/update.

**Comment by gardlt** [comment]
Is this to create memory/CPU limits on the helm chart and the kubernetes manifest?

**Comment by gardlt** [comment]
Could you please provide a little bit more detail on this. Is this adding resource limits in the helm and kubernetes manifest deployments?

**Comment by weikinhuang** [comment]
I believe this is for individual function deployments

**Comment by alexellis** [comment]
Yes this was for the functions created by the Kubernetes API. The OpenFaaS services are left unbounded at the moment.

**Comment by rayhero** [comment]
Currently how can we set the memory/CPU limits for functions in faas-netes??
