### ISSUE TITLE
Split armhf and ARM64 YAML files out to match x86_64

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#361]
## Expected Behaviour

Split armhf and ARM64 YAML files out to match x86_64

## Current Behaviour

The files are combined, but shouldn't be. They need to match the naming format in the yaml folder.

This change will only be accepted in a PR if it has been tested on device.

**Comment by alexellis** [comment]
Derek add label: help wanted

**Comment by rdimitrov** [comment]
@alexellis This can be considered as done, right?

**Comment by alexellis** [comment]
Let me know, if you're good then let's close this out.

**Comment by alexellis** [comment]
I'll close and can reopen if needed?
