### ISSUE TITLE
Status not ready for a function

### ISSUE THREAD

**Issue by JuniorCtba** [openfaas/faas-netes#374]
I have installed the openfaas in openshift using some older images and it was working.

Today i updated my images with the same version that you have on the master branch /yaml.

Everything almost looks good, i can deploy a new function and see that.

But i cant invoke function, because the status is not ready.

I saw in the container level and the function is up running.

![image](https://user-images.githubusercontent.com/13451867/53090215-8254cd80-34ed-11e9-93da-c7e7b9a75790.png)

**Comment by alexellis** [comment]
We're going to need way more detail than that. I'm closing the issue because you didn't fill out the issue template. Feel free to open a new issue with the template populated so that we can help you.

This lack of detail doesn't help us support you. 

Alex

**Comment by alexellis** [comment]
See also: https://docs.openfaas.com/deployment/troubleshooting/

**Comment by hikuley** [comment]
Status is  always "not ready" and my function logs like below

`WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.`

what should I do?

**Comment by alexellis** [comment]
Hi @hikuley 

We are currently offering commercial support via the [OpenFaaS Premium Subscription](https://www.openfaas.com/support) and I'd be happy to hear from you at sales@openfaas.com

You're also welcome to join Slack where you can see if the community has time to help you debug your issue.

Alex
