### ISSUE TITLE
Rename instances of "faasnetesd" to "faasnetes"

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#377]
## Actual vs. Expected Behaviour

We renamed "faasnetesd" to "faasnetes" in most locations but missed a few places in the helm chart.

## Possible Solution

Let's update the helm chart and re-test locally before pushing out a new version for consistency.

**Comment by marbar3778** [comment]
I can take this one

**Comment by alexellis** [comment]
@marbar3778 we now need to update all the docs where we see/have faasnetesd -> faasnetes including this:

https://docs.openfaas.com/deployment/kubernetes/#set-a-custom-imagepullpolicy

**Comment by alexellis** [comment]
Thank you @marbar3778 please can you respond to my message from a month ago?

**Comment by marbar3778** [comment]
Sorry, I made the changes and messaged you on slack for the pull requests to be merged, so I thought that solved it. From what I can see, I have updated throughout the repo, was it missed anywhere?
