### ISSUE TITLE
Setting write_debug triggers ReadString error

### ISSUE THREAD

**Issue by jpds** [openfaas/faas-netes#379]
## Expected Behaviour

I set `write_debug: true` in my only function's `environment` section as per this help section:

- https://docs.openfaas.com/deployment/troubleshooting/#function-execution-logs

....and the function started 404'ing. The gateway logs are full of:

```
openfaas/gateway-7847d555b9-64j77[operator]: E0305 14:40:43.742628       1 list.go:29] Function listing error: v1alpha2.FunctionList.Items: []v1alpha2.Function: v1alpha2.Function.Spec: v1alpha2.FunctionSpec.Environment: ReadString: expects " or n, but found t, error found in #10 byte of ...|e_debug":true},"imag|..., bigger context ...|...","write_debug":true},"image":"nnnnnnnn.dkr.ecr.eu-west-1.amazo|...
```

Changing it to `write_debug: "true"` and everything is fine.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.6.1

* What version and distriubtion of Kubernetes are you using? `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS): CoreOS

* What network driver are you using and what CIDR? Calico

**Comment by ivanayov** [comment]
Thanks for logging this @jpds . Do you reproduce the same with `openfaas-operator`?

**Comment by jpds** [comment]
@ivanayov This is with the operator.

**Comment by alexellis** [comment]
@jpds thanks for raising this. @ivanayov in future please post these into the Slack channel too in #kubernetes or #contributors.

I'll move it to the correct repo.

The faas-netes controller is much more stable, you could switch to that for now. I'll also notify @stefanprodan 

Alex

**Comment by alexellis** [comment]
I can't transfer this issue, please @jpds can you raise it on the openfaas-incubator/openfaas-operator repo?

**Comment by alexellis** [comment]
Just heard from @LucasRoesler - he said that you need to quote your boolean value for the "write_debug"

Fortunately this looks like "not an issue" 👍 

Alex

**Comment by jpds** [comment]
It kind of is an issue when following the documentation brings down the entirety of OpenFaaS...
