### ISSUE TITLE
wrong imagePullPolicy for faas-netes in helm chart

### ISSUE THREAD

**Issue by swachter** [openfaas/faas-netes#381]
The faas-netes container should use the openFaasImagePullPolicy and not the faasnetesd.imagePullPolicy.

Pull request #380 submitted.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I try local developments without a local registry.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
A new PR is needed for this work.

**Comment by alexellis** [comment]
faasnetes defines a pull policy for function images in this way:

```
faasnetes:
  image: openfaas/faas-netes:0.7.0
  readTimeout : "60s"
  writeTimeout : "60s"
  imagePullPolicy : "Always"    # Image pull policy for deployed functions
```
