### ISSUE TITLE
OpenFaas not working in an AKS with istio enabled 

### ISSUE THREAD

**Issue by Amardaya** [openfaas/faas-netes#391]
Openfaas in Azure K8s istio enabled is not working 

## Current Behaviour
faas-idler throwing error as shown below : 

     2019/03/19 05:36:08 invalid character 'E' looking for beginning of value
     2019/03/19 05:36:38 invalid character 'E' looking for beginning of value
     2019/03/19 05:37:08 invalid character 'E' looking for beginning of value
     2019/03/19 05:37:40 invalid character 'E' looking for beginning of value

and gatway returning null when it try to access /system/functions : 

    2019/03/19 06:13:40 <nil>
    2019/03/19 06:13:42 <nil>
    2019/03/19 06:13:46 <nil>
    2019/03/19 06:13:47 Forwarded [GET] to /healthz - [200] - 0.000703 seconds
    2019/03/19 06:13:50 Forwarded [GET] to /healthz - [200] - 0.003476 seconds
    2019/03/19 06:13:51 <nil>

i m able to access the gatway ui but enable to deploy or import a function, 

## Steps to Reproduce (for bugs)

1.  Install Istio in AKS cluster
2.  Install OpenFaaS with Helm

## Your Environment
* AKS Cluster  ver 1.12.6 
* FaaS-CLI version (0.8.5)
*Istio  ver 1.0.6

**Comment by stefanprodan** [comment]
Can you try it with OpenFaaS operator and se if the gateway works? 
https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/values.yaml#L49

**Comment by Amardaya** [comment]
yes thats one of the values that i set while installing open faas, here is below the helm command that i used to install openfaas : 

    helm repo update && helm upgrade openfaas --install openfaas/openfaas --namespace openfaas \
     --set functionNamespace=openfaas-fn \
     --set operator.create=true \
     --set basic_auth=true \
     --set exposeServices=false \
     --set operator.createCRD=true

**Comment by stefanprodan** [comment]
Any errors in the operator logs when you call `/system/functions`?

PS. The operator is running as a sidecar in the gateway pod.

**Comment by Amardaya** [comment]
interesting when i checked the log for the operator  here is what i found 

    E0319 13:48:39.390087       1 reflector.go:134] github.com/openfaas-incubator/openfaas-operator/pkg/client/informers/externalversions/factory.go:107: Failed to list *v1alpha2.Function: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/apis/openfaas.com/v1alpha2/namespaces/openfaas-fn/functions?limit=500&resourceVersion=0: EOF
    E0319 13:48:39.390377       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1beta2.Deployment: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/apis/apps/v1beta2/namespaces/openfaas-fn/deployments?limit=500&resourceVersion=0: EOF
    E0319 13:48:39.398316       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Service: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/api/v1/namespaces/openfaas-fn/services?limit=500&resourceVersion=0: EOF
    E0319 13:48:41.400428       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1beta2.Deployment: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/apis/apps/v1beta2/namespaces/openfaas-fn/deployments?limit=500&resourceVersion=0: EOF
    E0319 13:48:41.400428       1 reflector.go:134] github.com/openfaas-incubator/openfaas-operator/pkg/client/informers/externalversions/factory.go:107: Failed to list *v1alpha2.Function: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/apis/openfaas.com/v1alpha2/namespaces/openfaas-fn/functions?limit=500&resourceVersion=0: EOF
    E0319 13:48:41.401065       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Event: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/api/v1/namespaces/openfaas-fn/events?limit=500&resourceVersion=0: EOF
    E0319 13:48:41.405855       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Service: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/api/v1/namespaces/openfaas-fn/services?limit=500&resourceVersion=0: EOF
    E0319 13:48:43.411928       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Service: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/api/v1/namespaces/openfaas-fn/services?limit=500&resourceVersion=0: EOF
    E0319 13:48:44.415504       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Service: Get https://xxxxxxx.hcp.eastus.azmk8s.io:443/api/v1/namespaces/openfaas-fn/services?limit=500&resourceVersion=0: EOF

**Comment by stefanprodan** [comment]
You need to whitelist the API dmain. You can do that with a [service entry](https://istio.io/docs/concepts/traffic-management/#service-entries) for `xxxxxxx.hcp.eastus.azmk8s.io:443`

**Comment by Amardaya** [comment]
thx stefan 
that did the trick, i think we need to add this as part of AKS Istio OpenFaas Deployment check list
