### ISSUE TITLE
Suggestion: add NATS Streaming maximum payload option to helm chart

### ISSUE THREAD

**Issue by jpds** [openfaas/faas-netes#392]
## Current Behaviour

We have a function which when run asynchronously causes NATS to return this error:

```
nats: maximum payload exceeded
```

This is set to 1MB by default: https://nats.io/documentation/faq/#msgsize

And there doesn't appear to be a way to change this in the Helm chart.

**Comment by alexellis** [comment]
Derek set title: Suggestion: add NATS Streaming maximum payload option to helm chart

**Comment by alexellis** [comment]
Hi are you willing to look into this for yourself?

Generally I'd advise you use S3 or Minio to store large payloads for asynchronous requests. 

Alex

**Comment by alexellis** [comment]
@jpds if this is A) possible and B) you want to do this work then go ahead.

**Comment by alexellis** [comment]
/lock: closing as inactive. Feel free to raise a new issue if this is still required
