### ISSUE TITLE
(Maybe) missleading or deprecated note in the section "Deploy OpenFaaS"

### ISSUE THREAD

**Issue by kirladu** [openfaas/faas-netes#396]
## Expected Behaviour
Verify of installation according to https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md#verify-the-installation succeeds:

```
Calling the OpenFaaS server to validate the credentials...
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
credentials saved for admin http://1.2.3.4:8080
```

## Current Behaviour
If openfaas is deployed with Helm and the parameter '--set rbac=false' is set following the first note in section ["Deploy OpenFaaS"](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md#deploy-openfaas) verifying the installation with

```
export OPENFAAS_URL=http://...
echo -n $PASSWORD | faas-cli login -g $OPENFAAS_URL -u admin --password-stdin
```
leads to the following output:
```
Server returned unexpected status code: 500 - Error pulling metrics from provider/backend. Status code: 500
```

Googling for it I found this [issue post](https://github.com/openfaas/faas-cli/issues/382) with @burtonr commenting

> That blog post is a little outdated already (it's a fast moving project!) We have RBAC enabled by default on faas-netes. That could be the source of your troubles.

https://github.com/openfaas/faas-cli/issues/382#issuecomment-382574876

Which led me back to deploying openfaas with Helm once more, but this time without the parameter `--set rbac=false` - then it worked.

## Possible Solution
Since I didn't configure the cluster with role-based access control and `kubectl get nodes` shows me `<none>` in the ROLES column I followed the note guidance and used the `--set rbac=false` parameter.

Maybe it's clearer if the note is extended by the information that RBAC is enabled by default now. For me it was kind of missleading that I must pass the parameter, if RBAC wasn't configured - which I didn't do.

## Steps to Reproduce (for bugs)
```
helm repo update \
 && helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set functionNamespace=openfaas-fn \
    --set basic_auth=true \
    --set serviceType=LoadBalancer \
    --set rbac=false
```

## Context
The note made it harder for me to find out why I could call the GUI in browser, but couldn't verify the install successfully via CLI.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  bcff3a6bc8d066ba26233a0b5b0e2338476988e1
 version: 0.8.5

Gateway
 uri:     http://138.68.124.94:8080
 version: 0.11.1
 sha:     c394b09ae65177b3c6948b2c22b890068a8e6283
 commit:  Bump to nats-queue-worker 0.7.0

Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.7.0
 sha:           ab9b56c0760eadba05762fa53dbe99d890bc9e19

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 18.09.3, build 774a1f4

* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS):
Debian Stretch

**Comment by alexellis** [comment]
I'm really confused by this issue.

Are you claiming that using `--set rbac=true` caused an error at runtime on your chosen Kubernetes distro?

Alex

**Comment by alexellis** [comment]
You should always look at the defaults in the helm README file, in this case it's clearly documented that RBAC is enabled by default:

https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#configuration

Alex

**Comment by alexellis** [comment]
> What version and distribution of Kubernetes are you using? kubectl version

You didn't give the `distribution`.

I'm going to close this issue because I don't know what you're asking for me to do and the RBAC default is already documented.

Please feel free to keep commenting and raise a clearly actionable suggestion/issue or PR if needed.

Feel free to Join Slack for technical support

--
Join Slack to connect with the community
https://docs.openfaas.com

Alex
