### ISSUE TITLE
Question: can prometheus and alertmanager be optional?

### ISSUE THREAD

**Issue by botzill** [openfaas/faas-netes#398]
Hi.

Currently I did install prometheus and alertmanager via `prometheus-operator`, which is more advanced and has lot's of tools included(like grafana). Is there a way to disable deploying prometheus and alertmanager and instead use ones already installed? 

Thx.

**Comment by alexellis** [comment]
We could make Prometheus optional, but there is a caveat - you will then have to configure Prometheus on your own - manually. Do you want to carry that technical debt and maintenance?

Alex

**Comment by botzill** [comment]
Ho @alexellis. As said, `prometheus-operator` does it a lot more, include a complete list of suit tools needed for monitoring with predefined alerting rules for k8s. It's not an issue to use that, at least fo me,


Thx

**Comment by botzill** [comment]
So, just to make it clear, there are specific configurations in Prometheus and alert manager that are specific to the core of openfass?

**Comment by alexellis** [comment]
I think this should help: https://github.com/openfaas/faas-netes/tree/master/chart/openfaas/templates

Check-out the files and decide if you'd want to manually patch them into your Operator versions of Prometheus and AlertManager. If you have appetite for that then let's do the PR to the helm chart and document what people must do if they're using an "external" Prom/AlertManager.

Alex

**Comment by alexellis** [comment]
Ping @botzill

**Comment by botzill** [comment]
Hi. 

Sorry for delay.

Does this work without prom, alertmanager? 

Let say I don't want to use autoscale for now or other function, pure openfass, will it work?

**Comment by alexellis** [comment]
Hi this isn't really something that I would consider a core use case for the project. if you want to spend the cycles on it then I'm pretty sure that it should work without Prometheus. You'll need to configure it on your own with the various flags. 

Can you remind me what the objection was to using Prometheus in your stack?

**Comment by alexellis** [comment]
Alertmanager is used for the auto scaling and is optional..

**Comment by alexellis** [comment]
Closing as inactive.

**Comment by james-mchugh** [comment]
On a similar note, could faas-netes instead utilize prometheus-operator as a subchart instead of using templates to manage its own Prometheus?

**Comment by alexellis** [comment]
Feel free to play around on your own time, let us know on Slack when you find out the answer.
