### ISSUE TITLE
kafka-connector helm chart - make deployment name a parameter

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#400]
## Expected Behaviour

I should be able to install the kafka-connector helm chart twice into the same namespace with varying names such as:

```
kafka-connector-payments
kafka-connector-data-imports
```

## Current Behaviour

Can only be installed into the same namespace once

## Possible Solution

Allow the Deployment name to be overridden or suffixed 

See instructions for installing chart: https://github.com/openfaas/faas-netes/tree/master/chart/kafka-connector

**Comment by LucasRoesler** [comment]
I'll update it to to match the helm install name, that also needs to be unique already anyway

**Comment by alexellis** [comment]
What happens for helm charts like Postgres etc? Same/similar?

**Comment by LucasRoesler** [comment]
Postgres uses the "fullname"

```
{{- define "postgresql.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- printf .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

ours looks like this

```
{{- define "connector.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```

**Comment by alexellis** [comment]
I guess I don't understand how we get to `fullnameOverride` from a value defined as `fullname`? Is this some convention in helm?

Alex
