### ISSUE TITLE
Upgrade gateway to openfaas/gateway:0.12.0

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#402]
## Expected Behaviour

Upgrade gateway to openfaas/gateway:0.12.0

## Current Behaviour

On previous version. 

## Possible Solution

Update the YAML files and the helm chart. As part of this patch the configuration for Prometheus also needs to change so that the gateway is scraped on port 8082. 

## Steps to Reproduce (for bugs)

1. After updating the developer must test that autoscaling and metrics still work. 
2.
3.
4.

## Context

This version of the gateway removed the Prometheus handler and added it to a new HTTP port as mentioned. 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by alexellis** [comment]
I'll take this so that both Swarm / K8s are level.

**Comment by alexellis** [comment]
Derek close
