### ISSUE TITLE
Kafka Connector release 0.3.1 not in Dockerhub

### ISSUE THREAD

**Issue by martindekov** [openfaas/faas-netes#403]
When deploying with charts the Kafka-connector Since the image in dockerhub i 0.3.0 and the 0.3.1 release is not pushed image does not exist and it falls into ImagePullBackoff loop

## Expected Behaviour

`kafka-connector` deployed with charts

## Current Behaviour

ImagePullBackoff error due to missing image in dockerhub

## Possible Solution

Push kafka connector release [0.3.1](https://github.com/openfaas-incubator/kafka-connector/releases/tag/0.3.1) to dockerhub or revert Charts to use the already existing 0.3.0 tag.

## Steps to Reproduce (for bugs)

1. ```helm repo add openfaas https://openfaas.github.io/faas-netes/```
2. `helm upgrade kafka-connector openfaas/kafka-connector
    --install
    --namespace openfaas`
3. `kubectl get pods -n openfaas`

## Context

Tried to deploy the kafka-connector with charts and failed

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
dev
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.09.0
* What version and distriubtion of Kubernetes are you using? `kubectl version`
v1.13.3
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
N/A
* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Minikube

**Comment by alexellis** [comment]
What changed since @LucasRoesler created the chart?

**Comment by rgee0** [comment]
Lucas set it to 0.3.0.

[This](https://github.com/openfaas/faas-netes/commit/ceef3dd49ee77f5697b923e47f98be6820b6de3e#diff-8549d509288646f3270cecb4dd930285) set it to 0.3.1

**Comment by martindekov** [comment]
Minor thing, should we be pushing to `functions` rather than `openfaas`? I see faas-idler being in `openfaas` and `github-event` for example in functions?

**Comment by LucasRoesler** [comment]
When I created the chart, I simply used the value from the yaml, to make sure it matched.

**Comment by martindekov** [comment]
The problem was the CI in kafka-connector, it uses openfaas not functions, I opened PR to fix this.

**Comment by alexellis** [comment]
I want it to be OpenFaaS

**Comment by martindekov** [comment]
Sorry missed your comment I saw it now

**Comment by alexellis** [comment]
As in `openfaas/kafka-connector`.

I'm looking at this now.

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Chart updated and automated build fixed.
