### ISSUE TITLE
Feature: Configure ServiceAccount for functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#409]
## Expected Behaviour

I've had several requests from end-users to configure ServiceAccounts on a per-function level. We also have this need in OpenFaaS Cloud for several system-functions.

## Current Behaviour

Patch the pod spec after deployment 

## Possible Solution

My suggestion is that an annotation is documented which can be read by the Kubernetes operators and used to configure the service account on deploy / update.

For instance: 

```yaml
com.openfaas.service-account: create-pod
```

In the implementation the annotation would be used to determine whether to set the additional PodSpec field or not.

**Comment by Templum** [comment]
# Use-Case Vault Integration

## Description

We would like to leverage Vault inside the functions. Vault allows the obtaining of an access token via a Service Account. Which means we would need to assign a specific Service Account to a function as part of the K8S Deployment Object.

**Flow:** 
1. The function reads in the JWT of the Service Account which was mounted by Kubernetes.
2. The function requests an Access Token from Vault by providing the JWT + Vault-Role
3. Vault checks with K8S if the provided JWT is valid
4. Vault checks if the Service Account is registered with the specified Vault-Role
5. The function receives an Access Token, which can be used. Further, it can be renewed on-demand.

- More Information on the Vault Kubernetes Integration can be found [here](https://www.vaultproject.io/docs/auth/kubernetes.html).
-[ Example Go Code](https://github.com/sethvargo/vault-kubernetes-authenticator/blob/master/main.go) which performs the authentication flow

## Current Behaviour

This functionality is not yet supported. We found a working solution that patches the function deployment and just adds the Service Account. However, this is not a clean approach. As the function has for a short period no access to the required Service Account Token, which could lead to failing requests. Further during the patch, it will also be unavailable shortly.

 **Flow:** 
1. Deployment via faas-cli
2. Patching of the created deployment via K8S (Rest) Api === kubectl patch

**Comment by alexellis** [comment]
Please can you give the command for `kubectl patch` so that I can understand exactly what fields you are editing?

**Comment by Templum** [comment]
Added it
