### ISSUE TITLE
Helm and RBAC question

### ISSUE THREAD

**Issue by inge4pres** [openfaas/faas-netes#41]
On a fresh 1.7.5 minikube `helm` fails to deploy a release of openfaas due to RBAC rules inclusion with the error

## Expected Behaviour
`helm install --name openfaas --set async=true  ./openfaas/` should return the release details.

## Current Behaviour
```
Error: release openfaas failed: clusterroles.rbac.authorization.k8s.io "faas-controller" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["update"]}] user=&{system:serviceaccount:kube-system:tiller acb814ed-ab9a-11e7-ab23-1673569d708d [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]
```

## Possible Solution
You can still install openfaas via Helm skipping use of RBAC with
`helm install --name openfaas --set async=true --set rbac=false ./openfaas/`

## Steps to Reproduce (for bugs)
1. install minikube and start a new cluster (1.7.5)
2. follow the HELM.md steps to install Helm and Tiller with RBAC

## Context
This is preventing use of openfaas via Helm with default settings

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Version:      17.09.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Faas-Netes

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

**Comment by inge4pres** [comment]
Trying to debug the reason of the failure in openfaas/templates/rbac.yaml

**Comment by alexellis** [comment]
Have you run in the additional role needed for RBAC in the helm guide?

**Comment by alexellis** [comment]
We do have a `rbac=true/false` switch also. RBAC is on by default.

cc/ @weikinhuang

**Comment by weikinhuang** [comment]
Right now it's trying to create a cluster role. We should change it to use a regular role when functions are not being deployed to a separate namespace.

Or in the meantime give your user cluster-admin privileges.

**Comment by gardlt** [comment]
Was having similar problems also with this you can do `helm install local/openfaas --set rbac=false` and it should work fine, i think there is a permission issue when deploying additional rbac rule with `qinikube`

**Comment by weikinhuang** [comment]
I'll try to get around to making the needed fix next week

**Comment by inge4pres** [comment]
@alexellis yes I assigned RBAC role to Tiller but it looks like the issue is not there. 
However I tried with a GKE cluster just installed and everything works ok.
At this point it might just be a minikube issue.

Some details on my installation:
```
minikube version
minikube version: v0.22.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-09-29T05:56:06Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-10-06T20:53:14Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by inge4pres** [comment]
Great news! The chart works perfectly in 1.7.6 with RBAC too: `helm install --name openfaas --set async=true ./openfaas` works perfectly with k8s 1.7.6 but that version is still not in the stable channel for minikube hence requires additional parameters to install.

So for minikube users:
* update to latest minikube (v0.22.3)
* bootstrap cluster with `minikube start --kubernetes-version v1.7.6 --bootstrapper kubeadm [--vm-driver ...]` as mentioned in [minikube/issues/2003](https://github.com/kubernetes/minikube/issues/2003) 

As I was planning a PR to refine HELM.md, I will put the steps in there if you agree.

**Comment by alexellis** [comment]
Elliott @elliotbeach and myself have been deploying with `minikube` via the YAML files. I'll try with rbac=false on my Mac with `helm` this week and see how that goes.

**Comment by alexellis** [comment]
@inge4pres @weikinhuang where did we get on this?

**Comment by weikinhuang** [comment]
Looks like a minikube issue from @inge4pres's comments. However we can probably switch to using a `Role` instead of a `ClusterRole` when not deploying functions to a different namespace.

**Comment by alexellis** [comment]
Please could you run with this?
