### ISSUE TITLE
Switch to httpProbe for liveness/readiness

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#413]
## Current Behaviour

The use of "exec" probes for liveness and readiness is required for software like the current incarnation of Istio, but can be very inefficient. [In Swarm this seems pronounced](https://github.com/moby/moby/issues/39102), but in Kubernetes less so.

## Possible Solution

HTTP Probes are now supported in the OpenFaaS watchdogs via `/_/health`. We should change over to httpProbes by default for liveness/readiness as soon as possible.

Some functions in the store may need to be rebuilt before the release is done and the helm chart is cut over to the new version to ensure that they have a compatible watchdog.

## Steps to Reproduce (for bugs)

1. This is available as a flag, added by VMware last year

## Context

Increasing efficiencies - especially at "idle"

There is also a chance that HTTP probes may reduce cold-start time from scaling from zero or rolling over to a new version of a function.

Once fully tested this needs to be repeated in the operator.

**Comment by stefanprodan** [comment]
I see no harm in doing this if we have a flag in Helm that can let a Istio user to switch to exec. The http probes will work with Istio 1.2 see https://preliminary.istio.io/help/ops/setup/app-health-check/#probe-rewrite

**Comment by LucasRoesler** [comment]
Seems like a good usecase for helm's template helpers to keep the deployment yaml clean
