### ISSUE TITLE
chart: kafka-connector - prevent Prometheus scraping

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#416]
## Expected Behaviour

The kafka-connector deployment from the kafka-connector chart does not contain a Prometheus endpoint so shouldn't be scraped. 

## Current Behaviour

Weave Cloud will try to scrape and the Prometheus Operator may also try. 

## Possible Solution

See the annotations of other components: https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/queueworker-dep.yaml#L18

## Steps to Reproduce (for bugs)

1. Check for `prometheus.io.scrape: "false"` on the PodSpec

**Comment by alexellis** [comment]
@martindekov PTAL?

**Comment by martindekov** [comment]
So the helm should apply this annotation in order to stop trying to scrape metrics from prometheus, should this be added to the yaml file deployment in the kafka connector repo also?

**Comment by alexellis** [comment]
Please
