### ISSUE TITLE
Update ARM YAML files to use multi-arch images for Prometheus

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#422]
## Expected Behaviour

Given that Prometheus now publishes Docker images for Prometheus in a multi-arch format, we should move to use those images instead of the ones we build and maintain in the openfaas/faas/contrib folder.

## Current Behaviour

We build them via the openfaas/faas/contrib folder on each device then update as needed. 

## Possible Solution

Update `yaml_arm64`, `yaml_armhf` and `docker-compose.yml` files in the openfaas/faas repo.

## Dependencies

Keep an eye on: https://github.com/prometheus/prometheus/pull/5031#issuecomment-486565748 for when the images will be published.

**Comment by alexellis** [comment]
@zeerorg @viveksyngh please could you both take this? It covers Swarm + K8s.

**Comment by viveksyngh** [comment]
I will take this one.

**Comment by viveksyngh** [comment]
Should we also update the prometheus version to `v2.10.0` for `linux/amd64`?

**Comment by alexellis** [comment]
Yes

**Comment by alexellis** [comment]
Run a smoke test of auto-scaling up and then back down in response to load generated with `hey`. Instructions are in the workshop Labs for that.

**Comment by alexellis** [comment]
Linked issue: https://github.com/openfaas/faas-netes/issues/461
