### ISSUE TITLE
Proposal generate the static yaml manifests from the helm chart

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#423]
## Context

We could simplify the maintenance and ensure the consistency of the Helm chart and the static yaml manifests by using the `helm template` command to generate the static files.  This will require some additional modifications to remove the helm specific labels/annotations.

Generating the manifests will ensure that they stay in sync with any changes in the Helm chart.

**Comment by alexellis** [comment]
Derek close
