### ISSUE TITLE
Possibility to deploy function on setup

### ISSUE THREAD

**Issue by botzill** [openfaas/faas-netes#437]
Hi.

I was wondering if it's possible to configure, via the heml chart, to install by default a list of functions? Let say I want to install it and by default have `ocr` of other functions. How can we achieve that? 

Thx.

**Comment by LucasRoesler** [comment]
Seems like something that could possibly done as an optional `Job` that is deployed at startup. The only issue is waiting for the gateway health check to succeed before running the Job, i am not sure how we would ensure that it waits for OF to finish starting.

**Comment by botzill** [comment]
Hi @LucasRoesler. 

I see, yes it's may be challenging but find it useful when doing all the DevOps part and want to automate this, especially if we have multiple envs.

So, I think that this can be done using a `Job` as you say. If the `Job` fails because no `gateway` then it will retry, fail and retry until it succeeds.  

No?

**Comment by LucasRoesler** [comment]
You should be able to do a loop requesting against `/system/info` to check if the gateway is up.  Allowing the job to restart _should_ work, but I think it makes sense to try and check for the gateway first. 

If you want to give the Job access to the k8s api (via RBAC) then you could also use `kubectl rollout status deploy gateway` to block until the gateway passes health checks.

**Comment by alexellis** [comment]
What's the usecase?

OpenFaaS functions can be bundled in helm charts using the CRD.

**Comment by alexellis** [comment]
Closing as inactive / answered.

Feel free to keep commenting.

--
Join Slack to connect with the community
https://docs.openfaas.com
