### ISSUE TITLE
Trouble to get OpenFaas pods running - Queue-worker and Gateway pods in CrashLoopBackOff

### ISSUE THREAD

**Issue by hnanchahal** [openfaas/faas-netes#439]
Trying to install Openfaas on our Kubernetes cluster but the queue-worker and gateway pods keep crashing.

### Expected Behavior
All Openfaas pods should be running.

-----------------------------------------------------------------------------------------------------------------

### Current Behavior
![image](https://user-images.githubusercontent.com/16055046/58506357-fda8c980-8143-11e9-99db-d49500299adb.png)

### Pod Logs

kubectl logs queue-worker-7dcdb9c48b-nz768 -n openfaas
Loading basic authentication credentials
**_Connect: nats://nats.openfaas.svc.XXXXXXXX.net:4222
can't connect to nats://nats.openfaas.svc.XXXXXXXXXX.net:4222: nats: **no servers available for connection
panic: can't connect to nats://nats.openfaas.svc.XXXXXXXXX.net:4222: nats: no servers available for connection**_**

### **Your Environment**

- Docker version 

**Client**: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

**Server**: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- What version and distribution of Kubernetes are you using?

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

###  **Queue Worker Pod**

kubectl describe pod queue-worker-7dcdb9c48b-ftnl8 -n openfaas

![image](https://user-images.githubusercontent.com/16055046/58506775-0d74dd80-8145-11e9-85aa-e0a3e43c6cd4.png)
### **Gateway Pod**
kubectl describe pod gateway-647f77d9dc-fnnwh -n openfaas

![image](https://user-images.githubusercontent.com/16055046/58506931-66447600-8145-11e9-9559-bdabdc7db294.png)

**Comment by martindekov** [comment]
Hello @hnanchahal 

Sorry for the delay on this one, I am not sure why I there is only one container in the gateway pod.

Can you tell me how did you deploy OpenFaaS? There should be `faas-netes` and `gateway` containers in the gateway pod.

**Comment by martindekov** [comment]
Derek add label: support

**Comment by alexellis** [comment]
Just a thought. Have you been through the troubleshooting guide? It tells you how to debug including getting:

* Events
* Logs
* And output from kubectl describe

Did you install with helm or YAML?

Are you running on Kubernetes, which version *and* distribution?

Do you have your basic auth secret?

**Comment by hnanchahal** [comment]
> Hello @hnanchahal,
> 
> Sorry for the delay on this one, I am not sure why there is only one container in the gateway pod.
> 
> Can you tell me how did you deploy OpenFaaS? There should be `faas-netes` and `gateway` containers in the gateway pod.

Yes there are two containers in the gateway pod:

![image](https://user-images.githubusercontent.com/16055046/58649164-438a9c80-82c0-11e9-801a-a3fcf2d9baa8.png)

![image](https://user-images.githubusercontent.com/16055046/58649199-57360300-82c0-11e9-89d1-32ec7d168859.png)

**Comment by hnanchahal** [comment]
> Just a thought. Have you been through the troubleshooting guide? It tells you how to debug including getting:
> 
> * Events
> * Logs
> * And output from kubectl describe
> 
> Did you install with helm or YAML?
> 
> Are you running on Kubernetes, which version _and_ distribution?
> 
> Do you have your basic auth secret?

Thanks Alex for your reply. I am using the Helm chart to deploy OpenFass
https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md

Kubernetes version:
![image](https://user-images.githubusercontent.com/16055046/58649375-cd3a6a00-82c0-11e9-9c24-0f782c9967f3.png)

We are using rancher for the distribution: kubernetes_version: v1.13.4-rancher1-1

Yes i do have a basic auth:
![image](https://user-images.githubusercontent.com/16055046/58649599-594c9180-82c1-11e9-934d-725f618a88b1.png)

I was trying to understand the error and came across some other blogs with similar errors. I do not see core.Local when i list the DNS. The only DNS i see is what we have configured with xxxxxx.net. I also tried passing this in as an overwrite to the helm but got the same error.

**Comment by alexellis** [comment]
Please can you seek support / help from the Rancher community directly? I know of at least a dozen people using Rancher 2 successfully with OpenFaaS. You might want to try asking on our Slack group. As far as I know, they have a vanilla config.

Is there anything in your config that would be causing this problem?

--
Join Slack to connect with the community
https://docs.openfaas.com
