### ISSUE TITLE
Use curl | sh for getting license-check in all Dockerfiles

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#450]
## Expected Behaviour

We should use curl | sh for installing license-check in all Dockerfiles. This change would track the latest version and appropriate binary for the architecture.

## Current Behaviour

We only get a specific version via curl.

## Possible Solution

See faas-cli / faas repos on how we did it there.

**Comment by zeerorg** [comment]
I took a look at how it is done for faas-cli. Where does this need to be added. I'll pick this task up

**Comment by alexellis** [comment]
Dockerfile.* please

And then check openfaas-operator after that.

**Comment by alexellis** [comment]
@zeerorg how are we doing with this? Feel free to use Derek to close if we're done now

**Comment by zeerorg** [comment]
Derek close
