### ISSUE TITLE
Revisit: Istio forcing use of execProbe

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#455]
Revisit: Istio forcing use of execProbe

## Expected Behaviour

execProbe can use additional CPU cycles compared to httpProbe

## Current Behaviour

We use execProbe in the core services due to issues with Istio blocking httpProbes from the kubelet due to mutual TLS.

https://github.com/istio/istio/issues/2628#issuecomment-358111686

For the functions it's a config option to use httpProbe or execProbe, you can pick. If you pick httpProbe and use Istio, it may not work however.

## Possible Solution

For core services:

Revisit current versions of Istio to see if this is still a problem and change exec checks to httpProbe

For functions

No action required, we have already documented that httpProbe is available.

@stefanprodan please update note about the operator not supporting this since it does now.

**Comment by stefanprodan** [comment]
If we want to break compatibility with Istio 1.0 mTLS we can switch back to http probes and use the `sidecar.istio.io/rewriteAppHTTPProbers: "true"` annotations that works with Istio >1.1

**Comment by alexellis** [comment]
Hmm, what does `rewriteAppHTTPProbers` do?

**Comment by alexellis** [comment]
Thanks for the update @stefanprodan 

@ibuildthecloud, since you mentioned this yesterday I wondered what you are doing in Rio around this, or whether health-checks are being used in your core services and endpoints at this time?

**Comment by stefanprodan** [comment]
@alexellis form Istio docs:

Kubernetes HTTP health check request is sent from Kubelet, which does not have Istio issued certificate to the liveness-http service. So when mutual TLS is enabled, the health check request will fail. Probe rewrite: this approach rewrites the application PodSpec readiness/liveness probe, such that the probe request will be sent to Pilot agent. Pilot agent then redirects the request to application, and strips the response body only returning the response code.

https://istio.io/docs/ops/setup/app-health-check/

**Comment by alexellis** [comment]
/lock: closing as inactive. Feel free to raise a new issue if this is still required
