### ISSUE TITLE
Warning when deploying function

### ISSUE THREAD

**Issue by codyde** [openfaas/faas-netes#46]
When I perform a faas-cli deploy -f function.xml against my kubrnetes cluster, I receive the message "Server returned unexpected status code 500 deployment.extension 'function name' not found". The function works fine, no issues with using the function - it appears to be a cosmetic error but I can't determine the origin. 

## Expected Behaviour
I would expect the functions to deploy without the error message displaying OR provide more details around why the error was occurring. 

## Current Behaviour
When I perform a faas-cli deploy -f function.xml against my kubrnetes cluster, I receive the message "Server returned unexpected status code 500 deployment.extension 'function name' not found".

## Possible Solution
Provide additional details regarding the error message that's being triggered

## Steps to Reproduce (for bugs)
1. From a command line, run faas-cli deploy -f functions.xml 
2. Functions deploy and message is thrown 
3. Calling functions is successful with no errors displayed 

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Faas-Netes

* Operating System and version (e.g. Linux, Windows, MacOS):
CentOS 7 

* Link to your project or a code example to reproduce issue:
Examples of the code im deploying are here - https://github.com/codyde/faas-functions/

**Comment by alexellis** [comment]
See #31 - I am waiting on @zouyee to confirm whether the fix works with Kubernetes 1.6, 1.7 and 1.8. 

@codyde would you be able to test on 1.6?

**Comment by codyde** [comment]
Fyi - I'm working on getting a K8s 1.6 cluster up to test. To be continued....

**Comment by zouyee** [comment]
It is work fine in `v1.6+`, could you attach some logs? sorry for later response!

**Comment by ericstoekl** [comment]
I am running into this issue on 1.8.1:

```
fc deploy --name nodejs-echo --image alexellis/faas-nodejs-echo --gateway http://10.100.241.220:8080
Server returned unexpected status code 500 deployments.extensions "nodejs-echo" not found
Deployed.
URL: http://10.100.241.220:8080/function/nodejs-echo

202 Accepted

```

**Comment by alexellis** [comment]
Eric can you try the latest code? Do you still get this issue? I thought we'd included the change from @zouyee

**Comment by zouyee** [comment]
We may need to add a https://github.com/kubernetes/kube-state-metrics#compatibility-matrix

**Comment by alexellis** [comment]
Is this warning just saying "could not find deployment"? Or is this about the alpha/beta status of the Go client?
 
> Server returned unexpected status code 500 deployments.extensions "nodejs-echo" not found

**Comment by zouyee** [comment]
kubernetes 1.8.1 contain `apps/v1beta2|v1beta1/Deployment` and `extenions/v1beta1/deployment`

**Comment by alexellis** [comment]
Fixed
