### ISSUE TITLE
Update yaml_armhf to use multi-arch 

### ISSUE THREAD

**Issue by zeerorg** [openfaas/faas-netes#461]
Prometheus and alertmanager have published Multi arch images, Move armv7 images from arm tag to multi arch tags.

**Comment by alexellis** [comment]
Sounds good to me. 

https://github.com/openfaas/faas-netes/blob/master/contrib/values-arm64.yaml
https://github.com/openfaas/faas-netes/blob/master/contrib/values-armhf.yaml

We'd need the above to be changed ^

**Comment by viveksyngh** [comment]
This can be closed as this has been updated #501

**Comment by viveksyngh** [comment]
Derek close
