### ISSUE TITLE
Suggestion about CRD and Helm

### ISSUE THREAD

**Issue by raviqqe** [openfaas/faas-netes#464]
## Expected Behaviour

The `openfaas` Helm Chart should work even when the `Function` CRD is not yet deployed.

## Current Behaviour

It fails if the `Function` CRD is not yet deployed but `Function` resources exist in Helm Charts.

## Possible Solution

Add Helm Hook annotation of `crd-install` to the `Function` CRD.

## Steps to Reproduce (for bugs)

1. Create a new Helm Chart
1. Add `openfaas` to `requirements.yaml`.
1. Set `openfaas.operator.create` to `true`.
1. Add `Function` resources under the `templates` directory.
1. Run `helm install` or `helm upgrade --install`

You would see the error message like below.

```
> helm upgrade --install --wait --timeout 3600 --values values.yaml main chart
Release "main" does not exist. Installing it now.
Error: validation failed: unable to recognize "": no matches for kind "Function" in version "openfaas.com/v1alpha2"
```

## Context

`helm install` or `helm upgrade --install` command fails because of the issue described above.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

```
> faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  d97e5ad73249c46ee904205aab30307fbf7031e3
 version: 0.8.19
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):

```
> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

* What version and distriubtion of Kubernetes are you using? `kubectl version`

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
> helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
> system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F203)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Spare 0005 - Yota’s MacBook Pro
      User Name: Yota Toyama (ytoyama)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 39 days 13:39
```

**Comment by alexellis** [comment]
Can you share values.yaml?

The helm chart doesn't depend on the CRD, only if you've asked for the operator specifically, in which case the CRD is installed with the chart.

**Comment by alexellis** [comment]
/set title: Suggestion about CRD and Helm

**Comment by stefanprodan** [comment]
When using the OpenFaaS chart as a dependency you'll need to apply the CRD with kubectl, before installing your chart. In the operator config, inside your values.yaml set `createCRD: false`.

**Comment by stefanprodan** [comment]
@raviqqe if this works for you please close this issue. Thanks

**Comment by raviqqe** [comment]
Thanks for your quick feedback! Your solution works well for us.

We applied the solution described above by @stefanprodan in our deployment code. To deploy our Helm Chart, we run some script like the following with `openfaas.operator.create: true` and `openfaas.operator.createCRD: false` in `values.yaml`.

```
#!/bin/sh

set -ex

# Needs to install OpenFaaS Function CRD manually.
# it would better to stick with a specific version for production.
curl -fsSL https://raw.githubusercontent.com/openfaas/faas-netes/master/chart/openfaas/templates/crd.yaml |
  sed 's/{{.*}}//g' |
  kubectl apply -f /dev/stdin

helm upgrade --install --values values.yaml chart
```

**Comment by stefanprodan** [comment]
@raviqqe I would add the two OF namespaces to that script. 

From the [readme](https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#install):

```
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
```

Creating multiple namespace from a helm chart is not recommended.

**Comment by raviqqe** [comment]
Does it mean we should not use the `openfaas` Helm Chart as any dependencies of other Helm Charts? AFAIK, there is no way to control namespaces of dependency Charts in `requirements.yaml`.

[This line of `gateway-svc.yaml`](https://github.com/openfaas/faas-netes/blob/ead0d07a3c9bce71f5f901349bd938167d759cce/chart/openfaas/templates/gateway-svc.yaml#L11) uses the default namespace.

**Comment by alexellis** [comment]
It doesn't use the `default` namespace, it's parameterized, so it uses whatever you pass into helm.

Here's the usage: https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#install

**Comment by raviqqe** [comment]
FYI, the CRD upgrade PR on Helm repo is recently merged. https://github.com/helm/helm/issues/5853
