### ISSUE TITLE
Allow configuring of log provider via helm chart

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#474]
## Expected Behaviour

I should be able to install an external log provider and configure the env variable via the Helm chart

## Current Behaviour

This is not possible

## Possible Solution

Add a new `gateway.logProviderURL` or a `logProviderURL` variable, then it is not empty, it would then set this env variable on the gateway container

```yaml
  - name: logs_provider_url
    value: {{ .Values.logProviderURL }}
```

When it is empty, then the env variable is either not created.

## Context

This is required to support log providers that are not built into the function provider server. For example https://github.com/LucasRoesler/openfaas-loki

**Comment by brynnonpicard** [comment]
@LucasRoesler is there any chance this might be implemented soon? I have a use-case for it.

**Comment by LucasRoesler** [comment]
@brynnonpicard sorry for the delay, obviously other things came up and i forgot to come back to this.  

It should hopefully be a small change to the helm chart, if you are working on it, please feel free to submit it and I can help review and test.  Otherwise, it will probably work on it this weekend
