### ISSUE TITLE
Kafka-connector development instructions give error

### ISSUE THREAD

**Issue by kwojcicki** [openfaas/faas-netes#477]
When following the instructions here https://github.com/openfaas/faas-netes/blob/master/chart/kafka-connector/development.md and deploying the test client the markup has inproper indentation causing kubectl to throw an error.

![image](https://user-images.githubusercontent.com/2487946/61672631-3034f580-aca1-11e9-911c-335a64336e8b.png)

## Expected Behaviour
The copied commands from development.md work.

## Current Behaviour
Kubectl provides the above error.

## Possible Solution
Need to fix the indentation, PR coming in a bit :)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
Hi @kwojcicki thank you for raising this.

Pinging the author ( @martindekov )

Please could you compare these instructions to the blog?

https://www.openfaas.com/blog/kafka-connector/

Alex

**Comment by martindekov** [comment]
Hello @kwojcicki, I believe it is an indentation problem of the line:
```
command:
- sh
- c
...
```
Should be tab in like so:
```
command:
   - sh
   - c
...
```

**Comment by kwojcicki** [comment]
@martindekov I think the start of the command also had indentation problems but with the updated command here: https://github.com/openfaas/faas-netes/pull/478/files it all ran smoothly ^_^.

@alexellis from a quick scan of the blog seems like the techniques used for publishing are slightly different and as a result the command I fixed isn't utilized in the blog. I will try out the blogs approach to deploying Kafka some time and open any issues if I find a problem with that :)
