### ISSUE TITLE
Not all the pods are being used after scaling

### ISSUE THREAD

**Issue by krazavi** [openfaas/faas-netes#482]
## Expected Behaviour
After scaling from the minimum to the maximum number of pods in the Kubernetes cluster, we expect all the pods to receive the same amount of requests.

## Current Behaviour
Some pods are receiving requests after waiting a long time, others remain idle.

## Possible Solution
Checking that all the service endpoints are available for load balancing in the used technique (default is RR in Kubernetes)

## Steps to Reproduce (for bugs)
1. Follow https://github.com/openfaas/workshop/blob/master/lab1b.md to setup OpenFaaS with Kubernetes 
2. Create a simple java function that returns the input with the following specs and function:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.99.100:31112
functions:
  echo-java:
    lang: java8
    handler: ./echo-java
    image: krazavi/echo-java:latest
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 128Mi
      cpu: 100m
```
```java
public IResponse Handle(IRequest req) {
        Response res = new Response();
	res.setBody(req.getBody());
	return res;
}
```

3. deploy it to the cluster
```bash
faas-cli up -f echo-java.yml --label com.openfaas.scale.max=10 --label com.openfaas.scale.min=1
```
4. Save the following code in jmx format and run it in Apache Jmeter:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="2.8" jmeter="2.13.20170723">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Test Plan" enabled="true">
      <stringProp name="TestPlan.comments"></stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Thread Group" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <intProp name="LoopController.loops">-1</intProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">100</stringProp>
        <stringProp name="ThreadGroup.ramp_time"></stringProp>
        <longProp name="ThreadGroup.start_time">1564392654000</longProp>
        <longProp name="ThreadGroup.end_time">1564392654000</longProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <stringProp name="ThreadGroup.duration"></stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
      </ThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain">192.168.99.100</stringProp>
          <stringProp name="HTTPSampler.port">31112</stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
          <stringProp name="HTTPSampler.protocol"></stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path">/function/echo-java</stringProp>
          <stringProp name="HTTPSampler.method">POST</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <boolProp name="HTTPSampler.monitor">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>
```
5. Check the resource usage or logs:
```bash
kubectl top pod -n openfaas-fn
kubectl logs -f -n openfaas-fn echo-java-XXX
```
## Context
The assigned resources are not being used.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.8.15

* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.0

* What version and distribution of Kubernetes are you using? `kubectl version`
```bash
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04

* Apache Jmeter Version
2.13.20170723

* Cluster resources
4 CPUs, 4096 Memory

**Comment by krazavi** [comment]
Any update on this issue after a month?

**Comment by alexellis** [comment]
This is the default behaviour of KeepAlive in Kubernetes using an L4 LoadBalancer.

You can tune these settings in your jMeter test, or deploy Linkerd2 which uses its own proxy to balance without KeepAlive.

https://github.com/openfaas-incubator/openfaas-linkerd2

As for whether it has been one hour, one day, one week or one month since you asked a question, that's largely irrelevant. OpenFaaS is an open source community project and as far as I'm aware you have no commercial support contract.

Community members are encouraged to contribute to the project and to do their own research. If you feel that your issue is a priority then you can also join Slack and ask someone to prioritize it.

**Comment by alexellis** [comment]
I hope the reply was useful to you, it was on mobile so I had to keep it brief.

KeepAlive can be configured at the client-side, and in the server through the gateway, although it's not recommended. Generally if the connection is set for KeepAlive, then Kubernetes will honour that and will not break a connection between a single requestor and a single Pod.

We also make use of hey for load-testing and with more than a single concurrent requestor, you should see load-balancing. I would recommend trying Linkerd2 as an add-on and comparing your results.

[An example](https://twitter.com/alexellisuk/status/1166686339284295680?s=20) I tried today:

![](https://pbs.twimg.com/media/EDDnCHYXYAATjwr?format=jpg&name=medium)

Thank you for providing detailed instructions or reproducing this, not everybody does that so it's appreciated.
