### ISSUE TITLE
Can different functions be limited to different groups in one system?

### ISSUE THREAD

**Issue by EasyIoTAdmin** [openfaas/faas-netes#489]
I am working on a FaaS system for my company based on openFaas. The ideal group size should be about 100 -150 groups. I don't think it is possible to set up multi openfaas system at the same time. I am thinking if I can limit the functions to specific groups, and make sure they don't exposed to each other. Would It be possible? Or any ideal solutions

## Current Behaviour
 auth solutions are mostly in front of the gateway. Once the user log in , he can access all the functions in the system. Functions itself do not have any auths. 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

**Comment by burtonr** [comment]
An option I know some groups are using is deploying separate OpenFaaS systems for each team. 
In kubernetes, this can be achieved by using separate namespaces to ensure that the function groups are isolated from the other installations.

The resource usage on the core OpenFaaS components is very small, and shouldn't add much overhead to the cluster you are deploying to. Although 100-150 is quite a large number of groups! 

You could also have a look at [OpenFaaS Cloud](https://github.com/openfaas/openfaas-cloud/) that provides user separated function groups. That may be more ideal for such a large number of groups.

**Comment by EasyIoTAdmin** [comment]
So in k8s, am I able to use separate namespace for components like openfaas-fn? Like using one or two gateway to control several fn groups namespace?

**Comment by EasyIoTAdmin** [comment]
> An option I know some groups are using is deploying separate OpenFaaS systems for each team.
> In kubernetes, this can be achieved by using separate namespaces to ensure that the function groups are isolated from the other installations.
> 
> The resource usage on the core OpenFaaS components is very small, and shouldn't add much overhead to the cluster you are deploying to. Although 100-150 is quite a large number of groups!
> 
> You could also have a look at [OpenFaaS Cloud](https://github.com/openfaas/openfaas-cloud/) that provides user separated function groups. That may be more ideal for such a large number of groups.

So in k8s, am I able to use separate namespace for components like openfaas-fn? Like using one or two gateway to control several fn groups namespace?

**Comment by burtonr** [comment]
At the moment, it would be 1 gateway -> 1 function namespace

So, if you needed 3 teams with segregated functions (that cannot communicate with other teams' functions), you would need 3 gateways (and other OpenFaaS core components) deployed in separate namespaces that would each manage their own function namespace.

> Example
* Team 1
  * OpenFaaS Core Namespace: team1-of
  * Functions Namespace: team1-fn
* Team 2
  * OpenFaaS Core Namespace: team2-of
  * Functions Namespace: team2-fn
* Team 3
  * OpenFaaS Core Namespace: team3-of
  * Functions Namespace: team3-fn

You would defined those in the deployment parameters.

**Comment by EasyIoTAdmin** [comment]
> At the moment, it would be 1 gateway -> 1 function namespace
> 
> So, if you needed 3 teams with segregated functions (that cannot communicate with other teams' functions), you would need 3 gateways (and other OpenFaaS core components) deployed in separate namespaces that would each manage their own function namespace.
> 
> > Example
> 
> * Team 1
>   
>   * OpenFaaS Core Namespace: team1-of
>   * Functions Namespace: team1-fn
> * Team 2
>   
>   * OpenFaaS Core Namespace: team2-of
>   * Functions Namespace: team2-fn
> * Team 3
>   
>   * OpenFaaS Core Namespace: team3-of
>   * Functions Namespace: team3-fn
> 
> You would defined those in the deployment parameters.

Thank you so much. Just ask for some design advices. For the NATS and queue-worker parts, if I put them in a namespace eg. openfaas-nats, and process all OpenFaas  asyc-func requests in this section, would it be a good design?  Ideally, there should k8s HPA functionality in the NATS namespace. At the moment, NATS cost over 300M mem which would be too much if I install one for each groups T T.  
Perhaps, if you have any advices or components I can optimize in k8s system. 
Thank you!

**Comment by alexellis** [comment]
I would suggest looking at one of the two options:

* [Multiple installations in differing namespaces](https://www.openfaas.com/blog/gke-multi-stage/)
* [OpenFaaS Cloud](http://docs.openfaas.com/openfaas-cloud/) - which caters to your use-case better

**Comment by alexellis** [comment]
Thanks @burtonr 👍 

See also backlog item: #263
