### ISSUE TITLE
Allow configuring of gateway-external svc annotations via helm chart

### ISSUE THREAD

**Issue by lihaiswu** [openfaas/faas-netes#490]
## Expected Behaviour
Helm chart should allow configuring metadata/annotations for gateway-external svc

## Current Behaviour
No way to configure metadata/annotations for gateway-external svc unless user maintain a copy of helm chart locally

## Possible Solution
Expose annotations in helm chart like ingress did.

## Steps to Reproduce (for bugs)

1. add override configs to devops/helm/openfaas/values.yaml
2. deploy onpenfaas via "helm upgrade openfaas --install openfaas/openfaas \
    --tiller-namespace openfaas --debug --wait --timeout 180 \
    --set functionNamespace=openfaas \
    -f devops/helm/openfaas/values.yaml"
3. Can not pass annotations for gateway-external svc

## Context

There're some features in our k8s env. The feature read svc annotations to  determine if the feature will be enabled or not. For example, our k8s env support HTTP to HTTPS redirection. If we want to use https for openfaas gateway, we can just add an annotation to gateway-external svc to enable https without any other setup.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  750add9e2a6d1d1f1bfb788a6a85341b4b4140e8
 version: 0.8.22

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by lihaiswu** [comment]
@LucasRoesler @alexellis  Can i make a PR for this issue? I'd like to add a new entry in value.yml:

```
gateway-external:
    annotations: {}
```

or just at the root level:
```
   annotations: {}
```

Since the annotations are only used in gateway-external. I do not want to put it under gateway/annotations. Do you have any comments?

**Comment by LucasRoesler** [comment]
I think putting it under `gateway-external` makes sense, like you said
