### ISSUE TITLE
Merge faas-operator with faas-netes

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas-netes#491]
Port operator's code and CRD to faas-netes and allow switching between the two controllers with a command flag. This will enable us to add new features to both controllers at the same time without code duplication.

Code merge phases:
1. Move the operator code as it is
2. Add `-mode=crd` command flag to start the crd operator (defaults to `-mode=` faas-netes mode)
3. Extract common code in the `k8s` package and trim down the code duplication between operator and faas-netes

**Comment by alexellis** [comment]
This has been completed now. I've moved over the README and added a note on the operator repo.
