### ISSUE TITLE
Bump helm chart to golang 1.11.13 security patches

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#495]
Bump the chart versions to the latest releases referenced in https://github.com/openfaas/faas/issues/1291

**Comment by LucasRoesler** [comment]
@alexellis i started working on this but i noticed that many of the images are missing the arm64 an armhf for the latest release:

* https://hub.docker.com/r/openfaas/faas-netes/tags 
* https://hub.docker.com/r/openfaas/basic-auth-plugin/tags
* https://hub.docker.com/r/openfaas/gateway/tags
* https://hub.docker.com/r/openfaas/queue-worker/tags
* https://hub.docker.com/r/openfaas/faas-idler/tags

**Comment by alexellis** [comment]
As a rule, only bump up the x86-64 because arm is built manually and can fail mid-way.
