### ISSUE TITLE
Issue with ARM64 configuration

### ISSUE THREAD

**Issue by charles-d-burton** [openfaas/faas-netes#497]
Faas Idler and Basic Auth plugin are both missing arm64 builds.  

## Expected Behaviour
ARM64 builds in docker hub.

## Current Behaviour
Build are missing

## Possible Solution
Add ARM64 to the build scripts.

## Steps to Reproduce (for bugs)
kubectl apply -f yaml_arm64

## Context
Currently cannot install OpenFaas on my Graviton based cluster.

**Comment by alexellis** [comment]
Hi,

Thanks for your interest in OpenFaaS and in the ARM64 configuration.

To say that "arm64 builds are missing" is probably not quite correct. They are used by very few people, but are available and maintained, perhaps there is a mismatch somewhere in the YAML? Can you give the whole error you received?

If you want to try updating to later versions you can try updating `chart/openfaas/values-arm64.yaml`, then run this in the root directory:

```
make charts
```

These were built on 7th August:

```
Docker images
openfaas-incubator/openfaas-operator
 openfaas/openfaas-operator:0.9.9-arm64
openfaas-incubator/faas-idler
 openfaas/faas-idler:0.2.0-arm64
openfaas/faas
 openfaas/gateway:0.16.0-arm64
 openfaas/basic-auth-plugin:0.16.0-arm64
openfaas/faas-swarm
 openfaas/faas-swarm:0.7.2-arm64
openfaas/nats-queue-worker
 openfaas/queue-worker:0.7.2-arm64
openfaas/faas-netes
 openfaas/faas-netes:0.8.4-arm64
openfaas/faas-cli
 openfaas/faas-cli:0.9.0-arm64
```

Feel free to send a PR and it would be really helpful if you could fill out the whole issue template next time (https://raw.githubusercontent.com/openfaas/faas-netes/master/.github/ISSUE_TEMPLATE.md)

Thanks,

Alex

**Comment by alexellis** [comment]
These are the builds from 22nd August if you'd like to try them out:

```
Docker images
openfaas-incubator/openfaas-operator
 openfaas/openfaas-operator:0.10.0-arm64
openfaas-incubator/faas-idler
 openfaas/faas-idler:0.2.1-arm64
openfaas/faas
 openfaas/gateway:0.17.0-arm64
 openfaas/basic-auth-plugin:0.17.0-arm64
openfaas/faas-swarm
 openfaas/faas-swarm:0.7.2-arm64
openfaas/nats-queue-worker
 openfaas/queue-worker:0.8.0-arm64
openfaas/faas-netes
 openfaas/faas-netes:0.8.5-arm64
openfaas/faas-cli
 openfaas/faas-cli:0.9.2-arm64
```

As far as I'm aware the config hasn't been updated to use basic-auth-plugin or faas-idler as of yet.

**Comment by alexellis** [comment]
The problem may be that basic-auth is enabled, but you have no basic auth password?

Please see the instructions in the `yaml` folder's README or the help chart on how to create a basic-auth-password.

If you're still having issues, you can ask on Slack, or I'll have a look next week after the holidays in the UK.
