### ISSUE TITLE
Support question about kubectl port-forward

### ISSUE THREAD

**Issue by CentricStraaten** [openfaas/faas-netes#498]
During a clean installation of faas-netes the port forwarding fails

## Expected Behaviour
I followed the instruction page and entered the command below and receive an error message.
`kubectl -n openfaas port-forward svc/gateway 31112:8080` 

I removed the &-character from the example on [the instruction website](https://docs.openfaas.com/deployment/kubernetes/)

## Current Behaviour
The command above returns following error message:
```
kubectl : Unable to listen on port 31112: Listeners failed to create with the following errors: [Unable to create listener: Error listen tcp4 127.0.0.
1:31112: bind: An attempt was made to access a socket in a way forbidden by its access permissions. Unable to create listener: Error listen tcp6 [::1]
:31112: bind: An attempt was made to access a socket in a way forbidden by its access permissions.]
At line:1 char:1
+ kubectl -n openfaas port-forward svc/gateway 31112:8080
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to liste...s permissions.]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
error: Unable to listen on any of the requested ports: [{31112 8080}]
```
## Possible Solution
I don't have a suggestion. 

## Steps to Reproduce (for bugs)
1.  Clean installation of Docker Windows
2.  Followed instruction (option B) on https://docs.openfaas.com/deployment/kubernetes/
3. I removed the &-character in the port forwarding instruction

## Context
The Portal can be visited on http://127.0.0.1:331112 but faas-cli login fails

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
[32m  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|
[0mCLI:
 commit:  893972afffa5ea6672faa6e11743ae46322ec58c
 version: 0.9.2
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
`Docker version 19.03.1, build 74b1e89`
* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", B
uildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", B
uildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10, HyperV, Linux VM's

* Link to your project or a code example to reproduce issue:
does not apply

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
does not apply

**Comment by alexellis** [comment]
/set title: Kubernetes support issue about port-forwarding

**Comment by alexellis** [comment]
Hi,

Thanks for your interest in OpenFaaS.

Port forwarding is known to work reliably, so I suspect you may need to troubleshoot your Kubernetes installation.

You can probably find technical support from the Kubernetes Slack or Forum: https://kubernetes.io/community/

We may be able to help you with your Kubernetes distribution, but since this doesn't appear to be an issue with OpenFaaS I'm going to update the title.

Can you confirm your distribution of Kubernetes and how you set it up? 

Alex
