### ISSUE TITLE
[Feature Request] Support for Kubernetes 1.16

### ISSUE THREAD

**Issue by poussa** [openfaas/faas-netes#510]
Deploying openfaas to latest k8s version 1.16 fails

## Expected Behaviour

Deployment should work.

## Current Behaviour

```bash
kubectl apply -f ./yaml
configmap/alertmanager-config created
service/alertmanager created
service/basic-auth-plugin created
serviceaccount/faas-controller created
role.rbac.authorization.k8s.io/faas-controller created
rolebinding.rbac.authorization.k8s.io/faas-controller created
service/gateway-external created
service/gateway created
service/nats created
configmap/prometheus-config created
serviceaccount/faas-prometheus created
role.rbac.authorization.k8s.io/faas-prometheus created
rolebinding.rbac.authorization.k8s.io/faas-prometheus created
service/prometheus created
unable to recognize "yaml/alertmanager-dep.yml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "yaml/basic-auth-plugin-dep.yml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "yaml/faas-idler-dep.yml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "yaml/gateway-dep.yml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "yaml/nats-dep.yml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "yaml/prometheus-dep.yml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "yaml/queueworker-dep.yml": no matches for kind "Deployment" in version "apps/v1beta1"
```

## Possible Solution

DaemonSet, Deployment, StatefulSet, and ReplicaSet using k8s APIs apps/v1beta1 have been deprecated.

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Update the yaml files to use apps/v1

## Steps to Reproduce (for bugs)

See above

## Context

Not able to deploy openfaas to k8s cluster using 1.16

## Your Environment

```bash
kubectl get nodes -o wide
NAME        STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION              CONTAINER-RUNTIME
ceph-vm-0   Ready    <none>   21h   v1.16.0   10.237.71.242   <none>        CentOS Linux 7 (Core)   5.3.0-1.el7.elrepo.x86_64   docker://19.3.2
ceph-vm-1   Ready    <none>   21h   v1.16.0   10.237.71.234   <none>        CentOS Linux 7 (Core)   5.3.0-1.el7.elrepo.x86_64   docker://19.3.2
ceph-vm-2   Ready    <none>   21h   v1.16.0   10.237.71.235   <none>        CentOS Linux 7 (Core)   5.3.0-1.el7.elrepo.x86_64   docker://19.3.2
k8s         Ready    master   21h   v1.16.0   10.237.72.100   <none>        CentOS Linux 7 (Core)   5.3.0-1.el7.elrepo.x86_64   docker://19.3.2
k8s-vm-0    Ready    <none>   21h   v1.16.0   10.237.71.246   <none>        CentOS Linux 7 (Core)   5.3.0-1.el7.elrepo.x86_64   docker://19.3.2
k8s-vm-1    Ready    <none>   21h   v1.16.0   10.237.71.232   <none>        CentOS Linux 7 (Core)   5.3.0-1.el7.elrepo.x86_64   docker://19.3.2
k8s-vm-2    Ready    <none>   21h   v1.16.0   10.237.71.233   <none>        CentOS Linux 7 (Core)   5.3.0-1.el7.elrepo.x86_64   docker://19.3.2
```

**Comment by alexellis** [comment]
/set title: [Feature Request] Support for Kubernetes 1.16

**Comment by alexellis** [comment]
Thank you for your feature request. We are tracking this release, but would not expect many people to have a hard requirement to adopt this version with it not being available in managed clouds yet. 

if you have a hard business requirement to adopt this version immediately then please let us know more below to help triage.

**Comment by alexellis** [comment]
I should also say that contributions are welcome from end-user companies. If you have a solution in mind that retains backwards compatibility, then please feel free to outline it below.  :+1:

**Comment by LucasRoesler** [comment]
This should only require us to update the Helm chart Deployment objects, e.g. https://github.com/openfaas/faas-netes/blob/77cd525c7431d708fbea7b4562c604b604bd51fa/chart/openfaas/templates/gateway-dep.yaml#L2

We can then re-render the yaml files. 

Per the k8s changelog https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#deprecations-and-removals :

>DaemonSet, Deployment, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.

The `apps/v1` API should be available as far back as k8s v1.9.  Which is probably enough to cover most users.

**Comment by poussa** [comment]
I don't have any hard biz requirements and can easily go back in k8s version. Thanks for the quick responses.

**Comment by alexellis** [comment]
👍 

Happy to accept a PR from the community or members/core team. No need to wait for me to get to this.

Alex

**Comment by carlosedp** [comment]
Updating the manifests isn't the only issue. faas-netes is having trouble getting data from Kubernetes itself:

```
openfaas gateway-758569f6f5-77cll gateway 2019/09/20 20:55:49 <nil>
openfaas gateway-758569f6f5-77cll faas-netes 2019/09/20 20:55:49 the server could not find the requested resource
openfaas gateway-758569f6f5-77cll faas-netes 2019/09/20 20:55:52 the server could not find the requested resource
openfaas gateway-758569f6f5-77cll gateway 2019/09/20 20:55:52 Forwarded [GET] to /system/functions - [500] - 0.006435 seconds
openfaas gateway-758569f6f5-77cll gateway openfaas 2019/09/20 20:55:52 Forwarded [GET] to /system/functions - [500] - 0.005842 seconds
gateway-758569f6f5-77cll faas-netes 2019/09/20 20:55:52 the server could not find the requested resource
openfaas gateway-758569f6f5-77cll gateway 2019/09/20 20:55:54 <nil>
openfaas gateway-758569f6f5-77cll faas-netes 2019/09/20 20:55:54 the server could not find the requested resource
openfaas gateway-758569f6f5-77cll gateway 2019/09/20 20:55:55 Forwarded [GET] to /healthz - [200] - 0.001254 seconds
openfaas gateway-758569f6f5-77cll faas-netes 2019/09/20 20:55:55 the server could not find the requested resource
```

**Comment by alexellis** [comment]
Release available as: https://github.com/openfaas/faas-netes/releases/tag/0.9.0 with the move to apps/v1 via PR #517

**Comment by alexellis** [comment]
The Helm templates will need to be updated, which generate the `yaml*` files via `make charts`.
