### ISSUE TITLE
[Feature request] Show Pod status

### ISSUE THREAD

**Issue by wphowto** [openfaas/faas-netes#514]
Deploying a function with private registry, the deployment succeed, but checking the status it shown 'Not Ready'. If I switch this to dockerhub.com, things work perfectly, with the same source code, only image location differ.

## Expected Behaviour

It should show as "ready state" and works.

## Current Behaviour

It shown "Not ready" for private registry.

## Possible Solution

If deployment fail, it should not show "Deployed. 202 Accepted", or perhaps a way to check what cause the status to be "Not Ready"

## Steps to Reproduce (for bugs)

1. faas-cli new --lang node10-express --prefix=privateregistry.com/username test
2. faas-cli build -f test.yml
3. faas-cli push -f test.yml (push successfully, validated by pulling the image again)
4. faas-cli deploy -f test.yml test
```
Deploying: test.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://127.0.0.1:8080/function/test
```
5. faas-cli describe -f test.yml test
```
Name:                test
Status:              Not Ready
Replicas:            2
Available replicas:  0
Invocations:         27
Image:               privateregistry.com/username/test:latest
Function process:    node index.js
URL:                 http://127.0.0.1:8080/function/test
Async URL:           http://127.0.0.1:8080/async-function/test
```
6. change test.yml image to dockerhub, wphowto/test
7. faas-cli up -f test.yml
8. faas-cli describe -f test.yml test
```
Name:                test
Status:              Ready
Replicas:            1
Available replicas:  1
Invocations:         27
Image:               wphowto/test:latest
Function process:    node index.js
URL:                 http://127.0.0.1:8080/function/test
Async URL:           http://127.0.0.1:8080/async-function/test
```

## Context

Can't run function from my private repo.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  893972afffa5ea6672faa6e11743ae46322ec58c
 version: 0.9.2

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.17.3
 sha:     d322f109a8379d19b639c003846e721a24ce9dc0
 commit:  Fix logo location


Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.9.9
 sha:           4cdc63fa4be359239ac5bd30f7039b331bc38849
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
19.03.2
```
* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
```
Mac OS, with Docker For Desktop & Kubernetes
```
* Link to your project or a code example to reproduce issue:
```
https://cloud.docker.com/u/wphowto/repository/docker/wphowto/nodetest
```
* What network driver are you using and what CIDR? i.e. Weave net / Flannel
 
Not sure

**Comment by alexellis** [comment]
Please see the deployment guide for Kubernetes which covers private registries.

https://docs.openfaas.com/deployment/kubernetes/

**Comment by wphowto** [comment]
Thanks @alexellis. I fail to find this page from google search and I am stuck for a while. Useful info.

**Comment by alexellis** [comment]
Did it resolve your issue? It's the page for deploying OpenFaaS on Kubernetes, should be everyone's first port of call.

**Comment by wphowto** [comment]
Yes, It resolved my issue. I didn't manage to dig through the documentation and I rely on google search, it show me this instead.

https://ericstoekl.github.io/faas/operations/managing-images/
