### ISSUE TITLE
[Feature] Allow for customizing the security context of the OpenFaaS control-plane.

### ISSUE THREAD

**Issue by bmcustodio** [openfaas/faas-netes#521]
Following the discussion #509, I think it would be valuable to discuss how we could let users customize the security context of the OpenFaaS control-plane components without forcing any particular configuration on anyone. As far as I can tell, the only way of doing this would be to add a `.securityContexts` Helm value containing fields for every container and pod and possibly defaulting to the "safest" possible default value of `{}` (see #522).

**Comment by alexellis** [comment]
We should have this now in the Profiles feature.
