### ISSUE TITLE
[Feature] Allow for defining 'allowPrivilegeEscalation'.

### ISSUE THREAD

**Issue by bmcustodio** [openfaas/faas-netes#523]
While people don't arrive at a decision regarding the broader #371, I think it would be good to let users define the value of `allowPrivilegeEscalation` at a global level, in the same way they can use `set_nonroot_user` today. I propose we add an `allow_privilege_escalation` setting that gets propagated to each function's `securityContext`. If this sounds like something we can agree upon, I can go ahead and implement it.

**Comment by bmcstdio** [comment]
@alexellis @stefanprodan could you chime in please?

**Comment by alexellis** [comment]
>  I think it would be good to let users define the value of allowPrivilegeEscalation at a global level

This is something you want to enable or disable? What's the use case that you have for it given that you're the first person to ask for it so far.

**Comment by matzhaugen** [comment]
We also have a use case for this. In particular, with this flag set, nobody can make a function which can escalate the uid though e.g. a [setuid binary](https://en.wikipedia.org/wiki/Setuid) to gain root privileges of the pod.

**Comment by alexellis** [comment]
I've seen this elsewhere. @matzhaugen it looks like you deleted some of your comments? 

I believe you still need this. I would be open to a PR that sets `allowPrivilegeEscalation` to `false` permanently.

**Comment by alexellis** [comment]
This change has been made in the linked commit
