### ISSUE TITLE
Technical support for Pod Security Policys

### ISSUE THREAD

**Issue by floriankoch** [openfaas/faas-netes#539]
Openfaas does not work when pod security policys are in place

## Expected Behaviour
Openfaas works with Pod Security Policys

## Current Behaviour
Pods are in a Error state
kubectl -n openfaas get po
NAME                                 READY   STATUS                       RESTARTS   AGE
alertmanager-f5655f68c-97tv8         0/1     CreateContainerConfigError   0          13m
basic-auth-plugin-85994747dd-djbhh   1/1     Running                      0          13m
faas-idler-6568bb4c9b-249dd          0/1     CreateContainerConfigError   0          13m
nats-d4c9d8d95-q88qh                 0/1     CreateContainerConfigError   0          13m
queue-worker-56b64d6848-mzxxp        0/1     CreateContainerConfigError   0          13m

The Erroris:
 container has runAsNonRoot and image has non-numeric user (app), cannot verify user is non-root

## Possible Solution
Change the User in the Docker Images from a Name to Uids 

## Steps to Reproduce (for bugs)

1. Install a PSP enabled Cluster
2. Install the openfaas helmchart

## Context

Faas-Netes Version:

master af7f3fb428bc35b1ea97904c742fa5037942b981

Kubernetes 1.14.6

I can do the needed changes if the Fix  (Name to UID) is accepted

**Comment by alexellis** [comment]
As far as I'm aware this is something that works and was added by @stefanprodan 
please can you use the "steps to reproduce the problem section" to give us concrete steps that we can take to reproduce the problem you're facing.

**Comment by stefanprodan** [comment]
I don't think @floriankoch is using the Helm chart, in our PSP there is no user enforcement https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/psp.yaml

**Comment by alexellis** [comment]
That might be the case. Full instructions to reproduce the problem will show us that, hopefully.

**Comment by floriankoch** [comment]
@stefanprodan  i use the helm chart (with helm template), i recheck why the psp is not correctly used

But anyway when the containers does not need root, why  not useng ids and restrict the psp more?

**Comment by stefanprodan** [comment]
I think you missed interpret the error message, there is no need to change any of Dockerfiles. We do set the user id with https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/gateway-dep.yaml#L46

But we only do this only for the gateway, I don't see the gateway in your error log, does the gateway works for you with the `runAsNonRoot` PSP?

**Comment by floriankoch** [comment]
@stefanprodan  ok i tested this with a fresh cluster, ran into the same  issue

My Clusters come with psp policys preinstalled (from our vendor), and it seems that the pre installed psp is used instead of the openfaas psp

```
kubectl -n openfaas describe  po  queue-worker-5d86f844f-clmrq
Name:           queue-worker-5d86f844f-clmrq
Namespace:      openfaas
Priority:       0
Node:           worker-cd90j-66796c49dd-7q64m/172.23.3.202
Start Time:     Thu, 31 Oct 2019 20:18:58 +0100
Labels:         app=queue-worker
                pod-template-hash=5d86f844f
Annotations:    **kubernetes.io/psp: restricted**
                prometheus.io.scrape: false
Status:         Pending
IP:             192.168.92.203
Controlled By:  ReplicaSet/queue-worker-5d86f844f
Containers:
  queue-worker:
    Container ID:   
    Image:          openfaas/queue-worker:0.8.0 
```
I think the reason is the binding

`roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-psp-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated


regarding the user, you are right, you need either a numeric uid in the Container, or in the security context
`

**Comment by stefanprodan** [comment]
@floriankoch what about the gateway? does it have the same problem as queue-worker?

**Comment by floriankoch** [comment]
@stefanprodan   the gateway has this error
  Warning  FailedCreate  13m (x82 over 17h)  replicaset-controller  Error creating: pods "gateway-55b7d8848f-" is forbidden: unable to validate against any pod security policy: [spec.volumes[0]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used]

But this all happens because the wrng psp is used

**Comment by paurosello** [comment]
The error can be replicated if a restrictive policy is enabled by default and the release name for the helm installation is not "openfaas" as the reference in the ClusterRole is hardcoded

https://github.com/openfaas/faas-netes/blob/13399f96cd99d60ef24043ee4d928f92c4e96c2e/chart/openfaas/templates/psp.yaml#L52

**Comment by alexellis** [comment]
@paurosello is this fixed now? Can we close the issue?

**Comment by paurosello** [comment]
Yeah, I close it :)

**Comment by floriankoch** [comment]
@alexellis   yes its fixed

**Comment by alexellis** [comment]
Thank you. I'll close this now
