### ISSUE TITLE
Function names are not isolated by namespaces

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#541]
While testing the multi-namespace support, I found that function names must be globally unique.

For example, after deploying openfaas to a cluster with the namespaces `openfaas`, `openfaas-fn`, and `beta`, these commands will result in exactly one function deployment in the default namespace `openfaas-fn`

```sh
faas-cli deploy  \
    --fprocess=cat \
    -e write_debug=true \
    --image=functions/alpine \
    --name echo 

faas-cli deploy  \
    --fprocess=cat \
    -e write_debug=true \
    --image=functions/alpine \
    --name echo \
    --namespace=beta 

faas-cli list
Function                      	Invocations    	Replicas
echo                          	0              	1

faas-cli list -n beta
Function                      	Invocations    	Replicas
```

## Expected Behaviour

Names should be isolated by namespaces and I should be able to re-use a function name in additional namespaces.  In particular,

```sh
faas-cli deploy  \
    --fprocess=cat \
    -e write_debug=true \
    --image=functions/alpine \
    --name echo 

faas-cli deploy  \
    --fprocess=cat \
    -e write_debug=true \
    --image=functions/alpine \
    --name echo \
    --namespace=beta 
```

should result in two function 

```sh
faas-cli list
Function                      	Invocations    	Replicas
echo                          	0              	1

faas-cli list -n beta
Function                      	Invocations    	Replicas
echo                          	0              	1
```

## Current Behaviour

Once a name is used in a  namespace, e.g. `openfaas-fn`, further function deployments with that name will affect the original function as an update, regardless of the namespace supplied in the request.

```sh
faas-cli deploy  \
    --fprocess=cat \
    -e write_debug=true \
    --image=functions/alpine \
    --name echo 

faas-cli deploy  \
    --fprocess=cat \
    -e write_debug=true \
    --image=functions/alpine \
    --name echo \
    --namespace=beta 

faas-cli list
Function                      	Invocations    	Replicas
echo                          	0              	1

faas-cli list -n beta
Function                      	Invocations    	Replicas
```

@alexellis asked for the JSON sent to the server for each request:

In the deployment to the default namespace, the payload is
```json
{
    "service": "echo",
    "image": "functions/alpine",
    "network": "",
    "envProcess": "cat",
    "envVars": {
        "write_debug": "true"
    },
    "constraints": [],
    "secrets": [],
    "labels": {},
    "annotations": {},
    "limits": null,
    "requests": null,
    "readOnlyRootFilesystem": false
}
```

In the second request, to deploy to `beta`, the payload was

```json
{
    "service": "echo",
    "image": "functions/alpine",
    "network": "",
    "envProcess": "cat",
    "envVars": {
        "write_debug": "true"
    },
    "constraints": [],
    "secrets": [],
    "labels": {},
    "annotations": {},
    "limits": null,
    "requests": null,
    "readOnlyRootFilesystem": false,
    "namespace": "beta"
}
```

## Steps to Reproduce (for bugs)

1. create the `openfaas`, `openfaas-fn`, and `beta` namespaces
2.  install openfaas with the helm chart 
3. add a RoleBinding to the openfaas controller ServiceAccount in the `beta` namespace
4. deploy a function to the default namespace
5. attempt to deploy the same function with the same name to the `beta` namespace

## Context

I want to enable my data science team to deploy their functions to a beta namespace to test and verify their functions prior to deploying a release to production.  I thought the namespace support would enable this by allowing them to deploy the same functions multiple times.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

`0.10.1`

* What version and distriubtion of Kubernetes are you using? `kubectl version`
A GKE cluster
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.5", GitCommit:"5976cae75ee00b052334bfbbd28c4df4f40f1489", GitTreeState:"clean", BuildDate:"2019-10-05T00:04:27Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

**Comment by LucasRoesler** [comment]
A little more information, when I directly POST those payloads to the gateway, the deployments work as expected.  I did notice that the CLI is actually using PUT, which has a replace behavior.  Perhaps there is an issue with the CLI then?

**Comment by alexellis** [comment]
https://github.com/openfaas/faas-netes/releases/tag/0.9.10

**Comment by LucasRoesler** [comment]
I just confirmed that this now works exactly as expected  👍 🥇
