### ISSUE TITLE
Question: can pre-existing services (NATS, Prometheus, etc) be used?

### ISSUE THREAD

**Issue by Tails** [openfaas/faas-netes#547]
I would like to use NATS for my own app as well. Is it possible to configure OpenFaas to use the existing infrastructure to prevent duplication (and cost) of extra services? Or the other way around, where my app hooks into the OpenFaas NATS service?

Would this require customizing the faas-netes charts?

Or is this simply a matter of customizing the Kubernetes namespace for the service-layer to use the namespace of one's own app and would Kubernetes prevent service duplication?

**Comment by Tails** [comment]
Related: https://github.com/openfaas/faas-netes/issues/398

**Comment by alexellis** [comment]
Hi, thanks for your interest in the project. We don't use GitHub for technical support, please join Slack and ask there.
