### ISSUE TITLE
Add homebrew as install option for Helm

### ISSUE THREAD

**Issue by InTheCloudDan** [openfaas/faas-netes#55]
Update Readme to include Homebrew option

## Expected Behaviour
N/A not a code change

## Current Behaviour
N/A not a code change

## Possible Solution
N/A not a code change

## Steps to Reproduce (for bugs)
N/A not a code change

## Context
The current steps have it installing manually when there is also a package available for it.

## Your Environment
MacOS

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Merged, thank you Dan.
