### ISSUE TITLE
[Feature request] Add helmfile

### ISSUE THREAD

**Issue by Vad1mo** [openfaas/faas-netes#551]
We are operating a three OF test environments and would like to set up more for productive workloads. This means we need to make OF ready for day 2 operations and making OF easy usable for less experienced OPs people. With the current setup we see some difficulties as not everything is in the helm chart. Some steps are bypassing helm requiring to script a lot for CI/CD to cover some edge cases.

In short writing a CI/CD script for productive OF takes more effort than updating the charts.

As a first step, I would like to put more of the current manual steps into the chart in order to be able to automate deployment, maintenance and ease of use. 

## Expected Behavior
There should be less `kubectl`commands needed to operate OpenFaaS.
K8s Deployment files should all be managed by helm

## Current Behavior
Before installation of the helm chart some execution of`kubectl`commands is mandatory. 

## Solution
Refactor a bit the OpenFaaS helm chart and add the deployment descriptor into it.

Some changes are already in PR #550 this PR isolates this single proposal.
**Proposed Changes**
- Make basic-auth secret k8s definition part of the helm chart.
- Redeploy/Restart GW if password changes (Not sure at this time if GW needs a restart after config/secret change)
- Move `basic_auth: true` value in the YAML tree to `basicAuthPlugin.create: true` The true reason to do it is for consistency  with the other settings as basic_auth is the only one that sticks out.
- Move the function namespace deployment descriptor into the chart 
- Update the Readme to reflect the partly simplified workflow.

## Context
If installation is completely done with helm it becomes easier to operate and apply IaC Infrastructure as Code practices.

**Comment by alexellis** [comment]
Hi @Vad1mo thanks for raising the PR

Please can you outline what problem is being solved here and how it affects your usage of OpenFaaS?

Have you looked at the documentation for installing OpenFaaS via helm that can be done via `k3sup`? https://docs.openfaas.com/deployment/kubernetes/#a-deploy-with-k3sup-fastest-option

**Comment by Vad1mo** [comment]
Thank you @alexellis,  I updated the issue with describing our current problem. 
K3s isn't an option for us, as we now want to move beyond home-lab test setup. We have different IaC setups with AWS CDK & TF and different already operational k8s cluster.

**Comment by Vad1mo** [comment]
@alexellis 

If a user currently tries ot install OpenFaas he needs to execute kubectl + helm commands. 
I can make the installation completely with Helm only. The result is that it becomes easier to operate and built into IaC workflow.

**Comment by alexellis** [comment]
Hi @Vad1mo we're not looking to switch to a helmfile at this time, but will keep the issue around for future comments / discussion.

Thank you again for your interest.

**Comment by Vad1mo** [comment]
@alexellis the title is misleading (someone changed it). My proposal here isn't about Helmfile. 
I want to put more of the k8s deployment objects into Helm, for easier maintenance and automation.

**Comment by alexellis** [comment]
We have the objects automated away with k3sup, perhaps there's a feature / extension that you'd be able to contribute or suggest there?

The workflow is very simple and uses a single command along with helm2 or helm3. 

The PR you sent was to introduce a helmfile, so I updated the title to represent that.
