### ISSUE TITLE
registryAuth param not working for private docker images

### ISSUE THREAD

**Issue by lakhansamani** [openfaas/faas-netes#558]
Deploying private docker image, using `/system/functions`  API and `registryAuth` does not work.
here is the sample request body

```
POST  /system/functions
{
	"service": "node-test",
	"image": "username/image:tag",
	"resitryAuth": "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VybmFtZSIsInBhc3N3b3JkIjoicGFzc3dvcmQiLCJlbWFpbCI6Im1haWxAZ21haWwuY29tIiwiYXV0aCI6ImRYTmxjbTVoYldVNmNHRnpjM2R2Y21RSyJ9fX0="
}
``` 

## Expected Behaviour
This should deploy function in a similar way, it can deploy with `imagePullSecrets` option in YAML file. As the registryAuth value is the same as what secret data contains.

## Current Behaviour
It does not deploy function with private image and registryAuth and throws `ImagePullbackOff` error.

## Steps to Reproduce (for bugs)
1. Create a private docker image on docker hub
2. Create base64 encoded registryAuth data by replacing correct values here
```
{"auths":{"https://index.docker.io/v1/":{"username":"username","password":"password","email":"mail@gmail.com","auth":"dXNlcm5hbWU6cGFzc3dvcmQK"}}}
```
3.  Make post request with above registryAuth data and correct function + image name
```
POST  /system/functions
{
	"service": "node-test",
	"image": "username/image:tag",
	"resitryAuth": "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VybmFtZSIsInBhc3N3b3JkIjoicGFzc3dvcmQiLCJlbWFpbCI6Im1haWxAZ21haWwuY29tIiwiYXV0aCI6ImRYTmxjbTVoYldVNmNHRnpjM2R2Y21RSyJ9fX0="
}
``` 

## Context
*How has this issue affected you? What are you trying to accomplish?*
I allow users of my clusters to deploy their functions in a secure way, but they are not able to deploy private images with registryAuth option. Wondering if I am doing this correctly.

**Comment by alexellis** [comment]
`resitryAuth` is a typo. 

Please try using the faas-cli with the -a flag for faas-cli deploy. This is a well tested workflow and I'm unaware of any regression.

Please can you also not delete details from the issue template such as the version and orchestration? This is key information, I'm assuming you're a swarm user given that you're trying to use this approach.

If you're a Kubernetes user then please read the docs that explain how to achieve this result at https://docs.openfaas.com under Deployment -> Kubernetes. Scroll to the end.

**Comment by lakhansamani** [comment]
Thank you @alexellis for quick response.

I am using kubernetes with helm chart for deployment

**Comment by lakhansamani** [comment]
Thank you @alexellis for the quick response.

Thanks for pointing out the typo, but actually I have tried with `registryAuth` and confirmed that once again. But still, that doesn't work.

Also, I have deployed using the helm chart on k8s orchestration.
