### ISSUE TITLE
registryAuth param not working for private dockerhub images

### ISSUE THREAD

**Issue by lakhansamani** [openfaas/faas-netes#566]
Created this similar issue week back but still seeing this error
https://github.com/openfaas/faas-netes/issues/558

Have added more context and sandbox link in this issue

---
Deploying private docker image, using `/system/functions`  API and `registryAuth` does not work.
here is the sample request body

```
POST  /system/functions
{
	"service": "node-test",
	"image": "username/image:tag",
	"registryAuth": "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VybmFtZSIsInBhc3N3b3JkIjoicGFzc3dvcmQiLCJlbWFpbCI6Im1haWxAZ21haWwuY29tIiwiYXV0aCI6ImRYTmxjbTVoYldVNmNHRnpjM2R2Y21RSyJ9fX0="
}
``` 

## Expected Behaviour
This should deploy function in a similar way, it can deploy with `imagePullSecrets` option in YAML file. As the registryAuth value is the same as what secret data contains.

## Current Behaviour
It does not deploy function with private image and registryAuth and throws `ImagePullbackOff` error.

## Steps to Reproduce (for bugs)
1. Create a private docker image on docker hub
2. Create base64 encoded registryAuth data by replacing correct values here
```
{"auths":{"https://index.docker.io/v1/":{"username":"username","password":"password","email":"mail@gmail.com","auth":"dXNlcm5hbWU6cGFzc3dvcmQK"}}}
```
3.  Make post request with above registryAuth data and correct function + image name
```
POST  /system/functions
{
	"service": "node-test",
	"image": "username/image:tag",
	"registryAuth": "eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VybmFtZSIsInBhc3N3b3JkIjoicGFzc3dvcmQiLCJlbWFpbCI6Im1haWxAZ21haWwuY29tIiwiYXV0aCI6ImRYTmxjbTVoYldVNmNHRnpjM2R2Y21RSyJ9fX0="
}
``` 

For testing, I have created this sandbox and tried deploying `node-test` function with private image using `registryAuth` param with base64 encoded value.
http://admin:admin@34.73.110.219:8080/

## Context
*How has this issue affected you? What are you trying to accomplish?*

I allow users of my clusters to deploy their functions in a secure way, but they are not able to deploy private images with registryAuth option. Wondering if I am doing this correctly.

## Your Environment

Have deployed open-faas on Google Cloud using Kubernetes and helm chart.
Kubernetes Version: 1.14.8-gke.17

More context:
Following are the commands used for deployment

```
# Commands followed
kubectl create clusterrolebinding "cluster-admin-$(whoami)" \
  --clusterrole=cluster-admin \
  --user="$(gcloud config get-value core/account)"


# Add openfaas namespaces
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml

# Add openfaas repo
helm repo add openfaas https://openfaas.github.io/faas-netes/

# Generate secrets so that we can enable basic authentication for the gateway
PASSWORD=admin
kubectl -n openfaas create secret generic basic-auth \
--from-literal=basic-auth-user=admin \
--from-literal=basic-auth-password="$PASSWORD"


# Deploy open faas
helm repo update \
 && helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set basic_auth=true \
    --set functionNamespace=openfaas-fn \
		--set prometheus.create=false \
		--set alertmanager.create=false \
    --set serviceType=LoadBalancer
```

**Comment by LucasRoesler** [comment]
@lakhansamani unfortunately that value is specific to docker swarm. Kuberenetes does not support setting the registry auth this way. You must create k8s secrets before you deploy functions, and then, you can reference that secret in the secrets field. OpenFaaS will recognize that is an image pull secret and use it accordingly. This is the only way to specify the registry auth in k8s due to how k8s works.

Please see these OpenFaaS docs about how to use private images in k8s https://docs.openfaas.com/deployment/kubernetes/#option-1-use-an-ad-hoc-image-pull-secret

Also, the relevant doc about how image pull secrets work in k8s is here 
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by alexellis** [comment]
/set title: Question about Kubernetes and private registries

**Comment by lakhansamani** [comment]
@LucasRoesler @alexellis thank you for clearing it out. 👍
