### ISSUE TITLE
Namespaces handler status code

### ISSUE THREAD

**Issue by martindekov** [openfaas/faas-netes#567]
The namespaces handler returns `202` instead of `200` on request as per:
https://github.com/openfaas/faas-netes/blob/63fb7f04c57503c60fcf3c73e2788c7159d2280e/handlers/namespaces.go#L29

## Expected Behaviour

Return `200` on request as the other handlers.
## Current Behaviour

Returns `202`
## Possible Solution

Change status code
## Steps to Reproduce (for bugs)

1. Call the endpoint with `curl`
2. Check status returned `202`

## Context

I suppose the accepted status was meant in case we want to create namespaces with the endpoint in the future, now we only list already existing ones so we don't wait for anything. We just want to list the already existing namespaces so changing to `200` I think is the way to go for this handler.

When calling the endpoint with the cli I expect `200`. I can change the logic to have the expected status code as `202`, but still I think this can be quickly changed.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Dev
* Docker version `docker version` (e.g. Docker 17.0.05 ):
N/A
* What version and distriubtion of Kubernetes are you using? `kubectl version`
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
N/A
* Link to your project or a code example to reproduce issue:
N/A
`curl` the `system/namespaces` endpoint with more info on the response
* What network driver are you using and what CIDR? i.e. Weave net / Flannel
N/A

**Comment by alexellis** [comment]
You're absolutely right. Please do update to 200 - OK.
