### ISSUE TITLE
Don't create Service Accounts if .Values.RBAC set to false

### ISSUE THREAD

**Issue by rberrelleza** [openfaas/faas-netes#575]
Update the chart so Service Accounts are not craated  if `.Values.RBAC` is set to `false`

## Expected Behaviour
When I'm setting `RBAC` to `false`, my expectation is that I'm not going to be using RBAC and all the resources created will be using the default namespace account. In my experience, this is how other charts (e.g. NGINX and Cert-Manager) behave.

This makes it easier to use the chart is restricted environment like https://cloud.okteto.com

## Current Behaviour
When I set `RBAC` to `false`, the Service Accounts are still created, even if the roles are not. 

## Possible Solution
1. Not create the accounts and fallback to using the namespace's default account.
2. Add another setting (e.g. `RBAC.UseDefaultAccount`) to control this. (I think this is more verbose, and I'd prefer option 1).

**Comment by alexellis** [comment]
Is there ever a reason to set `RBAC=false`? I think we added it as a flag around K8s 1.6

**Comment by rberrelleza** [comment]
In our case, the SA of the namespace is already pre-configured with a restricted of permissions so we want to use that one instead of creating new ones.

**Comment by alexellis** [comment]
Have you got a PR for this?

**Comment by rberrelleza** [comment]
Not yet, but I'll prepare something in the next few days.

**Comment by rberrelleza** [comment]
we made some changes on our side that will let us consume the chart as is. I'll close this for now.
