### ISSUE TITLE
kafka-connector - add `asynchronous_invocation` to helm chart/template

### ISSUE THREAD

**Issue by dmcmorris** [openfaas/faas-netes#580]
Related to https://github.com/openfaas-incubator/kafka-connector/issues/58

There is an undocumented environment variable `asynchronous_invocation` for the [kafka-connector](https://github.com/openfaas-incubator/kafka-connector) that allows you to enable triggering async endpoints in the gateway.  This needs to be exposed through the helm chart to be usable for helm managed deployments

**Comment by alexellis** [comment]
Sounds good to me, feel free to document and raise a PR for it. Thanks for your interest @dmcmorris

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by alexellis** [comment]
/lock: inactive. Feel free to raise a new issue if this is still required by anyone.
