### ISSUE TITLE
Raspberry Pi custom cluster support request

### ISSUE THREAD

**Issue by kmjones1979** [openfaas/faas-netes#587]
Never has worked, this is a new setup. Following your guide, previously had flannel and moved to weave, not sure if that caused any issues.

## Current Behaviour

Getting CrashLoopBackOff occasionally and logs say cannot connect to Nats

## Context

pi@raspberrypi:~ $ kubectl logs queue-worker-86b68b85c4-7ftxb -n openfaas
Connect: nats://nats.openfaas.svc.cluster.local:4222
can't connect to nats://nats.openfaas.svc.cluster.local:4222: nats: no servers available for connection
panic: can't connect to nats://nats.openfaas.svc.cluster.local:4222: nats: no servers available for connection

goroutine 1 [running]:
log.Panic(0x10a0eec, 0x1, 0x1)
        /usr/local/go/src/log/log.go:326 +0x94
main.main()
        /go/src/github.com/openfaas/nats-queue-worker/main.go:222 +0x310
pi@raspberrypi:~ $ kubectl -n openfaas get po,svc
NAME                                READY   STATUS             RESTARTS   AGE
pod/alertmanager-5c69dcdb9d-nv4xl   1/1     Running            0          4m2s
pod/faas-idler-5fd4cc8654-fsv8q     1/1     Running            4          4m2s
pod/gateway-85589c54dd-g8lzl        1/2     CrashLoopBackOff   5          4m2s
pod/nats-b9d9cd4fb-v4blf            1/1     Running            0          3m59s
pod/prometheus-77d4c5865f-62vf5     1/1     Running            0          3m56s
pod/queue-worker-86b68b85c4-7ftxb   0/1     CrashLoopBackOff   5          3m56s

NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/alertmanager       ClusterIP   10.97.41.133     <none>        9093/TCP         4m2s
service/gateway            ClusterIP   10.100.113.140   <none>        8080/TCP         4m
service/gateway-external   NodePort    10.106.246.178   <none>        8080:31112/TCP   4m
service/nats               ClusterIP   10.103.68.68     <none>        4222/TCP         3m59s
service/prometheus         ClusterIP   10.107.1.218     <none>        9090/TCP         3m57s

pi@raspberrypi:~ $ kubectl logs -f nats-b9d9cd4fb-v4blf -n openfaas
[1] 2020/01/27 10:13:10.562775 [INF] STREAM: Starting nats-streaming-server[faas-cluster] version 0.11.2
[1] 2020/01/27 10:13:10.562892 [INF] STREAM: ServerID: u4eNd3Crk6KogbFshvjQ1g
[1] 2020/01/27 10:13:10.562907 [INF] STREAM: Go version: go1.11.1
[1] 2020/01/27 10:13:10.564324 [INF] Starting nats-server version 1.3.0
[1] 2020/01/27 10:13:10.564372 [INF] Git commit [not set]
[1] 2020/01/27 10:13:10.564645 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2020/01/27 10:13:10.564669 [INF] Server is ready
[1] 2020/01/27 10:13:10.593703 [INF] STREAM: Recovering the state...
[1] 2020/01/27 10:13:10.593733 [INF] STREAM: No recovered state
[1] 2020/01/27 10:13:10.844613 [INF] STREAM: Message store is MEMORY
[1] 2020/01/27 10:13:10.844704 [INF] STREAM: ---------- Store Limits ----------
[1] 2020/01/27 10:13:10.844719 [INF] STREAM: Channels:                  100 *
[1] 2020/01/27 10:13:10.844731 [INF] STREAM: --------- Channels Limits --------
[1] 2020/01/27 10:13:10.844744 [INF] STREAM:   Subscriptions:          1000 *
[1] 2020/01/27 10:13:10.844755 [INF] STREAM:   Messages     :       1000000 *
[1] 2020/01/27 10:13:10.844773 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2020/01/27 10:13:10.844785 [INF] STREAM:   Age          :     unlimited *
[1] 2020/01/27 10:13:10.844796 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2020/01/27 10:13:10.844818 [INF] STREAM: ----------------------------------

pi@raspberrypi:~ $ host nats.openfaas.svc.cluster.local
Host nats.openfaas.svc.cluster.local not found: 3(NXDOMAIN)
pi@raspberrypi:~ $

pi@raspberrypi:~ $ kubectl get pod -n kube-system -o wide
NAME                                  READY   STATUS    RESTARTS   AGE   IP                NODE          NOMINATED NODE   READINESS GATES
coredns-6955765f44-l8dtz              1/1     Running   0          63m   10.32.0.2         raspberrypi   <none>           <none>
coredns-6955765f44-mdj2h              1/1     Running   0          63m   10.32.0.3         raspberrypi   <none>           <none>
etcd-raspberrypi                      1/1     Running   2          63m   192.168.150.114   raspberrypi   <none>           <none>
kube-apiserver-raspberrypi            1/1     Running   2          63m   192.168.150.114   raspberrypi   <none>           <none>
kube-controller-manager-raspberrypi   1/1     Running   4          63m   192.168.150.114   raspberrypi   <none>           <none>
kube-proxy-8cmct                      1/1     Running   1          63m   192.168.150.114   raspberrypi   <none>           <none>
kube-scheduler-raspberrypi            1/1     Running   5          63m   192.168.150.114   raspberrypi   <none>           <none>
weave-net-q4jhc                       2/2     Running   12         62m   192.168.150.114   raspberrypi   <none>           <none>

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Newest 19.03.05

* What version and distriubtion of Kubernetes are you using? `kubectl version`
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/arm"}

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspbian

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
/set title: Raspberry Pi custom cluster support request

**Comment by alexellis** [comment]
Hi, I recommend using k3sup, it's bullet-proof and works every time. I can't support kubeadm clusters on Raspberry Pi at this time. 

Try it and report back, you'll be pleasantly surprised. 

Complete instructions are here https://blog.alexellis.io/raspberry-pi-homelab-with-k3sup/

**Comment by kmjones1979** [comment]
Ok thanks. Two questions, should I just kubeadm reset and then run k3sup? Second question, what exactly does the —load-balancer flag do?
