### ISSUE TITLE
Make it more clear how to install using helm in raspberry pi

### ISSUE THREAD

**Issue by rgl** [openfaas/faas-netes#593]
The instructions at https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md are not very clear on how to install under raspberry pi and helm.

This is what I ended up using:

```bash
# install openfaas.
# NB please make sure the namespaces.yml version and the chart version work together.
faas_netes_version='0.10.1'
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/$faas_netes_version/namespaces.yml
helm install \
    openfaas \
    openfaas/openfaas \
    --version 5.5.4 \
    --namespace openfaas \
    --values https://raw.githubusercontent.com/openfaas/faas-netes/$faas_netes_version/chart/openfaas/values-armhf.yaml \
    --set functionNamespace=openfaas-fn \
    --set generateBasicAuth=true
```

Is this OK?

This ends up being a bit odd having to specify two versions, the git repository version and the helm chart version.

**Comment by alexellis** [comment]
Hi @rgl,

Please can you use the documentation to install OpenFaaS? We provide full tooling via k3sup here:

https://docs.openfaas.com/deployment/kubernetes/

Alex

**Comment by rgl** [comment]
I did see it, but since I first want to see the "raw" experience to better appreciate the tools that try to hide all the complexity, I wanted to start with raw helm.

Thanks for the highlight patch, it makes things more clear to me!
