### ISSUE TITLE
Proposal: Disable EnableServiceLinks environment variables for functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#599]
Proposal to disable EnableServiceLinks environment variables for functions

## Expected Behaviour

Functions should not be able to discover other functions and services in the same namespace.

## Current Behaviour

Kubernetes injects environment variables to each Pod with the IP and port of ever other service in the cluster's namespace and for the Kubernetes API Server.

See here for more: https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services

## Possible Solution

Having dug into the Kubelet codebase, looking for a global flag, I didn't find one, but found an override in the PodSpec which seems reasonable to set as a default for all users.

https://github.com/kubernetes/kubernetes/blob/21d4d13d98219b2d6e04ba7d1a634fbd62f9a256/pkg/kubelet/kubelet_pods.go#L555

Simply set: pod.spec.enableServiceLinks to false.

## Steps to Reproduce (for bugs)

1. Deploy two functions
2. Look at os.env
3. You'll see both can see each other's IP and ports via env-vars.

## Context

As part of defence in depth, and multi-tenancy preparations this hardens an environment for commercial users.

**Comment by andeplane** [comment]
We at Cognite would benefit from this change because we have multiple customers deploying functions and we'd like to avoid to leak information about other functions through DNS or environment variables.

**Comment by alexellis** [comment]
From my perspective, there's been no concerns raised after two months. It seems like a sensible default to have this, a PR would be welcome to change the default to "disabled"
