### ISSUE TITLE
Add possibility to configure DNSPolicy and DNSConfig on function pods

### ISSUE THREAD

**Issue by andeplane** [openfaas/faas-netes#604]
I'm working at Cognite (a Norwegian based tech company), and we are using OpenFaaS to build a function service for our customers. We will reuse our existing kubernetes cluster for various reasons, so I have applied egress network policies to prevent internal traffic between pods in k8s. This cannot be controlled with ingress on all services as we are many teams who create services, and it's not feasible for everyone to implement network policies.

I have blocked the typical internal IP ranges that includes 10.x.x.x, which also blocks k8s DNS. This is also a good thing, because we don't want to reveal internal service names to these functions anyway.

In order to let the functions talk to the internet, I need to then configure another DNS. Currrently, faas-netes is hard coded to use the [DNSPolocy=DNSClusterFirst](https://github.com/openfaas/faas-netes/blob/master/handlers/deploy.go#L214) which afaik uses k8s DNS. I have for our internal usage as of now patched faas-netes so it looks like
```
DNSPolicy:          corev1.DNSNone,
DNSConfig: &corev1.PodDNSConfig{
	Nameservers: []string{"8.8.8.8", "8.8.4.4"},
},
```
instead, which works very well. Ideally, this should be possible to choose with the same pattern as other similar settings, namely using annotations.

## Expected Behaviour
I would like to be able to customize the DNSPolicy and DNSConfig using annotations.

## Current Behaviour
DNSPolicy is always `ClusterFirst`.

## Possible Solution
We can customize this using annotations. For instance:
```
com.openfaas.dns-policy: OneOf("ClusterFirstWithHostNet", "ClusterFirst", "Default", "None")
```
whereas the PodDNSConfig supports `Nameservers`, `Searches` and `Options` where I have only used the Namservers so far. Not surer how it can/should look like if we want this fully configurable.

## Context
To prevent the functions from accessing internal services (which we won't allow) I had to apply network policies that blocked k8s DNS, so I needed to patch faas-netes for functions to talk to internet.

## Your Environment
`openfaas/faas-netes:0.10.1`
Running on GKE in Google Cloud.
Function pods and other services have ip's  10.x.x.x in k8s.

**Comment by LucasRoesler** [comment]
It seems like this should be covered in the Profile feature #586

**Comment by wilsonianb** [comment]
I'm interested in this as well and agree that [profiles](https://docs.openfaas.com/reference/profiles/) seems like the right place.
@andeplane Would being able to configure [DNSPolicy](https://godoc.org/k8s.io/api/core/v1#DNSPolicy) as `DNSDefault` to use the node's DNS be sufficient? Or do you think profiles should also support [PodDNSConfig](https://godoc.org/k8s.io/api/core/v1#PodDNSConfig)?

**Comment by LucasRoesler** [comment]
The docs on the DNSPolicy `none` indicate that both are required

> // DNSNone indicates that the pod should use empty DNS settings. DNS
> // parameters such as nameservers and search paths should be defined via
> // DNSConfig.

**Comment by wilsonianb** [comment]
:+1: 
Profiles could potentially disallow `none`
but (like the issue originally suggested) supporting DNSPolicy and DNSConfig seems like the way to go.
