### ISSUE TITLE
Several image options in --set in the helm chart are missing

### ISSUE THREAD

**Issue by andeplane** [openfaas/faas-netes#605]
At Cognite, we've had to patch faas-netes as a workaround for https://github.com/openfaas/faas-netes/issues/604 and https://github.com/openfaas/faas-netes/issues/358. We use helm to produce a manifest that we then modify before it is deployed in our k8s clusters, so I need to modify which image I use. 

The list over options at the end of https://github.com/openfaas/faas-netes/tree/master/chart/openfaas does not include `image` for several of the services in OpenFaaS.

## Expected Behaviour
It should be documented that you can do 
`--set faasnetes.image`
`--set gateway.image`
`--set gateway.image`
`--set queueWorker.image`
`--set nats.image`
`--set faasIdler.image`,

## Current Behaviour
These are missing from the docs.

## Possible Solution
See fix here https://github.com/andeplane/faas-netes/commit/8c57c9debd7bef4c2e01ef8418445d0425159f90. Will create a PR.

## Context
I ended up doing it in a stupid way in the manifests.yaml instead.

**Comment by alexellis** [comment]
@andeplane feel free to contribute these, otherwise we'll close the issue and see if it comes up again.

**Comment by alexellis** [comment]
I believe that we have these now.
