### ISSUE TITLE
Volume secret name can limit length of the function name

### ISSUE THREAD

**Issue by andeplane** [openfaas/faas-netes#609]
This might only apply to k8s deployments.

If a secret is provided a function, a volume is mounted with name [{functionName}-projected-secrets](https://github.com/openfaas/faas-netes/blob/master/k8s/secrets.go#L221). This volume name also has a k8s limitation of 63 chars. As `-projected-secrets` is 18 chars, the function name should have max length 45 chars.

## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

If a secret is provided a function, a volume is mounted with name [{functionName}-projected-secrets](https://github.com/openfaas/faas-netes/blob/master/k8s/secrets.go#L221). This volume name also has a k8s limitation of 63 chars. As `-projected-secrets` is 18 chars, the function name should have max length 45 chars.

## Expected Behaviour
This limit should be documented. Closest thing I found was https://docs.openfaas.com/reference/yaml where it states that `Valid function names follow ietf rfc1035 which is also used for DNS sub-domains.`. I would then expect a function name of 63 chars to work.

## Current Behaviour
A function name of 63 chars with a secret fails with the following error
```
common.exceptions.DeployError: Message: unable create Deployment: Deployment.apps "veryLongServiceNameveryLongServiceNameveryLongServiceNameveryLo" is invalid: [spec.template.spec.volumes[0].name: Invalid value: "veryLongServiceNameveryLongServiceNameveryLongServiceNameveryLo-projected-secrets": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "veryLongServiceNameveryLongServiceNameveryLongServiceNameveryLo-projected-secrets"]
```

## Possible Solution
Rewrite the docs, and add a rejection in the API?

## Steps to Reproduce (for bugs)
1. Create function with name `veryLongServiceNameveryLongServiceNameveryLongServiceNameveryLo`
2. Remember to add at least one secret
3. Deploy

## Context
I'm generating function names based on multiple things (customer, function name, function id etc) and stumbled upon this as a function name became long. I did cap it to 63, but deployment failed.
## Your Environment
* FaaS-CLI version 0.11.7

* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
K8s, this happens in `faas-netes`.

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Code example or link to GitHub repo or gist to reproduce problem:
N/A

**Comment by alexellis** [comment]
/set title: Volume secret name can limit length of the function name

**Comment by LucasRoesler** [comment]
I think we can safely switch to the function name directly. I am pretty sure I used the prefix because we weren't 100% sure of the implementation at the start, but it is pretty well defined now and making that switch should be possible

**Comment by alexellis** [comment]
/lock: inactive. Feel free to raise a new issue if this is still required by anyone.
