### ISSUE TITLE
openshift Openfaas gateway doesn't start

### ISSUE THREAD

**Issue by DoctusHartwald** [openfaas/faas-netes#611]
## Expected Behaviour
openfaas gateway should be up and running

## Current Behaviour
the pod  gateway doesn't start up

## Steps to Reproduce (for bugs)
oc new-project openfaas-fn
oc new-project openfaas
oc create sa faas-controller
oc policy add-role-to-user admin  system:serviceaccount:openfaas:faas-controller --namespace=openfaas-fn 

helm repo add openfaas https://openfaas.github.io/faas-netes/
helm repo update
 helm repo update \
 && helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set basic_auth=true \
    --set functionNamespace=openfaas-fn

## Your Environment
minishift 
Helm 3.1.2

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://192.168.99.100:8443
kubernetes v1.11.0+d4cacc0

* Operating System and version (e.g. Linux, Windows, MacOS):
windows 10 with virtual box 

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
Hi,

I'm unaware of any issues with OpenFaaS on Kubernetes at present.

What instructions are you following?

Why haven't you created the requisite basic auth secrets? That is going to prevent openfaas from starting.

I would suggest you use the troubleshooting guide here 

See also: Check logs of the core services

https://docs.openfaas.com/deployment/troubleshooting/#check-logs-of-the-core-services

**Comment by DoctusHartwald** [comment]
i've created the basic auth secrets as :

OPEN GIT BASH
*************
head -c 12 /dev/urandom | shasum| cut -d' ' -f1
0b6808e131db6b5509c32b2ac6a702e6b1d2a72b

>> Recopier le password
PASSWORD=0b6808e131db6b5509c32b2ac6a702e6b1d2a72b
>> Verifier le password 
echo $PASSWORD

 oc -n openfaas create secret generic basic-auth --from-literal=basic-auth-user=admin --from-literal=basic-auth-password="$PASSWORD"
 
 secret/basic-auth created

**Comment by alexellis** [comment]
However you didn't show that in your initial setup, which is probably why it failed to work.

Now can you delete the helm chart and install again now that the auth secrets are present? Then go and work through the troubleshooting guide. The reason it exists is to help you, help yourself.

Commercial support is also available, if you need it, go to https://openfaas.com/support/

**Comment by DoctusHartwald** [comment]
bellow the commands i've executed, the pod of the gateway doesn't start.... did i miss something?
oc delete project openfaas
oc delete project openfaas-fn

oc new-project openfaas-fn
oc new-project openfaas
oc create sa faas-controller
oc policy add-role-to-user admin  system:serviceaccount:openfaas:faas-controller --namespace=openfaas-fn 

PASSWORD=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)	
oc -n openfaas create secret generic basic-auth --from-literal=basic-auth-user=admin --from-literal=basic-auth-password="$PASSWORD"

helm repo update \
 && helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set functionNamespace=openfaas-fn \
    --set generateBasicAuth=true

**Comment by DoctusHartwald** [comment]
![image](https://user-images.githubusercontent.com/9788043/79442365-c13ec000-7fd8-11ea-8602-f1ef7eae2039.png)

**Comment by DoctusHartwald** [comment]
its a bug ...
24s         11m          19        gateway-865955cd6f.160643dda30d19cc              ReplicaSet                                   Warning   FailedCreate        replicaset-controller   Error creating: pods "gateway-865955cd6f-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 10001: must be in the ranges: [1000180000, 1000189999] spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 10001: must be in the ranges: [**1000180000, 1000189999]**]

**Comment by alexellis** [comment]
Can you elaborate on what you mean by "it's a bug"? There is no defect that I'm aware of, OpenShift needs a specific range of user IDs, see also: #612 where we cover how you can disable the default user ID.

**Comment by alexellis** [comment]
Latest tested instructions -> https://blog.alexellis.io/openshift-in-a-footloose-container/
