### ISSUE TITLE
Feature request - OpenShift securityContext configuration

### ISSUE THREAD

**Issue by DoctusHartwald** [openfaas/faas-netes#612]
## Expected Behaviour
the gateway shall be able to start

## Current Behaviour
 oc get events --sort-by=.metadata.creationTimestamp -n openfaas
`1m          5m           17        gateway-68bb6dd664.160644b594b334ab              ReplicaSet                                   Warning   FailedCreate        replicaset-controller   Error creating: pods "gateway-68bb6dd664-" is forbidden: unable to validate against any security context constraint: [spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 10001: must be in the ranges: [1000180000, 1000189999]]`

## Possible Solution
change the value in the yaml

## Steps to Reproduce (for bugs)
```
oc new-project openfaas-fn
oc new-project openfaas
oc create sa faas-controller
oc policy add-role-to-user admin  system:serviceaccount:openfaas:faas-controller --namespace=openfaas-fn 

PASSWORD=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)	


oc -n openfaas create secret generic basic-auth --from-literal=basic-auth-user=admin --from-literal=basic-auth-password="$PASSWORD"	
 secret/basic-auth created
 helm repo update \
 && helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set functionNamespace=openfaas-fn \
    --set generateBasicAuth=true 
```
## Your Environment
Minishift on VirtualBOX 

oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://192.168.99.100:8443
kubernetes v1.11.0+d4cacc0

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):
windows 10 on virtual box 
* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by DoctusHartwald** [comment]
same error on basic-auth-plugin module

**Comment by alexellis** [comment]
/set title: Feature request - OpenShift securityContext configuration

**Comment by alexellis** [comment]
Intility are OpenFaaS and OpenShift users too, I asked them to log an issue for this but they didn't. 

The work-around for them was to use edit the deployments after they were deployed. I would suggest you use kubectl patch instead that will be much quicker/easier against deployments in the namespace. 

We don't have a lot of OpenShift users and none that contribute AFAIK. 

@stefanprodan @LucasRoesler one way to play nice with OpenShift is to not create the run as user. This could be a helm flag

**Comment by stefanprodan** [comment]
The security context can be disabled with https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/values.yaml#L14 so that OpenShift can set its own user id.

**Comment by alexellis** [comment]
That's great, does it retain the other security context settings like an R/O filesystem?

I'll close as resolved.

**Comment by DoctusHartwald** [comment]
the solution is simple change the id of runAsUser in the yaml for gateway and basic authen plugin then its working fine

**Comment by alexellis** [comment]
@stefanprodan said that you could just disable the security context. I guess you lose some other parameters right when doing that? Like the read only filesystem?

**Comment by alexellis** [comment]
Latest tested instructions -> https://blog.alexellis.io/openshift-in-a-footloose-container/
