### ISSUE TITLE
Multi-arch support for heterogeneous Kubernetes clusters

### ISSUE THREAD

**Issue by nicklasfrahm** [openfaas/faas-netes#613]
Currently, OpenFaaS supports multiple CPU architectures via separate `values.yaml` files. This means that it is possible to run `faas-netes` atop of a homogeneous cluster where all nodes have the same CPU architecture. I am currently running a heterogeneous cluster, where I would like the workloads and system containers to be automatically scheduled to either `arm` or `amd64` nodes.

I would like to contribute by:
- [x] Creating a list of all Docker images currently required for OpenFaaS
- [x] Researching necessary steps to make Docker images multi-arch (see [here](https://docs.docker.com/engine/reference/commandline/manifest/#create-and-push-a-manifest-list))
- [x] Creating a strategy to migrate images to multi-arch images
- [ ] Driving the effort of making all of them multi-arch, such that we can only provide a single `values.yaml` file.

The following images are used by OpenFaaS and provide image manifest lists for the followig architectures:
- [ ] openfaas/gateway:0.18.13
  - [ ] `arm`
  - [ ] `arm64`
  - [ ] `amd64`
- [ ] openfaas/basic-auth-plugin:0.18.11
  - [ ] `arm`
  - [ ] `arm64`
  - [ ] `amd64`
- [ ] openfaas/openfaas-oidc-plugin:0.3.3
  - [ ] `arm`
  - [x] `arm64`
  - [x] `amd64`
- [ ] openfaas/faas-netes:0.10.2-rc1
  - [ ] `arm`
  - [ ] `arm64`
  - [ ] `amd64`
- [x] openfaas/queue-worker:0.9.0
  - [x] `arm`
  - [x] `arm64`
  - [x] `amd64`
  - [x] `ppc64le`
- [x] prom/prometheus:v2.11.0
  - [x] `arm`
  - [x] `arm64`
  - [x] `amd64`
- [x] prom/alertmanager:v0.18.0
  - [x] `arm`
  - [x] `arm64`
  - [x] `amd64`
- [x] nats-streaming:0.17.0
  - [x] `arm`
  - [x] `arm64`
  - [x] `amd64`
- [x] openfaas/ingress-operator:0.5.0
  - [x] `arm`
  - [x] `arm64`
  - [x] `amd64`
- [ ] openfaas/faas-idler:0.3.0
  - [ ] `arm`
  - [ ] `arm64`
  - [ ] `amd64`

_Note:_ I used the `docker manifest inspect $IMAGE:$TAG` command to verify this.

**Comment by nicklasfrahm** [comment]
The strategy I would go for would be to create a new dedicated tag suffix for `amd64`, such that the images would look similar to this: `openfaas/faas-netes:0.10.2-rc1-amd64` and then creating and pushing image manifest via the `docker manifest` command.

The `docker manifest` command is experimental. Would that be a problem?

**Comment by alexellis** [comment]
I appreciate your interest in this area.

I am not aware of any commercial users that need armhf or arm64 support, and there are some downsides to adding it. For instance, look at the build time of the inlets-operator and how much it increased when adding this type of cross-compilation.

My worry is that the build would take > 20-35 minutes and that's not going to be practical. 

I mentioned on SIGFriday that I'm building most of the images out of band for armhf and arm64, we could still have a manifest for them pushed after the manual builds, would that work for your use-case?

**Comment by nicklasfrahm** [comment]
I understand that, commercial customers have to come first! Having a manifest would work for me, but I would advocate to give the `amd64` images a tag suffix too. Just like you do with the `armhf` and `arm64`. Then the manifest could exist without any version suffix.

In the future I would like to help you automate some of the process if you are up for it, under the condition that we can manage at reasonable speeds.

**Comment by alexellis** [comment]
/lock: inactive. Feel free to raise a new issue if this is still required by anyone.
