### ISSUE TITLE
The deployment never ends: ContainerCreating for 5 of 7 pods

### ISSUE THREAD

**Issue by thinkORo** [openfaas/faas-netes#619]
This might only apply to deployments on Windows 10 2004 (Insider Preview).

My Kubernetes environment runs under Docker on Window 10, but not with WSL2.
Note: Everything seems to work under MacOS.

## Expected Behaviour
OpenFAAS should run on local Kubernetes instance.

## Current Behaviour
5 of 7 pods are not running as expected with status: ContainerCreating
Only nats and prometheus is up and running with status: Running

## Possible Solution
-

## Steps to Reproduce (for bugs)
1. git clone https://github.com/openfaas/faas-netes.git
2. cd faas-netes
3. kubectl apply -f namespaces.yaml
4. kubectl apply -f yaml

## Your Environment
* Docker version: 19.03.8

* What version and distribution of Kubernetes are you using: 1.18.2

* Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 2004 (Insider Preview)

**Comment by alexellis** [comment]
You're missing steps for deployment which is why this isn't working.

Please read the instructions and follow them.

https://docs.openfaas.com/deployment/kubernetes/

**Comment by thinkORo** [comment]
Well, you're correct, sorry. For all others, this was missing:

# generate a random password
PASSWORD=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)

kubectl -n openfaas create secret generic basic-auth \
--from-literal=basic-auth-user=admin \
--from-literal=basic-auth-password="$PASSWORD"

Thanks for your support, Alex

**Comment by alexellis** [comment]
This is in the docs, so what instructions were you following?

Also, you should really use arkade or helm to install openfaas, not the generated YAML files.

**Comment by thinkORo** [comment]
On my MacBook I followed your instructions from the mentioned website/link. But I forgot to create the respective secrets on my Windows 10 machine.

I tried to use Arkade (as I used k3sup before on my Raspberry PI Cluster), but I got an error on my Windows machine. There was mix of "\" and "/" with the info that the executable for helm is missing.

**Comment by alexellis** [comment]
Can you create an issue please?

**Comment by thinkORo** [comment]
Sure, you can close this one. Thanks again.
