### ISSUE TITLE
Typo in chart template

### ISSUE THREAD

**Issue by juli3nk** [openfaas/faas-netes#628]
https://github.com/openfaas/faas-netes/blob/9d972d9d37d1f5bd8d837719baf884e72e31cf08/chart/openfaas/templates/gateway-dep.yaml#L201

## Expected Behaviour

`imagePullPolicy: {{ .Values.openfaasImagePullPolicy }}`

**Comment by alexellis** [comment]
Thanks for reporting the typo.

@viveksyngh please can you take this?

**Comment by alexellis** [comment]
The chart has been republished with this fix, thank you @viveksyngh
