### ISSUE TITLE
Unable to deploy a function with the Operator in K8s 1.18

### ISSUE THREAD

**Issue by flamedmg** [openfaas/faas-netes#630]
## My actions before raising this issue
- [x ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ x] Read/searched [the docs](https://docs.openfaas.com/)
- [x ] Searched [past issues](/issues)

Function can't be updated on kubernetes 1.17.5 (latest in DO). Update fails with the message:
```
Unexpected status: 500, message: functions.openfaas.com "function-name" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```
Freshly installed openfaas, ingress controller, cert manager. Installed function with 
`faas up -f function.yaml`
Right after deployment, deploying one more time to update and getting error message from above.

## Expected Behaviour
Function should be properly deployed

## Current Behaviour
Deployment fails

## Steps to Reproduce (for bugs)

1.  Install faas via helm3 chart
2. Install nginx ingress controller
3. Install cert manager
4. Deploy any function, i used python3-http
5. Redeploy, it will fail
Basicly i was following the following guide: https://docs.openfaas.com/reference/ssl/kubernetes-with-cert-manager/

## Context
I'm happy to provide access to this test cluster if required

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
I believe the code invoked lives here -> https://github.com/openfaas/faas-netes/blob/master/pkg/server/apply.go

faas-cli -> HTTP -> gateway -> faas-netes (in operator mode) -> apply.go

**Comment by alexellis** [comment]
Perhaps the CRD validation got tighter and fails in 1.18 and 1.17.5?

```
Status:
  Accepted Names:
    Kind:       Function
    List Kind:  FunctionList
    Plural:     functions
    Short Names:
      fn
    Singular:  function
  Conditions:
    Last Transition Time:  2020-05-07T18:59:19Z
    Message:               [spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[annotations].anyOf[0].type: Forbidden: must be empty to be structural, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[annotations].anyOf[1].type: Forbidden: must be empty to be structural, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[annotations].type: Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[constraints].items: Required value: must be specified, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[labels].anyOf[0].type: Forbidden: must be empty to be structural, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[labels].anyOf[1].type: Forbidden: must be empty to be structural, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[labels].type: Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[limits].type: Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[requests].type: Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[secrets].items: Required value: must be specified, spec.versions[0].schema.openAPIV3Schema.properties[spec].type: Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.type: Required value: must not be empty at the root, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[annotations].anyOf[0].type: Forbidden: must be empty to be structural, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[annotations].anyOf[1].type: Forbidden: must be empty to be structural, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[annotations].type: Required value: must not be empty for specified object fields, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[constraints].items: Required value: must be specified, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[labels].anyOf[0].type: Forbidden: must be empty to be structural, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[labels].anyOf[1].type: Forbidden: must be empty to be structural, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[labels].type: Required value: must not be empty for specified object fields, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[limits].type: Required value: must not be empty for specified object fields, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[requests].type: Required value: must not be empty for specified object fields, spec.versions[1].schema.openAPIV3Schema.properties[spec].properties[secrets].items: Required value: must be specified, spec.versions[1].schema.openAPIV3Schema.properties[spec].type: Required value: must not be empty for specified object fields, spec.versions[1].schema.openAPIV3Schema.type: Required value: must not be empty at the root]
    Reason:                Violations
    Status:                True
    Type:                  NonStructuralSchema
    Last Transition Time:  2020-05-07T18:59:19Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2020-05-07T18:59:19Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1
Events:  <none>

```

**Comment by flamedmg** [comment]
Confirming, open-faas works just fine without operator mode!

**Comment by alexellis** [comment]
My sense is that we have an issue with the CRD schema validation which one resolved may fix 1.17.5, 1.18 may need additional changes, but I'm not sure. We are using the 1.17 version of client-go, so I'd expect it work out the box with 1.18.

1.18 notes - https://kubernetes.io/docs/setup/release/notes/
1.17 notes - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v1174

**Comment by alexellis** [comment]
Reading [this post](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/)

> As you can see also logical constraints using oneOf, allOf, anyOf, not are allowed.

I wonder if it is related?

**Comment by liggitt** [comment]
The messages added to status surface issues with your schema that prevent it from being treated as a structural schema. That prevents openapi from being published for your type, and would prevent you from creating this CRD via the v1 API, but would not by itself prevent update of the v1beta1 CRD or submission of custom resources.

The `anyOf` part sounds like it might be related to https://github.com/kubernetes/kubernetes/issues/85127#issuecomment-605890538 in which server-side-apply aspects of the request handler make use of schema info, and appear to have issues with some complex schemas that are not structural. https://github.com/kubernetes/kubernetes/pull/90656 is in progress to handle schemas like that more gracefully.

**Comment by liggitt** [comment]
The 500 error with "managed fields: failed to convert live object to proper version" is related to server-side-apply, which enabled managed fields by default in 1.18. Can you open an issue in kubernetes/kubernetes specifically around this error? If there's a reproducer that can be seen with just CRD and CR manifests and kubectl, that would be ideal if possible.

**Comment by alexellis** [comment]
When creating a function via kubectl instead of the REST API, it creates the first time, but updating gives this error:

```
E0507 21:41:22.217223   17355 reflector.go:153] pkg/mod/k8s.io/client-go@
v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Function: v1.Fun
ctionList.Items: []v1.Function: v1.Function.Spec: v1.FunctionSpec.Labels:
 ReadString: expects " or n, but found t, error found in #10 byte of ...|:{"alex":true},"name|..., bigger context ...|mage":"functions/figlet:0.13.0","labels":{"alex":true},"name":"figlet"}}],"kind":"FunctionList","met|...
E0507 21:41:23.221735   17355 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Function: v1.FunctionList.Items: []v1.Function: v1.Function.Spec: v1.FunctionSpec.Labels: ReadString: expects " or n, but found t, error found in #10 byte of ...|:{"alex":true},"name|..., bigger context ...|mage":"functions/figlet:0.13.0","
```

kubectl apply -f for:

```
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: figlet
  namespace: openfaas-fn
spec:
  name: figlet
  image: functions/figlet:0.13.0
  labels:
    alex: yes
```

**Comment by liggitt** [comment]
> Then when updating to have labels it gave this error in a loop:

I think that's a red herring... `"alex":true` isn't a valid label... it needs to be quoted, e.g. `"alex":"true"`

**Comment by alexellis** [comment]
You are right :facepalm:  Let me verify it.

**Comment by alexellis** [comment]
```

# kubectl apply quoted label value
I0507 20:49:55.866090       1 controller.go:254] Creating deployment for 'figlet'
I0507 20:49:55.958536       1 controller.go:266] Creating ClusterIP service for 'figlet'

# kubectl apply quoted label value with a second label value
I0507 20:50:18.204932       1 controller.go:295] Updating deployment for 'figlet'

# deploy via the REST API (linked above in apply.go)
E0507 20:50:26.393631       1 apply.go:68] Function nodeinfo update error: failed to update object (Update for openfaas.com/v1, Kind=Function) managed fields: failed to convert live object to proper version: /, Kind= is unstructured and is not suitable for converting to "openfaas.com/v1"

# update the figlet function via the REST API (linked above in apply.go)
E0507 20:50:31.286874       1 apply.go:68] Function figlet update error: functions.openfaas.com "figlet" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

**Comment by alexellis** [comment]
I raised #631 to get around the error on metadata.resourceVersion. @stefanprodan if you have time, can you comment on why this code was doing an update, then checking for a 404, before doing a create? It seems like this isn't supported in the latest version of K8s unless there's an extra flag that's now needed.

`openfaas/faas-netes:0.10.5-3` contains the patch @flamedmg if you wanted to try it out? `arkade install openfaas --set operator.image=openfaas/faas-netes:0.10.5-3 --operator`

**Comment by liggitt** [comment]
> What's a good place to start debugging this?

Seeing the incoming request to the API server would be helpful. Enabling request body logging in audit events for this resource would enable that. See https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy for details on enabling audit logging at Request level for a specific resource. 

What version of client-go was the client doing the API updates built with, and what API server version(s) is this observed with?

**Comment by LucasRoesler** [comment]
I suspect that this is relevant https://github.com/kubernetes/kubernetes/issues/70674#issuecomment-436737939

Other projects had the same error for example https://github.com/elastic/cloud-on-k8s/issues/2200 and https://github.com/banzaicloud/terraform-provider-k8s/issues/25

I suspect that we need to try to Get the Function first _then_  use Update if it is found, otherwise use Create.  

I agree with @alexellis and we can fix this in https://github.com/openfaas/faas-netes/blob/1a7bcd976caa50ee6f4640f7f747d2b455dbecfc/pkg/server/apply.go#L52-L73

**Comment by alexellis** [comment]
I put this together last night and tested it. Not sure why the linking didn't put a nice pop-out box on the issue. 

https://github.com/openfaas/faas-netes/pull/631

**Comment by liggitt** [comment]
The `Invalid value: 0x0: must be specified for an update` message is because resourceVersion is required when PUTing updates to custom resources. That has always been the case for custom resources. Reproduced on 1.15:

```sh
curl -k -X PUT https://localhost:6443/apis/example.com/v1/namespaces/default/foos/test \
  -H "Content-Type: application/json" \
  --data '{"kind":"Foo","apiVersion":"example.com/v1","metadata":{"name":"test"}}'
```

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "foos.example.com \"test\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update",
  "reason": "Invalid",
  "details": {
    "name": "test",
    "group": "example.com",
    "kind": "foos",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: 0x0: must be specified for an update",
        "field": "metadata.resourceVersion"
      }
    ]
  },
  "code": 422
}
```

The `update error: failed to update object (Update for openfaas.com/v1, Kind=Function) managed fields: failed to convert live object to proper version: /, Kind= is unstructured and is not suitable for converting to "openfaas.com/v1"` error is definitely *not* expected. Definitely open an issue in kubernetes/kubernetes with whatever reproducer steps you have available.

**Comment by liggitt** [comment]
I created the [CRD](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/crd.yaml) manually in a 1.18 API server, then created/updated/patched Function API objects via the v1 and v1alpha2 APIs a lot of different ways, and was not able to reproduce the `failed to update object` 500 error... do you have any more details about the exact update request made that triggers that?

**Comment by alexellis** [comment]
The original poster appears to be on k8s 1.17.5 which may or may not have a bearing on it

**Comment by alexellis** [comment]
@flamedmg please can you try again with the latest release?
