### ISSUE TITLE
Add ability to configure the Prometheus host and port in the openfaas chart

### ISSUE THREAD

**Issue by talzion12** [openfaas/faas-netes#638]
## Expected Behaviour
I expect to be able to configure the Prometheus host/port through the chart's values.

## Current Behaviour
The Prometheus host/port is hardcoded, as can be seen [here](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/faas-idler-dep.yaml#L37).

## Possible Solution
I created a branch with a [possible fix](https://github.com/talzion12/faas-netes/commit/6fa4ff4ad85b970b8b3049feee449951306f8c62) in my fork.

## Context
I have a Prometheus instance that scrapes metrics from all of my environments. I'd like OpenFaas to be able to use this Prometheus instance.
The Prometheus instance is deployed in another namespace and so I'd like to be able to configure faas-idler's Prometheus host/port.

Also (this is a little unrelated to this specific issue) ideally I'd like multiple instances of faas-idler in different namespaces to be able to share a single Prometheus instance. This doesn't seem to be possible at the moment according to [this issue](https://github.com/openfaas-incubator/faas-idler/issues/37).

Awesome work btw, I'm really enjoying using this project =)

**Comment by talzion12** [comment]
@alexellis not sure if you're the right person to ask this but I can see you're active in this repo and probably the maintainer.
What do you think of this?
Would you be willing to merge if I create a pull request?

**Comment by alexellis** [comment]
Hi thank you for your interest in the project.

We will take a look into this request. 

You should probably know that projects that install their own versions of Prometheus do so for a reason and will often tune retention period and scrape interval to one that may not be generally useful.

Linkerd, Istio, OpenFaaS and several other projects take this approach. 

I don't understand the comment about multiple instances of faas-idler. Can you explain that usecase? 

Regards,

Alex

**Comment by alexellis** [comment]
@talzion12 we've started looking into this, but we need to hear from you again re: above.

Are you using multiple-namespaces? https://docs.openfaas.com/reference/namespaces/

**Comment by talzion12** [comment]
> You should probably know that projects that install their own versions of Prometheus do so for a reason and will often tune retention period and scrape interval to one that may not be generally useful.

I see, so does that mean that it's not recommended to share a single instance of Prometheus between my app and openfaas?

> I don't understand the comment about multiple instances of faas-idler. Can you explain that usecase?

Basically I have a cluster with multiple versions of my app, each in a separate namespace.
I thought it'd be nice for each of them to have a separate installation of openfaas local to their respective namespaces.
Not sure if this is the recommended approach, but I thought it makes sense to isolate the namespaces.
I already have an instance of Prometheus installed in another centralized namespace, and I wanted all of the installations of openfaas to share this Prometheus instance.

From my understanding if I have multiple instances of faas-idler (each in a separate namespace) and they share the Prometheus instance, faas-idler may not behave correctly.

**Comment by talzion12** [comment]
I'm reading about the multiple namespace support you mentioned and it sounds great. I'm not sure if I should switch to this approach when it supports openfaas operator which I'm using (in the issue you linked it seems to not be ready yet).

Although I think it may still be desirable sometimes to have separate gateway/nats-connector instances per environment, as a spike in traffic in one environment may affect the others.

On the other hand (correct me if I'm wrong) Prometheus and faas-idler shouldn't be affected by spikes in traffic, and so it makes sense for Prometheus be shared to save resources, as Prometheus is a rather large dependency.

**Comment by alexellis** [comment]
If you were thinking of sharing Prometheus between multiple openfaas instances, that is a different use-case to sharing Prometheus between openfaas and another set of apps (which I wouldn't recommend)

I am not sure that multiple instances of openfaas can even write to the same Prometheus instance, you will have to check that out manually and see if they all write and read appropriate keys, I don't believe that to be the case.

**Comment by talzion12** [comment]
Got it. I'll close this issue. Thanks =)

**Comment by alexgorbatchev** [comment]
I think being able to configure prometheus host/port is still valuable. I have a small cluster with one prometheus instance and would really prefer to continue using it instead of an additional sidecar.

**Comment by talzion12** [comment]
I agree it wouldn't hurt adding this as an option, although users should be aware of the drawbacks
