### ISSUE TITLE
OpenFaas chart readme refers to an old value's key

### ISSUE THREAD

**Issue by pasdam** [openfaas/faas-netes#640]
The OpenFaas chart documentation refer to old an value key, in particular in the [Tuning cold-start](https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#tuning-cold-start) the following key is used:

```yaml
faasnetes:
   imagePullPolicy: "IfNotPresent"    # Image pull policy for deployed functions
```

but according to the latest [values.yaml](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/values.yaml) it should be:

```yaml
openfaasImagePullPolicy: IfNotPresent
```

## Expected Behaviour

The README should refer to:

```yaml
openfaasImagePullPolicy: IfNotPresent
```

## Current Behaviour

It refers to:

```yaml
faasnetes:
   imagePullPolicy: "IfNotPresent"    # Image pull policy for deployed functions
```

## Possible Solution

Update the README

## Steps to Reproduce (for bugs)

N/A

## Context

N/A

## Your Environment

N/A

**Comment by alexellis** [comment]
Thanks for letting us know. Would you like to send a PR and to check the docs repo too?

**Comment by pasdam** [comment]
Sure, I can send a PR with the updated README

**Comment by pasdam** [comment]
Done:
* [PR for this repo](https://github.com/openfaas/faas-netes/pull/641)
* [Doc PR](https://github.com/openfaas/docs/pull/227)

**Comment by pasdam** [comment]
Closing this as I misunderstood the documentation, sorry about that
