### ISSUE TITLE
Function Resource should have status Ready condition

### ISSUE THREAD

**Issue by brandonkal** [openfaas/faas-netes#649]
## Expected Behaviour

Function resource returns status condition with Ready state.

## Current Behaviour

Not implemented.

## Possible Solution

I've fixed this in #648. But you can discuss here as well.

## Context

I can wait for other k8s resources to apply but not the Function resource currently. Since Function is essentially a deployment + service, it makes sense to track the child deployment and show its Ready status on the Function resource.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): latest

* Docker version `docker version` (e.g. Docker 17.0.05 ): latest

* What version and distriubtion of Kubernetes are you using? `kubectl version` latest

* Operating System and version (e.g. Linux, Windows, MacOS): All

* Link to your project or a code example to reproduce issue: not relevant

* What network driver are you using and what CIDR? i.e. Weave net / Flannel not relevant

**Comment by alexellis** [comment]
Hi @brandonkal thanks for your interest in the project.

Could you let us know *why* you want this change in your proposal?

In addition please list out the various scenarios and transitions you expect to see for the ready status.

Talk to us about Scaling from zero, scaling to zero, scaling from 1 to N, the initial deployment, when a function is updated and so on.

**Comment by brandonkal** [comment]
Why Function needs a status:

1. It's a useful and common feature in kubernetes
2. I need to know when the controller creates an associated deployment
3. I need to know that a function can potentially receive traffic. With scale-to-zero, as long as the initial deployment succeeded (no image pull issues etc) it's reasonable to expect that a deployment with zero replicas can handle a cold request.

This can be renamed from Ready to Deployed.

**Comment by alexellis** [comment]
> Talk to us about Scaling from zero, scaling to zero, scaling from 1 to N, the initial deployment, when a function is updated and so on.

I would like to see a complete list of scenarios that could occur based upon the above and their readiness transitions.

**Comment by brandonkal** [comment]
It doesn't need to be any more complex than if desired Replicas == available Replicas. That handles scaling in all directions.

**Comment by alexellis** [comment]
/lock: inactive. Feel free to raise a new issue if this is still required by anyone.
