### ISSUE TITLE
Performance Questions

### ISSUE THREAD

**Issue by yair12** [openfaas/faas-netes#657]
Hi,

I have some questions related to performance I was unable to find in the documentation/issues.
Would appreciate the answers or reference to related pages.

1. Cold starts: Are there any plans to further reduce cold start time? 
For example prewarmed generic (per environment) containers. From documentation I understand the minimum cold start time can get to ~1 second container start time + function process start time. I just wonder if there are any plans there (aside from having to keep 1 instance per function), or is there a case against chasing these goals in terms of ROI?

2. Are there any estimations regarding the resource cost (CPU + RAM) of the control plane modules?
I mainly try to understand what is the extra "payment" required for the management side, not for running the functions themselves.

Many thanks in advance!

Yair

**Comment by alexellis** [comment]
/lock: not an issue or a proposal

**Comment by alexellis** [comment]
Hi, feel free to join Slack to pose your questions to the community. We do not give technical support over GitHub (as per the contribution guide)

Regards,

Alex
