### ISSUE TITLE
Default Delete/Create approach gives 500 error when it should be 404

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#66]
Default Delete/Create approach gives 500 error when it should be 404

```
$ faas-cli deploy -f samples.yml
500 deployment function_name not found.

function_name deployed
```

This should say 404 instead.

@weikinhuang do you think you can take a look?

**Comment by alexellis** [comment]
https://github.com/openfaas/faas-netes/commit/6217e5be35bf9752904250a336bab2e7473f4e28

**Comment by weikinhuang** [comment]
Looks like you already got to it 😄

**Comment by alexellis** [comment]
Needs some playing/testing - I think it may get into an undesirable state if you delete/create over and over again. People will do that.. so we should handle it gracefully.

**Comment by alexellis** [comment]
Fixed in latest release:

https://github.com/openfaas/faas-netes/releases/tag/0.3.3
