### ISSUE TITLE
Support question

### ISSUE THREAD

**Issue by Jackbennett** [openfaas/faas-netes#667]
In the install section: https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#install

`https://openfaas.github.io/faas-netes/` -> redicrects to: `https://www.openfaas.com/faas-netes/` which is a 404 page.

I suspect it's supposed to link to `https://github.com/openfaas/faas-netes/tree/master/chart/openfaas` but the CLI fails:

`helm repo add openfaas https://github.com/openfaas/faas-netes/tree/master/chart/openfaas
Error: Looks like "https://github.com/openfaas/faas-netes/tree/master/chart/openfaas" is not a valid chart repository or cannot be reached: Failed to fetch https://github.com/openfaas/faas-netes/tree/master/chart/openfaas/index.yaml : 404 Not Found`

Since there's no index.yaml there to be found. 

More references to the link: https://hub.helm.sh/charts/openfaas/openfaas/5.8.6

Is this just me? I actually tried using arkade first but that 404's as well to `Error: download of https://get.helm.sh/helm-v3.1.2--amd64.tar.gz gave status: 404` but I pegged that to myself going against advice to use bash.

**Comment by alexellis** [comment]
Hi @Jackbennett,

> Is this just me?

I don't know, but nobody else has had issues here. You are not meant to navigate to `https://openfaas.github.io/faas-netes/` - did someone ask you to do that? Can you screenshot the instruction that instructs you that you must navigate there?

If you feel like you are encountering an issue with arkade, please raise an issue there so that we can get all the operating system details and version info from you.

Also - please do not delete the issue template as you did here, it's not good karma and makes everything harder for both of us.

Alex

**Comment by alexellis** [comment]
Please feel free to have another try at explaining what is wrong, or I'll close this issue out as I can't seem to work out what isn't working for you.

FYI, I cannot reproduce any issue with helm or arkade (arkade just automates helm):

```bash
alex@alexx:~$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊
alex@alexx:~$ 
alex@alexx:~$ rm -rf $HOME/.arkade
alex@alexx:~$ 
alex@alexx:~$ arkade install openfaas
Using kubeconfig: /home/alex/.kube/config
Using helm3
Node architecture: "amd64"
Client: "x86_64", "Linux"
2020/06/29 14:16:54 User dir established as: /home/alex/.arkade/
https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz
/home/alex/.arkade/bin/helm3/linux-amd64 linux-amd64/
/home/alex/.arkade/bin/helm3/helm linux-amd64/helm
/home/alex/.arkade/bin/helm3/README.md linux-amd64/README.md
/home/alex/.arkade/bin/helm3/LICENSE linux-amd64/LICENSE
2020/06/29 14:16:56 extracted tarball into /home/alex/.arkade/bin/helm3: 3 files, 0 dirs (935.347152ms)
"openfaas" has been added to your repositories

Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "traefik" chart repository
...Successfully got an update from the "inlets" chart repository
...Successfully got an update from the "istio" chart repository
...Successfully got an update from the "openfaas" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
VALUES values.yaml
Command: /home/alex/.arkade/bin/helm3/helm [upgrade --install openfaas openfaas/openfaas --namespace openfaas --values /tmp/charts/openfaas/values.yaml --set basic_auth=true --set serviceType=NodePort --set clusterRole=false --set gateway.directFunctions=true --set operator.create=false --set openfaasImagePullPolicy=IfNotPresent --set queueWorker.replicas=1 --set queueWorker.maxInflight=1 --set faasnetes.imagePullPolicy=Always --set basicAuthPlugin.replicas=1 --set gateway.replicas=1 --set ingressOperator.create=false]
Release "openfaas" does not exist. Installing it now.
NAME: openfaas
LAST DEPLOYED: Mon Jun 29 14:17:00 2020
NAMESPACE: openfaas
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To verify that openfaas has started, run:

  kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas"
=======================================================================
= OpenFaaS has been installed.                                        =
=======================================================================

# Get the faas-cli
curl -SLsf https://cli.openfaas.com | sudo sh

# Forward the gateway to your machine
kubectl rollout status -n openfaas deploy/gateway
kubectl port-forward -n openfaas svc/gateway 8080:8080 &

# If basic auth is enabled, you can now log into your gateway:
PASSWORD=$(kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode; echo)
echo -n $PASSWORD | faas-cli login --username admin --password-stdin

faas-cli store deploy figlet
faas-cli list

# For Raspberry Pi
faas-cli store list \
 --platform armhf

faas-cli store deploy figlet \
 --platform armhf

# Find out more at:
# https://github.com/openfaas/faas

Thanks for using arkade!
alex@alexx:~$ 
alex@alexx:~$ arkade version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.3.9
Git Commit: 1cc1a16e1e978b33ebcda25f3a1dbc88f84985f8
alex@alexx:~$ 

```
Alex

**Comment by Jackbennett** [comment]
Ok it's my fault, I tried to use arkade quickly in powershell because most things just work anyway when people say to use git bash, especially a cross platform compiled go app. Read on to see what the problem was, otherwise skip the the heading at the end.

arkade failed to run expecting $home being on linux, in powershell that's $env:homepath so I just set `$env:home = $env:homepath` and it got further (history attached);

```powershell
$ arkade.exe install openfaas
2020/06/29 13:05:13 exec: "uname": executable file not found in %PATH%
2020/06/29 13:05:13 exec: "uname": executable file not found in %PATH%
Using kubeconfig: .kube/config
Using helm3
Node architecture: "amd64"
Error: env-var HOME, not set
$ $env:HOME
$ $env:HOMEPATH
\Users\Jack
$ $env:HOME = $env:HOMEPATH
$ C:\ProgramData\open-faas\arkade.exe install openfaas
2020/06/29 13:06:42 exec: "uname": executable file not found in %PATH%
2020/06/29 13:06:42 exec: "uname": executable file not found in %PATH%
Using kubeconfig: \Users\Jack/.kube/config
Using helm3
Node architecture: "amd64"
2020/06/29 13:06:42 exec: "uname": executable file not found in %PATH%
2020/06/29 13:06:42 exec: "uname": executable file not found in %PATH%
Client: "", ""
2020/06/29 13:06:42 User dir established as: \Users\Jack/.arkade/
https://get.helm.sh/helm-v3.1.2--amd64.tar.gz
Error: download of https://get.helm.sh/helm-v3.1.2--amd64.tar.gz gave status: 404
```

Once that last line gave me a 404 I just went to install Option B with helm directly:
1. https://docs.openfaas.com/deployment/kubernetes/#b-deploy-with-helm-for-production-most-configurable links to ->
2. I'm using helm 2 (2.16) so follow -> https://github.com/openfaas/faas-netes/tree/master/chart/openfaas

Anyway, ignoring that, if `$env:home` exists for some reason it gets used twice by helm when making the path, you can see **\\users\Jack** in the path twice.

> `helm repo add openfaas https://openfaas.github.io/faas-netes/`
> Error: **Looks** like "https://openfaas.github.io/faas-netes/" is not a valid chart repository or cannot be reached: 
> open  **Users\\Jack\\**\\.helm\\repository\\cache **\\Users\\Jack\\**\\.helm\\repository\\cache\\openfaas-index.yaml: The system cannot find the path specified.

src λ helm repo add couchdb https://apache.github.io/couchdb-helm/
Error: Looks like "https://apache.github.io/couchdb-helm/" is not a valid chart repository or cannot be reached: open \\Users\\Jack\\.helm\\repository\\cache **\\Users\Jack\\** .helm\\repository\\cache\\couchdb-index.yaml: The system cannot find the path specified.


# Removed my own `$env:home` and we're good now.

```powershell
$ helm repo add couchdb https://apache.github.io/couchdb-helm/
"couchdb" has been added to your repositories
$ helm repo add openfaas https://openfaas.github.io/faas-netes/
"openfaas" has been added to your repositories
```

Usually if you curl an endpoint for a program you should get some gibberish not a 404, so that threw me off. I found the [faas CNAME](https://github.com/openfaas/faas/blob/master/CNAME) didn't work so thought something might have been changed.

Sorry to delete the template but I just wanted to know if the links were working. Couldn't find an IRC or something for a quick chat check.
