### ISSUE TITLE
Cannot deploy a faas function from the UI, using the docker file functionality, with docker hub images

### ISSUE THREAD

**Issue by PeriGK** [openfaas/faas-netes#670]
I am trying to deploy a public docker image as a FaaS function. I log in to the UI of my installation the screen doesn't seem to have the expected result, as the pod is throwing an error. This happens with 2 images I tried, but succeeds with others

## Expected Behaviour

I am expecting my function to be deployed in my cluster every time (given a valid image)

## Current Behaviour

Some images are not deployed successfully. All the failed ones are from docker hub, not sure if this is a coincidence though.

## Steps to Reproduce (for bugs)

1. Open faas ui
2. Click Deploy new function
3. Go to Custom
4. Enter the docker file location like `functions/figlet:0.13.0` or `tile38/tile38:latest` and click deploy
5. Tile will not get deployed while figlet is working fine.

## Context

I cannot FaaS-ify some desired docker images to make them accessible via HTTP from my cluster

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.11.3
* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.1

* What version and distriubtion of Kubernetes are you using? `kubectl version`
Rancher
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3+k3s1", GitCommit:"96653e8d86b74a1f73eadf09d4edc44778c2f8dd", GitTreeState:"clean", BuildDate:"2020-06-01T16:47:11Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}

```

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
N/A
* What network driver are you using and what CIDR? i.e. Weave net / Flannel
N/A

**Comment by alexellis** [comment]
We're going to need more diagnostics than you've given, but as this is a support issue, please take it over to Slack for help from the community.

**Comment by alexellis** [comment]
The most common issues like this can be fixed by working through the troubleshooting guide -> https://docs.openfaas.com/deployment/troubleshooting/

You can also help us, to help you by providing a full example of how to reproduce the issue that you're encountering.

**Comment by alexellis** [comment]
It looks as-if you are not deploying a function or a compatible workload.

You'll need to read up on what's required to package custom binaries like this in the documentation.

https://docs.openfaas.com/reference/workloads/

```
[alex@nuc ~]$ docker history tile38/tile38:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
5c48137799cf        6 weeks ago         /bin/sh -c #(nop)  CMD ["tile38-server" "-d"…   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  EXPOSE 9851                  0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  VOLUME [/data]               0B                  
<missing>           6 weeks ago         /bin/sh -c addgroup -S tile38 &&     adduser…   4.84kB              
<missing>           6 weeks ago         /bin/sh -c #(nop) ADD file:043149596902ffaec…   4.11MB              
<missing>           6 weeks ago         /bin/sh -c #(nop) ADD file:54df671f5be254a68…   3.97MB              
<missing>           6 weeks ago         /bin/sh -c #(nop) ADD file:b61c93ad89f43ae3a…   22.8MB              
<missing>           6 weeks ago         /bin/sh -c apk add --no-cache ca-certificates   543kB               
<missing>           5 months ago        /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B                  
<missing>           5 months ago        /bin/sh -c #(nop) ADD file:e38375b009a2e2c9b…   4.41MB              
[alex@nuc ~]$ docker run -ti tile38/tile38:latest 

   _______ _______
  |       |       |
  |____   |   _   |   Tile38 1.21.1 (c1ba2d8) 64 bit (amd64/linux)
  |       |       |   Port: 9851, PID: 1
  |____   |   _   | 
  |       |       |   tile38.com
  |_______|_______| 

2020/07/20 10:04:50 [INFO] Server started, Tile38 version 1.21.1, git c1ba2d8
2020/07/20 10:04:50 [INFO] AOF loaded 0 commands: 0.00s, 0/s, 0 bytes/s
2020/07/20 10:04:50 [INFO] Ready to accept connections at [::]:9851
```
