### ISSUE TITLE
Feature request: update helm Ingress resource to networking/v1beta1

### ISSUE THREAD

**Issue by everesio** [openfaas/faas-netes#674]
The ingress template https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/ingress.yaml uses
deprecated `extensions/v1beta1` version. Due to the https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/, the API version should be migrated to `networking.k8s.io/v1beta1`

**Comment by alexellis** [comment]
/set title: Feature request: update helm Ingress resource to networking/v1beta1

**Comment by alexellis** [comment]
Hi, thanks for your interest, however this doesn't appear to be an issue until 1.22?

> The v1.22 release will stop serving the following deprecated API versions in favor of newer and more stable API versions:
> Ingress in the extensions/v1beta1 API version will no longer be served

**Comment by alexellis** [comment]
There's an approach we can use which is backwards compatible that @nosceon added to inlets:

https://github.com/inlets/inlets-pro/blob/master/chart/inlets-pro/templates/ingress.yaml#L3-L7

@Waterdrips can you take this please?

**Comment by alexellis** [comment]
@dirien thanks for taking this.
