### ISSUE TITLE
[Question] IPv6-only support

### ISSUE THREAD

**Issue by valentin2105** [openfaas/faas-netes#68]
Hi,

I try to deploy Fass-netes in my IPv6-only Kubernetes cluster (v1.8.2).

Every services seem to work at glances, but the problem occur when the Gateway pod try to redirect to the Function pod. 

I try following this link : https://blog.alexellis.io/first-faas-python-function/ (hello-python function), 

```
#  Curl the final function pod 
16:31:22 › curl '[1404:f200:f::d011:e21d]:8080' -d 'open-faas is awesome'                                                                                                                                   
Hello! You said: open-faas is awesome

# Logs when trying to curl the Gateway pod : 
2017/10/30 05:29:44 > Forwarding [POST] to /function/hello-pytho
2017/10/30 05:31:22 http: proxy error: context canceled
2017/10/30 05:31:22 < [http://faas-netesd.openfaas.svc.domain-k8s.tld:8080/function/hello-python] - 502 took 97.582934 seconds
2017/10/30 05:31:22 function=hello-python
GetHeaderCode before 502

16:35:15 › k -n  openfaas exec -it gateway-b4bc9dd89-r79m4 sh                                                                                                                                        
~ # ping faas-netesd.openfaas.svc.domain-k8s.tld
PING faas-netesd.openfaas.svc.domain-k8s.tld (1404:f200:f::66a8:6360): 56 data bytes
64 bytes from 1404:f200:f::66a8:6360: seq=0 ttl=62 time=0.608 ms

( internal pod) 
bash-4.3# curl http://faas-netesd.openfaas.svc.domain-k8s.tld:8080
404 page not found
bash-4.3# curl http://gateway.openfaas.svc.domain-k8s.tld:8080/
<a href="/ui/">Moved Permanently</a>.

#  When curl the gateway without '-d curl argument' get HTTP 200 : 
- curl 'gateway.openfaas.svc.domain-k8s.tld:8080'/function/hello-python
2017/10/30 05:43:15 > Forwarding [GET] to /function/hello-python
2017/10/30 05:43:15 > Forwarding [GET] to /function/hello-python
2017/10/30 05:43:15 < [http://faas-netesd.openfaas.svc.domain-k8s.tld:8080/function/hello-python] - 200 took 0.004765 seconds
2017/10/30 05:43:15 function=hello-python
GetHeaderCode before 200
2017/10/30 05:43:15 < [http://faas-netesd.openfaas.svc.domain-k8s.tld:8080/function/hello-python] - 200 took 0.004765 seconds
2017/10/30 05:43:15 function=hello-python
GetHeaderCode before 200
```
EDIT : 

Maybe I found any cause of the problem, 
```
faas-netesd logs  :

2017/10/30 05:48:31 Post http://:8080/function/hello-python: EOF
2017/10/30 05:48:31 [1509342018] took 493.257782 seconds

```
It seem Faas-netesd try to use the ClusterIP, but in IPv6 only, ClusterIP is useless. 

Any feature to use Service'Endpoints instead of Service'ClusterIP to speak to function ? (Like Nginx-Ingress does) ? 

Thanks for OpenFaas ! Pretty awesome project.

**Comment by ericstoekl** [comment]
Derek add label: question

**Comment by alexellis** [comment]
Do you have a hard requirement to deploy to an IPv6-only environment? Is this for business/production use?

**Comment by valentin2105** [comment]
We basically want to deploy an IPv6 only Kubernetes cluster because we work in IPv6-only VM environment and we want to avoid use IPv4 for k8s only. 

About the ClusterIP to Endpoint change, it seem a good practice, like Ingress controller do, to avoid use IPTables : 

> The NGINX ingress controller does not uses Services to route traffic to the pods. Instead it uses the Endpoints API in order to bypass kube-proxy to allow NGINX features like session affinity and custom load balancing algorithms. It also removes some overhead, such as conntrack entries for iptables DNAT.

**Comment by alexellis** [comment]
So far you guys are the only users asking for this so we'd have to allocate time to research the topic and set up environments. What size is your business? Do you have a solution in mind that you can test and propose?

**Comment by valentin2105** [comment]
Don't bother you with that, 
I'll read the code and see if I can get it to work in my environment. 

Thanks a lot.
