### ISSUE TITLE
[Python] ImportError after build function with kaniko

### ISSUE THREAD

**Issue by hack3d** [openfaas/faas-netes#687]
We build a python3-http-debian with kaniko (v1.0.0) and deployed it in a kubernetes cluster. The build process has no errors. At startup of the function an "ImportError" occured. 

## Expected Behaviour
The container should start with no error and handle requests.

## Current Behaviour
Currently the started container ended with crashloopback and the following error inside:
```
Forking - python [index.py]
2020/09/23 06:56:57 Started logging stderr from function.
2020/09/23 06:56:57 Started logging stdout from function.
2020/09/23 06:56:57 OperationalMode: http
2020/09/23 06:56:57 Timeouts: read: 10s, write: 10s hard: 10s.
2020/09/23 06:56:57 Listening on port: 8080
2020/09/23 06:56:57 Writing lock-file to: /tmp/.lock
2020/09/23 06:56:57 Metrics listening on port: 8081
2020/09/23 06:57:04 stderr: Traceback (most recent call last):
2020/09/23 06:57:04 stderr:   File "index.py", line 6, in <module>
2020/09/23 06:57:04 stderr:     from function import handler
2020/09/23 06:57:04 stderr: ImportError: cannot import name 'handler' from 'function' (unknown location)
2020/09/23 06:57:05 Forked function has terminated: exit status 1
```
If you run the container on a local machine all is fine.

## Possible Solution
A workaround is to build the function with docker in docker.

## Steps to Reproduce (for bugs)
1. handler.py
`
def handle(event, context):
    return {
        "statusCode": 200,
        "body": event.body
    }
`
2. Gitlab-Pipeline:
```
build:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug-v1.0.0
        entrypoint: [""]
    script:
        - mkdir -p /root/.docker
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR/build/jira-webhook --dockerfile $CI_PROJECT_DIR/build/jira-webhook/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
```
3. Deploy the function

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): openfaas/faas-cli:0.12.9

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.09.2

* What version and distriubtion of Kubernetes are you using? `kubectl version`: v1.16.13

* Operating System and version (e.g. Linux, Windows, MacOS): Debian Stretch

* Link to your project or a code example to reproduce issue: 

* What network driver are you using and what CIDR? i.e. Weave net / Flannel: Calico

**Comment by alexellis** [comment]
Hi thank you for using OpenFaaS.

We are unaware of any issues with the template you referenced, and you can view its source-code at https://github.com/openfaas-incubator/python-flask-template

Please feel free to seek out technical support from the community on Slack.

Given that the template is working as expected, it's unlikely that we can help you unless you can provide a minimal GitHub repo that reproduces the same issue you're seeing here.

Alex

**Comment by alexellis** [comment]
If you suspect that Docker builds work, but that Kaniko (the way you are using it), then feel free to raise an issue with Google on their repo here -> https://github.com/GoogleContainerTools/kaniko/issues
