### ISSUE TITLE
Adjust function name regex - to allow DNS-1123

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#69]
> Deployment, pod and service names conform to a requirement to match a DNS-1123 label. These must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character. The regular expression used to validate names is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'. If you use a name, for your deployment, that does not validate, an error is returned.

## Expected Behaviour

"function1" should be valid, but isn't with our current regex.

## Current Behaviour

Must type functiontwo

## Possible Solution

Alter regex and unit tests in project.

## Steps to Reproduce (for bugs)

```
faas-cli deploy --image functions/alpine --name function1 --fprocess=env
```

Start here:

https://github.com/openfaas/faas-netes/blob/master/handlers/deploy.go#L29

## Acceptance Criteria:

* Must have unit test coverage for positive and negative scenarios
* Must be tested on Kubernetes 1.8 (with console output pasted into the PR)
* Must pass CI etc.

* Valid RegEx needs to be documented in the readme and in the troubleshooting guide in the main faas repo.

**Comment by rawkode** [comment]
```
$ faas-cli deploy --image functions/alpine --name function1 --fprocess=env

Server returned unexpected status code 500 deployments.extensions "function1" not found
Deployed.
URL: http://localhost:8080/function/function1

202 Accepted
```

```
$ faas-cli list

Function                      	Invocations    	Replicas
function1                     	0              	1    
```
