### ISSUE TITLE
Support issue about helm

### ISSUE THREAD

**Issue by rmathagiarun** [openfaas/faas-netes#694]
When I comment out the functionNamespace or if I assign functionNamespace as openfaas(Operator Namespace), OpenFaaS Installation using Helm fails.

## Expected Behaviour
Should be able to install OpenFaas using Helm when I comment out the functionNamespace or if I assign functionNamespace as openfaas(Operator Namespace)

## Current Behaviour
Helm installation fails with the below message. This is because as per the Template Logic, Role Binding is generated twice, once for Operator Namespace and other time for Functional Namespace. 

**Error: rolebindings.rbac.authorization.k8s.io "openfaas-prometheus" already exists
helm.go:81: [debug] rolebindings.rbac.authorization.k8s.io "openfaas-prometheus" already exists**

## Possible Solution
This can be fixed, by adding the following `condition` for RoleBinding generated specifically for functionNs in templates/prometheus-rbac.yaml:

**{{- if ne $functionNs (.Release.Namespace | toString) }}
{{- end }}**

[prometheus-rbac.yaml.txt](https://github.com/openfaas/faas-netes/files/5463225/prometheus-rbac.yaml.txt)

< Attaching prometheus-rbac.yaml template for reference >

## Steps to Reproduce (for bugs)
**Scenario 1:**
Comment out functionNamespace in values.yaml:
#functionNamespace: openfaas-fn

When functionNamespace is undefined, Below condition at the start of prometheus-rbac.yaml will assign functionNs is equal to Operator Namespace(openfaas)
 {{- $functionNs := default .Release.Namespace .Values.functionNamespace }}

**Scenario 2:**
functionNamespace is same as Operator namespace in values.yaml
functionNamespace: openfaas

Helm install will fail during both the above scenarios as it will try to create already existing role.

## Context
As OpenFaaS has support for multiple-namespaces, it becomes immaterial to define just only one functional namespace in Deployment. So, users may choose to comment out the variable functionNamespace. This fix will help overcome that challenge.

## Environment
* Faas-CLI Version:
CLI:
 commit:  c12d57c39ac4cc6eef3c9bba2fb45113d882432f
 version: 0.12.14

* Kubectl Version:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Operating System: Linux

**Comment by alexellis** [comment]
@rmathagi please use the template, or we will close this issue.

Can you reformat it, so that we have the fields that *we request* rather than what you want to tell us?

**Comment by alexellis** [comment]
https://raw.githubusercontent.com/openfaas/faas-netes/master/.github/ISSUE_TEMPLATE.md

**Comment by rmathagi** [comment]
> @rmathagi please use the template, or we will close this issue.
> 
> Can you reformat it, so that we have the fields that _we request_ rather than what you want to tell us?

Updated the format as requested.

**Comment by alexellis** [comment]
Thank you @rmathagi that helps more than you know 👍 

Would you be willing to work on a fix for this?

**Comment by rmathagi** [comment]
Yes, would like to. I have already proposed the solution for this and verified this in my deployment. Please let me know if you have any additional recommendations.

**Comment by alexellis** [comment]
How about a pull request?

**Comment by rmathagi** [comment]
Sure, will do. Let me work on it.

**Comment by rmathagi** [comment]
@alexellis Please review this Pull Request.

**Comment by alexellis** [comment]
I've commented. Please see what I've said

**Comment by alexellis** [comment]
If you need faster responses, we offer a paid Premium Subscription for commercial users. Please take a look and talk it over with your manager / CTO - https://www.openfaas.com/support/

**Comment by rmathagi** [comment]
> I've commented. Please see what I've said

@alexellis  Responded, please check.

**Comment by rmathagi** [comment]
> If you need faster responses, we offer a paid Premium Subscription for commercial users. Please take a look and talk it over with your manager / CTO - https://www.openfaas.com/support/

Sure, will do.

**Comment by rmathagi** [comment]
@alexellis Let's close this issue as the code fix has been merged into Master Branch.
