### ISSUE TITLE
ARM & ARM64 helm charts still reference faas-netes:0.12.2

### ISSUE THREAD

**Issue by CodeCutterUK** [openfaas/faas-netes#700]
## Expected Behaviour

AMD64 has been bumped to version 0.12.3 which fixes an issue with `directFunctions=false`

## Possible Solution

bump the version references so that ARM/ARM64 is aligned

**Comment by alexellis** [comment]
Please check if the tags are available for later versions, if they are then feel free to send a PR.

**Comment by CodeCutterUK** [comment]
Resolved now that the generate charts have been updated

**Comment by alexellis** [comment]
As the new images become available on GHCR, let's PR to values.yaml here.
