### ISSUE TITLE
Proposal: disable direct functions by default

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#706]
A common request in slack looks like this question

> I created a function by dividing it into 4 pods.
> If 4 users use this feature, sometimes 2 or 3 people work on 1 Pod.
> (The remaining Pods are resting!)
> Is there a way to do this fairly for each port every time? 

We have documented this behavior and how to fix it here https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md#endpoint-load-balancing

> Configure the gateway to pass invocations through to the faas-netes provider (alternative to using Linkerd2)
> ```
> --set gateway.directFunctions=false
> ```
> In this mode, all invocations will pass through the gateway to faas-netes, which will look up endpoint IPs directly from Kubernetes, the additional hop may add some latency, but will do fair load-balancing, even with KeepAlive.

This is such a common request in slack that we should consider changing the default behavior of `directFunctions` so that users need to opt into this behavior. This will match user expectations a little better without requiring additional configuration. 
Enabling direct functions seems like it would fit well in a "optimization" FAQ and we could document the changes to expect.

**Comment by alexellis** [comment]
What are the cons? @LucasRoesler

**Comment by LucasRoesler** [comment]
I think the main con is that users of `linkerd` (and probably other service meshes) will need to toggle this back to `true`. 

This would be a _**breaking change**_ for any existing users of `linkerd`

I think we can resolve this with documentation because I suspect/hope that users of service meshes are more likely to actually go to our docs and search for "name of service mesh" or "service mesh".  We could also consider adding a comment to the Helm chart `notes.txt` so that users see this right after installation.

In general, any other applications that interact with the cluster networking may cause unforeseen issues or behavior. But there is always a potential for this, I am not sure this is actually more likely with this change compared to not. 

Also, there will be a slight increase in latency because the extra hop from the Gateway to the Provider.

**Comment by alexellis** [comment]
Closing as the PR has been merged.
