### ISSUE TITLE
Migrate CRDs to v1 namespace

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#709]
Migrate CRDs to v1 namespace

## Expected Behaviour

`helm lint` should pass without failing a CI build, however with the latest version of helm3, this causes an unrecoverable error in CI.

## Steps to reproduce the issue

* Clone this repo
* Download latest helm 3 `arkade get helm --version v3.4.0`
* Run helm lint

See failing error.

```
==> Linting .
[ERROR] templates/profile-crd.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions.k8s.io/v1 CustomResourceDefinition"
Error: 1 chart(s) linted, 1 chart(s) failed
```

## Possible solution

* Update the tooling that generates the CRD YAML
* Update the chart's templates with generated YAML
* Re-test and check for breakages
* Note down any backwards compatibility changes. What is the new min-version of K8s after the migration?

Here is an example PR from the Contour project https://github.com/projectcontour/contour/issues/2678

**Comment by alexellis** [comment]
This will also apply to - https://github.com/openfaas/ingress-operator and https://github.com/inlets/inlets-operator

**Comment by alexellis** [comment]
@LucasRoesler please could you take a look?

**Comment by LucasRoesler** [comment]
@alexellis i am also getting the following lint errors

```
[ERROR] templates/controller-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 Role" is deprecated in favor of "rbac.authorization.k8s.io/v1 Role"
[ERROR] templates/controller-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 RoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 RoleBinding"
[ERROR] templates/controller-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 Role" is deprecated in favor of "rbac.authorization.k8s.io/v1 Role"
[ERROR] templates/controller-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 RoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 RoleBinding"

**Comment by LucasRoesler** [comment]
Doing a little bit of research 

* [k8s 1.16 introduced depreaction](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals) for `apiextensions.k8s.io/v1beta1` in favor of `apiextensions.k8s.io/v1`, removal in 1.19
* [k8s 1.17 introduced deprecation](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#deprecations-and-removals) for `rbac.authorization.k8s.io/v1beta1` and `rbac.authorization.k8s.io/v1beta2` in favor of `rbac.authorization.k8s.io/v1`, removal in 1.20


If we upgrade the CRD api group, the minimum version become 1.16, while updating the RBAC group bumps the minium verison to 1.17


Current versions in the major cloud providers:

* [GKE](https://cloud.google.com/kubernetes-engine/docs/release-notes#latest_versions) 1.16, 1.17, 1.18
* [EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html): 1.14, 1.15, 1.16, 1.17, 1.18
* [AKS](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar): 1.16, 1.17, 1.18, 1.19
* [Digital Ocean](https://www.digitalocean.com/docs/kubernetes/changelog/): 1.17, 1.18, 1.19

**Comment by LucasRoesler** [comment]
Apparently the operator RBAC was already upgraded https://github.com/openfaas/faas-netes/blob/e88c54c3854614fe02809c6931d544f74d64c6f0/chart/openfaas/templates/operator-rbac.yaml#L17
