### ISSUE TITLE
values-arm64.yaml: nodeselector is 'arm' instead of 'arm64'

### ISSUE THREAD

**Issue by campaquino** [openfaas/faas-netes#715]
As the value was changed to 'arm', but 'arm64' is reported by k8s as architecture, no applicable node for deployment can be found by k8s.

## Expected Behaviour
Openfaas can be deployed on 64bit arm machines like RPi4

## Current Behaviour
K8s reports it couldn't find any suitable node ('0/1 nodes are available: 1 node(s) didn't match node selector.')

## Possible Solution
Revert the change from 'arm64' to 'arm', made in values-arm64.yaml at the nodeSelector beta.kubernetes.io/arch

## Steps to Reproduce (for bugs)
1. setup arm64 machine (e.g. RPi4) with appropriate OS and K8s (e.g. k3sup install --ip <target IP> --user <sudoer>)
2. setup openfaas by 'arkade install openfaas' or the equivalent helm command line
3. wait until helm/arkade has finished its work 
4. check k8s for status of deployments

## Context
I tried to setup Openfaas on my RPi4 using Ubuntu and k3s. For convenience k3sup and arkade were used. 
Unfortunately it did not start any container of the helm chart on my RPi.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ): -

* Docker version `docker version` (e.g. Docker 17.0.05 ): -

* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-15T17:26:49Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12+k3s1", GitCommit:"56cd36302dc3188f21f9877d1309df7d80cd8b7d", GitTreeState:"clean", BuildDate:"2020-11-13T06:12:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm64"}

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 20.04.1 LTS on RPi4

* Link to your project or a code example to reproduce issue: -

* What network driver are you using and what CIDR? i.e. Weave net / Flannel 
-

**Comment by alexellis** [comment]
Please feel free to send a PR to revert it back. Thanks for letting us know.

**Comment by alexellis** [comment]
I'm confused because the 64-bit ARM value is as you directed?

```yaml
nodeSelector:
  beta.kubernetes.io/arch: arm64
```
