### ISSUE TITLE
OpenFaaS components should not be "BestEffort" pod

### ISSUE THREAD

**Issue by resouer** [openfaas/faas-netes#72]
The BestEffort pod (no resource definition) is the candidate to be evicted when node is under resource pressure. It is never recommended for system pods.
## Expected Behaviour

Faas components all have resource limit at least.
## Current Behaviour

Faas components all have no resource limit.
## Possible Solution

Add resource limit to Deployment.
## Steps to Reproduce (for bugs)

1. Create a kubernetes cluster on small size node
2. Enable pod eviction
3. faas-netes will be evicted to make room for other high priority pods

## Context

I have to patch faas-netes manually.

https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#qos-classes

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 1.12.6
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes 1.8.2 
* Operating System and version (e.g. Linux, Windows, MacOS):
ARM64 Linux
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Interesting.. we've not seen this yet. How small was the host you were using?

What memory usage did you observe for the faas-netesd controller?

**Comment by resouer** [comment]
The host is 8Gi size. The memory usage is small, while t is evicted due to node lack of memory and faas-netes is a lowest QoS class pod.

**Comment by alexellis** [comment]
What are you running on there to fill up 8GB? I run on a host with 1GB and I've not seen evictions with just very light use.

**Comment by resouer** [comment]
The node is filled a lot of workloads, I should mention that  earlier :)
