### ISSUE TITLE
variable name error

### ISSUE THREAD

**Issue by simone-zennaro** [openfaas/faas-netes#732]
Hi, in line 36 and 72 you put Values.basic_auth instead of Values.basicAuth 

https://github.com/openfaas/faas-netes/blob/43f64cf9b30fd5f0f56514dee6b9fe01cfbfed45/chart/kafka-connector/templates/deployment.yml#L36

https://github.com/openfaas/faas-netes/blob/43f64cf9b30fd5f0f56514dee6b9fe01cfbfed45/chart/kafka-connector/templates/deployment.yml#L72

**Comment by alexellis** [comment]
Thanks for letting us know.

Please can you use the templates for any further issues or PRs?

**Comment by alexellis** [comment]
@simone-zennaro we're still part way through migrating the Kafka code to GitHub Actions, can you hold off on your testing? Perhaps revisit it with us in a week.
