### ISSUE TITLE
Proposal: for non-helm deployment - use openfaas ns 

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#74]
Helm allows us to specify a namespaces:

For OpenFaaS system components: openfaas
For OpenFaaS functions: openfaas-fn

Let's leverage the changes we made for `helm` for our default set of YAML files including the mounted configs for Prometheus/alertmanager.

**Comment by stefanprodan** [comment]
I think I covered this in here https://github.com/stefanprodan/openfaas-gke/blob/master/faas.yml

There are some differences:
* rbac.authorization.k8s.io/v1 (compatible with K8S API 1.8+)
* apps/v1beta2 (compatible with K8S API 1.8+)
* prometheus:v1.8.2 (has predictable memory usage vs 1.5)
* alertmanager:v0.9.1
* all containers have the memory limit set to 128Mi except Prometheus 1Gi
* Prometheus/Alertmanager minimal ConfigMaps (no comments or unused settings)

If that's ok with you I could do PR with it.

**Comment by alexellis** [comment]
Please do, but we need to think about whether we provide a snapshot of 1.7 compatible YAML or force a forward upgrade.

**Comment by weikinhuang** [comment]
Currently blocked by https://github.com/openfaas/faas-netes/pull/52

**Comment by alexellis** [comment]
We are using openfaas/openfaas-fn namespaces in YAML now 👍 closing..
