### ISSUE TITLE
faas-idler versions other than 0.4.0 lost on docker hub

### ISSUE THREAD

**Issue by mcueto** [openfaas/faas-netes#740]
## Expected Behaviour
I was instaling `openfaas` based on an "old" helm chart that uses `faas-idler` on it's `0.3.0` version and i figured out that only version `0.4.0` is published on docker hub so i supose that was a unintentional mistake because of the ever changing codebase on the project.

## Current Behaviour
`ImagePullBackOff` for `faas-idler` on versions other than `0.4.0`

## Possible Solution
Re-upload the other docker image versions

## Steps to Reproduce (for bugs)

1. Install openfaas based on an old helm chart that sets `faas-idler` on a version different than `0.4.0` (see values.yml)

1. list pods with `kubectl get pods -n openfaas` to look at the failling pod(faas-idler)

## Context
I am using an old version of the chart that need to be supported and not broken.

Docker hub: https://hub.docker.com/r/openfaas/faas-idler/tags?page=1&ordering=last_updated

## Your Environment
`microk8s` over Ubuntu Focal Fossa

**Comment by alexellis** [comment]
Hi, thanks for your interest. We've moved over to GHCR for our images.

I would suggest taking a look at the latest changes in the helm chart README file or the docs for scale to zero.

If you're a commercial user, and feel you're affected by changes in the open source project, it may benefit you to have a support relationship in place. Happy to chat about that separately. https://openfaas.com/support

Alex
