### ISSUE TITLE
Function not respecting timeout when using operator mode

### ISSUE THREAD

**Issue by MrSimonEmms** [openfaas/faas-netes#743]
I have a function that takes approx 30 seconds to run. I've followed the instructions on the [Expanded Timeouts](https://docs.openfaas.com/tutorials/expanded-timeouts/) page but not working as expected. I've set the timeout to 2 minutes as per docs; after approx 7 seconds the function retuns a 502 Bad Gateway message and aborts the function call. To test the call, I'm using the [Go-Long](https://github.com/alexellis/go-long) function (I get the same results with both the Go and Node versions, indicating it's not a function issue).

When I change the `gateway.directFunctions` to `true`, the timeout is respected.

~I've tried this with both the OpenFaaS operator and without and there's no difference - for the record, I need to use the operator in the setup.~ This appears to be to do with the Operator as it works when removing the operator option

I've created [a gist with the Helm config](https://gist.github.com/MrSimonEmms/552743c1277e1005db3a76961a3e688d). This is the identical as when created with arkade or using the Helm chart.

There's been a long thread on this in the [Slack group](https://openfaas.slack.com/archives/C01JXQQD28K/p1610829835007600)

This is logged when the function errors:

```
2021/01/17 20:49:53 error with proxy request to: http://10.244.0.139:8080, Post "http://10.244.0.139:8080": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Also, seen a few instances of this - not sure if this is relevant:

```
E0117 20:49:23.671747       1 reflector.go:178] github.com/openfaas/faas-netes/pkg/client/informers/externalversions/factory.go:107: Failed to list *v1.Profile: profiles.openfaas.com is forbidden: User "system:serviceaccount:openfaas:openfaas-operator" cannot list resource "profiles" in API group "openfaas.com" in the namespace "openfaas"
```

## Expected Behaviour

The timeout configured by the `write_timeout`, `read_timeout` and `exec_timeout` params should be respected.

## Current Behaviour

Gateway returns a 502 Bad Gateway response after ~7 seconds - I've found I can run this for 6 seconds, but it fails if I set the timeout to 7.

## Steps to Reproduce (for bugs)

1. Deploy instance to K8S: 
```export TIMEOUT=2m

arkade install openfaas \
  --set gateway.upstreamTimeout=$TIMEOUT \
  --set gateway.writeTimeout=$TIMEOUT \
  --set gateway.readTimeout=$TIMEOUT \
  --set faasnetes.writeTimeout=$TIMEOUT \
  --set faasnetes.readTimeout=$TIMEOUT \
  --set queueWorker.ackWait=$TIMEOUT \
  --operator \
  --set gateway.directFunctions=false
```
2. Deploy [Go-Long](https://github.com/alexellis/go-long) function
3. `faas-cli invoke go-long`

## Context

I'm using OpenFaas to connect to a legacy system with a fire-and-forget call. The legacy system is slow and calls take approx 30 seconds to finish and I need to setup a retry system (easily done with OpenFaaS).

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```CLI:
 commit:  40555282492b1f7cfdb10d801fcdce251360ec25
 version: 0.12.9

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.20.2
 sha:     9bbb25e3c7c4cc5cd355edb3a122f8c7812e32db
 commit:  Fix a bug that caused the services list to keep growing


Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.12.13 
 sha:           65e480388c35b9ecf297fff023dc728c4e1a7839
Your faas-cli version (0.12.9) may be out of date. Version: 0.12.21 is now available on GitHub.
```

* Docker version `docker version` (e.g. Docker 17.0.05 ): `19.03.13`

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T16:05:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.10

* Link to your project or a code example to reproduce issue: https://github.com/foundry4/appeal-planning-decision/tree/feature/message-queue/packages/horizon-publisher

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
K8S provided via managed Azure service.

**Comment by alexellis** [comment]
/set title: Function not respecting timeout when using operator mode

**Comment by alexellis** [comment]
The arkade command doesn't look right, it should have `--operator` added I think?

**Comment by MrSimonEmms** [comment]
Yes, sorry. I tried it last without the operator - for the record, I got the same result whether using the operator or not.

I'll update the OP

**Comment by kevin-lindsay-1** [comment]
#729 is the same issue.
