### ISSUE TITLE
Allow configuring of prometheus deployment annotations via helm chart

### ISSUE THREAD

**Issue by allanyung** [openfaas/faas-netes#746]
## Expected Behaviour
Helm chart should allow configuring metadata/annotations for prometheus deployment

## Current Behaviour
No way to configure metadata/annotations for prometheus deployment unless user maintains a copy of helm chart locally

## Possible Solution
Update helm chart to support custom annotations for the prometheus deployment

## Context
Datadog requires some annotations to discover and configure the scraping of the federated metrics endpoint of a prometheus deployment

**Comment by alexellis** [comment]
Thanks for your interest in OpenFaaS and for taking the time to fill out an issue 🙏

**Comment by alexellis** [comment]
Merged.
