### ISSUE TITLE
Helm v2 does not render chart correctly

### ISSUE THREAD

**Issue by Voziv** [openfaas/faas-netes#756]
ArgoCD selects helm version 2 or 3 based on the apiVersion of the chart.

With helm version 2 and `clusterRole: false` it causes the `{{ .Release.Name }}-prometheus` Role
to render incorrectly.

## Expected Behaviour
Should render the prometheus role with a new line:
```
---
apiVersion: .....
```

## Current Behaviour
Helm v2 renders the role without a new line
```
---apiVersion: ....
```

## Possible Solution

I do have a fork + branch that I can PR if needed. I used it to test out
the fix with argocd v1.8.2 to make sure 

In `chart/openfaas/templates/prometheus-rbac.yaml:80`

```diff
   name: {{ .Release.Name }}-prometheus
   namespace: {{ .Release.Namespace | quote }}
 {{- end }}
 
- {{- else -}}
+ {{- else }}
 
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
 metadata:
   name: {{ .Release.Name }}-prometheus
```

## Steps to Reproduce (for bugs)

1. Download helm [v2.17](https://github.com/helm/helm/releases/tag/v2.17.0)
2. Run `/path/to/helmv2 template chart/openfaas | kubectl apply --validate=true --dry-run=client -f -`
3. You will see `error: unable to recognize "STDIN": no matches for kind "Role" in version "v1"`
4. Run `/path/to/helmv2 template chart/openfaas | grep "Source: openfaas/templates/prometheus-rbac.yaml" -A20`
5. You should see the erroneous line midway through: `---apiVersion: rbac.authorization.k8s.io/v1`

## Your Environment
* ArgoCD Version: `v1.8.2`

*  Helm Version: `helm v3.2.4` and `helm v2.17.0`

* Docker version `docker version` (e.g. Docker 17.0.05 ): `Docker for Windows: 20.10.2`

* What version and distribution of Kubernetes are you using? `kubectl version` 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2",
Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1600", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-07T09:22:27Z", GoVersion:"
go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS): `Windows 10 + WSL2 (Ubuntu 20.04)`

**Comment by alexellis** [comment]
Hi thank you for the detailed report.

What version of helm are you trying to use?

**Comment by alexellis** [comment]
Hi thank you for the detailed report.

I just want to understand what version of helm are you trying to use? Are you trying to use Helm 2, and that is where you have issues with Argo, or Helm 3?

We are making no attempt to support Helm 2 at present, so I just want to understand the use-case and how broadly this could affect users.

**Comment by Voziv** [comment]
ArgoCD selects helm version based on the chart's `apiVersion`. This means it selects helm 2 to render the openfaas chart.

We were attempting to upgrade the chart from `6.1.1` -> `7.0.3` when we encountered the issue.

So as things stand currently this would affect any users using ArgoCD and trying to upgrade to chart `6.2.1` or higher.

**Comment by alexellis** [comment]
> ArgoCD selects helm version based on the chart's apiVersion. This means it selects helm 2 to render the openfaas chart.

How do we make it use Helm 3?

**Comment by Voziv** [comment]
In theory upgrading from v1 to v2 of the helm chart api.

From the [docs](https://helm.sh/docs/topics/charts/) this involves updating to `apiVersion: v2`
> Changes from v1 to v2:
> 
> - A dependencies field defining chart dependencies, which were located in a separate requirements.yaml file for v1 charts (see Chart Dependencies).
> - The type field, discriminating application and library charts (see Chart Types).

It looks like the following diff for `Chart.yaml` allows argocd to correctly render the chart:

```diff
- apiVersion: v1
+ apiVersion: v2
+ type: application
```

Here's the diff I used to test: https://github.com/openfaas/faas-netes/compare/master...ratehub:dev-upgrade-helm-api

**Comment by alexellis** [comment]
I believe that we have resolved this for you now @Voziv

**Comment by Voziv** [comment]
7.1.0 rendered without any problems. Thanks!
