### ISSUE TITLE
How to set function's resource(request/limit) of pod memory

### ISSUE THREAD

**Issue by rayhero** [openfaas/faas-netes#76]
I have a image processing function that need to use 13G memory. I create a Cluster
have 16G memory with 3 nodes. But I can not find a way to configure my function's
Pod memory size or swap memory size. And if several request at same time, How to
set configure to make my each function call can have enough memory to complete the job?

## Expected Behaviour
The image processing job can have enough memory(13G) resource to finish job and upload the result.

## Current Behaviour
Since faas-cli use default settings to deploy function. The function's pod yaml only set cpu resource request = 100m. So this cause the image processing job return memory not enough error. I observe the pod resource usage are only use 40M memory and 0.419 core cpu.

## Possible Solution
Does faas-cli or faas-netes have command that can set the deploy function's memory/swap memory size? or I can manual set the function's pod's memory? If I can make sure the function's pod yaml can have request and limit memory resource, I can let large resource requirement job complete safety.

## Context
I can run my image processing function on local docker with large swap memory. I try to enlarge
my cluster's memory but I found the root cause is that the function's pod only can use 40M memory and 0.419 cores cpu for one job request. I try to check the pod's yaml: it shows resources->requests->cpu:100m. I guess this is create by faas-cli deploy command or default faas-netes settings. Can I use faas-cli or chage faas-netes settings to increase my function's pod memory? 

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
Version: 17.09.0-ce
API version: 1.32
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:40:09 2017
OS/Arch: darwin/amd64
Server:
Version: 17.09.0-ce
API version: 1.32 (minimum version 1.12)
Go version: go1.8.3
Git commit: afdb6d4
Built: Tue Sep 26 22:45:38 2017
OS/Arch: linux/amd64
Experimental: true
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes (FaaS-netes)
* Operating System and version (e.g. Linux, Windows, MacOS):
Local: MacOS 10.12.5, remote: GCP k8s
* Link to your project or a code example to reproduce issue:

**Comment by rayhero** [comment]
I can rebuild the faas-netes image. I think the deploy.go is the correct place to set the resource limit. Can I set the limit in clientset? Or I need to set limit in ctg? Does somebody know how to set?

**Comment by alexellis** [comment]
Yes that would make sense. I know you shared on Slack that you did this. We're adding memory limits into the `requests` package - when that's finished we'll close this issue.
