### ISSUE TITLE
Helm template missing namespace for Prometheus Role

### ISSUE THREAD

**Issue by matzhaugen** [openfaas/faas-netes#766]
Helm template missing namespace for Prometheus Role

## Expected Behavior
Same behavior between 
`helm install openfaas ./chart/openfaas --namespace openfaas` and
`helm template openfaas ./chart/openfaas --namespace openfaas | kubectl apply -f -`

## Current Behavior
The prometheus role is not templated with a namespace so it doesn't show up in the latter command. I'm not sure why it works with the former command. 

## Possible Solution
Add a namespace [below the name](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/prometheus-rbac.yaml#L85) argument in the template as is done in the [-fn version](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/prometheus-rbac.yaml#L125)

## Steps to Reproduce (for bugs)
1. `./contrib/create_cluster.sh`
2.  Create a basic auth secret
3. Apply the template `helm template openfaas ./chart/openfaas --namespace openfaas | kubectl apply -f -`

Alternative to 2 and 3, just modify the contrib/deploy.sh script to just use the `helm template` instead of `helm install`

## Context
In order to use kustomize and templating on top of helm, e.g. with a dev/test/prod setup, it's useful to pipe the helm template to a `base.yaml` and kustomize on top of that. Thus you need to use the helm template command instead of helm install.

## Your Environment
Setup as given in the master branch of this repo

**Comment by alexellis** [comment]
Are you willing to work on a fix @matzhaugen?

**Comment by alexellis** [comment]
@LucasRoesler CC

**Comment by matzhaugen** [comment]
Sure!

**Comment by alexellis** [comment]
This has been released, feel free to re-test
