### ISSUE TITLE
Populate CreatedAt in the REST API

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#771]
## Expected Behaviour

CreatedAt in the REST API should be populated, both for the controller and operator.

## Current Behaviour

This is a new field and was only just introduced.

https://github.com/openfaas/faas-provider/issues/59

For an example of how it was done in faasd, see: https://github.com/openfaas/faasd/commit/659f98cc0dd2c13633d511f143785808e84f21cb

## Possible Solution

Update both the REST API response for the controller and the operator, then test end to end that the field is populated when accessing the faas-netes/operator container directly with `curl http://127.0.0.1:8080/system/functions` and `http://127.0.0.1:8080/system/function/NAME`

You may also be able to test directly with the gateway, if you use the latest version as per: https://github.com/openfaas/faas/commit/a6dbb4cd0285f6dbc0bc3f43f72ceacdbdf6f227

## Context

See the issue on faas-provider for context.

**Comment by alexellis** [comment]
See also for testing: https://blog.alexellis.io/how-i-test-openfaas-with-kubernetes/

**Comment by cpanato** [comment]
I will work on this issue

**Comment by alexellis** [comment]
Sure. Feel free to ask questions here if you need to.

**Comment by cpanato** [comment]
make the tiny change and updated faas to use the latest available

However, I'm getting the same response when calling the `/system/functions`, and when I call the `/system/function/MYFUNC`, I receive the new field.

I bet is something foolish I'm doing (but I'm new to the code base)

for example when calling `/system/functions`

```JSON
[
    {
        "name": "nodeinfo",
        "image": "ghcr.io/openfaas/nodeinfo:75d61698aaaa14345c7983f5a5db91f6da80e5bb",
        "namespace": "openfaas-fn",
        "replicas": 1,
        "availableReplicas": 1
    }
]
```

and when calling `/system/function/nodeinfo` 
```
{
    "name": "nodeinfo",
    "image": "ghcr.io/openfaas/nodeinfo:75d61698aaaa14345c7983f5a5db91f6da80e5bb",
    "namespace": "openfaas-fn",
    "replicas": 1,
    "availableReplicas": 1,
    "createdAt": "2021-03-17T09:48:02Z"
}
```

There is an interceptor for the /system/functions that remove some fields?

**Comment by cpanato** [comment]
I knew that was something foolish, I need update the gateway container as well :(

now works

```
[
    {
        "name": "nodeinfo",
        "image": "ghcr.io/openfaas/nodeinfo:75d61698aaaa14345c7983f5a5db91f6da80e5bb",
        "namespace": "openfaas-fn",
        "replicas": 1,
        "availableReplicas": 1,
        "createdAt": "2021-03-17T09:48:02Z"
    }
]
```

@alexellis any idea when a new release of FAAS will be available?

**Comment by alexellis** [comment]
Hi, in the instructions I mentioned that you should port forward from the operator/faas-netes container itself. You may need to exec into the container to do that with wget.

There's also a new gateway that I published around the same time as creating this issue.
