### ISSUE TITLE
CI is using go1.13

### ISSUE THREAD

**Issue by cpanato** [openfaas/faas-netes#774]
both go modules and dockefile are using go 1.15 but ci is not 

## Expected Behaviour
Ci uses go.1.15

## Current Behaviour
ci is using go1.13

## Possible Solution
update ci to use go1.15

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
I don't actually think we use Go on the host, but happy for you to bump this to 1.15 or plain Ubuntu

What issue did you run into? I didn't see the details in the repro section
