### ISSUE TITLE
the server could not find the requested resource (get profiles.openfaas.com)

### ISSUE THREAD

**Issue by barelnir** [openfaas/faas-netes#777]
## Expected Behaviour
error is shown in faas-netes pod:

`gateway-6fdb69cdd-wk8m9 faas-netes E0322 17:45:26.524287       1 reflector.go:178] github.com/openfaas/faas-netes/pkg/client/informers/externalversions/factory.go:107: Failed to list *v1.Profile: the server could not find the requested resource (get profiles.openfaas.com)
`

## Current Behaviour
I don't know what is the impact of this error.

## Possible Solution
.

## Steps to Reproduce (for bugs)
Deploy openfaas in k8s (I used 0.12.15 - 8/2/2021)
`kubectl logs pod/gateway-6fdb69cdd-wk8m9 -c faas-netes
`
lots of errors similar to this

## Context
we had issues with functions not found even if they are deployed, I am not sure it was related.

## Your Environment
* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Trefik

**Comment by alexellis** [comment]
It seems like you're having issues, but I can't tell why from what you've said. OpenFaaS is working ok in our end to end tests. 

This seems to be missing a lot of context. Could you start off by describing your environment and how you are installing openfaas? (Exact instructions)

**Comment by barelnir** [comment]
sure @alexellis 
I took the chart from openfaas repo and used is as baseline.
I did changes in external services yml to support our custom terafik deployment guidelines and deploy it via helm.
I also disabled the following:
createCRDs: false # to avoid deploying on same cluster CRDs more than once.
exposeServices: false

if you can ask specific questions I can share more info, openfaas works now but because the error isn't clear to me and I can't tell if it indicates a problem or not I wanted to share it here.

**Comment by alexellis** [comment]
I'm going to close this because we cannot offer support for your forked version of the chart. All I will say at this point is that it sounds like you don't have the CRDs required because you disabled their creation. I would suggest you create them before deployment.

My advice is to use the upstream chart, which we can help you with.
