### ISSUE TITLE
Unify helm chart values for multi-arch support

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#781]
Now that we publish all of our images as multi-arch to GHCR 

```sh
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
helm upgrade openfaas --install openfaas/openfaas
```
should work on both arm and amd clusters (or even clusters with mixed node archs) without any special configuration. 

## Current Behaviour

We specify 

```yaml
nodeSelector:
  beta.kubernetes.io/arch: amd64
``` 

Which prevents the install command from working without special values, specifically we have to override the nodeSelector, for example

```yaml
nodeSelector:
  beta.kubernetes.io/arch: arm64
``` 

## Possible Solution

We should not specify the node arch via the `nodeSelector`, the same gateway image will work on all arm, amd64, and amd64, so we probably don't need to specify the selector at all.

Alternatively, if we want to really specify which nodes openfaas works with, we could use tolerations to create an explicit list of node types that we build multi-arch images for

```yaml
tolerations:
- key: beta.kubernetes.io/arch
  operator: Equal
  value: arm64
- key: beta.kubernetes.io/arch
  operator: Equal 
  value: amd64
- key: beta.kubernetes.io/arch
  operator: Equal
  value: arm
```

## Steps to Reproduce (for bugs)

1. create an ARM cluster
2. run the install 
```sh
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
helm upgrade openfaas --install openfaas/openfaas
```
3. check that the pods are never actually scheduled
```sh
$ kubectl get po -n openfaas
NAME                                READY   STATUS    RESTARTS   AGE
alertmanager-7b864c9cb6-n9jnz       0/1     Pending   0          10s
prometheus-58c899f45d-xrjb7         0/1     Pending   0          10s
queue-worker-77f4446d48-wfbbl       0/1     Pending   0          10s
nats-7d86c64647-vzx5q               0/1     Pending   0          10s
basic-auth-plugin-bc899c574-r49ql   0/1     Pending   0          10s
gateway-7778bccd8-qx8zd             0/2     Pending   0          10s
```
Then describe one of the Pods and check the events
```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  74s (x2 over 74s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity.
```

## Context

This was highlighted by microk8s because we need to disable the arm64 support there, see https://github.com/ubuntu/microk8s/pull/2142

**Comment by LucasRoesler** [comment]
In an ARM cluster (using microk8s) and an AMD64 cluster (using Kind) I have tested both 

1. simply removing the nodeSelector
2. adding the three tolerations

both work as expected.  We simply need to pick the option we prefer

**Comment by alexellis** [comment]
I think we can remove these restrictions now due to the use of multi-arch images. The separate YAML files are still useful to set lower memory requests for Raspberry Pi.

**Comment by alexellis** [comment]
Thanks for the PR. I'll close this issue now. The basic-auth-plugin was already multi-arch but had a different name, so I've added that change in after your PR.
