### ISSUE TITLE
Proposal to change the current exporter for nats

### ISSUE THREAD

**Issue by ionutz89** [openfaas/faas-netes#787]
Maybe it will be useful for someone else who needs prometheus-nats-exporter as `multi-arch`

Check the Docker hub [link](https://hub.docker.com/r/homeall/prometheus-nats-exporter)

**Comment by alexellis** [comment]
Hi @ionutz89 thanks for your interest in OpenFaaS,

Please can you follow the contribution guide and fill out the whole template?

We cannot use a third-party Docker image in OpenFaaS, so I would suggest you make a case with the NATS team on their GitHub repo. Feel free to raise an issue there and send us a PR, if the changes get made upstream.

Alex
