### ISSUE TITLE
Unable to enumerate functions deployed to non-standard namespace

### ISSUE THREAD

**Issue by zjpiazza** [openfaas/faas-netes#790]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
User should be able to list functions deployed in alternative namespaces using `faas-cli ls -n [namespace]`

## Current Behaviour
Function is deployed in non-standard namespace, but is not returned by the faas-cli list command. Namespace has been properly annotated with "openfaas=1" via kubectl. Role and RoleBinding have also been created. The deployment was definitely accepted by the gateway and the k8s scheduler created an associated deployment for the function. However I cannot list it via the cli or invoke via curl.

## Steps to Reproduce (for bugs)
1. Create secondary namespace for functions
2. Create Role and RoleBinding in new namespace for openfaas-controller to operate in newly created namespace
3. Deploy function to newly created namespace
4. Execute `faas-cli ls -n [namespace]` and no results are returned

## Context
Trying to setup multi tenant OpenFaaS installation so having fully working support for namespaces is criticial

## Your Environment
* FaaS-CLI version:
0.13.8

* Docker version:
Client 19.03.12

* OpenFaaS platform:
Kubernetes

* Operating System and version:
Windows 10 19041.804

**Comment by alexellis** [comment]
/set title: Question: how can a Role be used instead of a ClusterRole for multiple namespaces?

**Comment by alexellis** [comment]
We'll continue to support a ClusteRole for OSS, and offer new Role/Bindings for OpenFaaS PRO customers. If anyone is landing here and needing help for a work cluster, feel free to reach out.
