### ISSUE TITLE
Trying to Access OpenFaaS with an Istio Gateway

### ISSUE THREAD

**Issue by manjeettanwar-1026** [openfaas/faas-netes#800]
I was trying to access openfaas through istio in which i have included gateway and virtual service...I need to create a separate endpoint for the openfaas..eg:-"http://istio_ingress_Loadbalancer/openfaas" this should give me openfaas UI...Can anyone please help me regarding i am having hard time accessing this?? below is the code i have written for gateway and virtual service

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: openfaas-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port: 
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openfaas-vs
spec:
  hosts:
  - "*"
  gateways:
  - openfaas-gateway.openfaas.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /openfaas
    route:
    - destination:
        host: gateway.openfaas.svc.cluster.local
        port:
            number: 8080

**Comment by alexellis** [comment]
The gateway doesn't support a prefix, so you'd be better off using a sub-domain.

Alex
