### ISSUE TITLE
Unable to retrive logs in multi-namespace setup

### ISSUE THREAD

**Issue by saikiran2603** [openfaas/faas-netes#811]
## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)

faas-cli logs / API system/logs not working when multiple namespaces are enabled for openfaas. When a single namespace (default openfaas-fn) is used , both the cli and api returns the logs of the functions but when second namespace is enabled and annotated, logs of functions in both the namespaces are not visible either though cli or through api.

## Expected Behaviour
faas logs nodeinfo --gateway http://localhost:8080 --namespace openfaas-fn
faas logs nodeinfo --gateway http://localhost:8080 --namespace test-namespace

both should function, when multiple namespaces are annotated. 

## Current Behaviour
No log is visible 
$ faas logs nodeinfo-http --gateway http://localhost:8080 --namespace hwf-chatbot
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.
<execution hangs>

## Are you a GitHub Sponsor (Yes/No?)
Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## List All Possible Solutions and Workarounds
N/A

## Which Solution Do You Recommend?
Needs to be investigated.

## Steps to Reproduce (for bugs)
1. Install openfaas - this creates default openfaas-fn namespace as well 
```
 helm repo add openfaas https://openfaas.github.io/faas-netes/
helm repo update
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
helm install openfaas openfaas/openfaas --namespace openfaas \
	--set functionNamespace=openfaas-fn \
	--set operator.create=true \
	--set generateBasicAuth=true \
	--set gateway.upstreamTimeout=14m \
	--set gateway.writeTimeout=15m \
	--set gateway.readTimeout=15m \
	--set faasnetes.writeTimeout=15m \
	--set faasnetes.readTimeout=15m \
	--set exposeServices=false \
	--set ingressOperator.create=true \
	--set queueWorker.ackWait=15m \
	--set clusterRole=true \
	--set rbac=false \
	--set openfaasPRO=false 
```
2. Deploy function nodeinfo from gateway UI.
```
$ kubectl get all -n openfaas-fn
NAME                            READY   STATUS    RESTARTS   AGE
pod/nodeinfo-6b6cd8667d-dd7x8   1/1     Running   0          35s

NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/nodeinfo   ClusterIP   10.152.183.207   <none>        8080/TCP   35s

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nodeinfo   1/1     1            1           35s

NAME                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/nodeinfo-6b6cd8667d   1         1         1       35s

```

3. Check logs of the pod 

```
$ faas logs nodeinfo --gateway http://localhost:8080
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Version: 0.8.4	SHA: bbd2e96214264d6b87cc97745ee9f604776dd80f
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Forking: node, arguments: [index.js]
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Started logging: stderr from function.
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Started logging: stdout from function.
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Watchdog mode: http
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Timeouts: read: 15s, write: 15s hard: 10s.
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Listening on port: 8080
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Writing lock-file to: /tmp/.lock
2021-07-07T15:27:33+05:30 2021/07/07 09:57:33 Metrics listening on port: 8081
2021-07-07T15:27:34+05:30 node12 listening on port: 3000
```

4. Create a new namespace and annotate it for openfaas 

```
kind: Namespace
apiVersion: v1
metadata:
  name: test-namespace
  annotations:
    openfaas: '1'
```
```
$ kubectl get ns
NAME                 STATUS   AGE
kube-system          Active   7m26s
kube-public          Active   7m26s
kube-node-lease      Active   7m26s
default              Active   7m26s
ingress              Active   6m28s
container-registry   Active   6m21s
openfaas             Active   5m52s
openfaas-fn          Active   5m52s
test-namespace       Active   22s

```

5. Deploy function to the new namespace 

```
provider:
  name: openfaas
functions:
  nodeinfo-http:
    lang: node12
    namespace: test-namespace
    handler: ./nodeinfo
    image: ghcr.io/openfaas/nodeinfo:latest
    environment:
      RAW_BODY: true

```
```
$ kubectl get all -n test-namespace
NAME                                 READY   STATUS    RESTARTS   AGE
pod/nodeinfo-http-75cff78c5c-gfrlm   1/1     Running   0          16s

NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/nodeinfo-http   ClusterIP   10.152.183.75   <none>        8080/TCP   16s

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nodeinfo-http   1/1     1            1           16s

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/nodeinfo-http-75cff78c5c   1         1         1       16s

```

6. Check logs

```
$ faas logs nodeinfo --gateway http://localhost:8080 --namespace openfaas-fn
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.

```

CLI does not retrieve the logs which were previously being retrieved .

Same for the new deployed function

```
~$ faas logs nodeinfo-http --gateway http://localhost:8080 --namespace test-namespace
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.

```

## Context
We are using the API /system/logs to retrieve logs of deployed functions. but due to this issue we are unable to use this API when multuple namespaces are enabled. 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
 version: 0.13.9

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 20.10.6, build 370c289

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
Kubernetes 

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux 
* Code example or link to GitHub repo or gist to reproduce problem:
Provided above
* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
N/A

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by saikiran2603** [comment]
>@LucasRoesler mentioned that you were setting rbac=false within the helm chart. What's your reason for doing that? I believe it is required.

This was for a  dev setup,  i thought it would not matter much. Let me set it back to true and test the issue again. Will get back to you on it 

 >Hi, under "Steps to Reproduce (for bugs)", can you please format the output with line breaks so that we can read it more easily? 

sure i will do that

**Comment by saikiran2603** [comment]
i did a fresh install with rbac=true , here are the results 

logs before

$ faas logs nodeinfo --gateway http://10.152.183.76:8080 
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Version: 0.8.4	SHA: bbd2e96214264d6b87cc97745ee9f604776dd80f
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Forking: node, arguments: [index.js]
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Started logging: stderr from function.
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Started logging: stdout from function.
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Watchdog mode: http
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Timeouts: read: 15s, write: 15s hard: 10s.
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Listening on port: 8080
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Writing lock-file to: /tmp/.lock
2021-07-07T18:44:01+05:30 2021/07/07 13:14:01 Metrics listening on port: 8081
2021-07-07T18:44:01+05:30 node12 listening on port: 3000
^C



$kubectl apply -f namespace.yaml
namespace/test-namespace created

namespace.yaml contents

kind: Namespace
apiVersion: v1
metadata:
  name: test-namespace
  annotations:
    openfaas: '1'
    

Deploying function in new namespace 

$ faas deploy -f ./test/test-stack.yaml --gateway http://10.152.183.76:8080
Deploying: nodeinfo-http.
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.

Deployed. 202 Accepted.
URL: http://10.152.183.76:8080/function/nodeinfo-http.test-namespace

test-stack.yaml contents 
provider:
  name: openfaas
functions:
  nodeinfo-http:
    lang: node12
    namespace: test-namespace
    handler: ./nodeinfo
    image: ghcr.io/openfaas/nodeinfo:latest
    environment:
      RAW_BODY: true
      
checking logs

Couriously , i was able to view logs of my function in dummy namespace for some time , but after which i could not see any. And i could not see any logs for nodeinfo in openfaas-fn namespace.

saikiran@saikiran:~$ faas logs nodeinfo-http --gateway http://10.152.183.76:8080 -n test-namespace
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Version: 0.8.4	SHA: bbd2e96214264d6b87cc97745ee9f604776dd80f
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Forking: node, arguments: [index.js]
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Started logging: stderr from function.
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Started logging: stdout from function.
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Watchdog mode: http
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Timeouts: read: 15s, write: 15s hard: 10s.
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Listening on port: 8080
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Writing lock-file to: /tmp/.lock
2021-07-07T18:48:19+05:30 2021/07/07 13:18:19 Metrics listening on port: 8081
2021-07-07T18:48:19+05:30 node12 listening on port: 3000
^[[A^[[A^C
saikiran@saikiran:~$ faas logs nodeinfo --gateway http://10.152.183.76:8080 -n openfaas-fn
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.
^C
saikiran@saikiran:~$ faas logs nodeinfo --gateway http://10.152.183.76:8080 -n openfaas-fn
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.
^C
saikiran@saikiran:~$ faas logs nodeinfo-http --gateway http://10.152.183.76:8080 -n test-namespace
WARNING! You are not using an encrypted connection to the gateway, consider using HTTPS.

**Comment by LucasRoesler** [comment]
the logs command defaults to only returning logs from the last 5 minutes, but this can be controlled using these flags
```
      --since duration           return logs newer than a relative duration like 5s
      --since-time timestamp     include logs since the given timestamp (RFC3339)
```

so if you are seeing logs, but they disappear after some time, it could just mean that your function is not currently active.

**Comment by alexellis** [comment]
Please can you format your code blocks with backticks? We were discussing your issue but are finding it hard to read.

**Comment by LucasRoesler** [comment]
regarding how RBAC is configured, using both `--set clusterRole=true --set rbac=false` is definitely not compatible. 

If you disable RBAC there is an `if`-block  in the Helm chart that will disable the cluster role behavior https://github.com/openfaas/faas-netes/blob/afe50c53fedf12ba9766ba712dbd3105bc853e38/chart/openfaas/templates/controller-rbac.yaml#L15-L16

The purpose of `rbac=false` is for a very narrow use case where you are trying to install openfaas _but_ don't have sufficient access to the cluster to also install RBAC of where you have complete control over the installation of the cluster and have chosen to disable RBAC completely (which i am not even sure is still supported by the recent versions of k8s). 

When RBAC is disabled in the Helm chart, then the installation is inherently going to be a single-namespace installation. RBAC is required to enable the OpenFaaS controller access to the alternative namespaces.  In general, if you want multi-namespace support, you need the ability to set RBAC.

**Comment by saikiran2603** [comment]
>Please can you format your code blocks with backticks? We were discussing your issue but are finding it hard to read.

Sorry about that i've formatted the code now 



> the logs command defaults to only returning logs from the last 5 minutes, but this can be controlled using these flags
> 
> ```
>       --since duration           return logs newer than a relative duration like 5s
>       --since-time timestamp     include logs since the given timestamp (RFC3339)
> ```
> 
> so if you are seeing logs, but they disappear after some time, it could just mean that your function is not currently active.

Yes , i have it working if i increase the time duration ! , Previously we were tailing the output and closing our session once the work was done, i mistook it to mean it would fetch since beginning of time. 

>When RBAC is disabled in the Helm chart, then the installation is inherently going to be a single-namespace installation. RBAC is required to enable the OpenFaaS controller access to the alternative namespaces. In general, if you want multi-namespace support, you need the ability to set RBAC.

This explains a lot of issues which we were facing, we initially were not using clusterRole, and stuck to RBAC=false on a shared cluster during development. Now that we were finalizing deployment  these should have been reverted. 

I will make these amends and test the entire thing. Based on what you have explained i think it should solve our issues. Thanks for all your help with this @LucasRoesler @alexellis I think this can be closed, if i face any issues i will get in touch over slack /github

**Comment by saikiran2603** [comment]
btw , do you think it would be a good idea to update the documentation to reflect this ? 

>the logs command defaults to only returning logs from the last 5 minutes, but this can be controlled using these flags

I am open to do the PR, if you are okay with it.

**Comment by alexellis** [comment]
Thanks for your input, we will review the docs in this area.

Do consider becoming a personal or business sponsor via GitHub.

Cheers,

Alex
