### ISSUE TITLE
 [Proposal] New Secret management in faas-netes

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-netes#82]
## Context
Currently, `faas-netes` assumes that all secrets are related to docker creditials, specifically that they should be mounted as `ImagePullSecrets`. See [the current deploy handler](https://github.com/openfaas/faas-netes/blob/cd1130172de126845ab5041929b7abcd7a953aca/handlers/deploy.go#L126) where it sets each named secret as an image pull secret

```go
	imagePullSecrets := []apiv1.LocalObjectReference{}
	for _, secret := range request.Secrets {
		imagePullSecrets = append(imagePullSecrets,
			apiv1.LocalObjectReference{
				Name: secret,
			})
	}
```

The image pull secrets are a particular special use case for secrets, but does not actually facilitate the use of secrets by the functions for their unique needs, for example DB credentials. This functionality has been implemented for docker swarm, see [pull request 292](https://github.com/openfaas/faas/pull/292).

## Proposal
Kubernetes allows for several configuration options when mounting and using secrets, more than Swarm. I propose that we deploy functions so that the usage in Swarm and K8S is identical. Specifically, this means that secrets are deployed so that they are mounted as files at `/run/secrets`

Per the documentation [on kubernetes.io](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) this can be implemented 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/run/secrets"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
```

Implementing this requires a potentially backwards incompatible change or weird naming going forward. Concretely I propose that 

1. The `request.Secrets` should be reserved for function secrets
2. When creating the the `DeploymentSpec` for the function, the secrets list  should be added to the volumes list so that the secrets are mounted as files  at `/run/secrets`, see the example yaml above.  In the source code this  would roughly looks like
    ```go
    Containers: []Container{
        {
            VolumeMounts: []VolumeMount{
                {
                    Name: "Secret1"
                    ReadOnly: true,
                    MountPath: "/run/secrets",
                },
            },
        },
    },
    Volumes: []Volume{
        {
            Name: "Secret1",
            Secret: &SecretVolumeSource{
                SecretName: "Secret1",
            },
    }
    ```
2. Registry credentials secrets should be passed in a new `request.RegistryAuth`, this would again be a list of strings, e.g. 

   ```yaml
   RegistryAuth:
     - dockerHub
     - internalHub
     - internal-gcr
     - internal-ecr
   ```
   this would allow K8S to pull from multiple private registries and is already  supported by the K8S api.

## Problems

I believe this proposal will break the current support for `ImagePullSecrets`. Alternatively, we could continue the support for `ImagePullSecrets` via `request.Secrets` and then add a new `request.FunctionSecrets` to support secrets that are mounted as files as described above. This would require refactoring the secrets support in the core `gateway` and I also believe brings in weird naming issues.  Consider this table of how to translate between the platforms we currently support

|                | OpenFaas        | Swarm        |    k8s           |
| -------------- | --------------- | ------------ | ---------------- |
| Registry Auth  | secrets         | docker login | imagePullSecrets | 
| Secret value   | functionSecrets | secrets      | secrets          |

It feels like using a new name for secrets mounted as a file would be confusing in the long term.

The trickiest part of this proposal is agreeing on an API and the potential break in backwards compatibility.

**Comment by alexellis** [comment]
I like the level of detail in this proposal - I can tell you've really thought it through. Thank you @LucasRoesler. Could we maintain a list of secrets and then determine the type from the Kubernetes API in order to know where to attach them?

Pseudo code:

```
spec = new_spec

for secret in requested_secrets
  if k8s_lookup(secret).type == image_pull
     add_image_pull(secret, spec)
  else mount_secret(secret, spec)
```

**Comment by LucasRoesler** [comment]
I like this proposal by @alexellis, I will work on this tomorrow and hope to have a PR by end of Wednesday

**Comment by alexellis** [comment]
Please ping me if you need anything.
