### ISSUE TITLE
the problem of accessing to the service in openfaas in the local area network

### ISSUE THREAD

**Issue by lakomi** [openfaas/faas-netes#822]
I built an openfaas, using docker, and kubernetes using minikube，Use yaml of faas-netes to build openfaas.
Now I want to access the ui page of the gateway on a host in the same network as the server.

## Expected Behaviour

open the gateway ui

## Current Behaviour

I pass the command “minikube service gateway-external -n openfaas”  
and found that the url is “http://192.168.49.2:31112”。I access this url,but not return.

I know this url maybe not correct，I try “http://10.38.162.198:31112/”,it also not return. 
10.38.162.198 is my server ip.

Does anyone know how to make the created service accessible on other hosts in the LAN?

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

I judge the possible cause：
1. the internal and external port mapping of docker
2. The listening address is 127.0.0.1, not 0.0.0.0
3. or other.I don't know

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.13.13
* Docker version `docker version` (e.g. Docker 17.0.05 ):
docker 18.09.4
* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
* Operating System and version (e.g. Linux, Windows, MacOS):
linux,centos
* Link to your project or a code example to reproduce issue:
none
* What network driver are you using and what CIDR? i.e. Weave net / Flannel
none

**Comment by alexellis** [comment]
Hi @lakomi,

Thanks for your interest in OpenFaaS. What's your experience level with Kubernetes?

If you're new and feeling confused, then may I suggest that you follow a tutorial with KinD or K3d? Perhaps you can use `kubectl port-forward` as we describe [in the docs](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md)? 

Alternatively, we have a free course available in partnership with the LinuxFoundation: https://www.openfaas.com/blog/introduction-to-serverless-linuxfoundation/

Alex

**Comment by lakomi** [comment]
I change to use kinD.I want to access the gateway ui through the host ip.but now, I only can access through 127.0.0.1。what should I do?
