### ISSUE TITLE
Deployment method issues

### ISSUE THREAD

**Issue by lakomi** [openfaas/faas-netes#825]
Using our CLI installer arkade - (recommended)
With the Helm chart, Flux or ArgoCD (GitOps workflow)
Or using the statically generated YAML files (not recommended)

1、These three methods are provided on the official website。If I want to deploy openfaa on a k8s cluster, which is a production environment, which deployment method is better?

2、In addition, I found the relevant images on docker hub, can this be used for production deployment?

**Comment by alexellis** [comment]
Hi @lakomi thanks for your interest.

Please do use the issue template if you find problems with openfaas that you wish to report.

We have documentation that you're welcome to browse, but offer commercial services for production and commercial users. Feel free to book an hour of my time to go over your deployment.

https://openfaas.com/support

https://calendly.com/alexellis

Alex

**Comment by alexellis** [comment]
/set title: Question on best practices for production
