### ISSUE TITLE
Adding labels to Deployment and Service Objects of functions in K8s

### ISSUE THREAD

**Issue by omriarnon-s1** [openfaas/faas-netes#835]
Hi
We're using openfaas on K8s. 
We have a strict labeling policy for Deployment and Service objects (also others), which is enforced on the Cluster level.
Currently, I've easily labeled all of the function pods using the function.yml, utilizing the ability to add labels to functions.
What I haven't found a way to do - Is to add labels to the actual deployment and service object of each function.

Any help with this will be highly appreciated 

## Expected Behaviour
I suggest adding an ability to add the labels to the Deployment and Service object itself.

## Current Behaviour
Currently, I haven't found anything in the documentation/google that suggests it's possible to add labels to the deployment and service objects of each function in K8s.

## Are you a GitHub Sponsor (Yes/No?)
No

## List All Possible Solutions and Workarounds
Unfortuately no workaround.

## Which Solution Do You Recommend?
Exposing the ability to add labels to the deployment and service Objects

## Context
It affected us in the way that we need to find a pretty hard to find workaround for adding labels to function deployment and service objects.

**Comment by alexellis** [comment]
This seems like a specialised enterprise/commercial problem, rather than an open source need.

If you'd like to know more about enterprise support, please get in touch: https://www.openfaas.com/support
