### ISSUE TITLE
Can I change healthcheck period?

### ISSUE THREAD

**Issue by jungchul-dev** [openfaas/faas-netes#839]
When I deploy function to kubernetes, health check occur per 1 or 2 second.

## Expected Behaviour
I can change the healthcheck period just like I can change the healthcheck url with the annotation option
```
annotations:
    com.openfaas.health.http.path: "/healthz"
```

## Current Behaviour
There is no option about healthcheck period. So too many log is print in kubernetes pod
```
2021-09-17 02:46:04,679 werkzeug - INFO:10.122.16.27 - - [17/Sep/2021 02:46:04] "GET /healthz HTTP/1.1" 200 -
2021-09-17 02:46:06,305 werkzeug - INFO:10.122.16.27 - - [17/Sep/2021 02:46:06] "GET /healthz HTTP/1.1" 200 -
2021-09-17 02:46:06,680 werkzeug - INFO:10.122.16.27 - - [17/Sep/2021 02:46:06] "GET /healthz HTTP/1.1" 200 -
2021-09-17 02:46:08,305 werkzeug - INFO:10.122.16.27 - - [17/Sep/2021 02:46:08] "GET /healthz HTTP/1.1" 200 -
2021-09-17 02:46:08,679 werkzeug - INFO:10.122.16.27 - - [17/Sep/2021 02:46:08] "GET /healthz HTTP/1.1" 200 -
2021-09-17 02:46:10,305 werkzeug - INFO:10.122.16.27 - - [17/Sep/2021 02:46:10] "GET /healthz HTTP/1.1" 200 -
2021-09-17 02:46:10,679 werkzeug - INFO:10.122.16.27 - - [17/Sep/2021 02:46:10] "GET /healthz HTTP/1.1" 200 -
2021-09-17 02:46:12,305 werkzeug - INFO:10.122.16.27 - - [17/Sep/2021 02:46:12] "GET /healthz HTTP/1.1" 200 -
```

## Are you a GitHub Sponsor (Yes/No?)
No

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
Provide options to change health check period just like `com.openfaas.health.http.path`

## Which Solution Do You Recommend?
Provide options to change health check period

## Steps to Reproduce (for bugs)
1. deploy function to kuberntes
2. kubectl logs -f <podname> -n openfaas-fn

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  72816d486cf76c3089b915dfb0b66b85cf096634
 version: 0.13.13
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:13 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 18.04

**Comment by alexellis** [comment]
Hi @jungchul-dev welcome to the community and thanks for your interest in OpenFaaS.

We have an issue template and need every user to play by the same rules. Unfortunately you seem to have deleted it.

Could you edit your issue and help us to help you? https://raw.githubusercontent.com/openfaas/faas-netes/master/.github/ISSUE_TEMPLATE.md

Alex

**Comment by jungchul-dev** [comment]
> Hi @jungchul-dev welcome to the community and thanks for your interest in OpenFaaS.
> 
> We have an issue template that gives us information we require to help them. I'm not sure why you deleted it, but we would like you to edit your issue: https://raw.githubusercontent.com/openfaas/faas-netes/master/.github/ISSUE_TEMPLATE.md
> 
> Alex

Thanks Alex. I modified my issue

**Comment by alexellis** [comment]
Thanks for providing the additional information.

My question for you would be whether you've read the helm chart documentation on readiness checks and probes?

https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#tuning-function-cold-starts

**Comment by jungchul-dev** [comment]
I already know about value.yaml for helm.
But I was wondering if there is an option per function like `com.openfaas.health.http.path` .
I will edit the value.yaml file of helm as you mentioned.
Thanks @alexellis
