### ISSUE TITLE
[Feature Request] Expose values for prometheus config

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas-netes#852]
## Expected Behaviour

Per https://github.com/openfaas/nats-queue-worker/issues/105#issuecomment-942497834, creating an issue for the need to configure the default autoscaling alert in prometheus via helm rather than an imperative change after the fact.

This should be pretty trivial to expose, but I'm creating this issue to open the floor if there's any additional things that we might want to think about now and not introduce a breaking change in the chart later.

## Current Behaviour

This is not exposed.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Which Solution Do You Recommend?

At a minimum, just expose up that entry for the `APIHighInvocationRate` alert for `expr` and `for` with the current values as defaults.

Maybe it would be useful to add more alerts, but those would probably have to be configurable per function to really be of use as it pertains to autoscaling.

## Context

Trying to avoid imperative change after the fact, as it's not particularly great to do when working with helm.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.13.13

* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.8

* What version and distriubtion of Kubernetes are you using? `kubectl version`
server v1.21.3
client v1.22.2

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by kevin-lindsay-1** [comment]
Thinking about potentially adding something like `additionalAlerts`, which is just a sequence of alerts added to the alert rules.

Not sure how useful it would be to do something like override existing alert(s).

**Comment by kevin-lindsay-1** [comment]
> I wasn't expecting you to go ahead with a PR without us having had a chance to talk here first.

All good, if it's a fairly trivial implementation that doesn't really change any existing arch or patterns, I'm fairly likely to make a PR, if not for the sake of fallback to unblock, then to get other eyes to focus on alternative solutions, like we just saw.

> Perhaps we should have the ability to remove this specific alertmanager rule, and for you to introduce your own set of rules separately in manifests or your own helm chart?

Yeah, that would definitely be preferred in my opinion; all of these configmaps that get bundled up would be easier to work with if I had some kind of override.

One solution I could see is a default set of configmaps that are core to OF; just reasonable defaults. There is then a set of other configmaps that simply override.

"Why a separate set of configmaps?", you ask? Because if the helm chart doesn't expose the config, but it creates the 1 resource, helm will scream that the resource it's trying to create (the "override" in my separate chart) is not owned by the current release, and will fail to override, because only 1 release can own 1 resource.

You might be able to get rid of the "default" configmaps somehow, so as to not have two sets created, but I don't know if that's really possible or what the LoE would be.

Alternatively, you could simply set a flag in `values` on `faas-netes/openfaas` and not create any configmaps at all, allowing the user to supply them themselves in a separate release that comes before openfaas.

**Comment by kevin-lindsay-1** [comment]
@LucasRoesler do you know if it scans a namespace to find these and applies all of them, or if it only has 1 configmap?

**Comment by kevin-lindsay-1** [comment]
It's certainly not ideal, but I discovered a way to override these values declaratively using `helmfile`'s `kustomize` support seen in their [advanced usage](https://github.com/roboll/helmfile/blob/master/docs/advanced-features.md#adhoc-kustomization-of-helm-charts) guide.

Specifically, I'm using a strategic merge patch, because with helmfile I can just put that in a `patches/` directory next to my charts and it will do a fairly graceful merge after the fact.

**Comment by kevin-lindsay-1** [comment]
Scratch that, for some reason the strategic merge patch is deleting the CRD, so functions are deleted.

That's enough for a friday night; I'll have to look more into this if this feature isn't added.

**Comment by LucasRoesler** [comment]
Where does that leave us? do we want to just add a new value to the chart to allow replacing this section? https://github.com/openfaas/faas-netes/blob/5dfd3724f484fbce5e6a07286de0eca75b473b2c/chart/openfaas/templates/prometheus-cfg.yaml#L73-L86
This would be the simplest approach.


Or, do we want to support reading the alert config from additional configmaps?  It would require having a map from ConfigMap names to keys which then needs to be used here https://github.com/openfaas/faas-netes/blob/5dfd3724f484fbce5e6a07286de0eca75b473b2c/chart/openfaas/templates/prometheus-cfg.yaml#L24, here https://github.com/openfaas/faas-netes/blob/5dfd3724f484fbce5e6a07286de0eca75b473b2c/chart/openfaas/templates/prometheus-dep.yaml#L85-L95, and here https://github.com/openfaas/faas-netes/blob/5dfd3724f484fbce5e6a07286de0eca75b473b2c/chart/openfaas/templates/prometheus-dep.yaml#L76-L84 
This would be more complicated, for sure.

**Comment by kevin-lindsay-1** [comment]
I guess that depends on how confident OF is that the existing alert rules are good enough for all use cases to not need to override.

In my case, I need to create an alert rule to scale based off `429`s for async functions, but you could make the argument that that's a perfectly reasonable default. I think this use case is more-or-less a desired standard behavior, but the a reason why it would be difficult to make it a default alert rule is because of a comment I made a while back about this:

https://github.com/openfaas/nats-queue-worker/issues/105#issuecomment-785309835

> > Would this open the gate to requests for retryign on other HTTP codes?
>
> I would say that this is a contract between watchdog and the queue worker, and should therefore be only their collective concern, that is the scope of HTTP codes shouldn't increase unless the flow changes; application-level retry would maybe be a different feature request, but if that one day gets requested and implemented, a distinction between the watchdog and the function/handler itself may need to be made explicit in the HTTP request between the watchdog and queue-worker, if it's not already.

To try to keep this brief, I think that one of the main issues with being able to set standard OF alert rules that never need to be changed is an "issue" with the amount of layers going on in a function pod.

1. The watchdog
2. The template
3. The function/handler

The issue that could decrease confidence is say, a `429` being returned from the handler being indistinguishable from the watchdog on an alerting basis. In other words, if watchdog sends `429`s, it means there's a concurrency limit, and a pro queue worker/the end client should retry their request. However, if a developer, not realizing this architectural detail or porting from a lambda or other FaaS, returns a `429`, then prometheus would see that and infer that it's time to scale up. The infrastructure of openfaas and the handler can step on each other's toes.

There's potentially an argument for "but what if I want prometheus to know about a specific function in order to scale in a custom way?", which I would argue is better suited for custom metrics and/or HPA autoscaling, not OF prometheus-based scaling. I think it's potentially "dangerous" to let applications dictate something as foundational as global autoscaling rules.

> Where does that leave us? do we want to just add a new value to the chart to allow replacing this section?
> Or, do we want to support reading the alert config from additional configmaps?

I would say that the former is more trivial, and if the point above is resolved, then overrides will be unnecessary in the first place, which I would argue would probably be a good design goal. If the point about the watchdog/gateway/prometheus contract is resolved, then a function would probably never need its own bespoke prometheus rule, because there's no confusion on an HTTP level of whether or not a `429` came from watchdog or the template/handler.

**Comment by LucasRoesler** [comment]
@kevin-lindsay-1 that is a lot of detail. 

I am relatively convinced that we should make this configurable and it sounds like you are fine with doing it via a value. < @alexellis i think this is what we should do.

---

Regarding changing the default alert, 

I think changing the default based on some internal convention is fine, however, regarding 429, i think scaling could be dangerous because the semantics of a 429 are that the client should backoff the request, usually based on a Retry-After header. See https://httpstatuses.com/429

Scaling the function could simply cause more system errors by overwhelming downstream services. There are no standards about how requests are counted so we can't really make any assumptions about what is happening and what will happen if we allow more concurrent requests by scaling out.

**Comment by kevin-lindsay-1** [comment]
@LucasRoesler are you effectively saying in the latter portion that you don't think there are reasonable defaults for alert rules?

For example, I would scale my functions off concurrency limits (sync or async), until we either stop getting them or hit the max scale. However, I wouldn't scale off of successful invocations, which is currently the configured value.

By default, watchdog pods don't have a `max_inflight`, but that seems kinda dangerous to me from a concurrency standpoint, because:
1. you could theoretically send a single pod enough invocations to crash or overload the pod in some way, so I can't think of a reason why you wouldn't want a single pod to have the assurance that it can't be overloaded (according to what that particular fn pod can handle)
2. the default scaling goes off `200`s if I remember correctly, which works pretty well for sync jobs, but for anything longer running, it basically doesn't scale up at all. Since the prom alert rules are global to all functions in a namespace, seems to me like you would realistically configure everything according to `429`s because going based off of 200s is specific to one function's timing.
3. Scaling based off of `200`s seems to be opaque at best in regards to pod capacity. For example, let's say my global rule is `total{status_code="200"} > 5 for 5s`, meaning scale up if we have >5 `200`s for 5s or more; how this scaling ties into how much the actual functions can handle seems arbitrary. I could have 1 function that has a huge capacity and almost always has 1000/10000 invocations going at once, each taking 1s or so. This pod would basically always be triggering autoscale, even though it's at 1/10 capacity.

Seems to me like `pod.max_inflight` is not unlike kubernetes' `requests`, in that it's a pretty good idea to configure it, especially if you use autoscaling like a `HorizontalPodAutoscaler`. Since OF basically provides its own autoscaler for you, it seems to me like going based off of `pod.max_inflight` is a pretty close mirror of the semantics that you use in autoscaling, at least in kubernetes.

**Comment by LucasRoesler** [comment]
@kevin-lindsay-1 my point is that these error codes and when to scale is context dependent. A 429 isn't a signle to "send more messages or make more instances", yes you can imagine scenarios where this is true. But what happens when you scale up a function that is being rate limited by a dependent API, you simply make the problem worse. A 429 is supposed to be a signal to slow down.  

At this point the scope of this conversation has changed dramatically and I feel like we have gotten a bit lost.  If you want to discuss changing the implementation for metrics and scaling, then this is a completely different question and frankly I think a followup to the original question: let's add the ability to set a custom prometheus config, which will make it much easier to actually experiment with this other ideas.

**Comment by alexellis** [comment]
> @kevin-lindsay-1 my point is that these error codes and when to scale is context dependent. A 429 isn't a signle to "send more messages or make more instances", yes you can imagine scenarios where this is true. But what happens when you scale up a function that is being rate limited by a dependent API, you simply make the problem worse. A 429 is supposed to be a signal to slow down.

That is right.

It's the mechanism that the watchdog uses to limit concurrency.

So in the example where you can only run one request at a time due to memory constraints like video conversion or web scraping. So let's say you have a backlog of 1000 requests and only one function pod. How do you scale that? One option is to use the 429s which are being sent back by the watchdog and then to add more replicas up to the configured limit. Let's say it's 20 pods. You are now potentially able to clear down that backlog at 20x the speed.

If there was another API like "tweet message" which got a 429 from the tweepy library and then returned that to the caller, without any other context, then that would be an example of when you do not want to retry quickly. Retrying would extend the window that you have to wait.

So perhaps Kevin's rule for 429s should include or exclude specific functions, if he has that scenario?

I'm open to other suggestions. The core problem here as I see it (see also: https://github.com/openfaas/nats-queue-worker/issues/105) is not whether we can configure Prometheus alerts, but:

how do we do concurrency based limiting and scale up to accommodate that?

**Comment by alexellis** [comment]
A separate, but related question is:

How do you scale long-running jobs, even if they have no hard concurrency limits?

> Scaling based off of 200s seems to be opaque at best in regards to pod capacity. For example, let's say my global rule is total{status_code="200"} > 5 for 5s, meaning scale up if we have >5 200s for 5s or more; how this scaling ties into how much the actual functions can handle seems arbitrary. I could have 1 function that has a huge capacity and almost always has 1000/10000 invocations going at once, each taking 1s or so. This pod would basically always be triggering autoscale, even though it's at 1/10 capacity (for 1 pod).

Scaling based upon requests processed was the original rule I put together, and it seems to have worked OK for synchronous work, perhaps it could be better.

For long running invocations, the metric doesn't change quickly enough to trigger scaling rules. So could the rules be changed to accommodate both?

Kubernetes HPA with custom metrics works upon the idea of reaching a target number of X for a custom metric. Let's say it's http_requests_inflight. You may set a scaling trigger of 10 inflight requests, when you get over that number (11,12,13,14,15), more replicas are added until the number gets back to its target level of ~ 10 inflight requests.

Could we do similar?

HPA is also very slow to change, it could take 20 minutes to scale down, which helps with hysteresis that Kevin's seen when using custom Prometheus alerts. You may see a scale up, the 429s go down, then it scales down, and the 429s go up again. At a stable level, you don't want any alerts firing.

**Comment by kevin-lindsay-1** [comment]
@LucasRoesler 

> At this point the scope of this conversation has changed dramatically and I feel like we have gotten a bit lost.

I mean I agree that this is definitely evolving into a larger discussion. Perhaps we should move it somewhere, but where is the best place for this I couldn't say.

---

@alexellis 

> Kubernetes HPA with custom metrics works upon the idea of reaching a target number of X for a custom metric. Let's say it's http_requests_inflight. You may set a scaling trigger of 10 inflight requests, when you get over that number (11,12,13,14,15), more replicas are added until the number gets back to its target level of ~ 10 inflight requests.
>
> Could we do similar?

What happens when a function has an average amount of invocations being worked on that is always greater than your proposed 10 requests? For example, what if you have a super lightweight function that is constantly performing > 10 invocations at any given time? By that logic, it sounds like it would always be needing to scale up.

I see it as different functions simply have different concurrency requirements; different functions have a different ratio between the cost of the pod vs the cost of a new concurrent execution, and as such to tune that well is going to be specific to each function.

I would expect that every function has a very different finite value need for concurrent executions, similar to how different pods in kubernetes have different `requests`. When using a HorizontalPodAutoscaler, the typical pattern is not to scale based off of a static value of CPU, rather a percentage. Most HPAs don't even apply to multiple deployments, unlike OF's alert rules.

To me, it seems like you've got an unavoidable math problem where you can have a pretty good general approach if you use a percentage, but I don't think there is any static value that is going to satisfy all functions at once.

**Comment by alexellis** [comment]
> To me, it seems like you've got an unavoidable math problem where you can have a pretty good general approach if you use a percentage, but I don't think there is any static value that is going to satisfy all functions at once.

That is what I was proposing, that for this to work it might need to be set at a per function level.

The Kubernetes / GKE docs mention a few approaches which I think we should consider:

* requests per second processed
* queue depth of a pub/sub system
* latency per request

These are set to "value" (cumulative total) or to "average" which is (cumulative value / replicas of pod)

* `image-uploaded` with a target of 100 requests per second. The rule to scale up would be processing more than that as an average across pods. Very similar to what we have today.

Perhaps this configuration and "rule per function" would make synchronous scaling better?

It will still not perform well for long running invocations. Maybe using the average number of inflight requests could help?

It does seem like more configuration is needed - for three categories of function which are:

* long running
* concurrency limited
* fast to complete.

**Comment by LucasRoesler** [comment]
@alexellis and @kevin-lindsay-1 is most of this conversation resolved by the new pro scaler and the new function metrics?

**Comment by kevin-lindsay-1** [comment]
Yes
