### ISSUE TITLE
Functions being created w/ default TerminationGracePeriodSeconds

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas-netes#853]
When using the function CRD, pods that are created have the default `terminationGracePeriodSeconds` of `30`. This means that if I have a function that needs to run for longer than 30 seconds, the pod may be forcefully killed before being allowed to complete its work.

I do not know if this behavior is exclusive to functions created with the `Function` CRD.

## Expected Behaviour

When a function pod is terminating it should be gracefully shut down and exit after the `exec_timeout`.

## Current Behaviour

Deployments generated by the `Function` CRD are created with the default `TerminationGracePeriodSeconds` (30).

This causes pods with timeouts > `30s` to be `SIGKILL`ed while they're still trying to gracefully exit.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No
- [x] No, but I sponsor Alex https://github.com/sponsors/alexellis

## List All Possible Solutions and Workarounds

Overtly making this configurable, or computed via one of the environment variables inside the yaml, such as `exec_timeout`.

Then actually just use the config, because I don't see any reference to `TerminationGracePeriodSeconds` when doing a search all for this repo.

## Which Solution Do You Recommend?

Currently there's already a number of timeout config variables to keep track of. This might as well just be another one.

If there's a great way to combine all the existing timeouts, that'd be great, but otherwise just being able to manually specify the grace period termination seconds would be fine.

## Steps to Reproduce (for bugs)

1. Create a function using the `Function` CRD
2. Get the deployment's YAML
3. Look at the `terminationGracePeriodSeconds`

Alternatively:
1. Create a `sleep` function with a duration of `2m`. Invoke it once.
2. Delete the pod after the start of execution.
3. You should not expect to see a result returned by that pod, because it should receive a `SIGKILL` from kubernetes `30s` after entering the `terminating` state.

## Context

Pods are being forcefully killed before finishing their work, which effectively prevents autoscaling from being able to be enabled, because there is no guarantee that a pod that is created will have time to do its job.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.13.13

* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.8

* What version and distriubtion of Kubernetes are you using? `kubectl version`
server v1.21.3
client v1.22.2

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by LucasRoesler** [comment]
I think that having the termination grace period match the write timeout makes a lot of sense, maybe with a small bump of 50 or 100ms so that there is no possibility of those competing with each other. But it seems reasonable that the longest a function could possibly do meaningful work is the write timeout.

**Comment by alexellis** [comment]
To clarify:

1) This change means updating faas-netes to set a [Termination Grace Period](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) on  pods
2) The watchdog has been updated to finish its exit sequence quicker, if there are no remaining active connections

I've completed 2) which does not fix this issue, but makes it more tolerable if/when it's released.

**Comment by kevin-lindsay-1** [comment]
I have tested this behavior using the `golang-http` template, which uses `of-watchdog:0.9.0`, and I have verified that the container indeed exits early when its `healthcheck_interval` is set.

I do notice, however, that when not set, it uses the value of `write_timeout`, which for the sake of backwards compatibility may be appropriate, but it was unintuitive at first, because what was happening is that the pod was effectively waiting a full execution duration before actually attempting to shutdown.

In my test, I tested timeout values of `24h0m0s` for the sake of an overtly obvious proof, and updated `terminationGracePeriodSeconds` to match, and effectively what happened is that the pod was never actually going to exit early.

Maybe the healthcheck interval should be smaller, like `10s` or something by default (or based of a percentage of `write_timeout`), instead of `write_timeout`? The reason I propose this is because my `terminationGracePeriodSeconds` would probably be a little over `write_timeout`, meaning the function would "exit early" by like, 2 seconds if you don't specify a `healthcheck_interval` manually.

**Comment by alexellis** [comment]
Thanks for sharing your thoughts Kevin.

Let me think about how this could be integrated into the implementation. 

Did you also see the work drain and complete as expected?

**Comment by kevin-lindsay-1** [comment]
I just tested that a pod being given 10 sleep requests all at the same time via a simple "batch" function, each with a duration of `(10+ (10 * i))s`, where `i` is the index of a function (so effectively a start of 10, step of 10, 10 iterations).

I invoked all of them in parallel with a `healthcheck_interval` of `1s`, each invocation completed after 10 seconds of the previous execution, and after all 10 executions were finished the pod exited 0 within the healthcheck interval. All good here.

I also tested that batching those invocations twice also worked (first batch, scale 0, scale 1, wait for pod to be ready, second batch), in that none of the executions for the second batch were sent to the pod that was shutting down.

**Comment by kevin-lindsay-1** [comment]
To follow up on my previous comment regarding the default healthcheck interval, I would argue that for most functions, `1s` or so would probably be fine, because assuming that the pod only performs its internal healthcheck during the shutdown process, the resources that the pod would free up by terminating early would likely outweigh the resources used by performing said healthcheck.
