### ISSUE TITLE
Getting secret "openfaas-license" not found error for non-pro deployment

### ISSUE THREAD

**Issue by taylanisikdemir** [openfaas/faas-netes#867]
I use below command to continuously update our openfaas deployment
```
helm upgrade openfaas --wait --install openfaas/openfaas --namespace openfaas --set functionNamespace=openfaas-fn --set generateBasicAuth=true --set serviceType=LoadBalancer --set faasnetes.writeTimeout=1h5m --set faasnetes.readTimeout=1h5m --set gateway.writeTimeout=1h5m --set gateway.readTimeout=1h5m --set gateway.upstreamTimeout=1h --set queueWorker.ackWait=1h;
```

## Expected Behaviour
Successfully upgrade openfaas helm deployment.

## Current Behaviour
It started timing out today so I checked the pods in openfaas namespace. Noticed queue-worker pod was stuck at ContainerCreating. 

```kubectl describe pod queue-worker-5b46944dc7-z6r72 -n openfaas```
This shows following warning:
"Warning  FailedMount  89s (x67 over 121m)    kubelet, ip-***.us-west-2.compute.internal  MountVolume.SetUp failed for volume "license" : secret "openfaas-license" not found"

I wonder why is it requiring openfaas-license all of a sudden? 

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [] Yes
- [] No
- [x] Not yet - just learnt about sponsorship program

## Which Solution Do You Recommend?
Preserve existing behavior and don't expect openfaas-licence secret.

## Your Environment
* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by taylanisikdemir** [comment]
I digged in a little bit and found that [this change](https://github.com/openfaas/faas-netes/commit/20c7c5c0e3543affff4a942e8750685e9bc7d5e0#diff-29c1edd70e1fa2f7142f01cb0f55f663075b57dd50feb734b30347a4b9d55287) caused the issue. It should default to false to prevent breaking existing setups.

I worked around this by overriding it back to false. Helm upgrades work fine now after following steps below.
- Add following in the values.yml
```
queueWorkerPro:
  enabled: false
```
- Delete existing queue-worker deployment
`kubectl delete deployment queue-worker -n openfaas`
- Upgrade helm release with new values.yml
```
helm upgrade openfaas --wait --install openfaas/openfaas \
	--namespace openfaas \
	-f values.yml
```

**Comment by alexellis** [comment]
The chart now has:

```yaml
# Requires openfaas PRO subscription
queueWorkerPro:
  image: ghcr.io/openfaas/queue-worker-pro:0.1.0-rc5
  enabled: true
```

So that's why you're seeing this error. I'll change it back to false and publish the chart again, in the meantime you can just set this to false in your own values.yaml file.

If you're using OpenFaaS at work, please consider [becoming an individual sponsor](https://github.com/sponsors/openfaas) via GitHub since the project you're using isn't funded by the users who benefit from it. Individual sponsors also get regular updates on the 40+ repos, features and news on the project that are not published on the blog.

Alex

**Comment by alexellis** [comment]
@taylanisikdemir I cannot reproduce this after the change I made. Can you confirm?

**Comment by taylanisikdemir** [comment]
> @taylanisikdemir I cannot reproduce this after the change I made. Can you confirm?

As I mentioned in my previous comment it works fine when `queueWorkerPro.enabled: false` is set. Thanks for reverting the chart defaults to preserve existing behavior.

**Comment by bplein** [comment]
As of today (Dec 29, 2021), this issue still exists in the published charts (following the documentation). Looking at the docs, which say to enable Pro, use `--set openfaasPRO=true`, I did the opposite, redeploying openfaas with `--set openfaasPRO=false`. This removed the idler and allows it to function as the community version.

**Comment by psoares** [comment]
Same issue with the arkade install method. No idea how to change the helm settings using arkade though...
