### ISSUE TITLE
add NOTES.txt in Charts

### ISSUE THREAD

**Issue by zouyee** [openfaas/faas-netes#88]
## Current Behaviour

add NOTES.txt in Charts
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
I don't understand the format of the bash command:

`kubectl --namespace={{ .Release.Namespace }} get deployments -l "release={{ .Release.Name }}, app={{ template "faas-netesd.name" . }}"`

It has templating in it, but I can't run it in bash?

Is this just the output helm prints as a help message after deployment? If so it should say "OpenFaaS" too.
