### ISSUE TITLE
Helm is installing way too much

### ISSUE THREAD

**Issue by BryanDollery** [openfaas/faas-netes#882]
I've just run this:

```
helm repo add openfaas https://openfaas.github.io/faas-netes/
helm repo update
helm install openfaas openfaas/openfaas --namespace platform --set functionNamespace=orders --set operator.create=true --set generateBasicAuth=true
```

And the result is this:
```
service/alertmanager        ClusterIP   10.43.36.200    <none>        9093/TCP         19s
service/prometheus          ClusterIP   10.43.80.4      <none>        9090/TCP         19s
service/basic-auth-plugin   ClusterIP   10.43.145.183   <none>        8080/TCP         19s
service/nats                ClusterIP   10.43.156.242   <none>        4222/TCP         19s
service/gateway             ClusterIP   10.43.239.123   <none>        8080/TCP         19s
service/gateway-external    NodePort    10.43.150.165   <none>        8080:31112/TCP   19s
```

Which is, I suppose, as intended. The thing is, I wasn't trying to do any of that. I just want functions as a service with an operator (CRDs) for deployment of nodejs/REST functions. I am using kafka, not nats, and I already have a fully configured prometheus in my cluster with elastic and fluent-bit for logging and a lot more besides. I really don't want any of this but I can't tell which bits are needed and which bits are just extra -- I can't even tell which bit is openfaas because there's nothing with that name. Do you have any guides for how I can deploy openfaas into an existing enterprise kubernetes cluster?

Thanks,
B

**Comment by alexellis** [comment]
Hi @BryanDollery we need you to fill out the whole issue template here.

To talk about your enterprise's needs, please get in touch via https://openfaas.com/support/

Cheers,

Alex
