### ISSUE TITLE
Potential issue with env-vars and Deployment v1beta1

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#89]
I believe there is a potential issue with env-vars and Deployment v1beta1 when testing on Kubernetes 1.6.7 with RBAC enabled

## Expected Behaviour

Rolling updates should honour env-vars set in the container spec

## Current Behaviour

They're not honouring it.

## Possible Solution

Code is present, maybe need to try different versions of Kubernetes to see if if that resolves things.

https://github.com/openfaas/faas-netes/blob/master/handlers/update.go#L44

## Steps to Reproduce (for bugs)

Deploy:

```
faas-cli deploy --image functions/alpine:latest --fprocess="env" --name env-tester \
 --env env1=true
```

Invoke it and you'll see the `env1` set to "true"

Now do a rolling-update:

```
faas-cli deploy --image functions/alpine:latest --fprocess="env" --name env-tester \
 --env env1=false --update=true --replace=false
```

In my configuration I saw that Kubernetes did not honour the env-vars and `env1` was still `true`.

**Comment by stefanprodan** [comment]
On GKE with Kubernetes v1.8.3 it works fine, I'm getting `env1=false` after the update. I don't think we have to worry about v1.6

**Comment by alexellis** [comment]
Brilliant, thank you for helping. What about 1.7? It's still available as an option on GKE
