### ISSUE TITLE
when i start up my openfass on kubernetes i found that my faas-idler keeping request for the serect openfass-license,so how to get my openfaas-license

### ISSUE THREAD

**Issue by cryLuantic** [openfaas/faas-netes#893]
## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
/set title: OpenFaaS Pro enabled by default

**Comment by alexellis** [comment]
@cryLuantic this change was made in error and has been updated. OpenFaaS Pro is for production, you can find out about it at openfaas.com/support or carry on as you are if you're doing development.
