### ISSUE TITLE
Support `ingressClassName` when deploying an `Ingress`

### ISSUE THREAD

**Issue by aureq** [openfaas/faas-netes#895]
## Expected Behaviour
Currently, it appears that the OpenFaaS Helm Chart doesn't support the `Ingress` property named `spec.ingressClassName`.

As of k8s 1.22, the api `networking.k8s.io/v1` is the default api for ingress objects and as such uses the `ingressClassName` field rather than annotations.

## Current Behaviour
The current chart doesn't support the `ingressClassName`.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Context
Ingress-nginx has posted a FAQ here https://kubernetes.github.io/ingress-nginx/

Thank you for considering this issue.

**Comment by Re-veille** [comment]
When will this be released ?
