### ISSUE TITLE
[Question] is faas-idler no longer free?

### ISSUE THREAD

**Issue by mingfang** [openfaas/faas-netes#911]
I tested openfaas a while ago and am trying to get back to it again.
I used to use openfaas/faas-idler:0.3.0 to scale to zero.
But that image is no longer available.

I do see ghcr.io/openfaas/faas-idler-pro:0.4.4 but it appears to be a paid product.
Are there any free scale to zero options?

**Comment by LucasRoesler** [comment]
Hi @mingfang there are no open-source scale to zero projects currently supported directly by the OpenFaaS project. There may be some in the general community, but I haven't heard of any active projects.

The scaling endpoint is documented as part of the official API https://github.com/openfaas/faas/blob/ca2575afc54ab1e882eb04fe64c8526ca5840e14/api-docs/swagger.yml#L211 if you want to write your own integration.

**Comment by abdennour** [comment]
It's really sad to hear that.. Serverless without scale-to-zero !! unless you pay : (
@alexellis you need to review your OSS.
