### ISSUE TITLE
Disable Prometheus scraping 

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas-netes#93]
We should prevent Prometheus scraping of function services, this can be done by adding an annotation to the service meta.

## Expected Behaviour
Since the watchdog doesn't expose a `/metrics` endpoint, Prometheus should not try to scrape any function.

## Current Behaviour
If Prometheus is configured with Kubernetes service discovery it will try to scrape the functions resulting in function errors and high resources usage. 

## Possible Solution
On function deploy, add the `prometheus.io.scrape='false'` annotation to the function service.

## Context
The colorisebot will run into OOM after multiple calls to `/metrics`.

**Comment by alexellis** [comment]
Sounds like a good idea. Can you build that into the default template in the deployment handler?
