### ISSUE TITLE
Too many GitHub Actions jobs running upon commit

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-netes#934]
There are far too many GitHub Actions jobs running upon commit

## Expected Behaviour

This can probably be run within a bash or makefile / script for all of the charts, without wasting so many resources.

## Current Behaviour

I can see 80 different VMs that will be launched on GitHub's actions runners, per commit and push to a PR / branch.

## Steps to Reproduce (for bugs)

1. Trigger a build through a PR and watch it unfold

![Screenshot from 2022-03-31 10-45-30](https://user-images.githubusercontent.com/6358735/161027091-97998162-a77d-4cd1-bca2-0ccf2827e3bb.png)

If I'm getting this wrong, and there is just one job, but dozens of statuses for it, feel free to correct me.

## Context

This clogs up the build queue as an organisation is only allowed 20 at a time, and would cause havoc for self-hosted runner.

**Comment by LucasRoesler** [comment]
sure

**Comment by alexellis** [comment]
Closing as fixed in #935
