### ISSUE TITLE
HELM - Tiller Component Installation Error

### ISSUE THREAD

**Issue by tomtom215** [openfaas/faas-netes#95]
## Expected Behaviour
Install Server Side Tiller Component Via:
`$ helm init --skip-refresh --upgrade --service-account tiller`

## Current Behaviour
Installation Failed:
` $ sudo helm init --skip-refresh --upgrade --service-account tiller
/usr/local/bin/helm: 1: /usr/local/bin/helm:ELF: not found
/usr/local/bin/helm: 2: /usr/local/bin/helm: }▒: not found
/usr/local/bin/helm: 8: /usr/local/bin/helm: Syntax error: "(" unexpected
`
## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
- Docker 17.11ce
- Kubernetes 1.8.4

## Are you using Docker Swarm or Kubernetes (FaaS-netes)?
- Kubernetes

## Operating System and version (e.g. Linux, Windows, MacOS):
- Linux/arm

**Comment by stefanprodan** [comment]
How is this related to OpenFaaS? From the error message looks like you didn't installed helm, please follow these [instructions](https://github.com/kubernetes/helm/blob/master/docs/install.md).
