### ISSUE TITLE
Prometheus image in OpenFaaS Helm chart vulnerable for BoundServiceAccountTokenVolume

### ISSUE THREAD

**Issue by orhanasan** [openfaas/faas-netes#971]
As said in issue's title, Prometheus image that is used as default in OpenFaaS Helm chart is vulnerable BoundServiceAccountTokenVolume. After Kubernetes v1.21, tokens should be rotated by API wrapper libraries (such as `client-go` for Go) however current Prometheus image is using old version of this library so it should be updated. The reason why it should be fixed is lying behind the reason that AWS detects this behavior and warns the users who have this behavior in their clusters.  For more context, one can refer to [here](https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html).

## Expected Behaviour
There should be no BoundServiceAccountTokenVolume warning in AWS EKS dashboard.

## Current Behaviour
There is a BoundServiceAccountTokenVolume warning in AWS EKS dashboard due to old Prometheus image.

## Are you a GitHub Sponsor (Yes/No?)
- [ ] Yes
- [X] No

## List All Possible Solutions and Workarounds
Upgrading prometheus image version that would be something new (such as `prom/prometheus:v2.36.0`, currently `prom/prometheus:v2.11.0`).

## Which Solution Do You Recommend?
First and only recommendation.

## Context
As said in `Current Behaviour` section, AWS should not show these warnings. For this particular error, this error can cause expired token issues during API calls.

**Comment by alexellis** [comment]
@welteki could you send a PR in for this please?
