### ISSUE TITLE
How do I install OpenFaaS?

### ISSUE THREAD

**Issue by LijieZhang1998** [openfaas/faas-netes#986]
I followed this doc https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md to deploy OpenFaas on macOS. I used KinD as suggested to create a cluster. I can't log into gateway. Thank you for any suggestion.
## Current Behaviour

I ran command:
```
export OPENFAAS_URL=https://10.96.28.23:31112
echo -n $PASSWORD | faas-cli login -g $OPENFAAS_URL -u admin --password-stdin
```
I got error:
```
Calling the OpenFaaS server to validate the credentials...
Cannot connect to OpenFaaS on URL: https://10.96.28.23:31112. Get "https://10.96.28.23:31112/system/functions": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
If `OPENFAAS_URL=https://127.0.0.1:31112`, I got error
```
Calling the OpenFaaS server to validate the credentials...
Cannot connect to OpenFaaS on URL: https://127.0.0.1:31112. Get "https://127.0.0.1:31112/system/functions": dial tcp 127.0.0.1:31112: connect: connection refused
```

## Run commands to debug

1. Ran the command
```
kubectl get pods -o wide -n openfaas
```
response:
```
NAME                                READY   STATUS    RESTARTS      AGE   IP            NODE                 NOMINATED NODE   READINESS GATES
alertmanager-7f9c8b6845-mfjww       1/1     Running   0             40m   10.244.0.9    kind-control-plane   <none>           <none>
basic-auth-plugin-7b55f86b6-j5z7x   1/1     Running   0             40m   10.244.0.6    kind-control-plane   <none>           <none>
gateway-7845bcddd-2kvgm             2/2     Running   0             40m   10.244.0.10   kind-control-plane   <none>           <none>
nats-67d8f684f8-j42kd               1/1     Running   0             40m   10.244.0.8    kind-control-plane   <none>           <none>
prometheus-5cd69789b-fxf5c          1/1     Running   0             40m   10.244.0.7    kind-control-plane   <none>           <none>
queue-worker-5795ff9bb5-jbjj5       1/1     Running   1 (40m ago)   40m   10.244.0.5    kind-control-plane   <none>           <none>
```
2. Ran the command
```
kubectl get svc -n openfaas gateway-external -o wide
```
response:
```
NAME               TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE   SELECTOR
gateway-external   NodePort   10.96.28.23   <none>        8080:31112/TCP   41m   app=gateway
```
3. Ran the command
```
kubectl logs -n openfaas deploy/gateway
```
response:
```
Defaulted container "gateway" out of: gateway, faas-netes
2022/07/19 17:16:53 HTTP Read Timeout: 1m5s
2022/07/19 17:16:53 HTTP Write Timeout: 1m5s
2022/07/19 17:16:53 Binding to external function provider: http://127.0.0.1:8081/
2022/07/19 17:16:53 Async enabled: Using NATS Streaming.
2022/07/19 17:16:53 Opening connection to nats://nats.openfaas.svc.cluster.local:4222
&{0xc0002b8200}
2022/07/19 17:16:53 Connect: nats://nats.openfaas.svc.cluster.local:4222
2022/07/19 17:16:58 Get "http://127.0.0.1:8081/system/namespaces": dial tcp 127.0.0.1:8081: connect: connection refused
2022/07/19 17:16:58 Get "http://127.0.0.1:8081/system/functions?namespace=openfaas-fn": dial tcp 127.0.0.1:8081: connect: connection refused
2022/07/19 17:16:59 Forwarded [GET] to /healthz - [200] - 0.000814s seconds
2022/07/19 17:17:00 Forwarded [GET] to /healthz - [200] - 0.000736s seconds
2022/07/19 17:17:00 Forwarded [GET] to /healthz - [200] - 0.000786s seconds
```
Not sure if I need to do anything about this error.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.14.2
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker desktop engine version: 20.10.17
* What version and distribution of Kubernetes are you using? `kubectl version`
v1.24.1
* Operating System and version (e.g. Linux, Windows, MacOS):
macOS

**Comment by welteki** [comment]
Hi @LijieZhang1998

The instructions you followed use a NodePort to access the API Gateway. NodePorts don't always work on Docker Desktop due to the way networking is configured. On top of that you are using KinD which can cause issues with NodePorts as well.

You can forward the gateway to your local machine using port-forwarding
```
kubectl port-forward -n openfaas svc/gateway 8080:8080
```
I would recommend you to follow [the deployment instruction in our official documentation](https://docs.openfaas.com/deployment/kubernetes/).

[Using arkade](https://docs.openfaas.com/deployment/kubernetes/#1-deploy-the-chart-with-arkade-fastest-option) is the fastest option to deploy the OpenFaaS Chart. After the installation it will print out all the instructions to forward the gateway to your machine and login.

Regards,

Han

**Comment by LijieZhang1998** [comment]
Hi Han, thank you for your suggestion. With your `port-forward` command and `export OPENFAAS_URL=http://127.0.0.1:8080`, I'm able to login. 

Thanks,
Lijie

**Comment by alexellis** [comment]
We recommend following the OpenFaaS docs to get started. Please also check the official training we offer listed there.

New users would benefit from using arkade to install openfaas and arkade info openfaas to get connection information

**Comment by alexellis** [comment]
/set title: How do I install OpenFaaS?
