### ISSUE TITLE
[Question] Load balancing among async functions

### ISSUE THREAD

**Issue by amunozh** [openfaas/faas-netes#991]
**Context**
I created a function that requires around 1 hour to finish. I already tested it using a single replica of the function with maxInflight=1 and a queue worker with maxInflight=1. With this configuration I'm not having any problem, but obviously it takes a lot of time to manage a high quantity of requests. Now I want to scale the current deployment in order to be able to manage multiple request parallely having multiple replicas of the functions.

**Test scenario**
To test the load balancing and scalability I created a sleep function that requires 1 minute to finish, and I configured the OpenFaaS deployment as follows:
- gateway.directFunctions=false
- gateway.readTimeout=2h
- gateway.readTimeout=2h
- gateway.writeTimeout=2h
- queueWorker.ackWait=2h
- faasnetes.readTimeout=2h
- faasnetes.writeTimeout=2h
- queueWorker.maxInflight=5
- gateway.upstreamTimeout=2h

The deployment function has the following parameters:
  environment:
    read_timeout: 1h
    write_timeout: 1h
    exec_timeout: 1h
    max_inflight: 1
  labels:
    com.openfaas.scale.min: 5

After doing the deployment I tested it using the following hey command:

`hey -n 20 -c 2 -q 5 -m POST -d "" -H "X-Callback-Url: https://eooif1hkkkb8f5.m.pipedream.net"  http://127.0.0.1:8080/async-function/long-task`

However, I'm getting more 429 responses than 200. It means that the queue worker is sending requests to pods that are busy while the others are free. 

## Expected Behaviour
I would expect that the queue worker sends requests to the functions pods that are free. If the pods are not free just leave the requests in the queue until one of them gets free. 

## Current Behaviour
Seems like the queue worker is sending requests to busy pods while there are others pods free.  Why? How to correctly load balance the traffic? Is there any problem in my current configuratino or test setup?

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.15.1

* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.13

* What version and distriubtion of Kubernetes are you using? `kubectl version`: 1.23.5 (I'm using k3s cluster)

* Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu 18

Thanks for your help! OpenFaas is being really useful in our project!

**Comment by FTWH** [comment]
I have same questions! Could you please show me about your function yamls? How do you configure the max_inflights for the faas-netes?

**Comment by FTWH** [comment]
I really hope the official website could offer us some best practice for testing this concurrency feature. The official website's description of function concurrency make me feel confuse. It seems that each function is bundled to a queue-worker. And it does not support configuring different concurrency limits for different functions.

**Comment by alexellis** [comment]
Sorry, it seems like you've misunderstood how we use the issue tracker. I get it, some projects
give away free support via their issue tracker. We only use it track bugs and our own work.

For community support, you can check out our free training or come along to a weekly community call
and ask your questions there

https://docs.openfaas.com/community/

If you're interested in enterprise support, feel free to reach out: https://openfaas.com/support
